/* Open Philanthropy Project, global health and development */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Center for Global Development',300000,'2013-07-01','month','donation log','Global poverty/Global health and development','https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support','https://www.openphilanthropy.org/focus/global-health-and-development', 'Alexander Berger', NULL, NULL, NULL,NULL,
  /* donation_process */ 'This grant was made by Good Ventures with input from GiveWell, before the Open Philanthropy Project was a clear and distinct entity.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'The grant page says the grant is "to the Center for Global Development (CGD) in July 2013 for general operating support. The grant will support CGD’s research on topics related to global poverty and inequality."',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ 'The grant page says: "We’ve found CGD to be a valuable resource as we explore potential future focus areas for Good Ventures. Learn more about our rationale for awarding this grant and how CGD is informing our work. This award is a “learning grant,” meaning that it’s designed to help us learn more about an organization or cause we find promising. This grant is unrestricted so that the organization can decide for itself how best to translate the funds into impact." The linked blog post with the rationale is https://www.openphilanthropy.org/blog/grant-center-global-development-cgd',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup conversation with Todd Moss and Kathy Smith of grantee organization at https://www.openphilanthropy.org/sites/default/files/Todd_Moss_and_Kathy_Smith_12-15-2015_%28public%29.pdf on 2015-12-15. Followup grants https://www.openphilanthropy.org/focus/us-policy/miscellaneous/center-global-development-general-support-2016 and https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support-2019 suggest that the grant would be considered a success and Open Phil would continue to endorse its reasoning',
  /* notes */ NULL),
  ('Open Philanthropy Project','Center for Global Development',3000000,'2016-02-01','month','donation log','Global poverty/Global health and development','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/center-global-development-general-support-2016','https://www.openphilanthropy.org/focus/global-health-and-development','Alexander Berger', '2016-02-24', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/3S5tmSoAJZ8',NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support-2016#Our_process says: "In mid-2014 [...] we told CGD that we were interested in funding more policy outreach work. In October 2014, CGD sent us a proposal for a $2.3 million grant to create a “Do Fund”, which would support policy outreach work for three years. In follow-up conversations, CGD told us that it would prefer unrestricted funding, and we shifted to considering that. [...] CGD sent us an outline of some hypothetical activities that it might undertake with different levels of additional unrestricted funding [...]. Before reaching a decision, we investigated the case studies summarized above to improve our understanding of CGD’s track record."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'The funding is unrestricted, but as part of the grant proposal, the grantee, CGD, shared a list of activities it may use the funds for: https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support-2016#Grant_timeline_and_proposed_activities The activities include various forms of additional research, hiring people (consultants, associates, researchers) and expanding a fellowship exchange program',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support-2016#Considerations_in_favor_of_and_against_the_grant says: "We see our unrestricted grant to CGD as a way to support an organization with values closely aligned with ours. We think it is likely that CGD has produced a great deal more value for the global poor than it has spent as an organization, and the potential future activities that CGD has shared to date generally strike us as promising, so we see further unrestricted funding as an attractive grant opportunity. As is fairly typical of our policy grants, our modal guess is that this grant will have limited, if any, humanitarian impact, but that there is a sufficient probability of a very large positive impact to justify the grant." Earlier sections in the grant page discuss proposed activities and track record',
  /* donor_amount_reason */ 'Amount of $3 million (which is to be distributed in three annual installments of $1 million each) determined based on what CGD requested (initially, $2.3 million), as well as what Open Phil considers an appropriate level of fundings',
  /* donor_timing_reason */ 'Timing determined partly by the completion of the timeframe for the previous grant, and also by the time it took Open Phil and CGD to work out the case for the grant',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup conversation with Todd Moss and Kathy Smith of grantee organization at https://www.openphilanthropy.org/sites/default/files/Todd_Moss_Kathy_Smith_06-21-16_%28public%29.pdf on 2016-06-21. The grant would be renewed at https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support-2019 in June 2019 for the same amount ($3 million over 3 years) for the same reasons. This suggests that Open Phil would continue to endorse the reasoning behind the grant',
  /* notes */ NULL);

/* Other global health and development grants */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','University of Michigan',46696,'2018-10-01','month','donation log','Global poverty/Global health and development','https://www.openphilanthropy.org/giving/grants/university-of-michigan-support-for-david-manley','https://www.openphilanthropy.org/focus/global-health-and-development','Grant to support course development and research by Professor David Manley. Professor Manley is planning to develop and teach a new course titled “Changing the World.” The course will focus on global health and poverty, animal welfare, environmental preservation, and the long-term survival of human civilization. The goal is to provide students with the conceptual resources to evaluate which global causes matter most, and how they can most effectively make a difference.','2018-11-03','day',NULL,NULL);
