/* Grants to Project Peanut Butter */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, affected_countries,affected_states,affected_cities,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Project Peanut Butter',724929,'2016-09-01','month','donation log','Global health/nutrition','https://www.openphilanthropy.org/giving/grants/project-peanut-butter-ready-use-therapeutic-food-rct',NULL,NULL,NULL,NULL, '2016-10-26', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Oj3uALe_-TE',NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support a three-year randomized controlled trial (RCT) on the effect on cognitive development of reformulated ready-to-use therapeutic food (RUTF) with additional omega-3 fatty acids and decreased omega-6 fatty acids, compared to conventional RUTF',
  /*  intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ 'RUTF is primarily used to treat young children in the developing world with severe acute malnutrition. The grant is based on our belief that there is a reasonable chance that increasing the ratio of omega-3 to omega-6 fatty acids in RUTF will have a positive effect on the cognitive development of treated children, and that a clear result in a large randomized trial would be fairly likely to make use of the lipid-rebalanced RUTF standard practice.',
  /* donor_amount_reason */ 'Likely the estimated cost of running the RCT. No specific amount-related considerations are discussed',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Grants to Effective Altruism Foundation */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, affected_countries,affected_states,affected_cities,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Effective Altruism Foundation',1000000,'2019-07-01','month','donation log','Effective altruism','https://www.openphilanthropy.org/giving/grants/effective-altruism-foundation-research-operations','Nick Beckstead|Claire Zabel',NULL,NULL,NULL,'2019-07-30','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support research and operations"',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'The grant page says "A major purpose of this grant is to encourage and support EAF and our other grantees in the space in taking approaches to longtermism with greater emphasis on shared objectives between different value systems. We conceive of this grant as falling under our work aimed at growing and supporting the EA community." Earlier in the document, past reservations that Open Phil has had about EAF are described: "EAF is an organization whose values put a particular emphasis on trying to reduce the risks of future suffering. While preventing suffering is a value we share, we also believe that the speculative and suffering-focused nature of this work means that it needs to be communicated about carefully, and could be counterproductive otherwise. As a result, we have felt ambivalent about EAF’s work to date (despite feeling unambiguously positively about some of their projects)."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant would be discussed further by Simon Knutsson in his critical post https://www.simonknutsson.com/problems-in-effective-altruism-and-existential-risk-and-what-to-do-about-them/ that also includes discussion of guidelines that Nick Beckstead of the Open Philanthropy Project developed, and that EAF was now adopting and encouraging others to adopt. Knutsson sees the adoption of the guidelines as being linked to the grant money, due to both the timing matching and the language of the grant page. On separate pages, Knutsson publishes correspondence between him and people at Open Phil and EAF where he tried to get more specific information from the two organizations: https://www.simonknutsson.com/e-mail-exchange-with-the-open-philanthropy-project and https://www.simonknutsson.com/message-exchange-with-eaf/');

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, influencer, affected_countries,affected_states,affected_cities,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Associated Students of the University of California, Berkeley',10000,'2015-02-01','month','donation log','Effective altruism/movement growth','https://www.openphilanthropy.org/giving/grants/asuc-effective-altruists-berkeley-decal-university-course','Grant is for the Effective Altruists of Berkeley “DeCal” University Course to be held in Spring 2015. See http://files.givewell.org/files/conversations/Ajeya_Cotra_6-19-2015_(public).pdf for a followup conversation with Ajeya Cotra and Oliver Habryka (course architects), Rohin Shah and Davis Foote (Effective Altruists of Berkeley members), and Helen Toner and Catherine Hollander of the Open Philanthropy Project', NULL,'United States','California','Berkeley',NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Population Services International',1000000,'2012-08-01','month','donation log','Global health/malaria/resistance','https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/containment-artemisinin-resistance-eastern-myanmar','Grant made by Good Ventures before Open Phil formally came into being. Grant is a co-funding with the Bill & Melinda Gates Foundation, and supports work to prevent the spread of artemisinin resistance in Myanmar. Good Ventures hoped to use the grant opportunity to learn how big players like the Gates Foundation effect progress in global health', NULL,'Myanmar',NULL,NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Founders Pledge',1032947,'2016-09-01','month','donation log','Effective altruism/donor pledges','https://www.openphilanthropy.org/giving/grants/founders-pledge-general-support','Grant made over two years, via the Centre for Effective Altruism, to enable expansion to Germany, France, and Sweden, and hire a developer', NULL,'Germany|France|Sweden',NULL,NULL, '2016-10-31', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/xBVp_050-sE',NULL),
  ('Open Philanthropy Project','US Cochrane Center',100000,'2012-07-01','month','donation log','Biomedical research/meta-research','https://www.openphilanthropy.org/giving/grants/us-cochrane-center-general-support','Unrestricted grant met urgent short-term need to maintain uninterrupted minimal staffing. Grant is a “learning grant,” meaning that it’s designed to help us learn more about an organization or cause we find promising.', NULL,'United States',NULL,NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Brookings Institution',100000,'2015-06-01','month','donation log','International relations','https://www.openphilanthropy.org/giving/grants/brookings-institution-work-china-and-india','Grant supports work on India and China. Open Phil has historically focused on policy in the United States, so it also hopes that through this grant it will learn more about policy in other countries. That learning will be through non-public conversations, though some reflections from Open Phil may be shared in the future. See also a similar grant to the Carnegie Endowment for International Peace in 2015-03. Followup conversation with Paul Haenle of grantee organization at https://www.openphilanthropy.org/sites/default/files/Paul_Haenle_1-26-2016_%28public%29.pdf on 2016-01-26',NULL,'India|China',NULL,NULL, '2015-07-27','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/SGuQ3gKiiKM',NULL),
  ('Open Philanthropy Project','University of Pennsylvania',500000,'2016-03-01','month','donation log','Forecasting','https://www.openphilanthropy.org/giving/grants/university-pennsylvania-philip-tetlock-forecasting','Grant supports new work by Tetlock. He finished The Good Judgment Project and grant funds two new projects called called “Adversarial Collaboration Tournaments” and the “Alpha Pundit Challenge.”',NULL,NULL,NULL,NULL, '2016-04-14', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/N_4WPwpAZZ4','https://predictionbook.com/predictions/185306'),
  ('Open Philanthropy Project','Carnegie Endowment for International Peace',100000,'2015-03-01','month','donation log','International relations','https://www.openphilanthropy.org/giving/grants/carnegie-endowment-international-peace-work-india-and-china','Grant supports work on India and China. Open Phil has historically focused on policy in the United States, so it also hopes that through this grant it will learn more about policy in other countries. That learning will be through non-public conversations, though some reflections from Open Phil may be shared in the future. See also a similar grant to the Brookings Institition',NULL,'India|China',NULL,NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Center for Applied Rationality',304000,'2016-05-01','month','donation log','Rationality improvement/effective altruism/movement growth','https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc','Grant supports the Summer Program on Applied Rationality and Cognition (SPARC),  a two-week summer program for high school students. Students selected to participate in the program typically show exceptional ability in mathematics, with many scoring highly among US participants in national or international math competitions. Grant covers the program for two years, with 137000 for 2016 and 167000 for 2017. Detailed writeup available',NULL,'United States',NULL,NULL, '2016-07-07','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/2xhxrZZgjX8',NULL),
  ('Open Philanthropy Project','Alliance for Open Society International',500000,'2014-07-01','month','donation log','Public services improvement and transparency/Albania','https://www.openphilanthropy.org/giving/grants/alliance-open-society-international-albanian-renaissance','Grant to support the Open Society Foundation for Albania’s project “Albanian Renaissance,” a group of initiatives designed to upgrade public services, bring transparency to public life, and help position the country for European integration. Part of our effort to learn from other major foundations by co-funding projects with them, the major foundation in this case being Open Society Foundations (OSF)',NULL,'Albania',NULL,NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Center for Applied Rationality',1035000,'2016-07-01','month','donation log','Rationality improvement/effective altruism/movement growth','https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support','Grant over two years. Usage split: 915000 will support workshops and organizational improvements, and 120000 will fund a pilot version of EuroSPARC, an eight-day summer program in Europe run by CFAR for mathematically gifted high school students, modeled on SPARC (see also https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc the separate grant to SPARC). Reasons for grants include value alignment, improving rationality, highlighting risks for advanced AI and other GCRs, successful pipeline-building to things like the effective altruism movement',NULL,'United States|Europe',NULL,NULL, '2016-09-06', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/XkSl27jBDZ8',NULL),
  ('Open Philanthropy Project','Cochrane Collaboration',300000,'2014-06-01','month','donation log','Biomedical research/meta-research','https://www.openphilanthropy.org/giving/grants/cochrane-collaboration-general-support','Grant over three years to promote evidence-informed healthcare by producing high-quality, relevant, accessible systematic reviews and other synthesized research evidence.',NULL,NULL,NULL,NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','International Development Association',500000,'2014-03-01','month','donation log','Global health/measurement','https://www.openphilanthropy.org/focus/global-health-and-development/service-delivery-indicators-project','Grant supports work on the Service Delivery Indicators Program (SDI). Estimated budget is $27 million',NULL,NULL,NULL,NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','University of Pennsylvania',1550000,'2017-07-01','month','donation log','Forecasting','https://www.openphilanthropy.org/giving/grants/university-pennsylvania-philip-tetlock-making-conversations-smarter-faster','Grant to support development and pre-testing of the “Making Conversations Smarter, Faster” project. The work is led by Professors Philip Tetlock and Barbara Mellers of University of Pennsylvania, and Professor Emeritus Daniel Kahneman of Princeton University. The original grant amount was $1.3 million, and $250,000 was added in February 2019','Luke Muehlhauser',NULL,NULL,NULL,'2017-08-25','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/BCHYfQlh8xk',NULL),
  ('Open Philanthropy Project','Center for Applied Rationality',340000,'2017-05-01','month','donation log','Rationality improvement','https://www.openphilanthropy.org/giving/grants/center-applied-rationality-european-summer-program-rationality','Grant for the European Summer Program on Rationality','Nick Beckstead',NULL,NULL,NULL,'2017-09-27','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/5UjOZN6KlWQ',NULL),
  ('Open Philanthropy Project','Center for Applied Rationality',1000000,'2018-01-01','month','donation log','Rationality improvement','https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support-2018','Grant for general support. Grantee primarily organizes workshops and develops underlying material and tools to improve rationality. Grant is based on the belief that CFAR workshops help connect people better to the effective altruism movement and grow the talent pipeline in AI safety. Also, Open Phil considers CFAR to have met the milestones set with the 2016 grant','Nick Beckstead',NULL,NULL,NULL,'2018-03-01','day',NULL,NULL),
  ('Open Philanthropy Project','Founders Pledge',3222653,'2018-02-01','month','donation log','Effective altruism/donor pledges','https://www.openphilanthropy.org/giving/grants/founders-pledge-general-support-2018','Total across two grants for general support over three years, representing a renewal of the 2016 grant https://www.openphilanthropy.org/giving/grants/founders-pledge-general-support Since the previous grant, Founders Pledge has increased its pledge commitments and a large percentage of donations made by founders taking their pledge have been to organizations that prioritize an evidence based approach with respect to their interventions. However, its expansion into other parts of Europe has been more limited than anticipated. Instead, FP has shifted its primary expansion focus to the United States and Canada.','Nick Beckstead',NULL,NULL,NULL,'2018-04-05','day',NULL,NULL);

# -- Open Philanthropy Project, history of philanthropy
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Center for Global Development',50000,'2013-06-01','month','donation log','History of philanthropy','https://www.openphilanthropy.org/research/history-of-philanthropy/update-millions-saved-project','https://www.openphilanthropy.org/research/history-of-philanthropy','Grant for an update to the Millions Saved project',NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','ARNOVA',2000,'2015-08-01','month','donation log','History of philanthropy','https://www.openphilanthropy.org/research/history-of-philanthropy/arnova-history-philanthropy-prize','https://www.openphilanthropy.org/research/history-of-philanthropy','Grant to ARNOVA (Association for Research on Nonprofit Organizations and Voluntary Action) to support a prize on the history of philanthropy in memory of Peter Dobkin Hall, a leading historian of philanthropy', NULL, '2015-08-11', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/arZj76CEqBI',NULL),
  ('Open Philanthropy Project','Rockefeller Archive Center',25000,'2014-08-01','month','donation log','History of philanthropy','https://www.openphilanthropy.org/research/history-of-philanthropy/rockefeller-archive-center-workshop-history-philanthropy','https://www.openphilanthropy.org/research/history-of-philanthropy','Grant to support a workshop of  scholars interested in the history of philanthropy', NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Urban Institute',165833,'2017-12-01','month','donation log','History of philanthropy','https://www.openphilanthropy.org/research/history-of-philanthropy/urban-institute-history-of-philanthropy-project','https://www.openphilanthropy.org/research/history-of-philanthropy','Grant to support a series of literature reviews and case studies on the history of philanthropy. The work will be led primarily by Benjamin Soskis, a research associate at the Urban Institute, who has previously produced case studies for our history of philanthropy project.', 'Luke Muehlhauser|Alexander Berger', '2018-02-22','day',NULL,NULL);

# -- Open Philanthropy Project, global health and development
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Center for Global Development',300000,'2013-07-01','month','donation log','Global poverty/Global health and development','https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/center-global-development-general-support','https://www.openphilanthropy.org/focus/global-health-and-development','Grant for general support, to support efforts to reduce global poverty and inequality through rigorous research and active engagement. See also the blog post https://www.openphilanthropy.org/blog/grant-center-global-development-cgd for more. Followup conversation with Todd Moss and Kathy Smith of grantee organization at https://www.openphilanthropy.org/sites/default/files/Todd_Moss_and_Kathy_Smith_12-15-2015_%28public%29.pdf on 2015-12-15', NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Center for Global Development',3000000,'2016-02-01','month','donation log','Global poverty/Global health and development','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/center-global-development-general-support-2016','https://www.openphilanthropy.org/focus/global-health-and-development','Grant for general support. Note that the grant was misclassified on the Open Phil website as being under U.S. policy. Followup conversation with Todd Moss and Kathy Smith of grantee organization at https://www.openphilanthropy.org/sites/default/files/Todd_Moss_Kathy_Smith_06-21-16_%28public%29.pdf on 2016-06-21', '2016-02-24', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/3S5tmSoAJZ8',NULL),
  ('Open Philanthropy Project','University of Michigan',46696,'2018-10-01','month','donation log','Global poverty/Global health and development','https://www.openphilanthropy.org/giving/grants/university-of-michigan-support-for-david-manley','https://www.openphilanthropy.org/focus/global-health-and-development','Grant to support course development and research by Professor David Manley. Professor Manley is planning to develop and teach a new course titled “Changing the World.” The course will focus on global health and poverty, animal welfare, environmental preservation, and the long-term survival of human civilization. The goal is to provide students with the conceptual resources to evaluate which global causes matter most, and how they can most effectively make a difference.','2018-11-03','day',NULL,NULL);

# -- Open Philanthropy Project, misc. policy
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, affected_countries, affected_states,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Pepperdine University',150000,'2014-06-01','month','donation log','Drug policy/United States','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/december-2015-updates-angela-hawken','https://www.openphilanthropy.org/focus/us-policy','Grant in support of Washington THC monitoring by Angela Hawken. Grant made for time-sensitive experiment where Hawken expected NSF funding based on a grant application (but the funding would come too late). Only 120000 of the 150000 was spent and enough data was collected for a conclusion','United States',NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Georgetown University',250000,'2015-08-01','month','donation log','Drug policy/United States','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/georgetown-university-public-health-and-cannabis-legalization','https://www.openphilanthropy.org/focus/us-policy','Grant funds proposal developed by Graham Boyd with O’Neill Institute for National and Global Health Law at Georgetown University and the Washington Office on Latin America (WOLA)','United States',NULL, '2015-09-04', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/9TcM43UP3hM',NULL),
  ('Open Philanthropy Project','Waitlist Zero',50000,'2014-09-01','month','donation log','Organ donation','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-planning-grant','https://www.openphilanthropy.org/focus/us-policy','Planning grant. Organ donation not a focus area but identified as an area with potentially outstanding room for more philanthropy. Senior Research Analyst knows founders Thomas Kelly and Josh Morrison and vouched for them','United States',NULL, '2014-09-25','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/rFatWmHNZCE',NULL),
  ('Open Philanthropy Project','Waitlist Zero',200000,'2015-08-01','month','donation log','Organ donation/United States','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support','https://www.openphilanthropy.org/focus/us-policy','Grant over two years for policies that advocate for living kidney donation, following up on a planning grant in 2014. Conflict of interest due to relationships with Alexander Berger. Followup conversation with Josh Morrison of grantee organization at https://www.openphilanthropy.org/sites/default/files/Josh_Morrison_02-05-2016_%28public%29.pdf on 2016-02-05 and again at https://www.openphilanthropy.org/sites/default/files/Josh_Morrison_04-25-16_%28public%29.pdf on 2016-04-25','United States',NULL, '2015-08-14', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/MSD2VG7ePHo',NULL),
  ('Open Philanthropy Project','RAND Corporation',103000,'2014-08-01','month','donation log','Drug policy/United States','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/rand-corporation-research-vermont','https://www.openphilanthropy.org/focus/us-policy','Grant to enable researchers affiliated with the RAND Drug Policy Research Center to conduct a study about the consequences of legalizing marijuana in Vermont, on behalf of the State of Vermont.','United States','Vermont', NULL, NULL, NULL,NULL),
  ('Open Philanthropy Project','Drug Policy Alliance',1371630,'2017-03-01','month','donation log','Drug policy/United States/Criminal justice reform','https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/drug-policy-alliance-drug-decriminalization','https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform','Grant supports the work of asha bandele and Kassandra Frederique, who plan to lead culture change and pilot project strategies to advance a public health approach to the use and sale of all drugs. Although the grantee is working on drug policy, the current criminalization of various drugs also makes the grant fall under criminal justice reform. Open Phil hopes to move the United States toward a Portugal-style public health approach to drugs, and sees the grant as a step in that direction. Of the original grant amount of $1.4 million, $28,370 of unspent funds were returned by DPA in December 2018, and the grant amount was updated to reflect this','United States',NULL, '2017-04-22', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/KIkkIDG5ceQ',NULL),
  ('Open Philanthropy Project','WaitList Zero',100000,'2018-01-01','month','donation log','Organ donation','https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support-exit-grant-2017','https://www.openphilanthropy.org/focus/us-policy','Exit grant, to give WaitList Zero approximately 18 months of operating support to allow them to secure other funding','United States',NULL,'2018-01-30','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/5XHsBDrlA3Q',NULL);

# -- Other miscellaneous grants

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Centre for Effective Altruism',2500000,'2017-03-01','month','donation log','Effective altruism/movement growth','https://www.openphilanthropy.org/giving/grants/centre-effective-altruism-general-support-2017','https://www.openphilanthropy.org/focus/other-areas#EffectiveAltruism','Grant for general support. Donor impressed by what grantee has achieved in terms of Giving What We Can pledge amounts and recruit quality. Also believes it is value-aligned with other potential donors to donee, so less fungibility concern. Expected to renew grant for $1.25 million or $2.5 million next year. Predictions included in detailed grant page. See also https://www.centreforeffectivealtruism.org/blog/announcing-grant-from-the-open-philanthropy-project/ for the corresponding confirmation from the grantee. See https://donations.vipulnaik.com/donor.php?donor=Effective+Altruism+Grants for the full list of Effective Altruism Grants, for which part of the funds from this grant were used','Nick Beckstead','2017-08-17','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Xa_uIcnTZGw','https://predictionbook.com/prediction_groups/220|https://predictionbook.com/predictions/185300|https://predictionbook.com/predictions/185301|https://predictionbook.com/predictions/185302|https://predictionbook.com/predictions/185303|https://predictionbook.com/predictions/185304|https://predictionbook.com/predictions/185305'),
  ('Open Philanthropy Project','The Center for Election Science',628600,'2017-12-01','month','donation log','Politics','https://www.openphilanthropy.org/giving/grants/the-center-for-election-science-general-support','https://www.openphilanthropy.org/focus/other-areas','Grantee is a US-based nonprofit that promotes alternative voting methods to plurality voting, with an emphasis on cardinal methods and a special focus on approval voting. The grant is intended to go toward CES’ general expenses over the next year such as salaries, marketing, office supplies, as well as its Ballot Initiative Education Campaign project. In October of 2018, Open Phil added $30,000 to the original award amount of $598,600','William MacAskill','2018-01-23','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/5XHsBDrlA3Q',NULL),
  ('Open Philanthropy Project','Global Priorities Institute',2674284,'2018-02-01','month','donation log','Cause prioritization','https://www.openphilanthropy.org/giving/grants/global-priorities-institute-general-support','https://www.openphilanthropy.org/focus/other-areas','Grant of £2,051,232 over five years (estimated at $2,674,284, depending upon currency conversion rates at the time of annual installments) via Americans for Oxford for general support. GPI is an interdisciplinary research center at the University of Oxford that conducts foundational research to inform the decision-making of individuals and institutions seeking to do as much good as possible. GPI intends to use this funding to support global priorities research, specifically: to hire three early-career, non-tenured research fellows with expertise in philosophy or economics, as well as two operations staff; to secure a larger office space to accommodate them; to host visiting researchers; and to hold seminars which address global priorities research topics.','Nick Beckstead','2018-05-21','day',NULL,NULL),
  ('Open Philanthropy Project','Centre for Effective Altruism',2688000,'2018-06-01','month','donation log','Effective altruism/movement growth','https://www.openphilanthropy.org/giving/grants/centre-effective-altruism-general-support-2018','https://www.openphilanthropy.org/focus/other-areas#EffectiveAltruism','Grant of £2,000,000 ($2,688,000 at time of conversion). Renewal of previous grant https://www.openphilanthropy.org/giving/grants/centre-effective-altruism-general-support and related to statement made in previous grant write-up that they "planned to renew for between $1.25 million and $2.5 million."','Nick Beckstead','2018-06-28','day',NULL,NULL),
  ('Open Philanthropy Project','The Center for Election Science',1800000,'2019-02-01','month','donation log','Politics','https://www.openphilanthropy.org/giving/grants/the-center-for-election-science-general-support-2019','https://www.openphilanthropy.org/focus/other-areas','Grantee is a US-based nonprofit that promotes alternative voting methods to plurality voting. The grant is a renewal of December 2017 support https://www.openphilanthropy.org/giving/grants/the-center-for-election-science-general-support which allowed the grantee to organize a ballot initiative for approval voting https://www.vox.com/future-perfect/2018/11/15/18092206/midterm-elections-vote-fargo-approval-voting-ranked-choice that was adopted by Fargo, North Dakota. The renewal is intended to help CES scale up its operations and replicate ballot initiatives for approval voting in other cities.','Willam MacAskill','2019-03-01','day',NULL,NULL);

/* Grants to 80,000 Hours */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','80,000 Hours',1125000,'2017-03-01','month','donation log','Effective altruism/movement growth/career counseling','https://www.openphilanthropy.org/giving/grants/80000-hours-general-support','https://www.openphilanthropy.org/focus/other-areas#EffectiveAltruism','Nick Beckstead','2017-05-16','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/fRfAjul_pLM','https://predictionbook.com/prediction_groups/218|https://predictionbook.com/predictions/185283|https://predictionbook.com/prediction_groups/219',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'According to https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Budget_and_proposed_activities grantee plans to use the grant to fund the following activities: (1) Hiring four new junior staff members to (a) improve career guides and career profiles, (b) do career coaching, (c) replacing a departing part-time software engineer, (d) research/career coaching/marketing. (2) Increasing staff salaries  by 30% to be competitive in the Bay Area, to which it recently moved. (3) Marketing activities including online retargeting advertisements, Facebook advertisements for workshops targeted at universities, and giving away books. (4) Holding funds in reserve for year 2',
  /* intended_funding_timeframe_in_months */  NULL,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Case_for_the_grant explains the reasons. The key reason is that Open Phil finds impressive the large number of impact-adjusted significant plan changes (IASPCs) that 80,000 Hours claims to have brought about, and broadly agrees with 80,000 Hours'' calculation of their IASPCs',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ 'According to https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Case_for_the_grant "We expect to recommend another grant to 80,000 Hours at the beginning of 2018, with the amount recommended being whichever of the following is smallest: (1) $1.25 million (2) The amount 80,000 Hours raises from other donors in 2017 (3) The amount necessary for 80,000 Hours to have $3.75 million in its bank account"',
  /* donor_retrospective */ 'The renewal grant https://www.openphilanthropy.org/giving/grants/80000-hours-general-support-2018 of $510,000 is consistent with the expectations set during this grant; the constraining factor in determining the amount for the  renewal is "The amount 80,000 Hours raises from other donors in 2017"',
  /* notes */ NULL),
  ('Open Philanthropy Project','80,000 Hours',510000,'2018-02-01','month','donation log','Effective altruism/movement growth/career counseling','https://www.openphilanthropy.org/giving/grants/80000-hours-general-support-2018','https://www.openphilanthropy.org/focus/other-areas#EffectiveAltruism','Nick Beckstead|Nicole Ross','2018-02-22','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'No explicitly listed priority uses of the funds, but likely similar to the grant https://www.openphilanthropy.org/giving/grants/80000-hours-general-support that it is renewing',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'Likely the same reasons as for the 2017 grant that this is renewing; see https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Case_for_the_grant The key reason is that Open Phil finds impressive the large number of impact-adjusted significant plan changes (IASPCs) that 80,000 Hours claims to have brought about, and broadly agrees with 80,000 Hours'' calculation of their IASPCs',
  /* donor_amount_reason */ 'Amount determined by the amount ($510,000) raised from other donors in 2017, which turned out to be the smallest of the three constraining amounts described in the previous grant page https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Case_for_the_grant "We expect to recommend another grant to 80,000 Hours at the beginning of 2018, with the amount recommended being whichever of the following is smallest: (1) $1.25 million (2) The amount 80,000 Hours raises from other donors in 2017 (3) The amount necessary for 80,000 Hours to have $3.75 million in its bank account"',
  /* donor_timing_reason */ 'Timing as pre-committed on the previous grant page https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Case_for_the_grant "We expect to recommend another grant to 80,000 Hours at the beginning of 2018"',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/giving/grants/80000-hours-general-support-2019 for $4,795,803 in February 2019 (amount determined by the Committee for Effective Altruism Support) suggests general satisfaction with the grantee and the grant',
  /* notes */ NULL),

  ('Open Philanthropy Project','80,000 Hours',4795803,'2019-02-01','month','donation log','Effective altruism/movement growth/career counseling','https://www.openphilanthropy.org/giving/grants/80000-hours-general-support-2019','https://www.openphilanthropy.org/focus/other-areas#EffectiveAltruism','Committee for Effective Altruism Support','2019-03-28','day',NULL,NULL,
  /* donation_process */ 'The decision of whether to donate seems to have followed the Open Philanthropy Project''s usual process, but the exact amount to donate was determined by the Committee for Effective Altruism Support using the process described at https://www.openphilanthropy.org/committee-effective-altruism-support',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ '80,000 Hours aims to solve skill bottlenecks for career paths in what it considers to be the world’s most pressing problems. It does this by providing online research, in-person advice, and support with the goal of helping talented graduates age 20-40 enter high-impact careers.',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'Open Phil''s grant writeup says: "we see the basic pros and cons of this support similarly to what we’ve presented in past writeups on the matter" and links to the February 2018 support https://www.openphilanthropy.org/giving/grants/80000-hours-general-support-2018',
  /* donor_amount_reason */ 'The amount is decided by the Committee for Effective Altruism Support https://www.openphilanthropy.org/committee-effective-altruism-support but individual votes and reasoning are not public. Two other grants with amounts decided by the Committee for Effective Altruism Support, made at the same time and therefore likely drawing from the same money pot, are to the Machine Intelligence Research Institute ($2,112,5000) and Centre for Effective Altruism ($2,756,250)',
  /* donor_timing_reason */ 'Reasons for timing are not discussed, but likely include (1) It is about a year since the last grant to 80,000 Hours, and the grants are generally expected to last a year, so a renewal is due, (2) The Committee for Effective Altruism Support https://www.openphilanthropy.org/committee-effective-altruism-support did its first round of money allocation, so the timing is determined by the timing of that allocation round',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Centre for Effective Altruism',2756250,'2019-02-01','month','donation log','Effective altruism/movement growth','https://www.openphilanthropy.org/giving/grants/centre-effective-altruism-general-support-2019','https://www.openphilanthropy.org/focus/other-areas#EffectiveAltruism','Committee for Effective Altruism Support','2019-04-19','day',NULL,NULL,
  /* donation_process */ 'The decision of whether to donate seems to have followed the Open Philanthropy Project''s usual process, but the exact amount to donate was determined by the Committee for Effective Altruism Support using the process described at https://www.openphilanthropy.org/committee-effective-altruism-support',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'The grant writeup says: "CEA is a central organization within the effective altruism (EA) community that engages in a variety of activities aimed at helping the EA community."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'Open Phil''s grant writeup says: "we see the basic pros and cons of this support similarly to what we’ve presented in past writeups on the matter" and links to the June 2018 support https://www.openphilanthropy.org/giving/grants/centre-effective-altruism-general-support-2019',
  /* donor_amount_reason */ 'The amount is decided by the Committee for Effective Altruism Support https://www.openphilanthropy.org/committee-effective-altruism-support but individual votes and reasoning are not public. Two other grants with amounts decided by the Committee for Effective Altruism Support, made at the same time and therefore likely drawing from the same money pot, are to the Machine Intelligence Research Institute ($2,112,5000) and 80,000 Hours ($4,795,803)',
  /* donor_timing_reason */ 'Reasons for timing are not discussed, but likely include (1) It is about a year since the last grant to the Centre for Effective Altruism, and the grants are generally expected to last a year, so a renewal is due, (2) The Committee for Effective Altruism Support https://www.openphilanthropy.org/committee-effective-altruism-support did its first round of money allocation, so the timing is determined by the timing of that allocation round',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

# -- Special grant for Carl Shulman

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, influencer, donation_earmark, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Carl Shulman Discretionary Fund',5000000,'2018-03-01','month','donation log',NULL,'https://www.openphilanthropy.org/giving/grants/centre-for-effective-altruism-new-discretionary-fund',NULL,'Money for a discretionary fund to be administered by Carl Shulman, who is a Research Associate at the Future of Humanity Institute and an advisor to the Open Philanthropy Project. Based on experience working with Shulman, Open Phil believes that the first $5 million that Shulman could allocate would be better allocated than the last $5 million that Open Phil could allocate. Open Phil is simultaneously experimenting with an “external investigators” program with similar goals but a different setup, namely that grants recommended by external investigators go through our standard process where the reasoning and recommendation is discussed in detail with Open Philanthropy Project decision-makers. Carl is also part of the external investigators program.','Holden Karnofsky','Carl Shulman','2018-05-17','day',NULL,NULL);

insert into donations(donor,donee,amount,donation_date,donation_date_precision,donation_date_basis,cause_area,url,notes,influencer) values
  ('Open Philanthropy Project','One for the World',153750,'2018-07-01','month','donation log','Effective altruism/fundraising','https://www.openphilanthropy.org/focus/global-health-and-development/miscellaneous/one-for-the-world-general-support','The grant was announced and discussed on the donee blog at https://www.1fortheworld.org/blog/evanoppgrant The grant was also announced by GiveWell, the main influencer of the grant, on the page https://www.givewell.org/about/impact/one-for-the-world/july-2018-grant which also said it is a July 2018 grant. It is accompanied by a grant from Luke Ding of $51,250 (so the two grants are in a 3:1 ratio) also influenced by GiveWell. As of the time of entering this, the grant from the Open Philanthropy Project is not listed in the Open Philanthropy Project grants database. Also, the GiveWell page on the grant does not explicitly name either donor. The two grants together are expected to cover two years of costs, including budget for a COO (which they succeeded in doing: Evan McVail joined as COO for a year) and a CEO in 2019','GiveWell');
