# -- Peterson Institute for International Economics
insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Peterson Institute for International Economics',250000,'2016-04-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/peterson-institute-international-economics-macroeconomic-stabilization','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2016-04-29','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/UeMetwk5b74',NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support work  on macroeconomic stabilization',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page says: "We are considering making a larger grant to support PIIE to do substantially more work in this area (which is a focus area of ours), and are thinking of the present funding as an opportunity to try working with the organization while we (and they) think more about potential future engagement."',
  /* donor_amount_reason */ 'The grant is a relatively small one and is intended to kickstart a relationship with the donee, to decide on whether to make a bigger grant later',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Open Philanthropy Project','Peterson Institute for International Economics',400000,'2019-01-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/peterson-institute-international-economics-macroeconomic-projects','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2019-05-18','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support research by non-resident fellows Karen Dynan and Jason Furman on key questions in macroeconomic stabilization policy. Karen Dynan will study the optimal design of automatic stabilizer programs — taxes and government programs that respond automatically to changing economic conditions. Jason Furman will study the costs and benefits of allowing employment to exceed some estimates of full employment.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page says: "We see these both as crucially important questions in macroeconomic stabilization policy and believe Dynan and Furman are especially well-placed to address them in an influential and informative fashion."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donattion_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Employ America */
insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Employ America',300000,'2019-04-01','month','donation log','Macroecononic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-start-up','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2019-05-29','day',NULL,NULL,
  /* donation_process */ 'This is a total across two grants, one of which is being made by the Open Philanthropy Action Fund',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant "to help launch Employ America and cover a six-month pilot period." The grant page says: "Employ America will focus on making the public and intellectual case for policies that support full employment and building a broader set of allies to further that goal, especially with an eye to the next economic downturn. In order to do so, it will produce research and analysis on the state of the labor market and current and potential macroeconomic policies and policymakers. It will be led by Sam Bell, who has previously consulted for us and our grantee Fed Up."',
  /* intended_funding_timeframe_in_months */ 6,
  /* donor_donee_reason */ 'The grant page says: "As labor market conditions have improved over the last few years, we’ve become less confident about the appropriate short term stance of monetary policy, but we continue to believe it is worthwhile to support research and advocacy like this, at least through the next recession."',
  /* donor_amount_reason */ 'Amount likely determined based on how much is needed for an initial 6-month startup',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notets */ NULL);

# -- Macroeconomic policy research/United States
insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Center for Popular Democracy Action Fund',31500,'2016-10-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-october-2016','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve, and specifically in the selection of regional Federal Reserve Bank presidents and leaders. Related to other grants made to the Center for Popular Democracy; see https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016. Grant financed by the Open Philanthropy Action Fund. As explained at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/FrHyHKPNy-M the grant announcement was delayed till the Open Philanthropy Project was completely separate from GiveWell','Alexander Berger','United States','2018-01-19','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/FrHyHKPNy-M',NULL),
  ('Open Philanthropy Project','Center for Popular Democracy Action Fund',305000,'2017-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2017','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant from the Open Philanthropy Action Fund to CPD Action to support the "Fed Up" Campaign. This supplements the grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 to the Center for Popular Democracy. As explained at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg the grant announcement was delayed till the Open Philanthropy Project was completely separate from GiveWell','Alexander Berger','United States','2017-12-28','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg',NULL),
  ('Open Philanthropy Project','Center for Popular Democracy',1100000,'2017-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant from the Open Philanthropy Action Fund for the "Fed Up" campaign, renewing https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016 It is accompanied by the grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2017 to the CPD Action Fund. As explained at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg the grant announcement was delayed till the Open Philanthropy Project was completely separate from GiveWell','Alexander Berger','United States','2017-12-28','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg',NULL),
  ('Open Philanthropy Project','Roosevelt Institute',200000,'2016-06-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/roosevelt-institute-macroeconomic-policy-research','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant supports work on macroeconomic policy. Includes exploring monetary policy tools, automatic stabilizes, novel fiscal stimulus measures, also making the case for importance of continued focus on reducing unemployment and against premature monetary tightening today','Alexander Berger','United States', '2016-10-25', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/vAPhHDgenvY',NULL),
  ('Open Philanthropy Project','Center for Popular Democracy',1429000,'2015-12-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant supports the "Fed Up" campaign. Deemed unlikely to succeed but high-impact if it succeeds. Conversation with Ady Barkman of grantee organization around the time of the grant allocation at https://www.openphilanthropy.org/sites/default/files/Ady_Barkan_12-8-15_%28public%29.pdf on 2015-12-08. Followup conversations with Ady Barkan and Shawn Sebastian of grantee organization at https://www.openphilanthropy.org/sites/default/files/Fed_Up_07-14-16_and_08_31_16_and_09_02_16_%28public%29.pdf on 2016-07-14, 2016-08-31, and 2016-09-02','Alexander Berger','United States', '2016-04-06','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/JKm8ZFwuPlk',NULL),
  ('Open Philanthropy Project','Center on Budget and Policy Priorities',425000,'2016-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project-2016','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant supports the Full Employment Project, and renews a previous grant to CBPP made in 2014','Alexander Berger','United States', '2016-10-25', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/vAPhHDgenvY',NULL),
  ('Open Philanthropy Project','Center for American Progress',500000,'2016-03-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-american-progress-macroeconomic-stabilization','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant for macroeconomic stabilization policy: convenings, research reports on impacts (e.g., impact of Taylor rule on income distribution), policy proposals, and network and outreach capacity to share research and proposals with media, politicians, and Federal Reserve','Alexander Berger','United States','2016-04-19','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Br6kCBlTAkg',NULL),
  ('Open Philanthropy Project','Economic Policy Institute',500000,'2016-06-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant supports work on macroeconomic policy. Includes exploring monetary policy tools, automatic stabilizes, novel fiscal stimulus measures, also making the case for importance of continued focus on reducing unemployment and against premature monetary tightening today. Essentially, same as grant to Roosevelt Institute','Alexander Berger','United States', '2016-10-25', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/vAPhHDgenvY',NULL),
  ('Open Philanthropy Project','Center for Popular Democracy',750000,'2015-01-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant is for Fed Up Campaign 2015. Supports campaign to educate public and policymakers about monetary policy issues','Alexander Berger','United States', '2015-02-27', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Tuu9P250vVQ',NULL),
  ('Open Philanthropy Project','Center on Budget and Policy Priorities',335000,'2014-09-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant is for the Full Employment Project. Open Phil is impressed by the track record of CBPP. Followup conversation with Jared Bernstein and Ben Spielberg of grantee organization at https://www.openphilanthropy.org/sites/default/files/Jared_Bernstein_and_Ben_Spielberg_10-21-15_%28public%29.pdf on 2015-10-21','Alexander Berger','United States', '2014-09-19', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/HWCQwDbQhks',NULL),
  ('Open Philanthropy Project','Center for Popular Democracy',100000,'2014-08-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-federal-reserve-campaign','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant is to support a campaign to educate the public and policymakers about monetary policy issues','Alexander Berger','United States', '2014-09-25', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/1akCOFYWWOM',NULL),
  ('Open Philanthropy Project','Center for Popular Democracy Action Fund',100000,'2018-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant made by the Open Philanthropy Action Fund to the 501(c)(4) Center for Popular Democracy Action Fund to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve. Companion grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2018 to the Center for Popular Democracy, the associated 501(c)(3)','Alexander Berger','United States','2018-03-24','day',NULL,NULL),
  ('Open Philanthropy Project','Center for Popular Democracy',1200000,'2018-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve. Renewal of https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 (2017 grant). Companion grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 by the Open Philanthropy Action Fund to the Center for Popular Democracy Action Fund, the associated 501(c)(4)','Alexander Berger','United States','2018-03-24','day',NULL,NULL),
  ('Open Philanthropy Project','Center on Budget and Policy Priorities',100000,'2018-05-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-automatic-stabilizers','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to support work on enhancing automatic fiscal stabilizers. Automatic fiscal stabilizers are taxes and government programs that respond automatically to changing economic conditions, and do not require additional Congressional action.','Alexander Berger','United States','2018-06-21','day',NULL,NULL),
  ('Open Philanthropy Project','Center on Budget and Policy Priorities',250000,'2018-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Exit grant to support the Full Employment Project. Renewal of July 2016 grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project-2016 Open Phil will discontinue support after this grant, which completes five years of support for the project. The reason for not continuing further is the unclear impact of marginal funding and the desire to give space to other funders','Alexander Berger','United States','2018-08-02','day',NULL,NULL),
  ('Open Philanthropy Project','Economic Policy Institute',700000,'2018-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to support macroeconomic policy research. EPI plans to use these funds primarily to continue producing policy-relevant research on the ways in which macroeconomic policy can boost living standards for working Americans, including work on different aspects of the relationships between unemployment, wage growth, inflation, and productivity. Renewal of 2016 grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research','Alexander Berger','United States','2018-08-16','day',NULL,NULL),
  ('Open Philanthropy Project','Washington Center for Equitable Growth',100000,'2018-10-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/washington-center-for-equitable-growth-automatic-stabilizers-conference','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to host a conference, in partnership with the Hamilton Project, on a framework for thinking about optimal design of automatic stabilizer programs as well as specific suggestions for reforms. Automatic fiscal stabilizers are taxes and government programs that respond automatically to changing economic conditions, and do not require additional Congressional action, and the Open Philanthropy Project believes they are important for mitigating the effects of economic downturns.','Alexander Berger','United States','2018-11-27','day',NULL,NULL);
