/* University of Michigan */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url,influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','University of Michigan',2500000,'2019-03-01','month','donation log','Scientific research/transformative basic science','https://www.openphilanthropy.org/focus/scientific-research/university-michigan-research-on-mammalian-gamete-development','https://www.openphilanthropy.org/focus/scientific-research','Chris Somerville|Heather Youngs','2019-05-18','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support research by Professor Sue Hammoud on mammalian gamete development. Dr. Hammoud’s proposed research would be specifically focused on development of gametes from stem cells.',
  /* intended_funding_timeframe_in_months */ 48,
  /* donor_donee_reason */ 'The grant page says: "Progress in this area could eventually enable people with fertility challenges to have children and could eventually help reduce the incidence of a wide variety of high-burden disorders (such as heart disease, chronic pain, depression, and Alzheimer’s disease) and promote other positive outcomes. Dr. Hammoud’s research is amongst the most promising our science team has encountered so far in this field." The grant follows up on an April 2016 grant https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-southern-california-genomic-research-methods',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* University of Southern California */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url,influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','University of Southern California',1738500,'2016-04-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-southern-california-genomic-research-methods','https://www.openphilanthropy.org/focus/scientific-research',NULL,'2018-04-19','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support the Social Science Genetic Association Consortium and the Behavioral and Health',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page notes that Open Phil hopes the grant will advance scientific tools and techniques, by: (1) devekoping cross-cuttingly useful advances in analysis of genome-wide association studies (GWAS), (2) combining data from multiple sources and developing polygenic sources that can be distributed freely as public goods',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Open Phil would make a followup grant https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/research-institute-of-industrial-economics-genomic-research-methods to the Research Institute of Industral Economics, also to support the SSGAC, and a later grant https://www.openphilanthropy.org/focus/scientific-research/Social-Science-Genetic-Association-Consortium-general-support to USC to again support SSGAC',
  /* notes */ NULL),
  ('Open Philanthropy Project','University of Southern California',2250000,'2019-01-01','month','donation log','Scientific research/tools and techniques','https://www.openphilanthropy.org/focus/scientific-research/Social-Science-Genetic-Association-Consortium-general-support','https://www.openphilanthropy.org/focus/scientific-research','Alexander Berger','2019-05-18','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support the Social Science Genetic Association Consortium (SSGAC). Approximately 20% of this grant is intended to support work on bioethics and the public discussion of these topics.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page says: "Our understanding is that SSGAC has received substantially less funding to date than comparable consortia (such as in psychiatric genetics), but still produces high-quality, replicable research and serves as a model of careful public communication, most notably through their discussions of frequently asked questions."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Life Sciences Research Foundation grants */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Life Sciences Research Foundation',780000,'2018-04-01','month','donation log','Scientific research/transformative basic science','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/life-sciences-research-foundation-young-investigators','https://www.openphilanthropy.org/focus-area/scientific-research/transformative-basic-science','Chris Somerville|Heather Youngs','2018-05-03','day',NULL,NULL,
  /* donation_process */ 'Discretionary grant',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support early-career investigators. The funds will support four postdoctoral fellows for three years apiece. The fellows have proposed research projects investigating immunology, virology, neurobiology, and tuberculosis."',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup 2019 grant suggests that this grant would be considered a success',
  /* notes */ NULL),

  ('Open Philanthropy Project','Life Sciences Research Foundation',1170000,'2019-04-01','month','donation log','Scientific research/trasnformative basic science','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/life-sciences-research-foundation-young-investigators-2019','https://www.openphilanthropy.org/focus-area/scientific-research/transformative-basic-science','Chris Somerville|Heather Youngs','2019-06-26','day',NULL,NULL,
  /* donation_process */ 'Discretionary grant',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant page says: "The funds will support six postdoctoral fellows for three years apiece. The fellows have proposed research projects investigating Alzheimer’s disease, infectious disease dynamics, forebrain development, cross-species transmission of bird flu, muscle stem cell function, and immune system evolution."',
  /* intended_funding_timeframe_in_months  */ 36,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Target Malaria grant */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url,influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Target Malaria',17500000,'2017-05-01','month','donation log','Scientific research/malaria/gene drive testing and governance','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support','https://www.openphilanthropy.org/focus/scientific-research', NULL, '2017-05-17','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Me2Motxn8xQ',NULL,
  /* donation_process */ 'As explained in https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support#Our_process the donation process included conversations with Target Malaria, the Gates Foundation, Kevin Esvelt, Stephanie James, and several other people, and review by scientific advisors Chris Somerville and Daniel Martin-Alarcon',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant to help the project develop and prepare for the potential deployment of gene drive technologies to help eliminate malaria in Sub-Saharan Africa, if feasible, ethical, safe, approved by the regulatory authorities, and supported by the affected communities. This grant will support training and outreach programs, research into the potential ecological effects of releasing gene drives, operational development, regulatory support, and an unrestricted funding reserve.',
  /* intended_funding_timeframe_in_months */ 48,
  /* donor_donee_reason */ 'As described in https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support#Case_for_the_grant (1) Gene drives, and Target Malaria''s work in particular, seem important and tractable as a malaria elimination strategy, (2) Target Malaria has a lot of room for more funding, (3) Even a few weeks of speed-up of the work would likely have good cost-effectiveness. More explicit quantification is available in the back-of-the-envelope calculation (BOTEC) at https://docs.google.com/document/d/1GsE2_TNWn0x6MWL1PTdkZT2vQNFW8VFBslC5qjk4sgo/edit?ts=5cc10604#heading=h.g3c8stqygqae Quantification related to (3) is also in the spreadsheet https://docs.google.com/spreadsheets/d/1E8qu474nUUvPjK21oBqGkdQ9FuXanigOgSGfumhL3_c/edit#gid=1061406209',
  /* donor_amount_reason */ 'The reasoning for the amount is not articulated, but it is likely related to the budget https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support#Budget_and_proposed_activities as well as the cost-effectiveness calculations. One factor helping with the size of the grant is that the organization is also heavily funded by the Gates Foundation (grant of $36 million over 3.5 years) so that the Open Philanthropy Project will be under 50% of the grantee''s funds, and can also piggyback on th vetting already done by the Gates Foundation',
  /* donor_timing_reason */ 'The timing is probably affected by two factors: (a) The belief that even a few weeks of speed-up of the work would likely have good cost-effectiveness, qunaitified in the spreadsheet https://docs.google.com/spreadsheets/d/1E8qu474nUUvPjK21oBqGkdQ9FuXanigOgSGfumhL3_c/edit#gid=1061406209 (b) The timing of the Gates Foundation grant and the scaling up of the project',
  /* donor_next_donation_thoughts */ 'Key questions for follow-up are listed at https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support#Key_questions_for_follow-up but there is no explicit discussion of follow-up grants',
  /* donor_retrospective */ 'In the July 2019 blog post https://www.openphilanthropy.org/blog/givewells-top-charities-are-increasingly-hard-beat the grant is mentioned as one of the few grants that crosses the 1000x cost-effectiveness barrier in expected cost-effectiveness as of the time of making the grant, and also as accounting for over half of the total money volume of such grants',
  /* notes */ 'The grant is discussed in https://ssir.org/articles/entry/giving_in_the_light_of_reason as part of an overview of the Open Philanthropy Project grantmaking strategy');

/* Sherlock Biosciences grant */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','Sherlock Biosciences',17500000,'2019-01-01','month','donation log','Scientific research/Biosecurity and pandemic preparedness','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/sherlock-biosciences-research-viral-diagnostics','https://www.openphilanthropy.org/focus/scientific-research','Chris Somerville|Heather Youngs','2019-03-21','day',NULL,NULL,
  /* donation_process */ 'The Open Philanthropy Project''s scientific advisors Chris Somerville and Heather Youngs were hopeful about viral diagnostics after hearing of research coming out of Feng Zhang''s lab (Zhang would later co-found Sherlock Biosciences). When they ran into David Walt, they asked him if his new company (Sherlock Biosciences) would be interested in developing a viral diagnostic, and after consulting with his team, he said they would. This started the process of vetting Sherlock Biosciences for the grant',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support the development of a diagnostic platform to identify any virus present in a patient sample.',
  /* intended_funding_timeframe_in_months */ 60,
  /* donor_donee_reason */ 'Chris Somerville and Heather Youngs have been interested in viral diagnostics because development of this technology could both reduce threats from viral pandemics and also benefit health care broadly. The selection of Sherlock Biosciences was because of their team and technology, which made it plausible that they could develop this technology',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The Open Philanthropy Project also recommended an additional investment in Sherlock Biosciences. Sherlock recently spun out of Harvard University’s Wyss Institute and the Broad Institute of MIT and Harvard. The launch of Sherlock Biosciences, and the funding by the Open Philanthropy Project, are discussed in Forbes at https://www.forbes.com/sites/elliekincaid/2019/03/21/with-launch-of-new-crispr-company-competition-extends-to-diagnostics/ More background explanation related to the grant is in the conversation blog post https://www.openphilanthropy.org/blog/explaining-our-bet-sherlock-biosciences-innovations-viral-diagnostics');

/* Institute for Protein Design grant */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','University of Washington (Institute for Protein Design)',11367500,'2017-11-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-of-washington-universal-flu-vaccine','https://www.openphilanthropy.org/focus/scientific-research','Chris Somerville|Heather Youngs','2018-04-04','day',NULL,NULL,
  /* donation_process */ 'In the blog post https://www.openphilanthropy.org/blog/questions-we-ask-ourselves-making-grant Michael Levine describes the process of deciding the grant: "Through ongoing conversations, the original grant proposal focusing on the development of a universal flu vaccine evolved into an expanded grant incorporating work on a computational protein design system that we believe could have much broader utility if it makes it possible to rapidly design new vaccines or antiviral drugs."',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support research on the use of computational protein design to develop a universal influenza vaccine. This work will be led by UW Professor David Baker, Ph.D., and UW Assistant Professor Neil King, Ph.D. In addition, part of this funding is intended to improve the Rosetta molecular modeling and design software originally developed in Baker’s lab. UW Assistant Professor Frank DiMaio, Ph.D., and others will work to improve Rosetta to better predict the properties of proteins',
  /* intended_funding_timeframe_in_months */ 60,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'The blog post https://www.openphilanthropy.org/blog/questions-we-ask-ourselves-making-grant suggests a scope increase for the grant from being for a universal flu vaccine to being for improving computational protein design techniques as well.',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /*notes */ 'The grant is discussed in https://ssir.org/articles/entry/giving_in_the_light_of_reason as part of an overview of the Open Philanthropy Project grantmaking strategy');

/* University of California, Los Angeles */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','University of California, Los Angeles',2368300,'2019-04-01','month','donation log','Scientific research/transformative basic science','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/ucla-epigenetic-clock-research','https://www.openphilanthropy.org/focus-area/scientific-research/transformative-basic-science','Chris Somerville|Heather Youngs','2019-06-22','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to UCLA Professor Steve Horvath and collaborators to pursue a series of experiments directed toward understanding why an algorithm based on the presence or absence of epigenetic modifications at several hundred sites in the human genome, which they call the “epigenetic clock,” is able to predict age with very high accuracy. Dr. Horvath and his collaborators plan to systematically alter the activity of genes that are thought to affect the clock in mice, to test whether they can slow or accelerate the clock and, if they can, what effects perturbation of the clock may have on the aging processes in the mice. They will also investigate why some human syndromes are associated with accelerated aging, and will study how the clock works in various types of cultured human cells."',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ 'The grant page says "The research will seek to understand how the clock measures age and whether changes to the associated processes can have useful impact on aging in humans."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */  NULL,
  /* notes */ NULL);

/* Other scientific research grants */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes,influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Rescuing Biomedical Research',299112,'2016-01-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/princeton-university-rescuing-biomedical-research','https://www.openphilanthropy.org/focus/scientific-research','Grantee is a project based in Princeton University. Goal is to establish a more “predictable and stable” federal budget for research, and to improve grant funding so that trainees are funded by dedicated training grants. Followup conversation with Shirley Tilghman of grantee organization at https://www.openphilanthropy.org/sites/default/files/Shirley_Tilghman_05-19-16_%28public%29.pdf on 2016-05-19 and with Christopher Pickett of grantee organization at https://www.openphilanthropy.org/sites/default/files/Christopher_Pickett_11-16-16_%28public%29.pdf on 2016-11-16', NULL, '2016-01-27','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/A73bjnZOIEk',NULL),
  ('Open Philanthropy Project','Future of Research',300000,'2016-04-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/future-research-general-support','https://www.openphilanthropy.org/focus/scientific-research','Grantee is a new nonprofit with a stated mission “to improve the scientific research enterprise.” Grant is a preliminary one and Open Phil plans to revisit the organization after 2 years of progress', NULL, '2016-04-29','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/j31N12676aw',NULL),
  ('Open Philanthropy Project','Foundation for the National Institutes of Health',1228845,'2016-07-01','month','donation log','Scientific research/malaria/gene drive testing','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/foundation-national-institutes-health-working-group','https://www.openphilanthropy.org/focus/scientific-research','Grant to support ~20 experts recommending a consensus on field testing gene drives to fight malaria. This recommendation will include guidelines on how to safely field test gene drives for population modification and population suppression of vector mosquitoes in order to determine whether they could safely and ethically be deployed widely. FNIH and Gates Foundation have been the two big players in this area so far', NULL, '2016-08-01', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/39tSkTDR4vs',NULL),
  ('Open Philanthropy Project','Innovative Genomics Institute',63000,'2016-12-01','month','donation log','Scientific research/plant pathology','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/uc-berkeley-plant-pathology-workshop','https://www.openphilanthropy.org/focus/scientific-research','Money for a plant pathology workshop. Grantee housed at the University of California, Berkeley', NULL, '2017-03-27', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/YQPZywW2A8w',NULL),
  ('Open Philanthropy Project','CDC Foundation',1214437,'2016-09-01','month','donation log','Scientific research/malaria/mosquito cryopreservation','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/cdc-foundation-malaria-control-research','https://www.openphilanthropy.org/focus/scientific-research','Supplement to grant https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support to Target Malaria; see writeup for latter to understand grant reasoning', NULL, '2017-05-17','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Me2Motxn8xQ',NULL),
  ('Open Philanthropy Project','New Partnership for Africa’s Development',2350000,'2017-04-01','month','donation log','Scientific research/malaria/gene drive','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/new-partnership-africa-s-development-general-support','https://www.openphilanthropy.org/focus/scientific-research','Grant to the Planning and Coordinating Agency, the technical arm of the African Union, to support the evaluation, preparation, and potential deployment of gene drive technologies in some African regions. Part of a set of grants related to gene drives; see https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support for a larger grant to Target Malaria in the same domain and at around the same time','Claire Zabel', '2017-05-26','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/6od5J8N_vB0',NULL),
  ('Open Philanthropy Project','Duke University',81500,'2017-06-01','month','donation log','Scientific research/antiviral and inhibitor work','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/duke-university-timothy-haystead-hsp70','https://www.openphilanthropy.org/focus/scientific-research','Grant for work that will be led by Dr. Timothy Haystead, Professor of Pharmacology and Cancer Biology at the Duke University School of Medicine. Funding from this grant will allow Dr. Haystead to pay a specialized company to determine the molecular structure of the human Hsp70i protein in a complex with HS-72, and to hire a summer intern to support his antiviral and inhibitor work. The original grant amount was $49,500. In May 2018, $32,000 to the original award amount for additional work on the project.','Chris Somerville','2017-08-16','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Veich4FUgFM',NULL),
  ('Open Philanthropy Project','Future of Research',150000,'2017-07-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/future-research-exit-grant-2017','https://www.openphilanthropy.org/focus/scientific-research','Exit grant to allow grantee to find time for alternative funding sources. Follows a $300,000 grant made in 2016 for two years','Nick Beckstead','2017-08-21','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/BCHYfQlh8xk',NULL),
  ('Open Philanthropy Project','University of California, Berkeley',5000000,'2017-08-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/uc-berkeley-aging-related-research-conboy','https://www.openphilanthropy.org/focus/scientific-research','Grant over five years to support research on the basic biology of aging-related diseases and impairments, led by Dr. Irina Conboy. Grant is a result of https://www.openphilanthropy.org/research/cause-reports/mechanisms-aging (investigation into mechanisms of aging)','Heather Youngs','2017-11-03','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/RvDAoLSbFHE',NULL),
  ('Open Philanthropy Project','protocols.io',200000,'2017-12-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/protocols-io-platform-improvements','https://www.openphilanthropy.org/focus/scientific-research','Discretionary grant to ZappyLab, Inc (doing business as “protocols.io”) to support improvements to the protocols.io platform, which provides open access for science methods','Heather Youngs','2017-12-08','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/SReu0RkqPnM',NULL),
  ('Open Philanthropy Project','Beth Israel Deaconess Medical Center',2934400,'2018-01-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/beth-israel-deaconess-medical-center-clinical-trial-sepsis-therapy','https://www.openphilanthropy.org/focus/scientific-research','Grant to support Dr. Michael Donnino to conduct a multicenter clinical trial of a therapy for severe sepsis','Chris Somerville|Heather Youngs','2018-01-30','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/5XHsBDrlA3Q',NULL),
  ('Open Philanthropy Project','MIT Synthetic Neurobiology Group',2970000,'2016-03-01','month','donation log','Scientific research/neurobiology','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group','https://www.openphilanthropy.org/focus/scientific-research','Grant is to expand research at MIT Media Lab’s Center for Extreme Bionics. Among other things, the grantee is working on developing new methods and techniques for mapping the brain',NULL, '2016-05-09', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/a-W1_NVcHaI',NULL),
  ('Open Philanthropy Project','MIT Synthetic Neurobiology Group',3000000,'2018-02-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group-2018','https://www.openphilanthropy.org/focus/scientific-research','Grant over two years. Grantee group led by Ed Boyden. Followup to March 2016 grant, and made for similar reasons as that first grant: https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group','Chris Somerville|Heather Youngs','2018-03-08','day',NULL,NULL),
  ('Open Philanthropy Project','University of California, San Francisco',500000,'2018-02-01','month','donation log','Biosecurity and pandemic preparedness/Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/ucsf-research-antiviral-activity-hsp90-inhibitors','https://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity','Grant to support research led by Dr. Raul Andino to test the broad spectrum antiviral potential of several drugs. The grant will allow Dr. Andino to carry out tests of the effectiveness of two commercial-quality drugs against five different viruses. Original grant amount of $320,000 in February 2018, and an additional $180,000 added in June 2018 (grant page updated around 2018-06-29)','Chris Somerville|Heather Youngs','2018-03-24','day',NULL,NULL),
  ('Open Philanthropy Project','Research Institute of Industrial Economics',500000,'2016-08-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/research-institute-of-industrial-economics-genomic-research-methods','https://www.openphilanthropy.org/focus/scientific-research','Grant to the Research Institute of Industrial Economics (IFN) to support the Social Science Genetic Association Consortium (SSGAC). IFN is a private, non-profit research institute in Stockholm, Sweden, with around 40 researchers. Previous grant https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-southern-california-genomic-research-methods (2016-04) to the University of Southern California also supported SSGAC. Donor notes: "Our understanding is that SSGAC has received substantially less funding to date than comparable consortia (such as in psychiatric genetics), but still produces high-quality, replicable research and serves as a model of careful public communication"',NULL,'2018-04-19','day',NULL,NULL),
  ('Open Philanthropy Project','VasoRx',4700000,'2018-04-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/vasorx-atherosclerosis-investment','https://www.openphilanthropy.org/focus/scientific-research','Investment to test a new therapy for vascular diseases such as atherosclerosis and pulmonary hypertension. The original amount was $1.6 million. In January 2019, $3.1 million was addded to the amount, and the total on the website was updated to reflect this','Chris Somerville|Heather Youngs','2018-04-26','day',NULL,NULL),
  ('Open Philanthropy Project','Science Philanthropy Alliance',225000,'2018-04-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/science-philanthropy-alliance-general-support','https://www.openphilanthropy.org/focus/scientific-research','Discretionary grant over three years to join the Science Philanthropy Alliance, "a community of funders who work together to inspire new, emerging and current philanthropists to dedicate a portion of their philanthropy to basic science."','Chris Somerville|Heather Youngs','2018-05-15','day',NULL,NULL),
  ('Open Philanthropy Project','Mamoreruinochi wo Mamorukai',40000,'2018-02-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/mamoreruinochi-wo-mamorukai-legal-aid-for-scientists-in-japan','https://www.openphilanthropy.org/focus/scientific-research','Discretionary grant made by the Open Philanthropy Action Fund. Grantee, which translates roughly as Protect the Lives Protectable, is a Japanese organization that protects science journalists and scientists from attacks, insults, and litigation.','Chris Somerville|Heather Youngs','2018-07-06','day',NULL,NULL),
  ('Open Philanthropy Project','University of California, San Francisco',1021318,'2018-08-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-of-california-san-francisco-chronic-pain-research','https://www.openphilanthropy.org/focus/scientific-research','Grant over three years to support basic research on understanding the brain mechanisms that process pain messages and that contribute to the transition from acute to chronic pain after injury. The work will be led by Allan Basbaum, PhD, Professor and Chair of UCSF’s Department of Anatomy. This grant will allow UCSF to pursue an answer to the question of how the brain interprets various types of pain signals (e.g., heat, cold, mechanical) and itch, how these signals are regulated by different anesthetics and how they are altered when there is injury. Resolving these questions could facilitate the design of novel drugs that can block pain without also blocking consciousness.','Chris Somerville|Heather Youngs','2018-09-21','day',NULL,NULL),
  ('Open Philanthropy Project','University of California, Berkeley',200000,'2018-10-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-of-california-berkeley-research-on-drought-tolerant-rice-by-prof-brian-staskawicz','https://www.openphilanthropy.org/focus/scientific-research','Discretionary grant over three years to support the editing of the rice genome for increased drought tolerance led by Professor Brian Staskawicz. The work involves using CRISPR modifications to increase drought tolerance on Indian rice, and the goal is to address the problem of erratic rice yields which have negative impoact on the livelihoods of 100 million small farmers. The experiments are funded in part my a match from the Innovative Genomics Institute. This follows the plant pathology workshop grant of December 2016 https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/uc-berkeley-plant-pathology-workshop','Chris Somerville|Heather Youngs','2018-10-23','day',NULL,NULL),
  ('Open Philanthropy Project','CDC Foundation',1044501,'2018-10-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/cdc-foundation-malaria-control-research-project-2018','https://www.openphilanthropy.org/focus/scientific-research','Grant to support research on malaria control. This funding will be used to support work on the cryopreservation of mosquito larvae (which, if successful, would make it easier for researchers to maintain different strains of mosquitoes) and on RNA interference (which, if successful, would make it easier for researchers to avoid releasing female mosquitoes — which could potentially spread malaria — as part of field trials). Related previous grant https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/cdc-foundation-malaria-control-research (September 2016) and related grant to Target Malaria https://www.openphilanthropy.org/focus/scientific-research (May 2017)','Chris Somerville|Heather Youngs','2018-10-30','day',NULL,NULL),
  ('Open Philanthropy Project','Duke University',2550171,'2018-10-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/duke-university-CRISPR-Based-Epigenome-Editing-Tools','https://www.openphilanthropy.org/focus-area/scientific-research/scientific-innovation-tools-and-techniques','Grant over three years to Duke University to develop tools to apply epigenome editing to refine genome wide association studies (GWAS). The work will be led by Charles Gersbach, the Rooney Family Associate Professor of Biomedical Engineering. This funding will support research to develop CRISPR-based epigenetic tools to interrogate thousands of regions of DNA, allowing for more nuanced studies of genomic regions identified through GWAS. The grant will also fund testing and verification of the tools by identifying loci implicated in schizophrenia, a poorly understood disorder.','Chris Somerville|Heather Youngs','2018-10-30','day',NULL,NULL),
  ('Open Philanthropy Project','Boston Children''s Hospital',1695376,'2018-10-01','month','donation log','Scientific research','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/boston-childrens-hospital-chronic-pain-research','https://www.openphilanthropy.org/focus/scientific-research','Grant over four years to conduct basic research into the epigenetics of chronic pain. The work will be led by Yi Zhang, a Howard Hughes Medical Institute investigator and the Fred Rosen Chair Professor of Genetics at Harvard Medical School and Boston Children’s Hospital. This funding will support research to identify 1) specific neurons in a region of the brain involved in processing environmental stimulation into associative learning; 2) changes in gene expression and epigenetic modification in neurons associated with chronic pain; and 3) feedback and modulatory processes that may be involved in resolving pain signals and neuronal sensitivity.','Chris Somerville|Heather Youngs','2018-11-27','day',NULL,NULL),
  ('Open Philanthropy Project','Georgia Institute of Technology',50000,'2018-12-01','month','donation log','Scientific research/transformative basic science/Innocentive challenge','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/georgia-institute-of-technology-saad-bhamla','https://www.openphilanthropy.org/focus-area/scientific-research/transformative-basic-science','Grant to support research led by Dr. Saad Bhamla. Dr. Bhamla’s proposal, “Feathers as extreme water pumps,” was submitted in response to the Open Philanthropy Project''s Innocentive challenge https://www.innocentive.com/ar/challenge/9934081 on bioinspiration and unusual biology. While this funding is not restricted to the execution of that proposal, the Open Philanthropy Project science team believes Dr. Bhamla''s lab conducts other creative research, and wants to reward the spirit of creative science.','Chris Somerville|Heather Youngs','2019-02-12','day',NULL,NULL),
  ('Open Philanthropy Project','The University of Minnesota, Twin Cities',150000,'2018-12-01','month','donation log','Scientific research/transformative basic science/Innocentive challenge','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-of-minnesota-nanomaterials-research-led-by-prof-claudia-schmidt-dannert','https://www.openphilanthropy.org/focus-area/scientific-research/transformative-basic-science','Grant to support nanomaterials research led by Professor Claudia Schmidt-Dannert. Professor Schmidt-Dannert’s proposal, titled “Genetically programmable, adhesive nanomaterials as patterned and functional surface coatings,” is the grand prize winner of the Open Philanthropy Project''s Innocentive challenge https://www.innocentive.com/ar/challenge/9934081 on bioinspiration and unusual biology. The Open Philanthropy Project science team believes Professor Schmidt-Dannert could be able to design new materials with applications such as anti-fouling, anti-corrosion, and anti-freeze coatings, as well as coatings for biomedical applications.','Chris Somerville|Heather Youngs','2019-02-12','day',NULL,NULL),
  ('Open Philanthropy Project','Center for Global Development',333550,'2019-01-01','month','donation log','Scientific research/human health and wellbeing','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/center-for-global-development-gene-drive-research','https://www.openphilanthropy.org/focus-area/scientific-research/human-health-and-wellbeing','Discretionary grant to support research on the assessment and regulation of gene drive technology. CGD plans to use this grant to identify key political and social considerations that may inform global decisions on the development and deployment of gene drive technology, particularly with respect to malaria. CGD will conduct interviews and site visits to develop a better understanding of regulatory, social, and political considerations at play in different contexts. The research will be led by Gyude Moore, CGD visiting fellow and former Minister of Public Works in Liberia.','Alexander Berger','2019-02-15','day',NULL,NULL),
  ('Open Philanthropy Project','EicOsis Human Health, Inc.',5000000,'2018-11-01','month','donation log','Scientific research/human health and wellbeing','https://www.openphilanthropy.org/giving/grants/eicosis-human-health-inc-pain-research','https://www.openphilanthropy.org/focus-area/scientific-research/human-health-and-wellbeing','Grant to support clinical trials on a novel, non-opioid, oral therapy for neuropathic and inflammatory pain. The Open Philanthropy Project believes alternate therapies for chronic pain could help address the epidemic of opioid abuse and addiction. EicOsis previously received Blueprint funding https://neuroscienceblueprint.nih.gov/ for neuroscience research from the National Institutes of Health. This seed-stage investment is intended to support continued early research and development in the hopes that EicOsis can subsequently raise additional funds from other investors.','Chris Somerville|Heather Youngs','2019-02-15','day',NULL,NULL),
  ('Open Philanthropy Project','Kyoto University',4000000,'2019-04-01','month','donation log','Scientific research/transformative basic science/stem cell research','https://www.openphilanthropy.org/giving/grants/kyoto-university-research-reproductive-biology-mitinori-saitou','https://www.openphilanthropy.org/focus-area/scientific-research/transformative-basic-science','Grant to support research by Professor Mitinori Saitou on reproductive biology. Dr. Saitou has been at the forefront of research into methods of causing induced pluripotent stem cells to develop into oocytes in mice. Progress in this area could eventually enable people with fertility challenges to have children and could eventually help reduce the incidence of a wide variety of high-burden disorders (such as heart disease, chronic pain, depression, and Alzheimer’s disease) and lead to other beneficial outcomes.','Chris Somerville|Heather Youngs','2019-04-23','day',NULL,NULL),
  ('Open Philanthropy Project','University Health Network',1134975,'2019-02-01','month','donation log','Scientific research/human health and wellbeing','https://www.openphilanthropy.org/focus/scientific-research/university-health-network-preterm-birth-research','https://www.openphilanthropy.org/focus-area/scientific-research/human-health-and-wellbeing','Grant to the University Health Network, a Canadian research center affiliated with the University of Toronto, to support a randomized controlled trial investigating the efficacy of an intervention to reduce preterm birth in Malawi. Preterm birth is a leading cause of global under-five mortality, resulting in over 1 million deaths each year. The research will be led by Kevin Kain and Chloe McDonald','Heather Youngs','2019-04-26','day',NULL,NULL);
  
# -- Scientific research -- transformative R01 "second chance"
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes,influencer,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','Arizona State University',6421402,'2017-11-01','month','donation log','Scientific research/transformative R01','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/arizona-state-university-canine-clinical-trial-multivalent-cancer-vaccine','https://www.openphilanthropy.org/focus/scientific-research','Grant to be used in support of a canine clinical trial to assess the effectiveness of a multivalent, preventative cancer vaccine. The trial will test the cancer-prevention efficacy of a multi-valent frameshift peptide (FSP) vaccine, developed by Dr. Stephen Albert Johnston, in healthy, middle-aged pet dogs. The trial will be conducted under the direction of Dr. Douglas Thamm, Director of Clinical Research at the Flint Animal Cancer Center at Colorado State University. Part of a set of "second chance" grants by the Open Philanthropy Project for some rejected applications for the NIH Transformative R01 program https://commonfund.nih.gov/tra discussed at https://www.openphilanthropy.org/blog/our-second-chance-program-nih-transformative-research-applicants and https://www.nature.com/articles/d41586-017-08795-0','Heather Youngs','2017-12-20','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/tjCx1IUDQmM',NULL),
  ('Open Philanthropy Project','University of Notre Dame',2054142,'2017-06-01','month','donation log','Scientific research/transformative R01','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/university-notre-dame-nanopore-protein-sequencing-development','https://www.openphilanthropy.org/focus/scientific-research','Grant over three years to the University of Notre Dame to support the development of an instrument that uses a sub-nanometer-diameter pore (i.e. a sub-nanopore) to read the amino acid sequence of whole protein molecules. The collaborative effort led by Dr. Gregory Timp involves researchers at the University of San Diego and Johns Hopkins University. Part of a set of "second chance" grants by the Open Philanthropy Project for some rejected applications for the NIH Transformative R01 program https://commonfund.nih.gov/tra discussed at https://www.openphilanthropy.org/blog/our-second-chance-program-nih-transformative-research-applicants and https://www.nature.com/articles/d41586-017-08795-0','Heather Youngs','2017-12-20','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/tjCx1IUDQmM',NULL),
  ('Open Philanthropy Project','Rockefeller University',1600000,'2017-04-01','month','donation log','Scientific research/transformative R01','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/rockefeller-university-viral-histone-mimics','https://www.openphilanthropy.org/focus/scientific-research','Grant to support research on viral histone mimics led by Professor Alexander Tarakhovsky. Professor Tarakhovsky has discovered a novel mechanism through which viruses may influence host gene expression: he found that in influenza H3N2, the non-structural 1 (NS1) protein acts to downregulate antiviral genes (i.e. weaken host defense systems) by mimicking human histone 3, which interferes with normal histone regulation in the host cell. Professor Tarakhovsky and his collaborators plan to use this grant to further explore this mechanism in the life cycle of the yellow fever virus and to determine whether the mechanism occurs in other host-virus interactions. Part of a set of "second chance" grants by the Open Philanthropy Project for some rejected applications for the NIH Transformative R01 program https://commonfund.nih.gov/tra discussed at https://www.openphilanthropy.org/blog/our-second-chance-program-nih-transformative-research-applicants and https://www.nature.com/articles/d41586-017-08795-0 Original grant amount $1.5 million; an additional $100,000 added to grant in July 2018 (page update: 2018-07-10)','Heather Youngs','2017-12-20','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/tjCx1IUDQmM',NULL),
  ('Open Philanthropy Project','University of California, San Francisco',825000,'2017-06-01','month','donation log','Scientific research/transformative R01','https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/ucsf-liver-regeneration-experiments','https://www.openphilanthropy.org/focus/scientific-research','Grant over three years to the University of California, San Francisco (UCSF) to support research into the development of a stem cell treatment method for repairing or replacing damaged human livers. The work will be led by Tammy T. Chang, MD, PhD, assistant professor in the UCSF Department of Surgery. Part of a set of "second chance" grants by the Open Philanthropy Project for some rejected applications for the NIH Transformative R01 program https://commonfund.nih.gov/tra discussed at https://www.openphilanthropy.org/blog/our-second-chance-program-nih-transformative-research-applicants and https://www.nature.com/articles/d41586-017-08795-0','Chris Somerville','2017-12-20','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/tjCx1IUDQmM',NULL);
