# -- California Renters Legal Advocacy and Education Fund

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, affected_states, affected_cities, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy Project','California Renters Legal Advocacy and Education Fund',300000,'2016-06-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','United States','California','San Francisco','Alexander Berger','2016-06-28','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/O3uYqTZBFkE',NULL,
  /* donation_process */ 'According to https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Our_process "Alexander Berger, who leads our work on land use reform, heard from Trauss that she was planning to start a new organization focused on land use reform in the Bay Area."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds*/ 'Grantee is a nascent advocacy organization that intends to litigate and advocate against regulatory barriers to building housing in the San Francisco Bay Area. More at https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Proposed_activities',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'According to https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Case_for_the_grant (1) The San Francisco Bay Area is a key region for land use reform, (2) The founder, Sonja Trauss, has been able to attract some public interest to the issue in San Francisco through the SF Bay Area Renters’ Federation (SFBARF), which she also founded.',
  /* donor_amount_reason */ 'There is background at https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Budget_and_room_for_more_funding saying the organization has received $100,000 from another donor, and may be able to raise more funding if it attempts',
  /* donor_timing_reason */ 'This is (sort of) a founding grant to a nascent advocacy organization',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Open Philanthropy Project','California Renters Legal Advocacy and Education Fund',400000,'2019-02-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support-2019','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','United States','California',NULL,'Alexander Berger','2019-05-18','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grantee intends to continue pursuing litigation, advocating against regulatory barriers to building housing in the San Francisco Bay Area, and developing educational resources.',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'Renewal of previous June 2016 grant https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

# -- Land use reform/United States

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, influencer, affected_countries, affected_states, affected_cities,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy Project','East Bay Forward',40000,'2017-04-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/east-bay-forward-yimbytown-2017-conference','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Money to support a YIMBYtown 2017 conference planned for July 2017. Grant via the California Renters Legal Advocacy and Education Fund (CaRLA). Follows up on grant https://www.openphilanthropy.org/focus/us-policy/land-use-reform/better-boulder-yimby-2016 to Better Boulder supporting the YIMBY 2016 conference','Alexander Berger','United States',NULL,NULL,'2017-07-07','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/YPBvXvkkB1w',NULL),
  ('Open Philanthropy Project','Better Boulder',37000,'2016-04-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/better-boulder-yimby-2016','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Money to support a conference of land use reform advocates from around the United States and Canada, called YIMBY 2016, in Boulder, Colorado. YIMY = Yes, In My Backyard" is a play on the corresponding more famous opposite acronym NIMBY', NULL, 'United States|Canada', NULL, NULL, '2016-05-09','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/pkD3HWSPamM',NULL),
  ('Open Philanthropy Project','Sightline Institute',400000,'2015-10-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/sightline-institute-housing-and-urban-development','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Grant distribution over two years. Grant would support Sightline’s work to promote a package of land use reforms in Seattle that combines increases in market rate and below market rate housing. Followup conversation with Alan Durning of grantee organization at https://www.openphilanthropy.org/sites/default/files/Alan_Durning_07-05-16_%28public%29.pdf on 2016-07-05', NULL, 'United States','Washington','Seattle', '2016-02-03', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/MfSir1g7pgQ',NULL),
  ('Open Philanthropy Project','Seattle for Everyone',50000,'2016-02-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/seattle-everyone-general-support','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Recipient is a coalition of various interest groups (including market rate developers, affordable housing developers, labor and social justice advocates, businesses, environmentalists, and urbanists) formed to promote the same set of proposed land use reforms in Seattle that Sightline Institute (another Open Phil grantee) also promotes. No detailed writeup',NULL, 'United States','Washington','Seattle', '2016-03-30', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/7DX0fvv6aOI',NULL),
  ('Open Philanthropy Project','Urban Institute',97865,'2015-09-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/urban-institute-land-use-convening','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Funds research project and convening aimed at identifying policy changes that would allow more housing supply in the Washington, D.C. metropolitan area.',NULL, 'United States',NULL,'Washington, D.C.', '2015-10-06', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/YdjFV6LbrOA',NULL),
  ('Open Philanthropy Project','Smart Growth America',275000,'2015-07-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/smart-growth-america-greater-greater-washington-education-project','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','To support Smart Growth America’s Greater Greater Washington Education Project. Greater Greater Washington (GGW) is a group blog that covers local policy issues, such as housing, education, and transportation, in the greater Washington, D.C. metro area. Followup conversation with David Alpert, Sarah Guidi, and Jonathan Neeley of grante organization at https://www.openphilanthropy.org/sites/default/files/David_Alpert_Sarah_Guidi_and_Jonathan_Neeley_12-16-2015_%28public%29.pdf on 2015-12-16. Second followup conversation with David Alpert, Sarah Guidi, and David Whitehead of grantee organization at https://www.openphilanthropy.org/sites/default/files/David_Alpert_Sarah_Guidi_David_Whitehead_06-07-16_%28public%29.pdf on 2016-06-07',NULL, 'United States',NULL,'Washington, D.C.', '2015-07-28', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/4Bht6il4iX0',NULL),
  ('Open Philanthropy Project','Greater Greater Washington',250000,'2017-06-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/greater-greater-washington-housing-and-land-use-reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Grant to support work on housing affordability and land use reform, and the grant writeup cites the existing coalition http://www.dchousingpriorities.org/ as impressive evidence of progress so far','Alexander Berger','United States',NULL,'Washington, D.C.','2017-08-11','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/iyErXoVcmSE',NULL),
  ('Open Philanthropy Project','Sightline Institute',350000,'2017-10-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/sightline-institute-housing-and-urban-development-2017','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Grant supports work on housing and urban development. The grant renews a 2015-10 grant https://www.openphilanthropy.org/focus/us-policy/land-use-reform/sightline-institute-housing-and-urban-development for a similar purpose, but focused on Seattle. Grantee intends to use this funding to continue promoting the Housing Affordability and Livability Advisory Committee’s (HALA) land use reform agenda in Seattle, and to promote similar reforms nationally by disseminating lessons learned from the Seattle initiative.','Alexander Berger','United States',NULL,NULL,'2017-11-14','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/jYBHdqr_zAQ',NULL),
  ('Open Philanthropy Project','Harborlight Community Partners',40000,'2018-03-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/harborlight-community-partners-YIMBYtown-2018','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Discretionary grant to support the 2018 national "Yes In My Back Yard" conference, scheduled to take place in Boston, Masschusetts, in September. Open Phi has supported the conference for two previous years: https://www.openphilanthropy.org/focus/us-policy/land-use-reform/better-boulder-yimby-2016 (2016, grant to Better Boulder, organizing the conference in Boulder, Colorado), and https://www.openphilanthropy.org/focus/us-policy/land-use-reform/east-bay-forward-yimbytown-2017-conference (2017, to East Bay Forward, organizing the conference in Oakland, California)','Alexander Berger','United States',NULL,NULL,'2018-04-12','day',NULL,NULL),
  ('Open Philanthropy Project','California YIMBY',500000,'2018-04-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-yimby-general-support','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Grant to new organization founded by people that Open Phil previously funded at CaRLA (California Renters Legal Advocacy Fund): https://www.openphilanthropy.org/focus/us-policy/land-use-reform who successfully sponsored legislation in 2017 to strengthen California’s Housing Accountability Act, and who subsequently saw sufficient opportunity and need for statewide legislative advocacy to justify a new organization.','Alexander Berger','United States','California',NULL,'2018-05-24','day',NULL,NULL),
  ('Open Philanthropy Project','California YIMBY',350000,'2018-08-01','month','donation log','Land use reform','https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-yimby-general-support-august-2018','https://www.openphilanthropy.org/focus/us-policy/land-use-reform','Grant by the Open Philanthropy Action Fund to complete a match that had been established at the same time as the previous general operating support grant https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-yimby-general-support California YIMBY plans to use our support to hire additional staff members to focus on organizing, communications, digital outreach, data and analytics, and finance and operations.','Alexander Berger','United States','California',NULL,'2018-09-28','day',NULL,NULL);

