# -- Alexander Berger donations

insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, influencer) values
  # -- 2013
  ('Alexander Berger','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Actually, split evenly between giving now and waiting, but all the amount actually given went to GiveDirectly. Two main upside points: (1) May not remain a GiveWell top recommendation, so more need to grow enough to develop a non-GiveWell funding stream, (2) Helps to set cash as a baseline for recommendations','GiveWell'),
  # -- 2014
  ('Alexander Berger','GiveWell',NULL,0.1,'2014-12-17','day','date of donation announcement','Charity evaluator','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Does not like dynamic of asking people familiar with GiveWel work to donate entirely to GiveWell instead of top charities, and thinks a 10% to GiveWell rule makes more sense. So, doing that himself','GiveWell'),
  ('Alexander Berger','Against Malaria Foundation',NULL,0.7,'2014-12-17','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Giving a bit more to AMF than the recommended allocation that would work, because it seems more promising','GiveWell'),
  ('Alexander Berger','Schistosomiasis Control Initiative',NULL,0.1,'2014-12-17','day','date of donation announcement','Global health/deworming','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Less than GiveWell allocation target because of increased funding to AMF and 10% for GiveWell operations','GiveWell'),
  ('Alexander Berger','GiveDirectly',NULL,0.1,'2014-12-17','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Correct target after removing 10% for GiveWell and adjusting for non-donation to Deworm the World Initiative','GiveWell'),
  # -- 2015
  ('Alexander Berger','Against Malaria Foundation',NULL,0.9,'2015-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','More confidence in cost-effectiveness model and in GiveWell recommendation to donate almost all to AMF. 10% for other causes for other reasons','GiveWell'),
  ('Alexander Berger','GiveWell',NULL,0.05,'2015-12-09','day','date of donation announcement','Charity evaluator','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Reduced from 10% to 5% from last year. Reasons for donating a bit to GiveWell same as last year: wants to set and follow a norm of donating a bit to GiveWell. Due to increase in money moved (relative to cost of running GiveWell), reducing percentage from 10% to 5%','GiveWell'),
  ('Alexander Berger','GiveDirectly',NULL,0.05,'2015-12-09','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Outstanding organization and valuable for setting cash transfer benchmark','GiveWell'),
  # -- 2016
  ('Alexander Berger','GiveWell top charities',NULL,0.8,'2016-12-09','day','date of donation announcement','Global health and cash transfers','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Less than the 90% last year. Partly because of less urgency around top charities, and optimism regarding better opportunities to be found by the Open Philanthropy Project','GiveWell'),
  ('Alexander Berger','GiveWell',NULL,0.05,'2016-12-09','day','date of donation announcement','Charity evaluator','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Same reasons as in 2015: set a norm of donors giving to GiveWell to support their research','GiveWell'),
  ('Alexander Berger','GiveDirectly',NULL,0.05,'2016-12-09','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Same reasons as in 2015: outstanding organization and valuable for cash benchmark','GiveWell'),
  # -- Remaining 10% to as yet unspecified animal welfare charities
  # -- 2017
  ('Alexander Berger','GiveWell top charities',NULL,0.8,'2017-12-18','day','date of donation announcement','Global health and cash transfers','https://www.openphilanthropy.org/blog/staff-members-personal-donations-giving-season-2017#Alexander','Same allocation as in 2016, for same reasons','GiveWell'),
  ('Alexander Berger','GiveWell',NULL,0.05,'2017-12-18','day','date of donation announcement','Charity evaluator','https://www.openphilanthropy.org/blog/staff-members-personal-donations-giving-season-2017#Alexander','Same allocation as in 2016, for same reasons','GiveWell'),
  ('Alexander Berger','GiveDirectly',NULL,0.05,'2017-12-18','day','date of donation announcement','Cash transfers','https://www.openphilanthropy.org/blog/staff-members-personal-donations-giving-season-2017#Alexander','Same allocation as in 2016, for same reasons','GiveWell');
  #  -- 10% to as-yet-unspecified animal welfare charities recommended by Lewis Bollard

