# -- Andrew Martin donations
insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, influencer) values
  # -- 2015
  ('Andrew Martin','Against Malaria Foundation',NULL,0.9,'2015-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Slight deviation from the GiveWell recommendation of donating 100% to AMF (instead, donating only 90%) because of attraction to GiveDirectly as an opportunity with a low burden of proof','GiveWell'),
  ('Andrew Martin','GiveDirectly',NULL,0.1,'2015-12-09','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Slight deviation from the GiveWell recommendation by donating 10% to GiveDirectly because of attraction to GiveDirectly as an opportunity with a low burden of proof', 'GiveWell'),
  # -- 2016
  ('Andrew Martin','Against Malaria Foundation',NULL,0.75,'2016-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Donation in line with GiveWell recommendation (75% to Against Malaria Foundation, 25% to Schistosomiasis Control Initiative)', 'GiveWell'),
  ('Andrew Martin','Schistosomiasis Control Initiative',NULL,0.25,'2016-12-09','day','date of donation announcement','Global health/deworming','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Donation in line with GiveWell recommendation (75% to Against Malaria Foundation, 25% to Schistosomiasis Control Initiative)', 'GiveWell'),
  # -- 2017
  ('Andrew Martin','GiveWell top charities',NULL,1.0,'2017-12-11','day','date of donation announcement','Global health and cash transfers','https://blog.givewell.org/2017/12/11/staff-members-personal-donations-for-giving-season-2017/#Andrew','Donor decided to grant to GiveWell for regranting, rather than directly donating to top charities, because of his belief in the importance of the flexibility GiveWell gets to provide funding to whichever charities have the most pressing funding needs', 'GiveWell');
