# -- Catherine Hollander donations
insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes) values
  # -- 2015 donations
  ('Catherine Hollander','Against Malaria Foundation',NULL,0.95,'2015-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','This is the first giving season for the donor since she started working at GiveWell. She is convinced by the GiveWell charity evaluation process, and is therefore donating 95% based on the GiveWell recommendation. The remaining 5% will be donated to a charity working in the animal welfare/factory farming area, though the details are not yet decided'),
  # -- 2016 donations
  ('Catherine Hollander','Against Malaria Foundation',NULL,0.75,'2016-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','This part of the donation was based on the recommended allocation by GiveWell (75% to AMF)'),
  ('Catherine Hollander','Malaria Consortium',NULL,0.25,'2016-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','This part of the donation (25% to Malaria Consortium) deviates from the recommended allocation by GiveWell (which suggested 25% to the Schistosomiasis Control Initiative). The reason for selecting Malaria Consortium is the high value placed by the donor on health outcomes relative to improving income'),
  # -- 2017 donations
  ('Catherine Hollander','Against Malaria Foundation',NULL,0.9,'2017-12-11','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2017/12/11/staff-members-personal-donations-for-giving-season-2017/#Catherine','Donation (90% to AMF) is based on trust in the GiveWell process and its recommendation of the AMF gap as the most important one to fill'),
  ('Catherine Hollander','No Lean Season',NULL,0.1,'2017-12-11','day','date of donation announcement','Seasonal intracountry migration','https://blog.givewell.org/2017/12/11/staff-members-personal-donations-for-giving-season-2017/#Catherine','Like Sophie Monahan, the donor plans to support No Lean Season with 10% of her total giving to increase the visibility of the new top charity, and based on being impressed with its work');
