# -- Old GiveWell donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Dario Amodei','VillageReach',10000, 1.0, '2009-01-01','year','date of donation announced in announcement','Global health/vaccination','http://blog.givewell.org/2010/06/03/my-donation-for-2009-guest-post-from-dario-amodei/','Compared against Stop TB',NULL, NULL, 10000, 'GiveWell', NULL, NULL),
    ('Eric Friedman','Freedom from Hunger Fund',1000,NULL,'2006-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','Africare',2500,NULL,'2006-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','CARE',2500,NULL,'2006-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','Freedom from Hunger Fund',28000,NULL,'2008-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation. Relevant quote: In early 2007, my life took a turn for the better: I met the woman who is now my wife. In 2008, Freedom from Hunger offered us the opportunity to join them (at our expense) on a site visit to some of their programs in Ghana. During our time there, we spent a significant amount of time with some of their senior staff (including the CEO), three board members, program staff, and their clients. We saw the programs in action, which increased our conviction in what they do.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','Freedom from Hunger Fund',27000,NULL,'2009-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation. Relevant quote: I started following GiveWell in 2009. It was clear from their blog that we shared similar values, and I loved what they were trying to do. But I disagreed with some aspects of their approach. Their emphasis on measurement seemed excessive. This approach had a built-in bias towards smaller, single-program organizations that could measure their impact more precisely. I wasn’t convinced that there weren’t economies of scale in international development. And their focus on scaling up existing solutions and excluding funding unproven innovations seemed incomplete. While I liked what they were doing, I still had more conviction in my own ability to pick organizations.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','GiveWell top charities',31000,NULL,'2010-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Relevant quote: Eventually, we decided that there was one fundamental principle we should apply: giving was primarily about helping the less fortunate, not our friendships or personal interests. Breaking up with Freedom from Hunger would be hard. I explained our reasoning and they took it in stride, demonstrating that they care more about the less fortunate than their own institutional growth. They are a good group. But in 2010, we gave about $31,000 to GiveWell’s donor advised fund to ultimately be distributed as they recommended.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Ian Turner','VillageReach',35000,1.0,'2009-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2010/10/28/the-process-of-giving-a-personal-story-guest-post-from-ian-turner/','Last minute decision change from Population Services International based on news that VillageReach is starting a new program similar to its original pilot',NULL,NULL,NULL,'GiveWell',NULL,NULL);

# -- Eva Vivalt
insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Eva Vivalt','AidGrade',NULL,1.0,'2016-12-09','day','date of donation announcement','International aid/global health/global poverty/evaluation','http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/','AidGrade was founded by Eva Vivalt. She describes the donation as "putting my money where my mouth is"',NULL,NULL,NULL,NULL,NULL,NULL);

# -- Jacob Trefethen
insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Jacob Trefethen','Environmental Data and Governance Initiative',NULL,1.0,'2017-01-16','day','date of donation announcement','Environmentalism/watchdog','http://effective-altruism.com/ea/16b/why_i_donated_to_the_environmental_data/','Donation made to small nonprofit based on inside information and close contact with the organization, making it easier to evaluate',NULL,NULL,NULL,NULL,NULL,NULL);

# -- Blake Borgeson donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Blake Borgeson','Machine Intelligence Research Institute',50640,NULL,'2015-01-01','year','donee contributor list','AI risk','https://intelligence.org/topdonors/','Took total donation amount and subtracted known donation of 300000 for 2016',NULL, NULL, NULL, NULL, NULL, NULL),
    ('Blake Borgeson','Machine Intelligence Research Institute',300000,0.50,'2016-01-01','year','donee contributor list','AI risk','https://intelligence.org/2016/08/05/miri-strategy-update-2016/','Second biggest donation in the history of MIRI, see also http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/ for more context on overall donations for the year',NULL, NULL, NULL, NULL, NULL, NULL),
    ('Blake Borgeson','Center for Applied Rationality',90000,0.15,'2016-01-01','year','date of donation announced in announcement',NULL,'http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/','Borgeson did not specify numerical amounts but gave percentages, combined these with other info of 300000 dollars to MIRI in https://intelligence.org/2016/08/05/miri-strategy-update-2016/',NULL, NULL, NULL, NULL, NULL, NULL);

# -- Holden Karnofsky donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Holden Karnofsky','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','First considers not giving, then makes some argument on why it is better to give. Then looks at confidence multipliers for global health interventions relative to GiveDirectly and thinks they are not robust enough to overcome the case for GiveDirectly',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Holden Karnofsky','GiveWell top charities',NULL,1.0,'2014-12-17','day','date of donation announcement','Global health and cash transfers','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Giving opportunities in 2014 better than 2013, so giving a bit but to regrant to top charities',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Holden Karnofsky','Against Malaria Foundation',NULL,1.0,'2015-12-09','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Though not directly involved with top charity selection, found the top charity vetting process much more convincing this year, and placed more confidence in cost-effectiveness estimates. Considered other top charities seriously',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Holden Karnofsky','A political campaign',NULL,NULL,'2016-12-09','day','date of donation announcement','Politics/United States','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','States "Earlier this year, I gave to a political campaign that I considered important and high-impact per dollar. This falls under (a) because there are per-individual contribution limits." Details of political campaign not specified, but 2016 is a presidential election year in the United States',NULL,NULL,NULL,'GiveWell',NULL,NULL);

# -- Elie Hassenfeld donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Elie Hassenfeld','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Agrees with reasoning by Holden (in same blog post) but discounts deworming cost-effectiveness estimates entirely. Asked GiveDirectly not to include donation in Good Ventures match',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Elie Hassenfeld','Against Malaria Foundation',NULL,0.45,'2014-12-17','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Lower allocation to AMF (45%) relative to GiveWell allocation (67%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Elie Hassenfeld','GiveDirectly',NULL,0.45,'2014-12-17','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Higher allocation to GiveDirectly (45%) relative to GiveWell allocation (13%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Elie Hassenfeld','Schistosomiasis Control Initiative',NULL,0.05,'2014-12-17','day','date of donation announcement','Global health/deworming','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Lower allocation to SCI (5%) relative to GiveWell allocation (13%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Elie Hassenfeld','Deworm the World Initiative',NULL,0.05,'2014-12-17','day','date of donation announcement','Global health/deworming','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Lower allocation to DtWI (5%) relative to GiveWell allocation (7%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Elie Hassenfeld','Against Malaria Foundation',NULL,1.0,'2015-12-09','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','More confidence in cost-effectiveness model and in GiveWell recommendation to donate all to AMF',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Elie Hassenfeld','A political campaign',NULL,NULL,'2016-12-09','day','date of donation announcement','Politics/United States','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','States "I already gave a significant portion of this year’s donation to a political campaign, so I’m planning to give less at the end of this year than I have in previous years." Details of political campaign not specified, but 2016 is a presidential election year in the United States',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Elie Hassenfeld','GiveWell top charities',NULL,NULL,'2016-12-09','day','date of donation announcement','Global health and cash transfers','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','This donation covered all the end-of-year giving, and all giving left from after the donation to "a political campaign"',NULL,NULL,NULL,'GiveWell',NULL,NULL);

# -- Alexander Berger donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Alexander Berger','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Actually, split evenly between giving now and waiting, but all the amount actually given went to GiveDirectly. Two main upside points: (1) May not remain a GiveWell top recommendation, so more need to grow enough to develop a non-GiveWell funding stream, (2) Helps to set cash as a baseline for recommendations',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','GiveWell',NULL,0.1,'2014-12-17','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Does not like dynamic of asking people familiar with GiveWel work to donate entirely to GiveWell instead of top charities, and thinks a 10% to GiveWell rule makes more sense. So, doing that himself',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','Against Malaria Foundation',NULL,0.7,'2014-12-17','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Giving a bit more to AMF than the recommended allocation that would work, because it seems more promising',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','Schistosomiasis Control Initiative',NULL,0.1,'2014-12-17','day','date of donation announcement','Global health/deworming','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Less than GiveWell allocation target because of increased funding to AMF and 10% for GiveWell operations',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','GiveDirectly',NULL,0.1,'2014-12-17','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Correct target after removing 10% for GiveWell and adjusting for non-donation to Deworm the World Initiative',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','Against Malaria Foundation',NULL,0.9,'2015-12-09','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','More confidence in cost-effectiveness model and in GiveWell recommendation to donate almost all to AMF. 10% for other causes for other reasons',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','GiveWell',NULL,0.05,'2015-12-09','day','date of donation announcement','Charity evaluator','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Reduced from 10% to 5% from last year. Reasons for donating a bit to GiveWell same as last year: wants to set and follow a norm of donating a bit to GiveWell. Due to increase in money moved (relative to cost of running GiveWell), reducing percentage from 10% to 5%',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','GiveDirectly',NULL,0.05,'2015-12-09','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Outstanding organization and valuable for setting cash transfer benchmark',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Alexander Berger','GiveWell top charities',NULL,0.8,'2016-12-09','day','date of donation announcement','Global health and cash transfers','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Less than the 90% last year. Partly because of less urgency around top charities, and optimism regarding better opportunities to be found by the Open Philanthropy Project',NULL,NULL,NULL,'GiveWell',NULL,NULL),
     ('Alexander Berger','GiveWell',NULL,0.05,'2016-12-09','day','date of donation announcement','Charity evaluator','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Same reasons as in 2015: set a norm of donors giving to GiveWell to support their research',NULL,NULL,NULL,'GiveWell',NULL,NULL),
     ('Alexander Berger','GiveDirectly',NULL,0.05,'2016-12-09','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Same reasons as in 2015: outstanding organization and valuable for cash benchmark',NULL,NULL,NULL,'GiveWell',NULL,NULL);

# -- Josh Rosenberg donations
insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Josh Rosenberg','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Split donation in half, one half for giving now and the other half for giving next year at the latest. The half to give now went entirely to GiveDirectly',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Josh Rosenberg','GiveWell top charities',NULL,1.0,'2014-12-17','day','date of donation announcement','Global health and cash transfers','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','More convinced of GiveWell allocation recommendation, so following that',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Josh Rosenberg','Against Malaria Foundation',NULL,0.8,'2015-12-09','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','More confidence in cost-effectiveness model and in GiveWell recommendation to donate almost all to AMF. 10% for other causes for other reasons',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Josh Rosenberg','GiveDirectly',NULL,0.1,'2015-12-09','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Large potential upside, reward to GiveDirectly for being an outstanding organization, and funds directly to individuals to spend for themselves',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Josh Rosenberg','A political campaign',NULL,0.3,'2016-12-09','day','date of donation announcement','Politics/United States','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Details of political campaign not specified, but 2016 is a presidential election year in the United States',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Josh Rosenberg','GiveWell top charities',NULL,0.65,'2016-12-09','day','date of donation announcement','Global health and cash transfers','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Believed in collective wisdom of GiveWell. Rather than dissent by donating elsewhere, considered it more productive to raise issues in debate and have combined wisdom of fellow staffers',NULL,NULL,NULL,'GiveWell',NULL,NULL);

# -- Sophie Monahan donations
insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Sophie Monahan','Against Malaria Foundation',NULL,1.0,'2015-12-09','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Following GiveWell recommendation, does not believe there is information that gives her reason to do better than overall GiveWell recommendation',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Sophie Monahan','GiveDirectly',NULL,1.0,'2016-12-09','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Some differences with GiveWell re: cost-effectiveness estimates. Believes all charities recommended by GiveWell are roughly equal, but GiveWell prioritizes GiveDirectly lowest. Hence, donating to GiveDirectly',NULL,NULL,NULL,'GiveWell',NULL,NULL);

# -- Ajeya Cotra donations
insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Ajeya Cotra','A political campaign',2700,0.55,'2016-10-01','month','date of donation announced in announcement','Politics/United States','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Target of donation not specified, but this donation was in mid-October, in the runup to the November 2016 United States presidential and legislative elections. Also, amount not explicitly specified, but inferred from 55-45 split in donations and knowledge of donor lottery amount from http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/ Note also that political campaign donations are capped at 2700 USD in the United States.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Ajeya Cotra', 'Donor lottery', 2200.00, 0.45, '2016-12-07', 'day', 'transaction', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', 'Reasoning explained more in http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/ (go to section for Ajeya Cotra)', NULL, NULL, NULL, NULL, NULL, NULL);


