create table donations (
    donation_id int(11) not null auto_increment primary key,
    donor varchar(100),
    donee varchar(200),
    amount float(14,2),
    amount_original_currency float(14,2),
    original_currency enum('AUD','BRL','BTC','CAD','CHF','CZK','DKK','ETH','EUR','GBP','NOK','NZD','SEK','SGD','USD','XRP','ZAR') DEFAULT 'USD',
    currency_conversion_date date,
    currency_conversion_basis enum('donor calculation','donee calculation','Peter Hurford','Bloomberg','Fixer.io','Coindesk'),
    fraction float(5, 4),
    donation_date date,
    donation_date_precision enum('day','month','quarter','year','multi-year'),
    donation_date_basis enum('transaction','donation log','date of donation announced in announcement','date of donation announcement','donee contributor list', 'IATI','Effective Altruism Survey'),
    cause_area varchar(100),
    url varchar(200),
    donor_cause_area_url varchar(200),
    notes varchar(2000) DEFAULT NULL,
    payment_modality varchar(100),
    match_eligible boolean,
    goal_amount float(14,2),
    influencer varchar(1000),
    employer_match float(14,2),
    matching_employer varchar(100),
    special_donation_reason enum('Giving Game','Compensation to charity for effort','Committed periodic donation','Fundraiser/Gift','Hat tip','One-off opportunity', 'Offset'),
    donation_earmark varchar(100),
    affected_countries varchar(2000),
    affected_states varchar(200),
    affected_cities varchar(200),
    affected_regions varchar(2000),
    donation_announcement_date date,
    donation_announcement_date_precision enum('day','month','year','multi-year'),
    donation_announcement_url varchar(200),
    grant_stage enum('planning grant','initial grant','renewal grant','exit grant')
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
