create table donations (
    donation_id int(11) not null auto_increment primary key,
    donor varchar(100),
    donee varchar(200),
    amount float(14,2),
    amount_original_currency float(24,2),
    original_currency enum('AUD','BRL','BTC','CAD','CHF','CZK','DKK','ETH','EUR','GBP','INR','NOK','NZD','SEK','SGD','USD','XRP','ZAR','SHIB','AKITA','ELON','MKR','KRW') DEFAULT 'USD',
    currency_conversion_date date,
    currency_conversion_basis enum('donor calculation','donee calculation','Peter Hurford','Bloomberg','Fixer.io','Coindesk','Etherscan.io'),
    fraction float(5, 4),
    donation_date date,
    donation_date_precision enum('day','month','quarter','year','multi-year'),
    donation_date_basis enum('transaction','donation log','date of donation announced in announcement','date of donation announcement','donee contributor list', 'IATI','Effective Altruism Survey','private communication by donee'),
    cause_area varchar(100),
    url varchar(400),
    donor_cause_area_url varchar(200),
    notes varchar(2000) DEFAULT NULL,
    donation_process varchar(2500) DEFAULT NULL,
    intended_use_of_funds_category varchar(200) DEFAULT NULL,
    intended_use_of_funds varchar(1000) DEFAULT NULL,
    intended_funding_timeframe_in_months int(11) DEFAULT NULL,
    donor_donee_reason varchar(1000) DEFAULT NULL,
    donor_amount_reason varchar(1000) DEFAULT NULL,
    donor_timing_reason varchar(1000) DEFAULT NULL,
    donor_next_donation_thoughts varchar(1000) DEFAULT NULL,
    donor_retrospective varchar(1000) DEFAULT NULL,
    payment_modality varchar(100),
    match_eligible boolean,
    goal_amount float(14,2),
    influencer varchar(1000),
    employer_match float(14,2),
    matching_employer varchar(100),
    special_donation_reason enum('Giving Game','Compensation to charity for effort','Committed periodic donation','Fundraiser/Gift','Hat tip','One-off opportunity', 'Offset','Prize to charity of choice'),
    donation_earmark varchar(2000),
    affected_countries varchar(2000),
    affected_states varchar(300),
    affected_cities varchar(300),
    affected_regions varchar(2000),
    donation_announcement_date date,
    donation_announcement_date_precision enum('day','month','year','multi-year'),
    donation_announcement_url varchar(200),
    predictions varchar(2000),
    is_contractwork tinyint(1) default 0
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
