# -- Animal welfare
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, notes, affected_countries) values
  ('Effective Altruism Funds','The Humane League',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.1667,'Bollard describes how grantee is a promising organization that played a major role in US corporate campaigns for chicken welfare. Open Phil accounts for 50% of funding, so Open Phil may choose to not donate more due to dependence concerns','United States'),
  ('Effective Altruism Funds','Animal Equality',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.1667,'Bollard notes that grantee does grassroots activism, corporate campaigning, and undercover investigations across Europe, the Americas, and India. Bollard is impressed based on constant updating on evidence: moving from farm animal welfare work to a focus on corporate campaigns. Also impressed with co-founders',NULL),
  ('Effective Altruism Funds','New Harvest',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.1667,'Grantee is a clean meat research group. Unlike The Good Food Institute, it may not attract enough in funding from big donors like Open Phil. Grant partly because Bollard believes that the funds invested right now will determine the pace of progress in the next 20-50 years',NULL),
  ('Effective Altruism Funds','Effective Altruism Foundation',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.1667,'Grant will fund research on the welfare of wild animals done by researchers Ozy Brennan and Persis Eskander, which internal changes at EAF have resulted in a loss of funding for. Bollard is impressed with their recent research, which focuses on foundational questions like the best scientific methods for measuring the wellbeing of wild animals, and relatively non-controversial potential interventions, like more humane methods of pest control',NULL),
  ('Effective Altruism Funds','Fórum Nacional de Proteção e Defesa Animal',20000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.1111,'Grantee is Brazil’s largest animal protection network with 120+ affiliated NGOs (mainly companion animal groups). Open Phil accounts for 50% of funding, so Open Phil may choose to not donate more due to dependence concerns','Brazil'),
  ('Effective Altruism Funds','Compassion in World Farming USA',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.556,'Grantee has played a role in recent US corporate campaigns for chicken welfare. Open Phil accounts for 50% of funding, so Open Phil may choose to not donate more due to dependence concerns','United States'),
  ('Effective Altruism Funds','Albert Schweitzer Foundation for Our Contemporaries',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.556,'Grantee has played a role in corporate campaigns in Germany. Grantee has medium-term funding needs','Germany'),
  ('Effective Altruism Funds','Animal Charity Evaluators',10000,'2017-04-20','day','date of donation announcement','Animal welfare/factory farming/meta/charity evaluator','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.556,'Bollard likes the work that ACE does to build a more effective farm animal movement through research, charity recommendations, and outreach to donors, researchers, and advocates. After recommending the grant, Bolalrd became more confident that funding gaps of grantee would be met and so is less likely to recommend for further grants',NULL),
  ('Effective Altruism Funds','Otwarte Klatki',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.556,'Grantee achieved corporate reforms in tough political environment on small budget. Has medium-term funding needs','Poland'),
  # -- Q1 2018 update
  ('Effective Altruism Funds','Wild-Animal Suffering Research',50000,'2018-01-14','day','donation log','Animal welfare/wild-animal suffering','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.3333,'Bollard is happy with the way the April grant enabled Ozy Brennan, Persis Eskander, and Georgia Ray to launch Wild-Animal Suffering Research under the Effective Altruism Foundation.',NULL),
  ('Effective Altruism Funds','Compassion in World Farming USA',30000,'2018-01-14','day','donation log','Animal welfare/factory farming/chicken/cage-free','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.2,'Bollard is impressed with the track record of the grantee at corporate outreach, including the launch of EggTrack to push companies to fulfill cage-free pledges, and also has a high opinion of the leader, Leah Garces, and their focused approach. Open Phil already accounts for 50% of their budget, so will not fund more; moreover, its lack of an ACE recommendation and its welfarist focus mean it is unlikely to raise a lot of other money, hence the donation','United States'),
  ('Effective Altruism Funds','Fórum Nacional de Proteção e Defesa Animal',20000,'2018-01-14','day','donation log','Animal welfare/factory farming/chicken/cage-free','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.1333,'Bollard is impressed with their success in securing cage-free policies throughout Latin America, including the success with the Latin American operations of Subway and Kraft-Heinz. Open Phil already accounts for 50% of their budget, so will not fund more for now, and is unlikely to make a major grant to it soon, and its other fundraising options are more consrained given the challenging fundraising environment of Brazil','Brazil'),
  ('Effective Altruism Funds','Sinergia Animal',20000,'2018-01-14','day','donation log','Animal welfare/factory farming','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.1333,'The grantee focuses on farm animal welfare through hard-hitting campaigns in Chile, Argentina, and Colombia. These countries are relatively neglected compared to Mexico and Brazil, but still have a huge number of farm animals. The new group is led by Carolina Macedo Galvani, whose work at the Fórum Nacional impressed Bollard, and in its first few months it helped secure a pledge from a Chilean restaurant company with 320 locations to eliminate cages and crates from its supply chain. Since it is outside the United States and relatively new, it would have trouble raising a lot of funds initially, so Bollard thinks this grant would be valuable to it','Chile,Argentina,Colombia'),
  ('Effective Altruism Funds','Sentience Institute',10000,'2018-01-14','day','donation log','Animal welfare/factory farming','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.0667,'The grantee has conducted a survey https://www.sentienceinstitute.org/animal-farming-attitudes-survey-2017 related to US attitudes toward farmed animals, that Bollard finds impressive, and it has immediate funding needs',NULL),
  ('Effective Altruism Funds','The Humane League',10000,'2018-01-14','day','donation log','Animal welfare/factory farming','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.0667,'The grant is for grassroots campaigning and movement-building. Bollard is impressed with what the grantee has accomplished on this front, e.g., through the Open Wing Alliance. Not recommending more funding because he expects the funding gap to be mostly met',NULL),
  ('Effective Altruism Funds','The Good Food Institute',10000,'2018-01-14','day','donation log','Animal welfare/meat alternatives','https://app.effectivealtruism.org/funds/animal-welfare/payouts/3tRg1Hfwu46EQ8mskEGUOE','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',150000,0.0667,'Bollard impressed with long-term goals of the grantee which he considers promising. Not recommending more because he expects that most of the funding gap will be filled',NULL);

# -- Global catastrophic risks/long-term future
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, notes, affected_countries) values
  ('Effective Altruism Funds','Berkeley Existential Risk Initiative',14838.02,'2017-04-01','quarter','donation log','AI risk/other global catastrophic risks','https://app.effectivealtruism.org/funds/far-future/payouts/OzIQqsVacUKw0kEuaUGgI','https://app.effectivealtruism.org/funds/far-future','Nick Beckstead',14838.02,1.0,'Grant discussed at http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/ along with reasoning. Grantee approached Nick Beckstead with a grant proposal asking for 50000 USD. Beckstead provided all the money donated already from the far future fund, and made up the remainder via the EA Giving Group and some personal funds',NULL);

# -- Global health
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, notes, affected_countries) values
  ('Effective Altruism Funds','Against Malaria Foundation',331126,'2017-06-27','day','donation log','Global health/malaria','https://app.effectivealtruism.org/funds/global-development/payouts/5usCuBFHQk2UcQ0WYOIUEk','https://app.effectivealtruism.org/funds/global-development','Elie Hassenfeld',331126,1.0,'Grant discussed at http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/ along with reasoning, though the amount at the time was not the full amount (just $311,562). Grant to AMF because Hassenfeld believes it is the highest expected value opportunity in the domain. Also, all funding opportunities in GiveWell Incubation Grants have been fully met to his satisfaction, so no need to use this fund for that money. Hassenfeld is allocating the money immediately as he does not expect the situation to change over the next six months',NULL),
  ('Effective Altruism Funds','No Lean Season',150000,'2017-10-17','day','donation log','Seasonal intracountry migration','https://app.effectivealtruism.org/funds/global-development/payouts/3xW9fK4U7YqMsKaQgGG8So','https://app.effectivealtruism.org/funds/global-development','Elie Hassenfeld',150000,1.0,'Elie Hassenfeld recommended No Lean Season on 2017-09-27 after receiving a phone call from Karen Levy saying that No Lean Season had failed to raise funds to meet the unexpectedly high demand for money from borrowers. Hassenfeld recommended the grant amount because Levy told him that would enable the program to continue operating uninterrupted. This was before No Lean Season became a GiveWell top charity','Bangladesh');

# -- Effective altruism community

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, notes, affected_countries) values
  ('Effective Altruism Funds','EA Sweden',83264,'2018-01-14','day','donation log','Effective altruism/movement growth','https://app.effectivealtruism.org/funds/ea-community/payouts/1EjFHdfk3GmIeIaqquWgQI','https://app.effectivealtruism.org/funds/ea-community','Nick Beckstead',83264,1.0,'After the EA Grants Team made its selections, I discussed some applications that barely missed the cut with Will MacAskill. MacAskill recommended funding EA Sweden by Markus Anderljung given his track record of community-building at Cambridge and in Sweden, as well as a conversation that MacAskill had with Anderljung','Sweden');
  
