insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, notes) values
  # -- 2014 (actual date range: December 2013 to December 2014)
  ('EA Giving Group','80,000 Hours',NULL,'2014-01-01','multi-year','donation log','Effective altruism/movement growth/career counseling','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit', 'Nick Beckstead', 'Actual date range: December 2013 to December 2014. Exact date, amount, or fraction not known, but it is the donee with the highest amount donated out of five donees in this period'),
  ('EA Giving Group','Center for Applied Rationality',NULL,'2014-01-01','multi-year','donation log','Rationality improvement','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead', 'Actual date range: December 2013 to December 2014. Exact date, amount, or fraction not known, but it is the donee with the second highest amount donated out of five donees in this period'),
  ('EA Giving Group','Centre for the Study of Existential Risk',NULL,'2014-01-01','multi-year','donation log','Rationality improvement','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead', 'Actual date range: December 2013 to December 2014. Exact date, amount, or fraction not known, but it is the donee with the fourth highest amount donated out of five donees in this period'),
  ('EA Giving Group','Charity Science Outreach',NULL,'2014-01-01','multi-year','donation log','Rationality improvement','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2013 to December 2014. Exact date, amount, or fraction not known, but it is the donee with the lowest amount donated out of five donees in this period'),
  # -- 2015 (actual date range: December 2014 to December 2015)
  ('EA Giving Group','Centre for Effective Altruism',NULL,'2015-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the highest amount donated out of eight donees in this period. The original grant was to Effective Altruism Outreach, which is now a part of the Centre for Effective Altruism'),
  ('EA Giving Group','Future of Life Institute',NULL,'2015-01-01','multi-year','donation log','Global catastrophic risks','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the second highest amount donated out of eight donees in this period'),
  ('EA Giving Group','Charity Science',NULL,'2015-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the third highest amount donated out of eight donees in this period'),
  ('EA Giving Group','Founders Pledge',NULL,'2015-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the fifth highest amount donated out of eight donees in this period'),
  ('EA Giving Group','Rethink Charity',NULL,'2015-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the sixth highest amount donated out of eight donees in this period. Grant originally to the Local Effective Altruism Network (LEAN) which is now part of Rethink Charity'),
  ('EA Giving Group','Centre for Effective Altruism',NULL,'2015-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the seventh highest amount donated out of eight donees in this period. Money intended for regranting to local student groups, CEA is the intermediary for financing'),
  ('EA Giving Group','Effective Altruism Policy Analytics',NULL,'2015-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2014 to December 2015. Exact date, amount, or fraction not known, but it is the donee with the lowest amount donated out of eight donees in this period'),
  # -- Early 2016 (actual date range: December 2015 to February 2016)
  ('EA Giving Group','Founders Pledge',NULL,'2016-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2015 to February 2016. Exact date, amount, or fraction not known, but it is the donee with the highest amount donated out of six donees in this period'),
  ('EA Giving Group','80,000 Hours',NULL,'2016-01-01','multi-year','donation log','Effective altruism/movement growth/career counseling','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2015 to February 2016. Exact date, amount, or fraction not known, but it is the donee with the second highest amount donated out of six donees in this period'),
  ('EA Giving Group','Centre for Effective Altruism',NULL,'2016-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2015 to February 2016. Exact date, amount, or fraction not known, but it is the donee with the third highest amount donated out of six donees in this period. The original grant was to Effective Altruism Outreach, which is now a part of CEA'),
  ('EA Giving Group','Future of Life Institute',NULL,'2016-01-01','multi-year','donation log','Global catastrophic risks','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2015 to February 2016. Exact date, amount, or fraction not known, but it is the donee with the fourth highest amount donated out of six donees in this period'),
  ('EA Giving Group','Center for Applied Rationality',NULL,'2016-01-01','multi-year','donation log','Rationality improvement','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2015 to February 2016. Exact date, amount, or fraction not known, but it is the donee with the fifth highest amount donated out of six donees in this period'),
  ('EA Giving Group','Charity Entrepreneurship',NULL,'2016-01-01','multi-year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: December 2015 to February 2016. Exact date, amount, or fraction not known, but it is the donee with the lowest amount donated out of six donees in this period'),
  # -- February to December 2016
  ('EA Giving Group','Centre for Effective Altruism',NULL,'2016-01-01','year','donation log','Effective altruism/movement growth','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: February 2016 to December 2016. Exact date, amount, or fraction not known, but it is the donee with the highest amount donated out of three donees in this period. Money to be used at the discretion of William MacAskill'),
  ('EA Giving Group','80,000 Hours',NULL,'2016-01-01','year','donation log','Effective altruism/movement growth/career counseling','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: February 2016 to December 2016. Exact date, amount, or fraction not known, but it is the donee with the second highest amount donated out of three donees in this period'),
  ('EA Giving Group','Charity Science Health',NULL,'2016-01-01','year','donation log','Global health/vaccination/SMS reminders','https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit','Nick Beckstead','Actual date range: February 2016 to December 2016. Exact date, amount, or fraction not known, but it is the donee with the lowest amount donated out of three donees in this period'),
  # -- 2017
  ('EA Giving Group','Berkeley Existential Risk Initiative',35161.98,'2017-04-01','quarter','donation log','AI risk/other global catastrophic risks','https://app.effectivealtruism.org/funds/far-future/payouts/OzIQqsVacUKw0kEuaUGgI','Nick Beckstead','Grant discussed at http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/ along with reasoning. Grantee approached Nick Beckstead with a grant proposal asking for 50000 USD. Beckstead provided all the money donated already from the far future fund in Effective Altruism Funds, and made up the remainder via the EA Giving Group and some personal funds. It is not clear how much was personal funds, so for simplicity we are attributing the entirety of the remainder to EA Giving Group (creating some inaccuracy)');
  
