# -- Elie Hassenfeld donations

insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, payment_modality, match_eligible, goal_amount, influencer, employer_match, matching_employer) values 
  ('Elie Hassenfeld','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Agrees with reasoning by Holden (in same blog post) but discounts deworming cost-effectiveness estimates entirely. Asked GiveDirectly not to include donation in Good Ventures match',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','Against Malaria Foundation',NULL,0.45,'2014-12-17','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Lower allocation to AMF (45%) relative to GiveWell allocation (67%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','GiveDirectly',NULL,0.45,'2014-12-17','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Higher allocation to GiveDirectly (45%) relative to GiveWell allocation (13%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','Schistosomiasis Control Initiative',NULL,0.05,'2014-12-17','day','date of donation announcement','Global health/deworming','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Lower allocation to SCI (5%) relative to GiveWell allocation (13%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','Deworm the World Initiative',NULL,0.05,'2014-12-17','day','date of donation announcement','Global health/deworming','https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Donated jointly with wife. Lower allocation to DtWI (5%) relative to GiveWell allocation (7%), citing less weight to explicit cost-effectiveness and more weight to organizational strength',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','Against Malaria Foundation',NULL,1.0,'2015-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','More confidence in cost-effectiveness model and in GiveWell recommendation to donate all to AMF',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','A political campaign',NULL,NULL,'2016-12-09','day','date of donation announcement','Politics/United States','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','States "I already gave a significant portion of this year’s donation to a political campaign, so I’m planning to give less at the end of this year than I have in previous years." Details of political campaign not specified, but 2016 is a presidential election year in the United States',NULL,NULL,NULL,NULL,NULL,NULL),
  ('Elie Hassenfeld','GiveWell top charities',NULL,NULL,'2016-12-09','day','date of donation announcement','Global health and cash transfers','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','This donation covered all the end-of-year giving, and all giving left from after the donation to "a political campaign"',NULL,NULL,NULL,'GiveWell',NULL,NULL),
  ('Elie Hassenfeld','GiveWell top charities',NULL,1.0,'2017-12-11','day','date of donation announcement','Global health and cash transfers','https://blog.givewell.org/2017/12/11/staff-members-personal-donations-for-giving-season-2017/#Elie','Donation to GiveWell for discretionary regranting; this is what GiveWell recommends to donors',NULL,NULL,NULL,'GiveWell',NULL,NULL);
