# -- Good Ventures grants not affiliated with either GiveWell or the Open Philanthropy Project

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, influencer, affected_cities, affected_states, affected_countries) values
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Startup:Education',5000000,'2014-04-01','month','donation log','Education/United States','http://www.goodventures.org/our-portfolio/grants/startup-education-school-reform-in-newark-april-2014','Grant structured as a "match" to the grant by Mark Zuckerberg and Priscilla Chan of $100 million for school reform in Newark. Matching grants from other donors were needed to unlock the funding from Zuckerberg and Chan. Though the grant was not recommended by GiveWell, GiveWell staff assisted with a writeup at http://www.goodventures.org/report/school-reform-in-newark to help decide on the grant','Mark Zukerberg,Priscilla Chan,Cory Booker','Newark','New Jersey','United States'),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Brookings Institution',212500,'2014-03-01','month','donation log','Drug policy/United States','http://www.goodventures.org/our-portfolio/grants/brookings-institution-research-on-marijuana-policy-change','Grant was recommended by Graham Boyd, who had previously worked as an advisor to Peter Lewis','Graham Boyd',NULL,'Washington,Colorado','United States'),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Heffter Research Institute',100000,'2015-12-01','month','donation log','Drug policy/United States','http://www.goodventures.org/our-portfolio/grants/heffter-research-institute-general-support1','Grant was recommended by Graham Boyd, advisor to Good Ventures on drug policy. Grant supports work on psychedelics, an area that Good Ventures and Boyd consider neglected, and where ','Graham Boyd',NULL,NULL,'United States'),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Heffter Research Institute',100000,'2016-09-01','month','donation log','Drug policy/United States','http://www.goodventures.org/our-portfolio/grants/heffter-research-institute-general-support','Grant recipient a leading institute on psychedelics. It follows up on http://www.goodventures.org/our-portfolio/grants/heffter-research-institute-general-support1 a previous grant of the same amount. Grantee intends to use grant for communications work over the next two years',NULL,NULL,NULL,'United States'),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Freedom to Marry',150000,'2012-06-01','month','donation log','Same-sex marriage/United States','http://www.goodventures.org/our-portfolio/grants/freedom-to-marry-general-support-june-2012','Learning grant intended to understand more in the same-sex marriage advocacy (aka "marriage equality") space',NULL,NULL,NULL,'United States'),
  ('Good Ventures/unaffiliated with GiveWell or Open Philanthropy Project','Freedom to Marry',250000,'2014-03-01','month','donation log','Same-sex marriage/United States','http://www.goodventures.org/our-portfolio/grants/freedom-to-marry-general-support-march-2014','Exit grant to Freedom to Marry as Good Ventures decides to exit funding same-sex marriage organizations',NULL,NULL,NULL,'United States'),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Silicon Valley Community Foundation',100000,'2012-09-01','month','donation log','Same-sex marriage/United States','http://www.goodventures.org/our-portfolio/grants/media-buy-for-marriage-equality-campaign-in-maine-september-2012','Grant supports purchase of advertisements in Maine by Freedom to Marry Action as part of a campaign to legalized same-sex marriage',NULL,NULL,'Maine','United States'),
  ('Good Ventures/unaffiliated with GiveWell or Open Philanthropy Project','Stanford Center on Philanthropy and Civil Society',20000,'2012-07-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/stanford-center-on-philanthropy-and-civil-society-general-support-july-2012','Grant made via Stanford University, supports efforts of recipient to promote the study of philanthropic institutions and nonprofits',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Stanford Center on Philanthropy and Civil Society',20000,'2014-08-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/stanford-pacs-general-support','Grant for general operating support, and also labeled as a continuation of http://www.goodventures.org/our-portfolio/grants/stanford-center-on-philanthropy-and-civil-society-general-support-july-2012 a grant in 2012-07',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Stanford Center on Philanthropy and Civil Society',60000,'2015-04-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/stanford-center-on-philanthropy-and-civil-society-general-support','Grant for general operating support, to be disbursed as three annual payments of $20,000 each',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',50000,'2011-12-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-general-support-december-2011','Grant for general operating support, i.e., finding the best giving opportunities and writing up findings',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',50000,'2013-01-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-general-support-january-2013','Grant for general operating support, i.e., finding the best giving opportunities and writing up findings',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',20000,'2013-06-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-research-june-2013','Grant to support investigation into the history of philanthropy and investigation of funding opportunities in in policy advocacy',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',675000,'2013-11-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-research-november-2013','Grant to cover research-related expenses',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',56250,'2015-01-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-open-philanthropy-project-website-construction','Grant to support 50% of the costs of redesigning http://www.openphilanthropy.org (the new website)',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',240000,'2014-03-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-general-support-march-2014','Grant for general operating support',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',1186840,'2015-08-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-general-support-august-2015','Grant for general operating support',NULL,NULL,NULL,NULL),
  ('Good Ventures/not recommended by GiveWell or Open Philanthropy Project','GiveWell',1994850,'2016-06-01','month','donation log','Meta-philanthropy','http://www.goodventures.org/our-portfolio/grants/givewell-general-support','Grant for general poerating support',NULL,NULL,NULL,NULL);


# -- GiveWell discretionary regranting
insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries) values
  ('GiveWell discretionary regranting','Against Malaria Foundation',4400000,'2017-04-03','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/','Blog posts announces $4.4 million grant to AMF from the funds GiveWell has for discretionary regranting. This is because AMF has the largest remaining Execution Level 1 gap based on the funding gaps identified in November 2016, and reports of funds raised as of February 2017. An additional $0.5 million is being granted to Deworm the World Initiative, and GiveWell recommends that donors giving now should donate all their money to the Against Malaria Foundation',NULL),
  ('GiveWell discretionary regranting','Deworm the World Initiative',500000,'2017-04-03','day','date of donation announcement','Global health/deworming','http://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/','Blog posts announces $0.5 million to Deworm the World Initiative from the funds GiveWell has for discretionary regranting, to fill most of an unfilled $0.53 million Execution Level 2 funding gap. This is out of a total of $4.9 million in granted money (the remaining $4.4 million went to the Against Malaria Foundation, with the highest priority of funding gap). The funding to Deworm the World Initiative was decided over other alternatives, including Schistosomiasis Control Initiative, the END Fund, GiveDirectly, Malaria Consortium, and Sightsavers',NULL);


# -- GiveWell Incubation Grants

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url) values
  ('GiveWell Incubation Grants','New Incentives',100000,'2014-01-01','month','donation log','Conditional cash transfers/Potential top charity','http://www.givewell.org/charities/new-incentives/january-2014-grant','First of the incubation grants, made to encourage the creation of new GiveWell top charities. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization', NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','No Lean Season',250000,'2014-03-01','month','donation log','Seasonal intracountry migration/potential top charity','http://www.givewell.org/evidence-action/march-2014-grant','Grant made to Evidence Action (which manages the program, and separately runs the Deworm the World Initiative) to support preliminary work and additional research on the No Lean Season program in Bangladesh. See http://www.givewell.org/charities/evidence-action/no-lean-season/all-content for all GiveWell content on the organization','Bangladesh', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','No Lean Season',170792,'2014-03-01','month','donation log','Seasonal intracountry migration','http://www.givewell.org/evidence-action/march-2014-grant','Second grant made to Evidence Action (which manages the program, and separately runs the Deworm the World Initiative) to support preliminary work and additional research on the No Lean Season program in Bangladesh.. See http://www.givewell.org/charities/evidence-action/no-lean-season/all-content for all GiveWell content on the organization','Bangladesh', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','IDinsight',34382,'2014-09-01','month','donation log','Global health and development/scale-up','http://www.givewell.org/charities/IDinsight/september-2014-grant','Help with scaling up a high-potential development intervention in India','India', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',100000,'2015-03-01','month','donation log','Conditional cash transfers/Potential top charity','http://www.goodventures.org/our-portfolio/grants/new-incentives-general-support','Grant for general support, with a view to helping scale up a potential top charity. Follows up a grant of the same amount in 2014-01. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Abdul Latif Jameel Poverty Action Lab',100000,'2015-09-01','month','donation log','Global health and development/immunization and cash incentives','http://www.givewell.org/JPAL-IRD-grant','Grant for research on whether non-cash incentives increase child immunization rates','India,Pakistan', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Interactive Research and Development',100000,'2015-09-01','month','donation log','Global health and development/immunization and cash incentives','http://www.givewell.org/JPAL-IRD-grant','Grant for research on whether non-cash incentives increase child immunization rates','India,Pakistan', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','No Lean Season',812351,'2016-03-01','month','donation log','Seasonal intracountry migration/Potential top charity','http://www.givewell.org/charities/evidence-action/march-2016-grant','Grant to fully cover projected No Lean Season costs for 2016. Hope that it would become a GiveWell top charity in the long term. See http://www.givewell.org/charities/evidence-action/no-lean-season/all-content for all GiveWell content on the organization','Bangladesh', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',300000,'2016-03-01','month','donation log','Conditional cash transfers','http://www.givewell.org/charities/new-incentives/march-2016-grant','General support grant to New Incentives (that had received a grant previously, NULL, NULL, NULL), in the hope of creating a future top charity. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Innovations for Poverty Action',350000,'2016-05-01','month','donation log','Unconditional cash transfers/mindset','http://www.givewell.org/international/charities/ipa/may-2016-grant','Grant supports research by Richard Sedlmayr and colleagues in collaboration with GiveDirectly to test mindset engagement in the context of unconditional cash transfers',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Results for Development',6400000,'2016-05-01','month','donation log','Global health/pneumonia','http://www.givewell.org/charities/results-for-development/may-2016-grant','Grant for the Market Dynamics practice area’s pneumonia treatment program in Tanzania. The organization aims to use these funds to increase use of amoxicillin, the WHO-recommended first-line treatment for childhood pneumonia.','Tanzania', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','IDinsight',1985000,'2016-06-01','month','donation log','Nonprofit ecosystem','http://www.givewell.org/charities/IDinsight/june-2016-grant','General support grant, to scale its model of supporting and evaluating development interventions. See http://www.givewell.org/charities/idinsight/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','IDinsight',314752,'2016-10-01','month','donation log','Consulting','http://www.givewell.org/charities/IDinsight/october-2016-grant','Grant for embedded GiveWell team. See http://www.givewell.org/charities/idinsight/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Charity Science: Health',200000,'2016-11-01','month','donation log','Immunization/potential top charity','http://www.givewell.org/charities/charity-science/charity-science-health/november-2016-grant','SMS immunization in India. Budget of 250000 per year, so 80% funding for a year','India', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',368587,'2016-11-01','month','donation log','Conditional cash transfers','http://www.givewell.org/charities/new-incentives/november-2016-grant','Exit grant, indicating end of relationship (and to give recipient time to transition gracefully). No longer a top charity contender. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',820000,'2017-04-01','month','donation log','Conditional cash transfers','http://www.givewell.org/charities/new-incentives/april-2017-grant','After an exit grant in 2016-11 for conditional cash transfers for maternal health, the new grant is for a new New Incentives program doing conditional cash transfers to create incentives for immunization. Evaluation would probably be in partnership with IDinsight starting 2017-09','Nigeria', '2017-05-05', 'day', 'https://groups.google.com/forum/#!topic/newly-published-givewell-materials/tnTm4xnuCjI'),
  ('GiveWell Incubation Grants','No Lean Season',1687500,'2016-12-01','month','donation log','Seasonal intracountry migration/potential top charity','http://www.givewell.org/charities/evidence-action/december-2016-grant','Grant to Evidence Action follows previous grants to expand seasonal migration program. Now operates in Bangladesh and Indonesia', 'Bangladesh,Indonesia', '2017-05-11','day', 'https://groups.google.com/forum/#!topic/newly-published-givewell-materials/gBK7-BgPIjY'),
  ('GiveWell Incubation Grants','Georgetown University Initiative on Innovation Development and Evaluation',900000,'2017-01-01','month','donation log','Road safety','http://www.givewell.org/charities/gui2de/january-2017-grant','Grant for Zusha! Road Safety Campaign in Kenya','Kenya','2017-06-15','day','https://groups.google.com/forum/#!topic/newly-published-givewell-materials/e55AvcrOBkc');

# -- Good Ventures grant to GiveWell top charities

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries, affected_states, affected_cities, influencer) values
  # -- 2011 top and standout charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',500000,'2011-12-23','day','date of donation announcement','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support-december-2011','Grant made by Good Ventures and announced at http://blog.givewell.org/2011/12/23/guest-post-from-cari-tuna/ based on GiveWell top charity list at http://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/ and http://www.givewell.org/charities/top-charities/November-2011 and the 2011 review: http://www.givewell.org/charities/AMF/2011-review','Malawi',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',250000,'2011-12-23','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support-december-2011','Grant made by Good Ventures and announced at http://blog.givewell.org/2011/12/23/guest-post-from-cari-tuna/ based on GiveWell top charity list at http://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/ and the 2011 review: http://www.givewell.org/charities/schistosomiasis-control-initiative/November-2011-review',NULL,NULL,NULL,'GiveWell'),
  # -- 2012 mid-year standout charities
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',100000,'2012-05-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support-may-2012','Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06. Amount of 100000 for GiveDirectly was twice the amount of 50000 for each of the other top and standout charities','Kenya',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Possible',50000,'2012-05-01','month','donation log','Global health/regional healthcare','http://www.goodventures.org/our-portfolio/grants/nyaya-health-general-support-may-2012','Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','Nepal',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','KIPP Houston',50000,'2012-05-01','month','donation log','Education','http://www.goodventures.org/our-portfolio/grants/kipp-houston-general-support-may-2012','Grant to support KIPP Houston’s efforts to improve learning outcomes for underserved youth in Houston. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','United States','Texas','Houston','GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Small Enterprise Foundation',50000,'2012-05-01','month','donation log','Microloans/global poverty','http://www.goodventures.org/our-portfolio/grants/small-enterprise-foundation-general-support-may-2012','Grant to support SEF’s efforts to help alleviate poverty by providing microloans to women in South Africa. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','South Africa',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Innovations for Poverty Action',50000,'2012-05-01','month','donation log','Global poverty/research','http://www.goodventures.org/our-portfolio/grants/innovations-for-poverty-action-general-support-may-2012','Grant for general support. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Pratham',50000,'2012-05-01','month','donation log','Education','http://www.goodventures.org/our-portfolio/grants/pratham-general-support-may-2012','Grant for general support. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','India',NULL,NULL,'GiveWell'),
  # -- 2012 end-of-year top charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',1250000,'2012-12-28','day','date of donation announcement','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support-december-2012','Grant made by Good Ventures and announced at http://www.goodventures.org/research-and-ideas/blog/year-end-grants-to-givewells-top-charities based on GiveWell top charity recommendations http://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/ and http://www.givewell.org/charities/top-charities/November-2012 and the 2012 review: http://www.givewell.org/charities/AMF/2012-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',500000,'2012-12-28','day','date of donation announcement','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support-december-2012','Grant made by Good Ventures and announced at http://www.goodventures.org/research-and-ideas/blog/year-end-grants-to-givewells-top-charities based on GiveWell top charity recommendations http://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/ and http://www.givewell.org/charities/top-charities/November-2012 and the 2012 review: http://www.givewell.org/charities/give-directly/November-2012-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',250000,'2012-12-28','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support-december-2012','Grant made by Good Ventures and announced at http://www.goodventures.org/research-and-ideas/blog/year-end-grants-to-givewells-top-charities based on GiveWell top charity recommendations http://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/ and http://www.givewell.org/charities/top-charities/November-2012 and the 2012 review: http://www.givewell.org/charities/schistosomiasis-control-initiative/November-2012-review',NULL,NULL,NULL,'GiveWell'),
  # -- 2013 top and standout charities
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',7000000,'2014-01-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support-december-and-january-2013','Grant announced at http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans on 2013-12-03 by Cari Tuna, including 2 million unconditional + 5 million in matches. Full match amount paid out. Match was not approved by GiveWell. Grant based on GiveWell top charities list at http://www.givewell.org/charities/top-charities/November-2013 and http://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/ and the 2013 review: http://www.givewell.org/international/top-charities/give-directly/November-2013-review','Kenya',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',750000,'2013-12-03','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support-december-2013','Grant announced at http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans on 2013-12-03 by Cari Tuna. Grant based on GiveWell top charities list at http://www.givewell.org/charities/top-charities/November-2013 and http://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/ and the 2013 review: http://www.givewell.org/charities/schistosomiasis-control-initiative/November-2013-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',1500000,'2013-12-03','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support-december-2013','Grant announced at http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans on 2013-12-03 by Cari Tuna. Grant based on GiveWell top charities list at http://www.givewell.org/charities/top-charities/November-2013 and http://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/ and the 2013 review: http://www.givewell.org/charities/deworm-world-initiative/November-2013-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',5000000,'2014-12-01','day','date of donation announcement','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support','Grant announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/give-directly/December-2014-review','Kenya',NULL,NULL,'GiveWell'),
  # -- 2014 top and standout charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',5000000,'2014-12-01','day','date of donation announcement','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support','Grant to top charity announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/AMF/2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',3000000,'2014-12-01','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support','Grant to top charity announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/schistosomiasis-control-initiative/November-2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',250000,'2014-12-01','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support','Grant to standout charity announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/international/top-charities/deworm-world-initiative/November-2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Global Alliance for Improved Nutrition',250000,'2014-12-01','day','date of donation announcement','Global health/nutrition/iodine','http://www.goodventures.org/our-portfolio/grants/global-alliance-for-improved-nutrition-general-support','Grant for Universal Salt Iodization Program, a standout charity. Grant announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/GAIN/December-2014-version',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Development Media International',250000,'2014-12-01','day','date of donation announcement','Global health/development communication','http://www.goodventures.org/our-portfolio/grants/development-media-international-general-support','Grant to standout charity announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/DMI/2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Iodine Global Network',250000,'2014-12-01','day','date of donation announcement','Global health/nutrition/iodine','http://www.goodventures.org/our-portfolio/grants/ign-general-support','Grant to standout charity announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/IGN',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Living Goods',250000,'2014-12-01','day','date of donation announcement',NULL,'http://www.goodventures.org/our-portfolio/grants/living-goods-general-support','Grant to standout charity announced at http://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also http://www.givewell.org/charities/top-charities/November-2014 and the review http://www.givewell.org/charities/living-goods',NULL,NULL,NULL,'GiveWell'),
  # -- 2015 mid-year grant to GiveDirectly
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',25000000,'2015-08-03','day','date of donation announcement','Cash transfers','http://www.goodventures.org/research-and-ideas/blog/announcing-a-25-million-grant-to-givedirectly','One-off grant to top charity over three years also announced at http://blog.givewell.org/2015/08/03/good-ventures-25-million-grant-to-givedirectly/',NULL,NULL,NULL,'GiveWell'),
  # -- 2015 end-year top and standout charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',22845500,'2016-01-01','month','donation log','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support1','Intent to make grant announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',9750000,'2016-01-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support2','Intent to make grant announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',10790000,'2016-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support1','Intent to make grant announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',1000000,'2016-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support1','Intent to make grant announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Global Alliance for Improved Nutrition',250000,'2015-10-01','month','donation log','Global health/nutrition/iodine','http://www.goodventures.org/our-portfolio/grants/global-alliance-for-improved-nutrition-general-support1','Grant to standout charity for Universal Salt Iodization Program announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Living Goods',250000,'2015-12-01','month','donation log',NULL,'http://www.goodventures.org/our-portfolio/grants/living-goods-general-support1','Grant to standout charity announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Iodine Global Network',250000,'2015-12-01','month','donation log',NULL,'http://www.goodventures.org/our-portfolio/grants/iodine-global-network-general-support','Grant to standout charity announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Development Media International',250000,'2015-12-01','month','donation log','Global health/development communication','http://www.goodventures.org/our-portfolio/grants/development-media-international-general-support1','Grant to standout charity announced on 2015-11-20 at http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  # -- 2016 end-of-year top charities
  ('Good Ventures/GiveWell top and standout charities','Malaria Consortium',5000000,'2017-02-01','month','donation log','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/malaria-consortium-seasonal-malaria-chemoprevention','Grant specific to the Seasonal Malaria Chemoprevention (SMC) program, a 2016 GiveWell top charity program. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top charities list -- this was the first inclusion of a Malaria Consortium program as a top or standout charity and the first grant from Good Ventures',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',13500000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/malaria-consortium-seasonal-malaria-chemoprevention','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',2500000,'2017-01-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support3','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',15080000,'2017-01-01','month','donation log','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support2','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',4470000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support2','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Living Goods',250000,'2017-01-01','month','donation log',NULL,'http://www.goodventures.org/our-portfolio/grants/living-goods-general-support2','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Project Healthy Children',250000,'2017-01-01','month','donation log','Global health','http://www.goodventures.org/our-portfolio/grants/project-healthy-children-general-support','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Development Media International',250000,'2017-01-01','month','donation log','Global health/development communication','http://www.goodventures.org/our-portfolio/grants/development-media-international-general-support2','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Food Fortification Initiative',250000,'2017-01-01','month','donation log','Global health/nutrition','http://www.goodventures.org/our-portfolio/grants/food-fortification-initiative-general-support','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Sightsavers',2950000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/sightsavers-deworming','Grant for deworming program, a 2016 GiveWell top charity program. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','The END Fund',5000000,'2016-12-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/the-end-fund-deworming','Grant for deworming program, a 2016 GiveWell top charity program. Grant announced on 2016-11-28 at http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell');
