# -- GiveWell discretionary regranting
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries, goal_amount, fraction) values
  ('GiveWell discretionary regranting','Deworm the World Initiative',700000,'2017-11-27','day','date of donation announcement','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and September 2017. See https://blog.givewell.org/2017/11/27/our-top-charities-for-giving-season-2017/ for more details. This is part of $15.9 million GiveWell is attempting to allocate to Deworm the World Initiative; the remaining $15.2 million will come from Good Ventures','India|Kenya',700000,1.0),
  ('GiveWell discretionary regranting','Deworm the World Initiative',2250000,'2017-08-30','day','date of donation announcement','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and June 2017. Blog post https://blog.givewell.org/2017/08/30/why-were-allocating-discretionary-funds-to-the-deworm-the-world-initiative/ announces $2.25 million in made and planned grants to Deworm the World Initiative from funds given to GiveWell to regrant at its discretion (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities). This is the entirety of the money being granted or considered for granting at this time; the blog post explains why the grant is being made to Deworm the World Initiative even though GiveWell continues to recommend Against Malaria Foundation as the top charity that donors should allocate 100% of their donations to. Amount includes $1.25 million already granted and an additional $1 million that is planned for granting in the next month or two',NULL,2250000,1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',4400000,'2017-04-03','day','date of donation announcement','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and December 2016. Blog post https://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/ announces $4.4 million grant to AMF from the funds GiveWell has for discretionary regranting (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities). This is because AMF has the largest remaining Execution Level 1 gap based on the funding gaps identified in November 2016, and reports of funds raised as of February 2017. An additional $0.5 million is being granted to Deworm the World Initiative, and GiveWell recommends that donors giving now should donate all their money to the Against Malaria Foundation',NULL,4900000,0.898),
  ('GiveWell discretionary regranting','Deworm the World Initiative',500000,'2017-04-03','day','date of donation announcement','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and December 2016. Blog post https://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/ announces $0.5 million to Deworm the World Initiative from the funds GiveWell has for discretionary regranting (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities), to fill most of an unfilled $0.53 million Execution Level 2 funding gap. This is out of a total of $4.9 million in granted money (the remaining $4.4 million went to the Against Malaria Foundation, with the highest priority of funding gap). The funding to Deworm the World Initiative was decided over other alternatives, including Schistosomiasis Control Initiative, the END Fund, GiveDirectly, Malaria Consortium, and Sightsavers',NULL, 4900000, 0.102),
  ('GiveWell discretionary regranting','Against Malaria Foundation',500000,'2016-12-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and September 2016', NULL, 500000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',300000,'2016-09-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between May and June 2016', NULL, 300000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',200000,'2016-06-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between March and April 2016', NULL, 200000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',1000000,'2016-04-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and February 2016', NULL, 1000000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',1600000,'2016-02-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated in December 2015', NULL, 1600000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',800000,'2016-01-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and November 2015', NULL, 800000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',600000,'2015-12-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between June and September 2015', NULL, 600000, 1.0),
  ('GiveWell discretionary regranting','Against Malaria Foundation',667000,'2015-07-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.667),
  ('GiveWell discretionary regranting','GiveDirectly',133000,'2015-07-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.133),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',133000,'2015-07-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.133),
  ('GiveWell discretionary regranting','Deworm the World Initiative',67000,'2015-07-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.067),

  ('GiveWell discretionary regranting','Against Malaria Foundation',1467400,'2015-03-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.667),
  ('GiveWell discretionary regranting','GiveDirectly',292600,'2015-03-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.133),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',292600,'2015-03-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.133),
  ('GiveWell discretionary regranting','Deworm the World Initiative',147400,'2015-03-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.133),

  ('GiveWell discretionary regranting','Against Malaria Foundation',66700,'2015-01-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.667),
  ('GiveWell discretionary regranting','GiveDirectly',13300,'2015-01-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.133),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',13300,'2015-01-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.133),
  ('GiveWell discretionary regranting','Deworm the World Initiative',6700,'2015-01-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.067),

  ('GiveWell discretionary regranting','GiveDirectly',60000,'2014-08-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between April and June 2014',NULL,100000,0.6),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',20000,'2014-08-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between April and June 2014',NULL,100000,0.2),
  ('GiveWell discretionary regranting','Deworm the World Initiative',20000,'2014-08-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between April and June 2014',NULL,100000,0.2),
  
  ('GiveWell discretionary regranting','GiveDirectly',110000,'2014-05-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2014',NULL,200000,0.55),
  ('GiveWell discretionary regranting','Schistosomasis Control Initiative',80000,'2014-05-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2014',NULL,200000,0.4),
  ('GiveWell discretionary regranting','Deworm the World Initiative',10000,'2014-05-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2014',NULL,200000,0.05);


