# -- GiveWell Incubation Grants

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url) values
  ('GiveWell Incubation Grants','New Incentives',100000,'2014-01-01','month','donation log','Conditional cash transfers/Potential top charity','http://www.givewell.org/charities/new-incentives/january-2014-grant','First of the incubation grants, made to encourage the creation of new GiveWell top charities. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization', NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','No Lean Season',250000,'2014-03-01','month','donation log','Seasonal intracountry migration/potential top charity','http://www.givewell.org/evidence-action/march-2014-grant','Grant made to Evidence Action (which manages the program, and separately runs the Deworm the World Initiative) to support preliminary work and additional research on the No Lean Season program in Bangladesh. See http://www.givewell.org/charities/evidence-action/no-lean-season/all-content for all GiveWell content on the organization','Bangladesh', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','No Lean Season',170792,'2014-03-01','month','donation log','Seasonal intracountry migration','http://www.givewell.org/evidence-action/march-2014-grant','Second grant made to Evidence Action (which manages the program, and separately runs the Deworm the World Initiative) to support preliminary work and additional research on the No Lean Season program in Bangladesh.. See http://www.givewell.org/charities/evidence-action/no-lean-season/all-content for all GiveWell content on the organization','Bangladesh', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','IDinsight',34382,'2014-09-01','month','donation log','Global health and development/scale-up','http://www.givewell.org/charities/IDinsight/september-2014-grant','Help with scaling up a high-potential development intervention in India','India', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',100000,'2015-03-01','month','donation log','Conditional cash transfers/Potential top charity','http://www.goodventures.org/our-portfolio/grants/new-incentives-general-support','Grant for general support, with a view to helping scale up a potential top charity. Follows up a grant of the same amount in 2014-01. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Abdul Latif Jameel Poverty Action Lab',100000,'2015-09-01','month','donation log','Global health and development/immunization and cash incentives','http://www.givewell.org/JPAL-IRD-grant','Grant for research on whether non-cash incentives increase child immunization rates','India,Pakistan', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Interactive Research and Development',100000,'2015-09-01','month','donation log','Global health and development/immunization and cash incentives','http://www.givewell.org/JPAL-IRD-grant','Grant for research on whether non-cash incentives increase child immunization rates','India,Pakistan', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','No Lean Season',812351,'2016-03-01','month','donation log','Seasonal intracountry migration/Potential top charity','http://www.givewell.org/charities/evidence-action/march-2016-grant','Grant to fully cover projected No Lean Season costs for 2016. Hope that it would become a GiveWell top charity in the long term. See http://www.givewell.org/charities/evidence-action/no-lean-season/all-content for all GiveWell content on the organization','Bangladesh', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',300000,'2016-03-01','month','donation log','Conditional cash transfers','http://www.givewell.org/charities/new-incentives/march-2016-grant','General support grant to New Incentives (that had received a grant previously, NULL, NULL, NULL), in the hope of creating a future top charity. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Innovations for Poverty Action',350000,'2016-05-01','month','donation log','Unconditional cash transfers/mindset','http://www.givewell.org/international/charities/ipa/may-2016-grant','Grant supports research by Richard Sedlmayr and colleagues in collaboration with GiveDirectly to test mindset engagement in the context of unconditional cash transfers',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Results for Development Institute',6400000,'2016-05-01','month','donation log','Global health/pneumonia','http://www.givewell.org/charities/results-for-development/may-2016-grant','Grant for the Market Dynamics practice area’s pneumonia treatment program in Tanzania. The organization aims to use these funds to increase use of amoxicillin, the WHO-recommended first-line treatment for childhood pneumonia.','Tanzania', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','IDinsight',1985000,'2016-06-01','month','donation log','Nonprofit ecosystem','http://www.givewell.org/charities/IDinsight/june-2016-grant','General support grant, to scale its model of supporting and evaluating development interventions. See http://www.givewell.org/charities/idinsight/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','IDinsight',314752,'2016-10-01','month','donation log','Consulting','http://www.givewell.org/charities/IDinsight/october-2016-grant','Grant for embedded GiveWell team. See http://www.givewell.org/charities/idinsight/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','Charity Science: Health',200000,'2016-11-01','month','donation log','Immunization/potential top charity','http://www.givewell.org/charities/charity-science/charity-science-health/november-2016-grant','SMS immunization in India. Budget of 250000 per year, so 80% funding for a year','India', NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',368587,'2016-11-01','month','donation log','Conditional cash transfers','http://www.givewell.org/charities/new-incentives/november-2016-grant','Exit grant, indicating end of relationship (and to give recipient time to transition gracefully). No longer a top charity contender. See http://www.givewell.org/charities/new-incentives/all-content for all GiveWell content on the organization',NULL, NULL, NULL, NULL),
  ('GiveWell Incubation Grants','New Incentives',820000,'2017-04-01','month','donation log','Conditional cash transfers','http://www.givewell.org/charities/new-incentives/april-2017-grant','After an exit grant in 2016-11 for conditional cash transfers for maternal health, the new grant is for a new New Incentives program doing conditional cash transfers to create incentives for immunization. Evaluation would probably be in partnership with IDinsight starting 2017-09','Nigeria', '2017-05-05', 'day', 'https://groups.google.com/forum/#!topic/newly-published-givewell-materials/tnTm4xnuCjI'),
  ('GiveWell Incubation Grants','No Lean Season',1687500,'2016-12-01','month','donation log','Seasonal intracountry migration/potential top charity','http://www.givewell.org/charities/evidence-action/december-2016-grant','Grant to Evidence Action follows previous grants to expand seasonal migration program. Now operates in Bangladesh and Indonesia', 'Bangladesh,Indonesia', '2017-05-11','day', 'https://groups.google.com/forum/#!topic/newly-published-givewell-materials/gBK7-BgPIjY'),
  ('GiveWell Incubation Grants','Georgetown University Initiative on Innovation Development and Evaluation',900000,'2017-01-01','month','donation log','Road safety','http://www.givewell.org/charities/gui2de/january-2017-grant','Grant for Zusha! Road Safety Campaign in Kenya','Kenya','2017-06-15','day','https://groups.google.com/forum/#!topic/newly-published-givewell-materials/e55AvcrOBkc'),
  ('GiveWell Incubation Grants','Evidence Action',2642300,'2017-04-01','month','donation log','Global health and development','http://www.givewell.org/charities/evidence-action/april-2017-grant','Grant to strengthen its financial systems, human resources, and information technology. In addition to its role as an incubation grant (for the development of new top charities) the grant would also support Deworm the World Initiative, which is run by Evidence Action',NULL,'2017-07-31','day','https://groups.google.com/forum/#!topic/newly-published-givewell-materials/T8-yz273EfQ');
