# -- Good Ventures grant to GiveWell top charities

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries, affected_states, affected_cities, influencer) values
  # -- 2011 top and standout charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',500000,'2011-12-23','day','date of donation announcement','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support-december-2011','Grant made by Good Ventures and announced at https://blog.givewell.org/2011/12/23/guest-post-from-cari-tuna/ based on GiveWell top charity list at https://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/ and https://www.givewell.org/charities/top-charities/November-2011 and the 2011 review: https://www.givewell.org/charities/AMF/2011-review','Malawi',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',250000,'2011-12-23','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support-december-2011','Grant made by Good Ventures and announced at https://blog.givewell.org/2011/12/23/guest-post-from-cari-tuna/ based on GiveWell top charity list at https://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/ and the 2011 review: https://www.givewell.org/charities/schistosomiasis-control-initiative/November-2011-review',NULL,NULL,NULL,'GiveWell'),
  # -- 2012 mid-year standout charities
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',100000,'2012-05-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support-may-2012','Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06. Amount of 100000 for GiveDirectly was twice the amount of 50000 for each of the other top and standout charities','Kenya',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Possible',50000,'2012-05-01','month','donation log','Global health/regional healthcare','http://www.goodventures.org/our-portfolio/grants/nyaya-health-general-support-may-2012','Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','Nepal',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','KIPP Houston',50000,'2012-05-01','month','donation log','Education','http://www.goodventures.org/our-portfolio/grants/kipp-houston-general-support-may-2012','Grant to support KIPP Houston’s efforts to improve learning outcomes for underserved youth in Houston. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','United States','Texas','Houston','GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Small Enterprise Foundation',50000,'2012-05-01','month','donation log','Microloans/global poverty','http://www.goodventures.org/our-portfolio/grants/small-enterprise-foundation-general-support-may-2012','Grant to support SEF’s efforts to help alleviate poverty by providing microloans to women in South Africa. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','South Africa',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Innovations for Poverty Action',50000,'2012-05-01','month','donation log','Global poverty/research','http://www.goodventures.org/our-portfolio/grants/innovations-for-poverty-action-general-support-may-2012','Grant for general support. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Pratham',50000,'2012-05-01','month','donation log','Education','http://www.goodventures.org/our-portfolio/grants/pratham-general-support-may-2012','Grant for general support. Along with grants to five other standout charities, see http://www.goodventures.org/research-and-ideas/blog/grants-to-standout-charities from 2012-08-06','India',NULL,NULL,'GiveWell'),
  # -- 2012 end-of-year top charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',1250000,'2012-12-28','day','date of donation announcement','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support-december-2012','Grant made by Good Ventures and announced at http://www.goodventures.org/research-and-ideas/blog/year-end-grants-to-givewells-top-charities based on GiveWell top charity recommendations https://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/ and https://www.givewell.org/charities/top-charities/November-2012 and the 2012 review: https://www.givewell.org/charities/AMF/2012-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',500000,'2012-12-28','day','date of donation announcement','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support-december-2012','Grant made by Good Ventures and announced at http://www.goodventures.org/research-and-ideas/blog/year-end-grants-to-givewells-top-charities based on GiveWell top charity recommendations https://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/ and https://www.givewell.org/charities/top-charities/November-2012 and the 2012 review: https://www.givewell.org/charities/give-directly/November-2012-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',250000,'2012-12-28','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support-december-2012','Grant made by Good Ventures and announced at http://www.goodventures.org/research-and-ideas/blog/year-end-grants-to-givewells-top-charities based on GiveWell top charity recommendations https://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/ and https://www.givewell.org/charities/top-charities/November-2012 and the 2012 review: https://www.givewell.org/charities/schistosomiasis-control-initiative/November-2012-review',NULL,NULL,NULL,'GiveWell'),
  # -- 2013 top and standout charities
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',7000000,'2014-01-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support-december-and-january-2013','Grant announced at http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans on 2013-12-03 by Cari Tuna, including 2 million unconditional + 5 million in matches. Full match amount paid out. Match was not approved by GiveWell. Grant based on GiveWell top charities list at https://www.givewell.org/charities/top-charities/November-2013 and https://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/ and the 2013 review: https://www.givewell.org/international/top-charities/give-directly/November-2013-review','Kenya',NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',750000,'2013-12-03','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support-december-2013','Grant announced at http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans on 2013-12-03 by Cari Tuna. Grant based on GiveWell top charities list at https://www.givewell.org/charities/top-charities/November-2013 and https://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/ and the 2013 review: https://www.givewell.org/charities/schistosomiasis-control-initiative/November-2013-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',1500000,'2013-12-03','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support-december-2013','Grant announced at http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans on 2013-12-03 by Cari Tuna. Grant based on GiveWell top charities list at https://www.givewell.org/charities/top-charities/November-2013 and https://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/ and the 2013 review: https://www.givewell.org/charities/deworm-world-initiative/November-2013-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',5000000,'2014-12-01','day','date of donation announcement','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support','Grant announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/give-directly/December-2014-review','Kenya',NULL,NULL,'GiveWell'),
  # -- 2014 top and standout charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',5000000,'2014-12-01','day','date of donation announcement','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support','Grant to top charity announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/AMF/2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',3000000,'2014-12-01','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support','Grant to top charity announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/schistosomiasis-control-initiative/November-2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',250000,'2014-12-01','day','date of donation announcement','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support','Grant to standout charity announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/international/top-charities/deworm-world-initiative/November-2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Global Alliance for Improved Nutrition',250000,'2014-12-01','day','date of donation announcement','Global health/nutrition/iodine','http://www.goodventures.org/our-portfolio/grants/global-alliance-for-improved-nutrition-general-support','Grant for Universal Salt Iodization Program, a standout charity. Grant announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/GAIN/December-2014-version',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Development Media International',250000,'2014-12-01','day','date of donation announcement','Global health/development communication','http://www.goodventures.org/our-portfolio/grants/development-media-international-general-support','Grant to standout charity announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/DMI/2014-review',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Iodine Global Network',250000,'2014-12-01','day','date of donation announcement','Global health/nutrition/iodine','http://www.goodventures.org/our-portfolio/grants/ign-general-support','Grant to standout charity announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/IGN',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Living Goods',250000,'2014-12-01','day','date of donation announcement',NULL,'http://www.goodventures.org/our-portfolio/grants/living-goods-general-support','Grant to standout charity announced at https://blog.givewell.org/2014/12/01/our-updated-top-charities/ based on GiveWell charity recommendations in the same post; see also https://www.givewell.org/charities/top-charities/November-2014 and the review https://www.givewell.org/charities/living-goods',NULL,NULL,NULL,'GiveWell'),
  # -- 2015 mid-year grant to GiveDirectly
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',25000000,'2015-08-03','day','date of donation announcement','Cash transfers','http://www.goodventures.org/research-and-ideas/blog/announcing-a-25-million-grant-to-givedirectly','One-off grant to top charity over three years also announced at https://blog.givewell.org/2015/08/03/good-ventures-25-million-grant-to-givedirectly/',NULL,NULL,NULL,'GiveWell'),
  # -- 2015 end-year top and standout charities
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',22845500,'2016-01-01','month','donation log','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support1','Intent to make grant announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',9750000,'2016-01-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support2','Intent to make grant announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',10790000,'2016-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support1','Intent to make grant announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',1000000,'2016-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/schistosomiasis-control-initiative-general-support1','Intent to make grant announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Global Alliance for Improved Nutrition',250000,'2015-10-01','month','donation log','Global health/nutrition/iodine','http://www.goodventures.org/our-portfolio/grants/global-alliance-for-improved-nutrition-general-support1','Grant to standout charity for Universal Salt Iodization Program announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Living Goods',250000,'2015-12-01','month','donation log',NULL,'http://www.goodventures.org/our-portfolio/grants/living-goods-general-support1','Grant to standout charity announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Iodine Global Network',250000,'2015-12-01','month','donation log',NULL,'http://www.goodventures.org/our-portfolio/grants/iodine-global-network-general-support','Grant to standout charity announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Development Media International',250000,'2015-12-01','month','donation log','Global health/development communication','http://www.goodventures.org/our-portfolio/grants/development-media-international-general-support1','Grant to standout charity announced on 2015-11-20 at https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/#Sec4a along with grants to other GiveWell top and standout charities',NULL,NULL,NULL,'GiveWell'),
  # -- 2016 end-of-year top charities
  ('Good Ventures/GiveWell top and standout charities','Malaria Consortium',5000000,'2017-02-01','month','donation log','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/malaria-consortium-seasonal-malaria-chemoprevention','Grant specific to the Seasonal Malaria Chemoprevention (SMC) program, a 2016 GiveWell top charity program. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top charities list -- this was the first inclusion of a Malaria Consortium program as a top or standout charity and the first grant from Good Ventures',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Schistosomiasis Control Initiative',13500000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/malaria-consortium-seasonal-malaria-chemoprevention','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','GiveDirectly',2500000,'2017-01-01','month','donation log','Cash transfers','http://www.goodventures.org/our-portfolio/grants/givedirectly-general-support3','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Against Malaria Foundation',15080000,'2017-01-01','month','donation log','Global health/malaria','http://www.goodventures.org/our-portfolio/grants/against-malaria-foundation-general-support2','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list. The grant appears to show up in AMF records (see https://www.againstmalaria.com/Milestones.aspx section "Money raised") on January 18, causing a bump for AMF lifetime money raised from ~$101 million to ~$116 million',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Deworm the World Initiative',4470000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/deworm-the-world-initiative-general-support2','Grant for general support to a 2016 GiveWell top charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Living Goods',250000,'2017-01-01','month','donation log',NULL,'http://www.goodventures.org/our-portfolio/grants/living-goods-general-support2','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Project Healthy Children',250000,'2017-01-01','month','donation log','Global health','http://www.goodventures.org/our-portfolio/grants/project-healthy-children-general-support','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Development Media International',250000,'2017-01-01','month','donation log','Global health/development communication','http://www.goodventures.org/our-portfolio/grants/development-media-international-general-support2','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Food Fortification Initiative',250000,'2016-12-01','month','donation log','Global health/nutrition','http://www.goodventures.org/our-portfolio/grants/food-fortification-initiative-general-support','Grant for general support to a 2016 GiveWell standout charity. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Sightsavers',2950000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/sightsavers-deworming','Grant for deworming program, a 2016 GiveWell top charity program. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','The END Fund',5000000,'2016-12-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/the-end-fund-deworming','Grant for deworming program, a 2016 GiveWell top charity program. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Iodine Global Network',250000,'2016-12-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/the-end-fund-deworming','Grant for general operating support to a standout charity focused on improving iodine content in food. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell'),
  ('Good Ventures/GiveWell top and standout charities','Global Alliance for Improved Nutrition',250000,'2017-01-01','month','donation log','Global health/deworming','http://www.goodventures.org/our-portfolio/grants/the-end-fund-deworming','Grant to standout charity for Universal Salt Iodization program. Grant announced on 2016-11-28 at https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/#Sec3a along with GiveWell top and standout charities list',NULL,NULL,NULL,'GiveWell');
  
