# -- Holden Karnofsky donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Holden Karnofsky','GiveDirectly',NULL,1.0,'2013-12-12','day','date of donation announcement','Cash transfers','http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','First considers not giving, then makes some argument on why it is better to give. Then looks at confidence multipliers for global health interventions relative to GiveDirectly and thinks they are not robust enough to overcome the case for GiveDirectly',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Holden Karnofsky','GiveWell top charities',NULL,1.0,'2014-12-17','day','date of donation announcement','Global health and cash transfers','http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Giving opportunities in 2014 better than 2013, so giving a bit but to regrant to top charities',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Holden Karnofsky','Against Malaria Foundation',NULL,1.0,'2015-12-09','day','date of donation announcement','Global health/malaria','http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Though not directly involved with top charity selection, found the top charity vetting process much more convincing this year, and placed more confidence in cost-effectiveness estimates. Considered other top charities seriously',NULL,NULL,NULL,'GiveWell',NULL,NULL),
    ('Holden Karnofsky','A political campaign',NULL,NULL,'2016-12-09','day','date of donation announcement','Politics/United States','http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','States "Earlier this year, I gave to a political campaign that I considered important and high-impact per dollar. This falls under (a) because there are per-individual contribution limits." Details of political campaign not specified, but 2016 is a presidential election year in the United States',NULL,NULL,NULL,'GiveWell',NULL,NULL);
