# -- Isabel Arjmand donations
insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, influencer) values
  # -- 2016
  ('Isabel Arjmand','Against Malaria Foundation',NULL,0.5,'2016-12-09','day','date of donation announcement','Global health/malaria','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Donation in line with GiveWell headline recommendation (75% to Against Malaria Foundation, 25% to Schistosomiasis Control Initiative), but applied to 2/3 of the total charity spend of the donor','GiveWell'),
  ('Isabel Arjmand','Schistosomiasis Control Initiative',NULL,0.167,'2016-12-09','day','date of donation announcement','Global health/deworming','https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Donation in line with GiveWell headline recommendation (75% to Against Malaria Foundation, 25% to Schistosomiasis Control Initiative), but applied to 2/3 of the total charity spend of the donor','GiveWell'),
  ('Isabel Arjmand','Causa Justa :: Just Cause',NULL, NULL, '2016-12-09','day','date of donation announcement',NULL,'https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','One of a few organizations supported with the 1/3 of the charitable donation budget reserved for donations outside of GiveWell recommendations', NULL),
  ('Isabel Arjmand','Planned Parenthood',NULL, NULL, '2016-12-09','day','date of donation announcement',NULL,'https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','One of a few organizations supported with the 1/3 of the charitable donation budget reserved for donations outside of GiveWell recommendations', NULL),
  ('Isabel Arjmand','International Refugee Assistance Project',NULL, NULL, '2016-12-09','day','date of donation announcement',NULL,'https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','One of a few organizations supported with the 1/3 of the charitable donation budget reserved for donations outside of GiveWell recommendations', NULL),
  ('Isabel Arjmand','StrongMinds',NULL, NULL, '2016-12-09','day','date of donation announcement',NULL,'https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','One of a few organizations supported with the 1/3 of the charitable donation budget reserved for donations outside of GiveWell recommendations', NULL),
  ('Isabel Arjmand','GiveDirectly',NULL, NULL, '2016-12-09','day','date of donation announcement',NULL,'https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','One of a few organizations supported with the 1/3 of the charitable donation budget reserved for donations outside of GiveWell recommendations. Although GiveDirectly does happen to be a GiveWell top charity (unlike the other donees for this allocation) the donor classifies it as a non-GiveWell-influenced expense because her reasons for supporting it are as a model of distributive justice that she would like to see further developed', NULL),
  # -- 2017
  ('Isabel Arjmand','GiveWell top charities',NULL,0.75,'2017-12-11','day','date of donation announcement','Global health and cash transfers','https://blog.givewell.org/2017/12/11/staff-members-personal-donations-for-giving-season-2017/#Isabel','Donation of 75% of the charity budget allocated based on the GiveWell headline recommendation: giving to GiveWell for discretionary regranting to top charities. Donor considered giving directly to Malaria Consortium, as she believes its funding gap to be the highest-impact among the top charities, but ultimately decided to trust GiveWell with the money instead', 'GiveWell'),
  ('Isabel Arjmand','GiveDirectly',NULL,0.05,'2017-12-11','day','date of donation announcement','Cash transfers','https://blog.givewell.org/2017/12/11/staff-members-personal-donations-for-giving-season-2017/#Isabel','Donor is supporting GiveWell because it is an "exceptionally strong, innovative organization with high potential for ‘upside,’ including the potential to serve as a model for other organizations." Donor views rationale for giving to GiveDirectly as somewhere in between the rationale for the GiveWell top charities (75% of total charity budget) and the rationale for the allocation of the remaining 20%', NULL); # -- more to add
