# -- Old GiveWell donations

insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values 
    ('Dario Amodei','VillageReach',10000, 1.0, '2009-01-01','year','date of donation announced in announcement','Global health/vaccination','http://blog.givewell.org/2010/06/03/my-donation-for-2009-guest-post-from-dario-amodei/','Compared against Stop TB',NULL, NULL, 10000, 'GiveWell', NULL, NULL),
    ('Eric Friedman','Freedom from Hunger Fund',1000,NULL,'2006-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','Africare',2500,NULL,'2006-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','CARE',2500,NULL,'2006-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','Freedom from Hunger Fund',28000,NULL,'2008-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation. Relevant quote: In early 2007, my life took a turn for the better: I met the woman who is now my wife. In 2008, Freedom from Hunger offered us the opportunity to join them (at our expense) on a site visit to some of their programs in Ghana. During our time there, we spent a significant amount of time with some of their senior staff (including the CEO), three board members, program staff, and their clients. We saw the programs in action, which increased our conviction in what they do.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','Freedom from Hunger Fund',27000,NULL,'2009-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Historical donation mentioned when explaining more recent donation. Relevant quote: I started following GiveWell in 2009. It was clear from their blog that we shared similar values, and I loved what they were trying to do. But I disagreed with some aspects of their approach. Their emphasis on measurement seemed excessive. This approach had a built-in bias towards smaller, single-program organizations that could measure their impact more precisely. I wasn’t convinced that there weren’t economies of scale in international development. And their focus on scaling up existing solutions and excluding funding unproven innovations seemed incomplete. While I liked what they were doing, I still had more conviction in my own ability to pick organizations.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Eric Friedman','GiveWell top charities',31000,NULL,'2010-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2011/06/21/guest-post-from-eric-friedman/','Relevant quote: Eventually, we decided that there was one fundamental principle we should apply: giving was primarily about helping the less fortunate, not our friendships or personal interests. Breaking up with Freedom from Hunger would be hard. I explained our reasoning and they took it in stride, demonstrating that they care more about the less fortunate than their own institutional growth. They are a good group. But in 2010, we gave about $31,000 to GiveWell’s donor advised fund to ultimately be distributed as they recommended.',NULL,NULL,NULL,NULL,NULL,NULL),
    ('Ian Turner','VillageReach',35000,1.0,'2009-01-01','year','date of donation announced in announcement',NULL,'http://blog.givewell.org/2010/10/28/the-process-of-giving-a-personal-story-guest-post-from-ian-turner/','Last minute decision change from Population Services International based on news that VillageReach is starting a new program similar to its original pilot',NULL,NULL,NULL,'GiveWell',NULL,NULL);
