<style type="text/css">
body.dark {
    background-color: #002b36;
    color: #93a1a1;
}
body.dark a:link { color: rgb(83,173,247); }
body.dark a:visited { color: rgb(167,149,210); }
body.dark table { background-color: #073642; }
body.dark table th { background-color: #1C454F; }

body.dark table.tablesorter {
    background-color: #595957;
    color: #93a1a1;
}

body.dark table.tablesorter thead tr th, body.dark table.tablesorter tfoot tr th {
    background-color: #00252e;
    border: 1px solid #000;
}

body.dark table.tablesorter tbody td {
    background-color: #002b36;
    color: #93a1a1;
}
</style>
