# -- 80,000 Hours hoi polloi writeups

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://80000hours.org/2015/12/where-should-you-donate-to-have-the-most-impact-in-giving-season-2015/','Where should you donate to have the most impact during giving season 2015?','2015-12-24',NULL,'Robert Wiblin','80,000 Hours',NULL,'Against Malaria Foundation|Giving What We Can|GiveWell|AidGrade|Effective Altruism Outreach|Animal Charity Evaluators|Machine Intelligence Research Institute|Raising for Effective Giving|Center for Applied Rationality|Johns Hopkins Center for Health Security|Ploughshares Fund|Future of Humanity Institute|Future of Life Institute|Centre for the Study of Existential Risk|Charity Science|Deworm the World Initiative|Schistosomiasis Control Initiative|GiveDirectly','Evaluator consolidated recommendation list','Global health and development,Effective altruism/movement growth,Rationality improvement,Biosecurity and pandemic preparedness,AI risk,Global catastrophic risks','Robert Wiblin draws on GiveWell recommendations, Animal Charity Evaluators recommendations, Open Philanthropy Project writeups, staff donation writeups and suggestions, as well as other sources (including personal knowledge and intuitions) to come up with a list of places to donate'),
  ('https://80000hours.org/2016/12/the-effective-altruism-guide-to-donating-this-giving-season/','The effective altruism guide to donating this giving season','2016-12-28',NULL,'Robert Wiblin','80,000 Hours',NULL,'Blue Ribbon Study Panel on Biodefense|Cool Earth|Alliance for Safety and Justice|Cosecha|Centre for Effective Altruism|80000 Hours|Animal Charity Evaluators|Compassion in World Farming USA|Against Malaria Foundation|Schistosomiasis Control Initiative|StrongMinds|Ploughshares Fund|Machine Intelligence Research Institute|Future of Humanity Institute','Evaluator consolidated recommendation list','Biosecurity and pandemic preparedness,Global health and development,Animal welfare,AI risk,Global catastrophic risks,Effective altruism/movement growth','Robert Wiblin draws on a number of annual charity evaluations and reviews, as well as staff donation writeups, from sources such as GiveWell and Animal Charity Evaluators, to provide an "effective altruism guide" for 2016 Giving Season donation');

# -- Donation cases
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/15d/why_donate_to_80000_hours/','Why donate to 80,000 Hours','2016-12-24',NULL,'Benjamin Todd','80,000 Hours',NULL,'80000 Hours','Donee donation case','Effective altruism/movement growth','Makes the case for 80000 Hours to be funded by effective altruists (and posted on the Effective Altruism Forum). Supplements their annual review https://80000hours.org/2016/12/annual-review-dec-2016 that provides the underlying data and narrative; however, the case made here explicitly focuses on argumentation appealing to EAs, and makes a clearer ask');
  
# -- Periodic updates
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://80000hours.org/2017/12/annual-review/','Annual review December 2017','2017-12-24',NULL,'Benjamin Todd','80,000 Hours',NULL,'80000 Hours','Donee periodic update','Career coaching/life guidance','80,000 Hours reviews its efforts in 2017 to push more people toward priority paths, both through writeups and through personalized coaching. Also announced at http://effective-altruism.com/ea/1j1/80000_hours_annual_review_released/');

