# -- Animal Charity Evaluators recommendations

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://animalcharityevaluators.org/blog/updated-recommendations-december-2015/','Updated Recommendations: December 2015','2015-12-01',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Animal Equality,Mercy For Animals,The Humane League,Animal Ethics,Animals Australia,Faunalytics,New Harvest,Nonhuman Rights Project,Albert Schweitzer Foundation for Our Contemporaries,The Humane Society of the United States,Vegan Outreach','Evaluator consolidated recommendation list','Animal welfare','2015 recommendations list; top charities are Animal Equality,Mercy For Animals, and The Humane League; five new standout charities added to existing four'),
  ('https://animalcharityevaluators.org/blog/updated-recommendations-december-2016/','Updated Recommendations: December 2016','2016-11-28',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Mercy For Animals,The Humane League,The Good Food Institute,VEBU,Animal Equality,The Humane Society of the United States,Vegan Outreach,Albert Schweitzer Foundation for Our Contemporaries','Evaluator consolidated recommendation list','Animal welfare','Mercy For Animals and The Humane League remain top charities, and The Good Food Institute added to the list; Animal Equality moved from top charity to standout charity; VEBU added to standout charities'),
  ('https://animalcharityevaluators.org/blog/updates-on-select-recommended-charities-room-for-more-funding/','Updates on selected recommended charities’ room for more funding','2017-06-14',NULL,'Toni Adleberg','Animal Charity Evaluators',NULL,'The Good Food Institute,Mercy For Animals,The Humane League,Animal Equality','Evaluator consolidated recommendation list','Animal welfare','Animal Charity Evaluators reports results of a check-in with all its 2016 top charities and one standout charity (Animal Equality) that had previously been a top charity. It verifies that all of them still have room for more funding, therefore continues to recommend them'),
  ('https://animalcharityevaluators.org/blog/ace-fundraising-restrictions/','ACE fundraising restrictions','2017-06-09',NULL,'Kalista Barter','Animal Charity Evaluators',NULL,'Animal Charity Evaluators','Donee periodic update','Animal welfare','ACE describes its fundraising plans: it will restrict fundraising to the months of November and December, it will set a cap of $1 million on funds raised (any money over that will go to its recommended charities). And it will not fundraise if it raises $1 million by November'),
  ('https://animalcharityevaluators.org/blog/updated-charity-recommendations-december-2017/','Updated Charity Recommendations: December 2017','2017-11-27',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Animal Equality,The Good Food Institute,The Humane League,Faunalytics,Vegan Outreach,ProVeg,Albert Schweitzer Foundation for Our Contemporaries,Compassion in World Farming USA,The Humane Society of the United States,L214,Nonhuman Rights Project,Otwarte Klatki','Evaluator consolidated recommendation list','Animal welfare','Animal Charity Evaluators publishes its top charity and standout charity recommendations for year-end 2017. Top charities are Animal Equality, The Good Food Institute, and The Humane League. Standout charities of general interest are Compassion in World Farming USA, L214, and Otwarte Klatki. Standout charities of special interest are Faunalytics and Nonhuman Rights Project');

# -- Donation documentations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://animalcharityevaluators.org/blog/where-the-ace-staff-members-are-giving-in-2017-and-why/','Where the ACE Staff Members Are Giving in 2017 and Why','2017-12-26',NULL,'Allison Smith','Animal Charity Evaluators','Jon Bockman,Allison Smith,Toni Adleberg,Sofia Davis-Fogel,Kieran Greig,Jamie Spurgeon,Erika Alonso,Eric Herboso,Gina Stuessy','Animal Charity Evaluators,The Good Food Institute,Vegan Outreach,A Well-Fed World,Better Eating International,Encompass,Direct Action Everywhere,Animal Charity Evaluators Recommended Charity Fund,Against Malaria Foundation,Animal equality,The Nonhuman Rights Project,AnimaNaturalis Internacional,The Humane League,GiveDirectly,Food Empowerment Project,Mercy For Animals,New Harvest,StrongMinds,Centre for Effective Altruism,Effective Altruism Funds,Machine Intelligence Research Institute,Donor lottery,Sentience Institute,Wild-Animal Suffering Research','Periodic donation list documentation','Animal welfare','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2017'),
  ('https://animalcharityevaluators.org/blog/where-the-ace-staff-members-are-giving-in-2016-and-why/','Where the ACE Staff Members are Giving in 2016 and Why','2016-12-23',NULL,'Leah Edgerton','Animal Charity Evaluators','Allison Smith,Jacy Reese,Toni Adleberg,Gina Stuessy,Kieran Grieg,Eric Herboso,Erika Alonso','Animal Charity Evaluators,Animal Equality,Vegan Outreach,Act Asia,Faunalytics,Farm Animal Rights Movement,Sentience Politics,Direct Action Everywhere,The Humane League,The Good Food Institute,Collectively Free,Planned Parenthood,Future of Life Institute,Future of Humanity Institute,GiveDirectly,Machine Intelligence Research Institute,The Humane Society of the United States,Farm Sanctuary,StrongMinds','Periodic donation list documentation','Animal welfare','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2016'),
  ('https://animalcharityevaluators.org/blog/where-ace-staff-are-giving-and-why/','Where the ACE Staff Members Are Giving and Why','2015-12-21',NULL,'Leah Edgerton','Animal Charity Evaluators','Jon Bockman,Allison Smith,Erika Alonso,Jacy Reese,Kieran Grieg','Animal Charity Evaluators,Vegan Outreach,Mercy For Animals,Direct Action Everywhere,The Humane League,Animal Equality,Farm Sanctuary,The Humane Society of the United States,Animal Equality,Nonhuman Rights Project,New Harvest,Charity Science,Schistosomiasis Control Initiative,Raising for Effective Giving','Periodic donation list documentation','Animal welfare','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2015');
