# -- CEA donation case
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.centreforeffectivealtruism.org/blog/fundraising-2019/','CEA is Fundraising for 2019','2018-11-27','2018-12-05','Larissa Hesketh-Rowe','Centre for Effective Altruism',NULL,'Centre for Effective Altruism','Donee donation case','Effective altruism/movement growth','CEA announces it is fundraising for its 2019 budget, and makes the case for donating to it. The post also includes some updates on how CEA has been doing, but it is not the main post for a review of work and plans for the next year; that post is deferred to early 2019. Cross-posted to the Effective Altruism Forum at https://forum.effectivealtruism.org/posts/jv2og63wwa7rkakf5/cea-is-fundraising-for-2019 where it received 2 comments'),
  ('https://forum.effectivealtruism.org/posts/fM6Qv7aAe7FJGDC3D/cea-is-fundraising-winter-2016','CEA is Fundraising! (Winter 2016)','2016-12-06',NULL,'William MacAskill','Centre for Effective Altruism',NULL,'Centre for Effective Altruism','Donee donation case','Effective altruism/movement growth','CEA makes its case to be funded in 2016');

# -- CEA donation documentations

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.centreforeffectivealtruism.org/blog/cea-staff-donation-decisions-2016/','CEA Staff Donation Decisions 2016','2016-12-06','2016-12-07','Sam Deere','Centre for Effective Altruism','William MacAskill|Michelle Hutchinson|Tara MacAulay|Alison Woodman|Seb Farquhar|Hauke Hillebrandt|Marinella Capriati|Sam Deere|Max Dalton|Larissa Hesketh-Rowe|Michael Page|Stefan Schubert|Pablo Stafforini|Amy Labenz','Centre for Effective Altruism|80,000 Hours|Against Malaria Foundation|Schistosomiasis Control Initiative|Animal Charity Evaluators|Charity Science Health|New Incentives|Project Healthy Children|Deworm the World Initiative|Machine Intelligence Research Institute|StrongMinds|Future of Humanity Institute|Future of Life Institute|Centre for the Study of Existential Risk|Effective Altruism Foundation|Sci-Hub|Vote.org|The Humane League|Foundational Research Institute','Periodic donation list documentation',NULL,'Centre for Effective Altruism (CEA) staff describe their donation plans. The donation amounts are not disclosed.');

# -- CEA periodic update

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.centreforeffectivealtruism.org/blog/cea-s-2017-review-and-2018-plans/','CEA’s 2017 Review and 2018 Plans','2017-12-18','2017-12-19','Larissa Hesketh-Rowe','Centre for Effective Altruism','Effective Altruism Grants','Centre for Effective Altruism','Donee periodic update','Effective altruism/movement growth','The Centre for Effective Altruism reports on its progress in 2017 and describes its plans for 2018. It posts its org chart, describing the five teams (Individual Outreach, Community, Research, Tech, and Operations, and describes the progress and plans for each of the teams. Cross-posted to the Effective Altruism Forum at http://effective-altruism.com/ea/1ir/centre_for_effective_altruism_cea_2017_review_and/');

# -- CEA misc commentary

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/awS28gHCM9GBmhcAA/cea-on-community-building-representativeness-and-the-ea','CEA on community building, representativeness, and the EA Summit','2018-12-15',NULL,'Larissa Hesketh-Rowe|Kerry Vaughan','Effective Altruism Forum','Centre for Effective Altruism','Centre for Effective Altruism','Miscellaneous commentary','Effective altruism/movement growth','CEA describes its current take on community building, explaining that it is focusing more on the most engaged donors, but is financially supporting other initiatives focused on more broad-based community-building'),
  ('https://www.centreforeffectivealtruism.org/blog/introducing-ceas-guiding-principles/','Introducing CEA’s Guiding Principles','2017-03-07','2019-03-26','William MacAskill','Centre for Effective Altruism','Effective Altruism Foundation','Rethink Charity|Centre for Effective Altruism|80,000 Hours|Animal Charity Evaluators|Charity Science|Effective Altruism Foundation|Foundational Research Institute|Future of Life Institute|Raising for Effective Giving|The Life You Can Save','Miscellaneous commentary','Effective altruism','Willam MacAskill outlines CEA''s understanding of the guiding principles of effective altruism: commitment to others, scientific mindset, openness, integrity, and collaborative spirit. The post also lists other organizations that voice their support for these definitions and guiding principles, including: .impact, 80,000 Hours, Animal Charity Evaluators, Charity Science, Effective Altruism Foundation, Foundational Research Institute, Future of Life Institute, Raising for Effective Giving, and The Life You Can Save. The following individuals are also listed as voicing their support for the definition and guiding principles: Elie Hassenfeld of GiveWell and the Open Philanthropy Project, Holden Karnofsky of GiveWell and the Open Philanthropy Project, Toby Ord of the Future of Humanity Institute, Nate Soares of the Machine Intelligence Research Institute, and Peter Singer. William MacAskill worked on the document with Julia Wise, and also expresses gratitude to Rob Bensinger, Jeff Alstott, and Hilary Mayhew for their comments and wording suggestions. The post also briefly mentions an advisory panel set up by Julia Wise, and links to https://forum.effectivealtruism.org/posts/mdMyPRSSzYgk7X45K/advisory-panel-at-cea for more detail'),
  ('https://forum.effectivealtruism.org/posts/mdMyPRSSzYgk7X45K/advisory-panel-at-cea','Advisory panel at CEA','2017-03-06',NULL,'Julia Wise','Effective Altruism Forum',NULL,'Centre for Effective Altruism','Miscellaneous commentary','Effective altruism','Julia Wise announces that CEA is forming an advisory panel to advise it on how to act or respond in cases that have broader implications for the effective altruism community. As of the time of writing the document, the committee comprises Alexander Gordon-Brown, Claire Zabel, Peter Hurford, and Julia Wise. Of the four members, Julia is the only person employed by CEA');



