/* Donee donation cases and periodic updates */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.lesswrong.com/posts/JjGs6mDZxeCWkg3ii/why-cfar','Why CFAR?','2013-12-28',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Salamon, the boss of CFAR, explains the long-term goal (Competence, Epistemic Rationality, and Do-Gooding), plan, and progress to date. This is the first year for CFAR as a standalone organization, after its spinoff from MIRI. Funding situation is dire, with an emergency loan currently taken out that is due in three months. Comments include a $40K donation and a number of other donations'),
  ('https://www.lesswrong.com/posts/KDGnsReYomusL89Rs/cfar-in-2014-continuing-to-climb-out-of-the-startup-pit','CFAR in 2014: Continuing to climb out of the startup pit, heading toward a full prototype','2014-12-26',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','CFAR reports better finances than 2013 (more stability), improvements to its curriculum, attempts to do a full prototype. There is a long discussion of how it redefined the way epistemic rationality fit into the curriculum (moving away from a separate low-rating module to something that is incorporated throughout the course through practical application). Comments are supportive, and include the first appearance of Gleb Tsipursky advertising Intentional Insights'),
  ('https://www.lesswrong.com/posts/MhGamLhQTGFFhLchm/why-cfar-the-view-from-2015','Why CFAR? The view from 2015','2015-12-23',NULL,'Pete Michaud','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Reports 2015 as a year of consolidation and streamlining. Fewer workshops, more efforts to streamline both workshops and continued research on improving rationality. Consolidated original three goals (Competence, Epistemic Rationality, and Do-Gooding) into single framework of applying epistemic rationality. Emphasis on concept of double crux'),
  ('http://rationality.org/resources/updates/2017/cfar-2017-fundraiser','CFAR 2017 Fundraiser','2017-12-20',NULL,'Pete Michaud','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','CFAR gives an update on its plans and hopes for 2018, and asks supporters to donate. CFAR hopes to drive much greater impact by focusing on its summer programs -- the AI Summer Fellows Program (AISFP) and Workshops for AI Safety Strategy (WAISS), as well as more experimental x-risk workshops. The main uncertain variable in its plan is whether and when it will start being able to use its own dedicated venue to conduct events'),
  ('http://rationality.org/resources/updates/2017/cfar-2017-impact-report','CFAR 2017 Impact Report','2017-12-20',NULL,'Dan Keys','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee periodic update','Rationality improvement','The document is an impact report for CFAR in 2017. It breaks the impact question into two parts: what impact does CFAR have on people, and what impact do these people have on the world relative to the counterfactual, particularly in the domain of AI risk?'),
  ('https://www.lesswrong.com/posts/vj6CYLuDPw3ieCB4A/cfar-progress-report-and-future-plans-1','CFAR: Progress Report & Future Plans','2019-12-19',NULL,'Adam Scholl','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee periodic update','Rationality improvement','The blog post describes the progress in 2018 and 2019 of the Center for Applied Rationality (CFAR), including work on AI Risk for Computer Scientists (AIRCS) workshops conducted jointly with MIRI, European workshops, instructor training, and internal improvements. The post also describes plans for 2020, including efforts to mitigate employee burnout, a plan to publicly release the workshop handbook, and hiring and fundraising plans');

/* Reviews */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://benjaminrosshoffman.com/a-first-impression-review-of-the-cfar-ny-workshop/','A First Impression Review of the CFAR NY Workshop','2013-11-04',NULL,'Benjamin Hoffman',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Initial impressions of CFAR workshop. See http://benjaminrosshoffman.com/cfar-second-thoughts-and-a-bleg/ for updated thoughts'),
  ('http://benjaminrosshoffman.com/cfar-second-thoughts-and-a-bleg/','CFAR - Second Impression and a Bleg','2013-12-26',NULL,'Benjamin Hoffman',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR along with suggestion that people donate to it for its fundraiser. Also links to official CFAR funding ask https://www.lesswrong.com/posts/JjGs6mDZxeCWkg3ii/why-cfar (published after original version of post was published'),
  ('https://www.benkuhn.net/cfar-workshop','CFAR workshop review','2013-07-01',NULL,'Ben Kuhn',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of workshop attended; credence in workshop being actually valuable rose significantly'),
  ('http://aarongertler.net/review-cfar-workshop/','Review: CFAR Workshop','2014-05-09',NULL,'Aaron Gertler',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop attended'),
  ('https://forum.effectivealtruism.org/posts/4eNqLMwG3mCTqc8jm/an-ea-at-a-cfar-rationality-workshop-thoughts-and-review','An EA at a CFAR Rationality Workshop: Thoughts and Review','2016-06-06',NULL,'Gleb Tsipursky',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop attended. See http://lesswrong.com/lw/nog/review_and_thoughts_on_current_version_of_cfar/ for a cross-post to LessWrong'),
  ('https://www.lesswrong.com/posts/zqqQDtsWGpXN3wBLZ/the-centre-for-applied-rationality-a-year-later-from-a','The Centre for Applied Rationality: a year later from a (somewhat) outside perspective','2013-05-27',NULL,'Miranda Dixon-Luinenberg',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop attended, one year later'),
  ('https://mindlevelup.wordpress.com/2017/02/28/cfar-workshop-february-2017-review/','CFAR Workshop February 2017 Review','2017-02-28',NULL,'Owen Shen',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop of somebody (unaffiliated with CFAR) who mentored at the workshop recently. Also mirrored at http://lesswrong.com/lw/ool/cfar_workshop_review_february_2017/ on LessWrong'),
  ('https://mindlevelup.files.wordpress.com/2017/02/post-cfar-workshop-compilation.pdf','Post-CFAR Workshop Compilation','2017-02-18',NULL,'Owen Shen',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of post-CFAR experience by soembody who recently mentored at a CFAR workshop. Five parts, all in one PDF; also accessible separately on the web starting with https://mindlevelup.wordpress.com/2017/02/18/ontologies-and-operating-systems-post-cfar-1/'),
  ('http://malcolmocean.com/2016/01/cfar-3-year-retrospective/','CFAR 3 year retrospective','2016-01-28',NULL,'Malcolm Ocean',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Three-year retrospective from CFAR workshop attendee, who has applied techniques learned extensively and attended Alumni Workshops'),
  ('http://www.patheos.com/blogs/hallq/2014/12/cfar-workshop-review/','CFAR workshop review','2014-12-08',NULL,'Topher Brennan',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Delayed review of CFAR workshop experience, mostly linking to and endorsing reviews http://kajsotala.fi/2014/11/event-report-cfars-rationality-workshop-england/ by Kaj Sotala and http://jesswhittlestone.com/blog/2014/11/25/becoming-more-rational-what-i-got-out-of-the-cfar-workshop by Jess Whittlestone'),
  ('http://jesswhittlestone.com/blog/2014/11/25/becoming-more-rational-what-i-got-out-of-the-cfar-workshop','Becoming More Rational: What I got out of attending a CFAR workshop','2014-11-27',NULL,'Jess Whittlestone',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of key lessons learned from a recently attended CFAR workshop'),
  ('http://kajsotala.fi/2014/11/event-report-cfars-rationality-workshop-england/','Event report: CFAR’s rationality workshop, England','2014-11-26',NULL,'Kaj Sotala',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of key lessons learned from a recently attended CFAR workshop'),
  ('http://avalonawoken.tumblr.com/post/160455412324/alright-so-i-just-finished-the-cfar-workshop-which','Alright so I just finished the CFAR workshop','2017-05-08',NULL,NULL,NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop by somebody on Tumblr'),
  ('https://medium.com/@tanyaivanova/field-notes-from-the-cfar-workshop-part-1-personal-mythology-and-the-spinning-plates-489002354cf7','Field notes from the CFAR workshop — Part 1 — Personal mythology and the spinning plates','2016-05-26',NULL,'Tetiana Ivanova',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Part 1 of review of CFAR workshop and of personal takeaway and impact. See https://medium.com/@tanyaivanova/field-notes-from-the-cfar-workshop-part-2-fifty-shades-of-focus-319429d73aa1 for part 2'),
  ('https://medium.com/@tanyaivanova/field-notes-from-the-cfar-workshop-part-2-fifty-shades-of-focus-319429d73aa1','Field notes from the CFAR workshop — Part 2 — fifty shades of focus','2016-05-26',NULL,'Tetiana Ivanova',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Part 2 of review of CFAR workshop and of personal takeaway and impact. See https://medium.com/@tanyaivanova/field-notes-from-the-cfar-workshop-part-1-personal-mythology-and-the-spinning-plates-489002354cf7 for part 1'),  
  ('https://acesounderglass.com/2015/12/03/unquantified-self/','Unquantified Self','2015-12-03',NULL,'Elizabeth Van Nostrand',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of experience at CFAR workshop and personal takeaways'),
  ('https://namelessvirtue.com/2015/08/07/boston-cfar-alumni-workshop/','The Boston CFAR alumni workshop','2015-07-08',NULL,'Alex Altair',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR alumni workshop'),
  ('https://vkrakovna.wordpress.com/2015/05/17/hamming-questions-and-bottlenecks/','Hamming questions and bottlenecks','2015-05-17',NULL,'Victoria Krakovna',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Discussion of CFAR worshop and the Hamming question (about the most important things one is working on)'),
  ('http://aslanides.io/travel/2017/04/30/cfar-games/','Bay Area II: CFAR Workshop','2017-04-30',NULL,'John Aslanides',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Write-up about experience at the Summer 2016 Workshop for AI Researchers run by CFAR');
  
