# -- Donee donation cases
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://lesswrong.com/lw/jej/why_cfar/','Why CFAR','2013-12-28',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Salamon, the boss of CFAR, explains the long-term goal (Competence, Epistemic Rationality, and Do-Gooding), plan, and progress to date. This is the first year for CFAR as a standalone organization, after its spinoff from MIRI. Funding situation is dire, with an emergency loan currently taken out that is due in three months. Comments include a $40K donation and a number of other donations'),
  ('http://lesswrong.com/lw/lfg/cfar_in_2014_continuing_to_climb_out_of_the/','CFAR in 2014: Continuing to climb out of the startup pit, heading toward a full prototype','2014-12-26',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','CFAR reports better finances than 2013 (more stability), improvements to its curriculum, attempts to do a full prototype. There is a long discussion of how it redefined the way epistemic rationality fit into the curriculum (moving away from a separate low-rating module to something that is incorporated throughout the course through practical application). Comments are supportive, and include the first appearance of Gleb Tsipursky advertising Intentional Insights'),
  ('http://lesswrong.com/lw/n39/why_cfar_the_view_from_2015/','Why CFAR? The view from 2015','2015-12-23',NULL,'Pete Michaud','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Reports 2015 as a year of consolidation and streamlining. Fewer workshops, more efforts to streamline both workshops and continued research on improving rationality. Consolidated original three goals (Competence, Epistemic Rationality, and Do-Gooding) into single framework of applying epistemic rationality. Emphasis on concept of double crux');

# -- Reviews
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://benjaminrosshoffman.com/a-first-impression-review-of-the-cfar-ny-workshop/','A First Impression Review of the CFAR NY Workshop','2013-11-04',NULL,'Ben Hoffman',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Initial impressions of CFAR workshop. See http://benjaminrosshoffman.com/cfar-second-thoughts-and-a-bleg/ for updated thoughts'),
  ('http://benjaminrosshoffman.com/cfar-second-thoughts-and-a-bleg/','CFAR - Second Impression and a Bleg','2013-12-26',NULL,'Ben Hoffman',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR along with suggestion that people donate to it for its fundraiser. Also links to official CFAR funding ask http://lesswrong.com/lw/jej/why_cfar/ (published after original version of post was published'),
  ('https://www.benkuhn.net/cfar-workshop','CFAR workshop review','2013-07-01',NULL,'Ben Kuhn',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of workshop attended; credence in workshop being actually valuable rose significantly'),
  ('http://aarongertler.net/review-cfar-workshop/','Review: CFAR Workshop','2014-05-09',NULL,'Aaron Gertler',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop attended'),
  ('http://effective-altruism.com/ea/yg/an_ea_at_a_cfar_rationality_workshop_thoughts_and/','An EA at a CFAR Rationality Workshop: Thoughts and Review','2016-06-06',NULL,'Gleb Tsipursky',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop attended'),
  ('http://lesswrong.com/lw/hiv/the_centre_for_applied_rationality_a_year_later/','The Centre for Applied Rationality: a year later from a (somewhat) outside perspective','2013-05-27',NULL,'Miranda Dixon-Luinenberg',NULL,NULL,'Center for Applied Rationality','Evaluator review of donee','Rationality improvement','Review of CFAR workshop attended, one year later');
  

