# -- TLYCS donation case
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/19k/the_life_you_can_saves_2016_annual_report/',"The Life You Can Save's 2016 Annual Report",# '
   '2017-04-26',NULL,'Jon Behar','The Life You Can Save',NULL,'The Life You Can Save','Donee donation case','Effective altruism/movement growth/fundraising','TLYCS provides an annual report of money moved and influenced');

# -- Donation documentations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/dznyZNkAQMNq6HtXf/my-2018-donations','My 2018 donations','2018-11-23',NULL,'Vipul Naik','Effective Altruism Forum','Vipul Naik','GiveWell top charities|Machine Intelligence Research Institute|Donor lottery','Periodic donation list documentation','Global health and development|AI safety','The blog post describes an allocation of $2,000 to GiveWell for regranting to top charities, and $500 each to MIRI and the $500,000 donor lottery. The latter two donations are influenced by Issa Rice, who describes his reasoning at https://issarice.com/donation-history#section-3 Vipul Naik''s post explains the reason for donating now rather than earlier or later, the reason for donating this amount, and the selection of recipients. The post is also cross-posted at https://vipulnaik.com/blog/my-2018-donations/ and https://github.com/vipulnaik/working-drafts/blob/master/eaf/my-2018-donations.md'),
  ('http://slatestarcodex.com/2017/02/02/guest-post-the-international-refugee-assistance-program/','[GUEST POST] The International Refugee Assistance Project','2017-02-02',NULL,'Elizabeth Van Nostrand','Slate Star Codex','Elizabeth Van Nostrand','International Refugee Assistance Project','Single donation documentation','Migration policy/refugee assistance','Discusses 100 dollar donation to International Refugee Assistance Project (IRAP) in light of the executive order by Donald Trump on 2017-01-27 banning entry of people from 7 countries. Highlights value of strong existing capacity in the American Civil Liberties Union (ACLU) that allowed for a quick response, and help from the IRAP in doing so. ACLU is well-funded, but IRAP has just gotten off the ground with a grant from the Open Philanthropy Project, so donating to that'),
  ('https://acesounderglass.com/2016/12/01/5167/','Seeing Like A State, Flashlights, and Giving This Year','2016-12-01',NULL,'Elizabeth Van Nostrand','Personal blog','Elizabeth Van Nostrand|Ozy Brennan','Tostan','Third-party case for donation','Education','Argues that donations to things that build capacity could be more valuable than donations to things with directly measured impact. Recommends Tostan for its capacity-building. The post influenced others to donate to Tostan: see https://thingofthings.wordpress.com/2016/12/22/donations-post-2016/ and https://acesounderglass.com/2017/01/05/tracking-donations/'),
  ('http://effective-altruism.com/ea/16b/why_i_donated_to_the_environmental_data/','Why I donated to the Environmental Data & Governance Initiative','2017-01-16',NULL,'Jacob Trefethen','Effective Altruism Forum','Jacob Trefethen','Environmental Data and Governance Initiative','Single donation documentation','Environmentalism/watchdog','Part 1 of the post focused on the case for donating to young, promising organizations. Part 2 explained why the author considered the specific donee a good fit'),
  ('http://effective-altruism.com/ea/15y/where_i_gave_and_why_in_2016/','Where I gave and why in 2016 ','2017-01-06',NULL,'Ben Kuhn','Effective Altruism Forum','Ben Kuhn','EA Giving Group|GiveWell|GiveDirectly','Periodic donation list documentation','Global health and development','Originally posted at http://www.benkuhn.net/giving-2016 and cross-posted to Effective Altruism Forum due to evidence that people like donation write-ups'),
  ('http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/','EAs write about where they give','2016-12-09',NULL,'Julia Wise','Effective Altruism Forum','Blake Borgeson|Eva Vivalt|Ben Kuhn|Alexander Gordon-Brown and Denise Melchin|Elizabeth Van Nostrand','Machine Intelligence Research Institute|Center for Applied Rationality|AidGrade|Charity Science: Health|80,000 Hours|Centre for Effective Altruism|Tostan','Periodic donation list documentation','Global health and development, AI risk','Julia Wise got submissions from multiple donors about their donation plans and put them together in a single post. The goal was to cover people outside of organizations that publish such posts for their employees'),
  ('https://www.leafscience.org/vitalik-buterin-the-best-thing-to-donate-money-to-is-the-fight-against-aging/','Vitalik Buterin: The Best Thing to Donate Money to is The Fight Against Aging','2018-03-20','2018-03-20','Elena Milova|Josh Conway','Life Extension Advocacy Foundation','Vitalik Buterin','SENS Research Foundation','Reasoning supplement','Life sciences/anti-aging','An interview with Vitalik Buterin describing his reasons for donating to SENS.'),
  ('https://www.benkuhn.net/giving-2017','Where, why and how I donated in 2017','2018-02-01',NULL,'Ben Kuhn',NULL,'Ben Kuhn|Open Philanthropy Project|Effective Altruism Funds|Effective Altruism Grants','GiveWell|GiveWell top charities|EA Giving Group|Effective Altruism Funds','Periodic donation list documentation','Global health and development','Kuhn describes his decision to allocate money between GiveWell, GiveWell top charities, and his own donor-advised fund managed by Fidelity. Kuhn also discusses the Open Philanthropy Project, EA Funds, and EA Grants, and the EA Giving Group he donated to the previous year'),
  ('https://medium.com/thinking-about-animals/thinking-behind-2017-donations-to-reduce-animal-use-9259253dbcbb','Thinking behind 2017 donations to reduce animal use','2017-12-31', NULL, 'Jason Ketola', NULL, NULL, 'New Harvest|The Good Food Institute|Plant Based Foods Association|Wild-Animal Suffering Research','Single donation documentation','Animal welfare','The document describes recent developments with The Good Food Institute, New Harvest, and other organizations, and why the author decided to donate to New Harvest');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016','Donations for 2016','2016-12-28',NULL,'Jacob Steinhardt',NULL,'Jacob Steinhardt','Donor lottery|GiveWell top charities|GiveDirectly|Blue Ribbon Study Panel|Carnegie Endowment for International Peace','Periodic donation list documentation','Biosecurity and pandemic preparedness,International relations,Global health and development','Explanation for donation choices, also mention experimental funding of smaller projects');

# -- Older stuff on Deworm the World Initiative
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://endtheneglect.org/2011/01/spotlight-on-deworm-the-world/','Spotlight on Deworm the World','2011-01-26',NULL,'Alanna Shaikh','End the Neglect',NULL,'Deworm the World Initiative','Evaluator review of donee','Global health/deworming','Alanna Shaikh praises Deworm the World for working with existing groups rather than creating redundant, duplicative effort. This is still in the early days of the organization, before it goes under Innovations for Poverty Action and then Evidence Action');

# -- Other

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://issarice.com/against-malaria-foundation','Against Malaria Foundation','2017-04-27','2017-04-28','Issa Rice',NULL,NULL,'Against Malaria Foundation','Evaluator review of donee','Global health/malaria','The document records off-the-cuff thoughts that the author had while creating https://timelines.issarice.com/wiki/Timeline_of_Against_Malaria_Foundation as part of contract work. It is a collection of interrelated but distinct observations. See https://www.facebook.com/vipulnaik.r/posts/10211866218306794 for a Facebook discussion of the post'),
  ('https://issarice.com/open-philanthropy-project-non-grant-funding','Open Philanthropy Project non-grant funding','2017-04-02','2017-05-17','Issa Rice',NULL,'Open Philanthropy Project',NULL,'Miscellaneous commentary',NULL,'The document lists some funding by the Open Philanthropy Project that is publicly disclosed (either by Open Philanthropy Project or by the donee or another reliable source) but is not part of the Open Philanthropy Project grants database, and is not included in employee salaries and benefits.'),
  ('https://forum.effectivealtruism.org/posts/4bg2qxWrEdzPmR3ze/ea-orgs-are-trying-to-fundraise-usd10m-usd16m','EA orgs are trying to fundraise ~$10m - $16m','2019-01-06',NULL,'Hauke Hillebrandt','Effective Altruism Forum',NULL,'Centre for Effective Altruism|Effective Altruism Foundation|Machine Intelligence Research Institute|Forethought Foundation for Global Priorities Research|Sentience Institute|Alliance to Feed the Earth in Disasters|Global Catastrophic Risk Institute|Rethink Priorities|EA Hotel|80,000 Hours|Rethink Charity','Miscellaneous commentary',NULL,'The blog post links to and discusses the spreadsheet https://docs.google.com/spreadsheets/d/10zU6gp_H_zuvlZ2Vri-epSK0_urbcmdS-5th3mXQGXM/edit which tables various organizations and their fundraising targets, along with quotes and links to fundraising posts. The blog post itself has three points, the last of whichis that the EA community is relatively more funding constrained again');

# -- Kevin Watkinson critique
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1e8/should_eas_think_twice_before_donating_to_gfi/','Should EAs think twice before donating to GFI?','2017-08-31',NULL,'Kevin Watkinson','Effective Altruism Forum','Open Philanthropy Project','The Good Food Institute','Third-party case against donation','Animal welfare','The post argues against donations to The Good Food Institute, noting its limited track record as well as the huge amount of funding it is already receiving from the Open Philanthropy Project. This post is made shortly after an exchange between the post author (Kevin Watkinson) and Holden Karnofsky of the Open Philanthropy Project in http://www.openphilanthropy.org/blog/march-2017-open-thread?page=1#comment-305 (the open thread of the Open Philanthropy Project). The post also critiques Animal Charity Evaluators (ACE) for a positive assessment of GFI, and comments include a response from an ACE employee and an ACE board member (neither in an official capacity)');

# -- Effective Altruism Foundation docs

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1in/effective_altruism_foundation_update_plans_for/','Effective Altruism Foundation update: Plans for 2018 and room for more funding','2017-12-15',NULL,'Jonas Vollmer','Effective Altruism Foundation',NULL,'Effective Altruism Foundation|Raising for Effective Giving|Foundational Research Institute|Wild-Animal Suffering Research','Donee donation case','Effective altruism/movement growth/s-risk reduction','The document describes the 2018 plan and room for more funding of the Effective Altruism Foundation. Subsidiaries include Raising for Effective Giving, Foundational Research Institute, and Wild-Animal Suffering Research, Also cross-posted at https://ea-foundation.org/blog/our-plans-for-2018/ (own blog)');

# -- Global Catastrophic Risk Institute docs

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://gcrinstitute.org/summary-of-gcris-2018-2019-accomplishments-plans-and-fundraising/','Summary of GCRI’s 2018-2019 Accomplishments, Plans, and Fundraising','2018-12-12',NULL,'Seth Baum','Global Catastrophic Risk Institute',NULL,'Global Catastrophic Risk Institute','Donee periodic update','Global catastrophic risks','This is the summary post for a series of blog posts detailing the 2018 accomplishments, 2019 plans in terms of topics covered and organization development, and the 2018 and 2019 finances. Individual posts dealing with these topics are linked. A teaser post linking to this summary post is posted to the Effective Altruism Forum at https://forum.effectivealtruism.org/posts/J3T6mPN9JmY7htF5f/global-catastrophic-risk-institute-2018-2019-updates on 2018-12-17');

# -- Forethought Foundation docs

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/vxwcxwiDKCnyHJhbz/announcing-the-new-forethought-foundation-for-global','Announcing the new Forethought Foundation for Global Priorities Research','2018-12-04',NULL,'William MacAskill','Effective Altruism Forum',NULL,'Forethought Foundation for Global Priorities Research|Global Priorities Institute|Centre for Effective Altruism','Launch','Cause prioritization','The blog post announces the launch of the Forethought Foundation for Global Priorities Research. The planned total budget for 2019 and 2020 is £1.12 million - £1.47 million, and a breakdown is provided in the post. The project will be incubated by the Centre for Effective Altruism, and its work is intended to complement the work of the Global Priorities Institute');

# -- Miscellaneous job ads

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1mq/job_opportunity_at_the_future_of_humanity/','Job opportunity at the Future of Humanity Institute and Global Priorities Institute','2018-04-01',NULL,'Hayden Win','Effective Altruism Forum',NULL,'Global Priorities Institute|Future of Humanity Institute','Job advertisement','AI safety','The blog post advertises a Senior Administrator position that would be shared between the Future of Humanty Institute and the Global Priorities Institute');

# -- Miscellaneous reviews

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1ls/introducing_czech_association_for_effective/','Introducing Czech Association for Effective Altruism - history','2018-03-12',NULL,'Jan Kulveit','Effective Altruism Forum',NULL,'Czech Association for Effective Altruism','Launch','Effective altruism','The document describes the history of the Czech Association for Effective Altruism (CZEA) and its inspiration from LessWrong and EAGx Oxford'),
  ('http://effective-altruism.com/ea/1mu/review_of_czea_intense_ea_retreat/','Review of CZEA "Intense EA Weekend" retreat','2018-04-05',NULL,'Jan Kulveit','Effective Altruism Forum',NULL,'Czech Association of Effective Altruism','Evaluator review of donee','Effective altruism','The blog post describes a weekend long intense retreat in March 2018, conducted by the CZEA');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.bayesianinvestor.com/charities.html','Peter McCluskey''s favorite charities','2015-12-06',NULL,'Peter McCluskey',NULL,'Peter McCluskey','Center for Applied Rationality|Future of Humanity Institute|AI Impacts|GiveWell|GiveWell top charities|Future of Life Institute|Centre for Effective Altruism|Brain Preservation Foundation|Multidisciplinary Association for Psychedelic Studies|Electronic Frontier Foundation|Methuselah Mouse Prize|SENS Research Foundation|Foresigh Institute','Evaluator consolidated recommendation list',NULL,'The page discusses the favorite charities of Peter McCluskey and his opinion on their current room for more funding in light of their financial situation and expansion plans');

