# -- Donee donation cases: CFAR
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://lesswrong.com/lw/jej/why_cfar/','Why CFAR','2013-12-28',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Salamon, the boss of CFAR, explains the long-term goal (Competence, Epistemic Rationality, and Do-Gooding), plan, and progress to date. This is the first year for CFAR as a standalone organization, after its spinoff from MIRI. Funding situation is dire, with an emergency loan currently taken out that is due in three months. Comments include a $40K donation and a number of other donations'),
  ('http://lesswrong.com/lw/lfg/cfar_in_2014_continuing_to_climb_out_of_the/','CFAR in 2014: Continuing to climb out of the startup pit, heading toward a full prototype','2014-12-26',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','CFAR reports better finances than 2013 (more stability), improvements to its curriculum, attempts to do a full prototype. There is a long discussion of how it redefined the way epistemic rationality fit into the curriculum (moving away from a separate low-rating module to something that is incorporated throughout the course through practical application). Comments are supportive, and include the first appearance of Gleb Tsipursky advertising Intentional Insights'),
  ('http://lesswrong.com/lw/n39/why_cfar_the_view_from_2015/','Why CFAR? The view from 2015','2015-12-23',NULL,'Pete Michaud','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Reports 2015 as a year of consolidation and streamlining. Fewer workshops, more efforts to streamline both workshops and continued research on improving rationality. Consolidated original three goals (Competence, Epistemic Rationality, and Do-Gooding) into single framework of applying epistemic rationality. Emphasis on concept of double crux');

# -- Donee donation cases: other
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/14p/cea_is_fundraising_winter_2016/','CEA is Fundraising! (Winter 2016)','2016-12-06',NULL,'William MacAskill','Centre for Effective Altruism',NULL,'Centre for Effective Altruism','Donee donation case','Effective altruism/movement growth','CEA makes its case to be funded in 2016'),
  ('http://effective-altruism.com/ea/19k/the_life_you_can_saves_2016_annual_report/',"The Life You Can Save's 2016 Annual Report",# '
   '2017-04-26',NULL,'Jon Behar','The Life You Can Save',NULL,'The Life You Can Save','Donee donation case','Effective altruism/movement growth/fundraising','TLYCS provides an annual report of money moved and influenced');

# -- Donation documentations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://slatestarcodex.com/2017/02/02/guest-post-the-international-refugee-assistance-program/','[GUEST POST] The International Refugee Assistance Project','2017-02-02',NULL,'Elizabeth Van Nostrand','Slate Star Codex','Elizabeth Van Nostrand','International Refugee Assistance Project','Single donation documentation','Migration policy/refugee assistance','Discusses 100 dollar donation to International Refugee Assistance Project (IRAP) in light of the executive order by Donald Trump on 2017-01-27 banning entry of people from 7 countries. Highlights value of strong existing capacity in the American Civil Liberties Union (ACLU) that allowed for a quick response, and help from the IRAP in doing so. ACLU is well-funded, but IRAP has just gotten off the ground with a grant from the Open Philanthropy Project, so donating to that'),
  ('https://acesounderglass.com/2016/12/01/5167/','Seeing Like A State, Flashlights, and Giving This Year','2016-12-01',NULL,'Elizabeth Van Nostrand','Personal blog','Elizabeth Van Nostrand,Ozy Brennan','Tostan','Third-party case for donation','Education','Argues that donations to things that build capacity could be more valuable than donations to things with directly measured impact. Recommends Tostan for its capacity-building. The post influenced others to donate to Tostan: see https://thingofthings.wordpress.com/2016/12/22/donations-post-2016/ and https://acesounderglass.com/2017/01/05/tracking-donations/'),
  ('http://effective-altruism.com/ea/16b/why_i_donated_to_the_environmental_data/','Why I donated to the Environmental Data & Governance Initiative','2017-01-16',NULL,'Jacob Trefethen','Effective Altruism Forum','Jacob Trefethen','Environmental Data and Governance Initiative','Single donation documentation','Environmentalism/watchdog','Part 1 of the post focused on the case for donating to young, promising organizations. Part 2 explained why the author considered the specific donee a good fit'),
  ('http://effective-altruism.com/ea/15y/where_i_gave_and_why_in_2016/','Where I gave and why in 2016 ','2017-01-06',NULL,'Ben Kuhn','Effective Altruism Forum','Ben Kuhn','EA Giving Group,GiveWell,GiveDirectly','Periodic donation list documentation','Global health and global poverty','Originally posted at http://www.benkuhn.net/giving-2016 and cross-posted to Effective Altruism Forum due to evidence that people like donation write-ups'),
  ('http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/','EAs write about where they give','2016-12-09',NULL,'Julia Wise','Effective Altruism Forum','Blake Borgeson,Eva Vivalt,Ben Kuhn,Alexander Gordon-Brown and Denise Melchin,Elizabeth Van Nostrand','Machine Intelligence Research Institute,Center for Applied Rationality,AidGrade,Charity Science: Health,80000 Hours,Centre for Effective Altruism,Tostan','Periodic donation list documentation','Global health and global poverty, AI risk','Julia Wise got submissions from multiple donors about their donation plans and put them together in a single post. The goal was to cover people outside of organizations that publish such posts for their employees'),
  ('https://www.centreforeffectivealtruism.org/blog/cea-staff-donation-decisions-2016/','CEA Staff Donation Decisions 2016','2016-12-06','2016-12-07','Sam Deere','Centre for Effective Altruism','William MacAskill,Michelle Hutchinson,Tara MacAulay,Alison Woodman,Seb Farquhar,Hauke Hillebrandt,Marinella Capriati,Sam Deere,Max Dalton,Larissa Hesketh-Rowe,Michael Page,Stefan Schubert,Pablo Stafforini,Amy Labenz','Centre for Effective Altruism,80000 Hours,Against Malaria Foundation,Schistosomiasis Control Initiative,Animal Charity Evaluators,Charity Science: Health,New Incentives,Project Healthy Children,Deworm the World Initiative,Machine Intelligence Research Institute,Strong Minds,Future of Humanity Institute,Future of Life Institute,Centre for the Study of Existential Risk,Effective Altruism Foundation,Sci-Hub,Vote.org,The Humane League,Foundational Research Institute','Periodic donation list documentation',NULL,'Centre for Effective Altruism (CEA) staff describe their donation plans. The donation amounts are not disclosed.'),
  
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016','Donations for 2016','2016-12-28',NULL,'Jacob Steinhardt',NULL,'Jacob Steinhardt','Donor lottery,GiveWell top charities,GiveDirectly,Blue Ribbon Study Panel,Carnegie Endowment for International Peace','Periodic donation list documentation','Biosecurity and pandemic preparedness,International relations,Global health and global poverty','Explanation for donation choices, also mention experimental funding of smaller projects');

# -- documents related to SHIC
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/128/students_for_high_impact_charity_review_and_10k/','Students for High Impact Charity: Review and $10K Grant','2016-09-27',NULL,'Peter Hurford',NULL,'Peter Hurford','Students for High Impact Charity','Single donation documentation','Effective altruism/movement growth','Explanation of some of the investigative process that led the author to decide to donate to SHIC. The focus is on the investigation process and information revealed about SHIC rather than on the amount donated'),
  ('http://effective-altruism.com/ea/190/students_for_highimpact_charity_interim_report/','Students for High-Impact Charity Interim Report','2017-04-03',NULL,'Baxter Bullock',NULL,NULL,'Students for High Impact Charity','Donee periodic update','Effective altruism/movement growth','Full report linked to is at https://drive.google.com/file/d/0B_YyyNcGXfb6ZVljWFVSdThVVjg/view (Google Drive)');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/','2017 AI Risk Literature Review and Charity Comparison','2016-12-13',NULL,'Ben Hoskin',NULL,'Ben Hoskin','Machine Intelligence Research Institute,Future of Humanity Institute,OpenAI,Center for Human-Compatible AI,Future of Life Institute,Centre for the Study of Existential Risk,Leverhulme Centre for the Future of Intelligence,Global Catastrophic Risks Institute,Global Priorities Project,AI Impacts,Xrisks Institute,X-Risks Net,Center for Applied Rationality,80000 Hours,Raising for Effective Giving','Review of current state of cause area','AI risk','The lengthy blog post covers all the published work of prominent organizations focused on AI risk. References http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#sources1007 for the MIRI part of it but notes the absence of information on the many other orgs'),
  ('http://effective-altruism.com/ea/14c/why_im_donating_to_miri_this_year/',"Why I'm donating to MIRI this year", #'
   '2016-11-30',NULL,'Owen Cotton-Barratt',NULL,'Owen Cotton-Barratt','Machine Intelligence Research Institute','Single donation documentation','AI risk','Primary interest is in existential risk. Cited CoI and other reasons for not donating to own employer, Centre for Effective Altruism. Notes disagreements with MIRI, citing http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#research but highlights need for epistemic humility'),
  ('https://www.centreforeffectivealtruism.org/blog/changes-in-funding-in-the-ai-safety-field','Changes in funding in the AI safety field','2017-02-01','2017-02-02','Sebastian Farquhar','Centre for Effective Altruism',NULL,'Machine Intelligence Research Institute,Center for Human-Compatible AI,Leverhulme Centre for the Future of Intelligence,Future of Life Institute,Future of Humanity Institute,OpenAI,MIT Media Lab','Review of current state of cause area','AI risk','The post reviews AI safety funding from 2014 to 2017 (projections for 2017). Cross-posted on EA Forum at http://effective-altruism.com/ea/16s/changes_in_funding_in_the_ai_safety_field/');

# -- OpenAI
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://slatestarcodex.com/2015/12/17/should-ai-be-open/','Should AI Be Open?','2015-12-17',NULL,'Scott Alexander','Slate Star Codex',NULL,'OpenAI','Evaluator review of donee','AI risk','Scott Alexander draws a parallel between "open" AI and open nuclear weapons, to highlight that openness is not necessarily good here. Plus a lot of general rambling'),
  ('http://lesswrong.com/r/discussion/lw/oul/openai_makes_humanity_less_safe/','OpenAI makes humanity less safe','2017-04-03',NULL,'Ben Hoffman','LessWrong','Open Philanthropy Project','OpenAI','Evaluator review of donee','AI risk','Hoffman argues that OpenAI is good intentions gone awry, and is critical of the Open Philanthropy Project donation to OpenAI');

# -- Older stuff on Deworm the World Initiative
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://endtheneglect.org/2011/01/spotlight-on-deworm-the-world/','Spotlight on Deworm the World','2011-01-26',NULL,'Alanna Shaikh','End the Neglect',NULL,'Deworm the World Initiative','Evaluator review of donee','Global health/deworming','Alanna Shaikh praises Deworm the World for working with existing groups rather than creating redundant, duplicative effort. This is still in the early days of the organization, before it goes under Innovations for Poverty Action and then Evidence Action');

# -- Effective Altruism Funds

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/174/introducing_the_ea_funds/','Introducing the EA Funds','2017-02-09',NULL,'William MacAskill','Centre for Effective Altruism','Effective Altruism Funds','Effective Altruism Funds','Launch','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','William MacAskill of the Centre for Effective Altruism (CEA) proposes EA Funds, inspired by the Shulman/Christiano donor lottery from 2016-12, while also incorporating elements of the EA Giving Group run by Nick Beckstead'),
  ('http://effective-altruism.com/ea/17v/ea_funds_beta_launch/','EA Funds Beta Launch','2017-02-28',NULL,'Tara MacAulay','Centre for Effective Altruism','Effective Altruism Funds','Effective Altruism Funds','Launch','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','Tara MacAulay of the Centre for Effective Altruism (CEA), the parent of Effective Altruism Funds, describes the beta launch of the project. CEA will revisit within three months to decide whether to make the EA Funds permanent'),
  ('http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','Update on Effective Altruism Funds','2017-04-20',NULL,'Kerry Vaughan','Centre for Effective Altruism','Effective Altruism Funds','Effective Altruism Funds','Periodic donation list documentation','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','Kerry Vaughan provides a progress report on the beta launch of EA Funds, and says it will go on beyond beta. The post includes information on reception of EA Funds so far, money donated to the funds, and fund allocations for the money donated so far'),
  ('http://effective-altruism.com/ea/1ax/discussion_adding_new_funds_to_ea_funds/','Discussion: Adding New Funds to EA Funds','2017-06-01',NULL,'Kerry Vaughan','Centre for Effective Altruism','Effective Altruism Funds',NULL,'Broad donor strategy','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','Kerry Vaughan of Effective Altruism Funds discusses the alternatives being considered regarding expanding the number of funds, and asks readers for opinions');
