# -- Animal Charity Evaluators recommendations

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://animalcharityevaluators.org/blog/updated-recommendations-december-2015/','Updated Recommendations: December 2015','2015-12-01',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Animal Equality,Mercy For Animals,The Humane League,Animal Ethics,Animals Australia,Faunalytics,New Harvest,Nonhuman Rights Project,Albert Schweitzer Foundation for Our Contemporaries,The Humane Society of the United States,Vegan Outreach','Evaluator consolidated recommendation list','Animal welfare','2015 recommendations list; top charities are Animal Equality,Mercy For Animals, and The Humane League; five new standout charities added to existing four'),
  ('https://animalcharityevaluators.org/blog/updated-recommendations-december-2016/','Updated Recommendations: December 2016','2016-11-28',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Mercy For Animals,The Humane League,The Good Food Institute,VEBU,Animal Equality,The Humane Society of the United States,Vegan Outreach,Albert Schweitzer Foundation for Our Contemporaries','Evaluator consolidated recommendation list','Animal welfare','Mercy For Animals and The Humane League remain top charities, and The Good Food Institute added to the list; Animal Equality moved from top charity to standout charity; VEBU added to standout charities'),
  ('https://animalcharityevaluators.org/blog/updates-on-select-recommended-charities-room-for-more-funding/','Updates on selected recommended charities’ room for more funding','2017-06-14',NULL,'Toni Adleberg','Animal Charity Evaluators',NULL,'The Good Food Institute,Mercy For Animals,The Humane League,Animal Equality','Evaluator consolidated recommendation list','Animal welfare','Animal Charity Evaluators reports results of a check-in with all its 2016 top charities and one standout charity (Animal Equality) that had previously been a top charity. It verifies that all of them still have room for more funding, therefore continues to recommend them'),
  ('https://animalcharityevaluators.org/blog/ace-fundraising-restrictions/','ACE fundraising restrictions','2017-06-09',NULL,'Kalista Barter','Animal Charity Evaluators',NULL,'Animal Charity Evaluators','Donee periodic update','Animal welfare','ACE describes its fundraising plans: it will restrict fundraising to the months of November and December, it will set a cap of $1 million on funds raised (any money over that will go to its recommended charities). And it will not fundraise if it raises $1 million by November');

# -- Giving What We Can recommendations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.givingwhatwecan.org/post/2015/12/giving-what-we-cans-recommendations-for-giving-season-2015/','Giving What We Can’s Recommendations for Giving Season 2015','2015-12-16','2015-12-17','Hauke Hillebrandt','Giving What We Can',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,Project Healthy Children','Evaluator consolidated recommendation list','Global health','Same charities as for 2014 (i.e., no change to list). Noted that Project Healthy Children is a good option for those concerned about crowding out by GiveWell-moved money (since GiveWell had not recommended it). Also, noted GiveDirectly as a fallback option for people concerned about scalability'),
  ('https://www.givingwhatwecan.org/post/2014/12/our-recommended-charities-year/','Our recommended charities for the year','2014-12-05','2015-11-10','Michelle Hutchinson','Giving What We Can',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,Project Healthy Children','Evaluator consolidated recommendation list','Global health','Same charity list as for 2013');

# -- 80000 Hours hoi polloi writeups

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://80000hours.org/2015/12/where-should-you-donate-to-have-the-most-impact-in-giving-season-2015/','Where should you donate to have the most impact during giving season 2015?','2015-12-24',NULL,'Robert Wiblin','80000 Hours',NULL,'Against Malaria Foundation,Giving What We Can,GiveWell,AidGrade,Effective Altruism Outreach,Animal Charity Evaluators,Machine Intelligence Research Institute,Raising for Effective Giving,Center for Applied Rationality,Johns Hopkins Center for Health Security,Ploughshares Fund,Future of Humanity Institute,Future of Life Institute,Centre for the Study of Existential Risk,Charity Science,Deworm the World Initiative,Schistosomiasis Control Initiative,GiveDirectly','Evaluator consolidated recommendation list','Global health and global poverty,Effective altruism/movement growth,Rationality improvement,Biosecurity and pandemic preparedness,AI risk,Global catastrophic risks','Robert Wiblin draws on GiveWell recommendations, Animal Charity Evaluators recommendations, Open Philanthropy Project writeups, staff donation writeups and suggestions, as well as other sources (including personal knowledge and intuitions) to come up with a list of places to donate'),
  ('https://80000hours.org/2016/12/the-effective-altruism-guide-to-donating-this-giving-season/','The effective altruism guide to donating this giving season','2016-12-28',NULL,'Robert Wiblin','80000 Hours',NULL,'Blue Ribbon Study Panel on Biodefense,Cool Earth,Alliance for Safety and Justice,Cosecha,Centre for Effective Altruism,80000 Hours,Animal Charity Evaluators,Compassion in World Farming USA,Against Malaria Foundation,Schistosomiasis Control Initiative,Strong Minds,Ploughshares Fund,Machine Intelligence Research Institute,Future of Humanity Institute','Evaluator consolidated recommendation list','Biosecurity and pandemic preparedness,Global health and global poverty,Animal welfare,AI risk,Global catastrophic risks,Effective altruism/movement growth','Robert Wiblin draws on a number of annual charity evaluations and reviews, as well as staff donation writeups, from sources such as GiveWell and Animal Charity Evaluators, to provide an "effective altruism guide" for 2016 Giving Season donation');

# -- Donee donation cases: MIRI

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://lesswrong.com/r/discussion/lw/mj0/miri_fundraiser_why_now_matters/','MIRI Fundraiser: Why now matters','2015-07-24',NULL,'Nate Soares','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','AI risk','Cross-posted at LessWrong and on the MIRI blog at https://intelligence.org/2015/07/20/why-now-matters/ -- this post occurs just two months after Soares takes over as MIRI Executive Director. It is a followup to https://intelligence.org/2015/07/17/miris-2015-summer-fundraiser/'),
  ('https://intelligence.org/2015/07/17/miris-2015-summer-fundraiser/','MIRI’s 2015 Summer Fundraiser!','2015-07-17',NULL,'Nate Soares','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','AI risk','MIRI announces its summer fundraiser and links to a number of documents to help donors evaluate it. This is the first fundraiser under new Executive Director Nate Soares, just a couple months after he assumed office'),
  ('https://intelligence.org/2016/09/16/miris-2016-fundraiser/','MIRI’s 2016 Fundraiser','2016-09-16',NULL,'Nate Soares','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','AI risk','MIRI announces its single 2016 fundraiser (as opposed to previous years when it conducted two fundraisers, it is conducting just one this time, in the Fall)'),
  ('https://intelligence.org/2017/04/30/2017-updates-and-strategy/','2017 Updates and Strategy','2017-04-30',NULL,'Rob Bensinger','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','AI risk','MIRI provides updates on its progress as an organization and outlines its strategy and budget for the coming year. Key update is that recent developments in AI have made them increase the probability of AGI before 2035 by a little bit. MIRI has also been in touch with researchers at FAIR, DeepMind, and OpenAI');

# -- Donee donation cases: CFAR
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://lesswrong.com/lw/jej/why_cfar/','Why CFAR','2013-12-28',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Salamon, the boss of CFAR, explains the long-term goal (Competence, Epistemic Rationality, and Do-Gooding), plan, and progress to date. This is the first year for CFAR as a standalone organization, after its spinoff from MIRI. Funding situation is dire, with an emergency loan currently taken out that is due in three months. Comments include a $40K donation and a number of other donations'),
  ('http://lesswrong.com/lw/lfg/cfar_in_2014_continuing_to_climb_out_of_the/','CFAR in 2014: Continuing to climb out of the startup pit, heading toward a full prototype','2014-12-26',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','CFAR reports better finances than 2013 (more stability), improvements to its curriculum, attempts to do a full prototype. There is a long discussion of how it redefined the way epistemic rationality fit into the curriculum (moving away from a separate low-rating module to something that is incorporated throughout the course through practical application). Comments are supportive, and include the first appearance of Gleb Tsipursky advertising Intentional Insights'),
  ('http://lesswrong.com/lw/n39/why_cfar_the_view_from_2015/','Why CFAR? The view from 2015','2015-12-23',NULL,'Pete Michaud','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Rationality improvement','Reports 2015 as a year of consolidation and streamlining. Fewer workshops, more efforts to streamline both workshops and continued research on improving rationality. Consolidated original three goals (Competence, Epistemic Rationality, and Do-Gooding) into single framework of applying epistemic rationality. Emphasis on concept of double crux');

# -- Donee donation cases: other
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/14p/cea_is_fundraising_winter_2016/','CEA is Fundraising! (Winter 2016)','2016-12-06',NULL,'William MacAskill','Centre for Effective Altruism',NULL,'Centre for Effective Altruism','Donee donation case','Effective altruism/movement growth','CEA makes its case to be funded in 2016'),
  ('http://effective-altruism.com/ea/15d/why_donate_to_80000_hours/','Why donate to 80,000 Hours','2016-12-24',NULL,'Benjamin Todd','80000 Hours',NULL,'80000 Hours','Donee donation case','Effective altruism/movement growth','Makes the case for 80000 Hours to be funded by effective altruists (and posted on the Effective Altruism Forum). Supplements their annual review https://80000hours.org/2016/12/annual-review-dec-2016 that provides the underlying data and narrative; however, the case made here explicitly focuses on argumentation appealing to EAs, and makes a clearer ask'),
  ('http://effective-altruism.com/ea/19k/the_life_you_can_saves_2016_annual_report/',"The Life You Can Save's 2016 Annual Report",# '
   '2017-04-26',NULL,'Jon Behar','The Life You Can Save',NULL,'The Life You Can Save','Donee donation case','Effective altruism/movement growth/fundraising','TLYCS provides an annual report of money moved and influenced');



# -- Donation documentations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://slatestarcodex.com/2017/02/02/guest-post-the-international-refugee-assistance-program/','[GUEST POST] The International Refugee Assistance Project','2017-02-02',NULL,'Elizabeth Van Nostrand','Slate Star Codex','Elizabeth Van Nostrand','International Refugee Assistance Project','Single donation documentation','Migration policy/refugee assistance','Discusses 100 dollar donation to International Refugee Assistance Project (IRAP) in light of the executive order by Donald Trump on 2017-01-27 banning entry of people from 7 countries. Highlights value of strong existing capacity in the American Civil Liberties Union (ACLU) that allowed for a quick response, and help from the IRAP in doing so. ACLU is well-funded, but IRAP has just gotten off the ground with a grant from the Open Philanthropy Project, so donating to that'),
  ('https://acesounderglass.com/2016/12/01/5167/','Seeing Like A State, Flashlights, and Giving This Year','2016-12-01',NULL,'Elizabeth Van Nostrand','Personal blog','Elizabeth Van Nostrand,Ozy Brennan','Tostan','Third-party case for donation','Education','Argues that donations to things that build capacity could be more valuable than donations to things with directly measured impact. Recommends Tostan for its capacity-building. The post influenced others to donate to Tostan: see https://thingofthings.wordpress.com/2016/12/22/donations-post-2016/ and https://acesounderglass.com/2017/01/05/tracking-donations/'),
  ('http://effective-altruism.com/ea/16b/why_i_donated_to_the_environmental_data/','Why I donated to the Environmental Data & Governance Initiative','2017-01-16',NULL,'Jacob Trefethen','Effective Altruism Forum','Jacob Trefethen','Environmental Data and Governance Initiative','Single donation documentation','Environmentalism/watchdog','Part 1 of the post focused on the case for donating to young, promising organizations. Part 2 explained why the author considered the specific donee a good fit'),
  ('http://effective-altruism.com/ea/15y/where_i_gave_and_why_in_2016/','Where I gave and why in 2016 ','2017-01-06',NULL,'Ben Kuhn','Effective Altruism Forum','Ben Kuhn','EA Giving Group,GiveWell,GiveDirectly','Periodic donation list documentation','Global health and global poverty','Originally posted at http://www.benkuhn.net/giving-2016 and cross-posted to Effective Altruism Forum due to evidence that people like donation write-ups'),
  ('http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/','EAs write about where they give','2016-12-09',NULL,'Julia Wise','Effective Altruism Forum','Blake Borgeson,Eva Vivalt,Ben Kuhn,Alexander Gordon-Brown and Denise Melchin,Elizabeth Van Nostrand','Machine Intelligence Research Institute,Center for Applied Rationality,AidGrade,Charity Science: Health,80000 Hours,Centre for Effective Altruism,Tostan','Periodic donation list documentation','Global health and global poverty, AI risk','Julia Wise got submissions from multiple donors about their donation plans and put them together in a single post. The goal was to cover people outside of organizations that publish such posts for their employees'),
  ('http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Staff members’ personal donations for giving season 2016','2016-12-09','2016-12-09','Natalie Stone-Crispin','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Timothy Telleen-Lawton,Josh Rosenberg,Rebecca Raible,Helen Toner,Sophie Monahan,Laura Muñoz,Catherine Hollander,Andrew Martin,Lewis Bollard,Chelsea Tabart,Sarah Ward,Chris Somerville,Ajeya Cotra,Chris Smith,Isabel Arjmand','A political campaign,GiveWell top charities,International Genetically Engineered Machine Foundation,UPMC Center for Health Security,Donor lottery,EA Giving Group,GiveDirectly,Center for Applied Rationality,Malaria Consortium,Animal Charity Evaluators,Northwest Health Law Advocates,Strong Minds,Against Malaria Foundation,Schistosomiasis Control Initiative,The Humane Society of the United States,The Humane League,Mercy For Animals,Humane Society International,Compassion in World Farming USA,The Good Food Institute,Citizens for Farm Animal Protection,END Fund,Causa Justa,Planned Parenthood,International Refugee Assistance Project','Periodic donation list documentation',NULL,'GiveWell and Open Philanthropy Project staff describe their annual donation plans for 2016. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Staff members’ personal donations for giving season 2015','2015-12-09','2016-12-09','Elie Hassenfeld','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Timothy Telleen-Lawton,Sean Conley,Josh Rosenberg,Jake Marcus,Rebecca Raible,Milan Griffes,Helen Toner,Sophie Monahan,Laura Muñoz,Catherine Hollander,Andrew Martin,Claire Zabel,Nicole Ross,Lewis Bollard','GiveWell top charities,Against Malaria Foundation,GiveWell,GiveDirectly,Wikimedia Foundation,Center for Global Development,Martha’s Table,Country Dance and Song Society,Northwest Health Law Advocates,Mercy For Animals,The Humane League,Animal Charity Evaluators,Raising for Effective Giving,Humane Society of te United States','Periodic donation list documentation',NULL,'GiveWell and Open Philanthropy Project staff describe their annual donation plans for 2015. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Staff members’ personal donations – giving season 2014','2014-12-17','2016-12-09','Holden Karnofsky','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Eliza Scheffler,Timothy Telleen-Lawton,Josh Rosenberg,Ben Rachbach,Jake Marcus,Rebecca Raible,Milan Griffes,Tyler Heishman','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveWell standout charities','Periodic donation list documentation',NULL,'GiveWell staff describe their annual donation plans for 2014. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Staff members’ personal donations','2013-12-12','2016-12-09','Holden Karnofsky','GiveWell','Holden Karnofsky,Elie Hassenfeld,Alexander Berger,Natalie Stone-Crispin,Eliza Scheffler,Timothy Telleen-Lawton,Sean Conley,Josh Rosenberg,Ben Rachbach,Howie Lempel,Jake Marcus','GiveDirectly,Mercy For Animals,Schistosomiasis Control Initiative,Against Malaria Foundation,Deworm the World Initiative,The Humane Society of the United States','Periodic donation list documentation',NULL,'GiveWell staff describe their annual donation plans for 2013. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('https://www.centreforeffectivealtruism.org/blog/cea-staff-donation-decisions-2016/','CEA Staff Donation Decisions 2016','2016-12-06','2016-12-07','Sam Deere','Centre for Effective Altruism','William MacAskill,Michelle Hutchinson,Tara MacAulay,Alison Woodman,Seb Farquhar,Hauke Hillebrandt,Marinella Capriati,Sam Deere,Max Dalton,Larissa Hesketh-Rowe,Michael Page,Stefan Schubert,Pablo Stafforini,Amy Labenz','Centre for Effective Altruism,80000 Hours,Against Malaria Foundation,Schistosomiasis Control Initiative,Animal Charity Evaluators,Charity Science: Health,New Incentives,Project Healthy Children,Deworm the World Initiative,Machine Intelligence Research Institute,Strong Minds,Future of Humanity Institute,Future of Life Institute,Centre for the Study of Existential Risk,Effective Altruism Foundation,Sci-Hub,Vote.org,The Humane League,Foundational Research Institute','Periodic donation list documentation',NULL,'Centre for Effective Altruism (CEA) staff describe their donation plans. The donation amounts are not disclosed.'),
  ('http://www.openphilanthropy.org/blog/suggestions-individual-donors-open-philanthropy-project-staff-2016','Suggestions for Individual Donors from Open Philanthropy Project Staff - 2016','2016-12-14',NULL,'Holden Karnofsky','Open Philanthropy Project','Jaime Yassif,Chloe Cockburn,Lewis Bollard,Daniel Dewey,Nick Beckstead','Blue Ribbon Study Panel on Biodefense,Alliance for Safety and Justice,Cosecha,Animal Charity Evaluators,Compassion in World Farming USA,Machine Intelligence Research Institute,Future of Humanity Institute,80000 Hours,Ploughshares Fund','Donation suggestion list','Animal welfare,AI risk,Biosecurity and pandemic preparedness,Effective altruism,Migration policy','Open Philanthropy Project staff describe suggestions for best donation opportunities for individual donors in their specific areas'),
  ('http://blog.givewell.org/2015/12/23/suggestions-for-individual-donors-from-open-philanthropy-project-staff/','Suggestions for individual donors from Open Philanthropy Project staff','2015-12-23','2016-01-03','Holden Karnofsky','Open Philanthropy Project','Chloe Cockburn,Lewis Bollard,Alexander Berger,Nick Beckstead,Howie Lempel','Alliance for Safety and Justice,Bronx Freedom Fund,The Humane League,The Humane Society of the United States,Center for Global Development,Center for Popular Democracy,Ploughshares Fund','Donation suggestion list','Criminal justice reform,animal welfare,Global health','Open Philanthropy Project stff describe suggestions for best donation opportunities for individual donors in their specific areas. The post is originally published to the GiveWell blog'),
  ('https://animalcharityevaluators.org/blog/where-the-ace-staff-members-are-giving-in-2016-and-why/','Where the ACE Staff Members are Giving in 2016 and Why','2016-12-23',NULL,'Leah Edgerton','Animal Charity Evaluators','Allison Smith,Jacy Reese,Toni Adleberg,Gina Stuessy,Kieran Grieg,Eric Herboso,Erika Alonso','Animal Charity Evaluators,Animal Equality,Vegan Outreach,Act Asia,Faunalytics,Farm Animal Rights Movement,Sentience Politics,Direct Action Everywhere,The Humane League,The Good Food Institute,Collectively Free,Planned Parenthood,Future of Life Institute,Future of Humanity Institute,GiveDirectly,Machine Intelligence Research Institute,The Humane Society of the United States,Farm Sanctuary,Strong Minds','Periodic donation list documentation','Animal welfare','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2016'),
  ('https://animalcharityevaluators.org/blog/where-ace-staff-are-giving-and-why/','Where the ACE Staff Members Are Giving and Why','2015-12-21',NULL,'Leah Edgerton','Animal Charity Evaluators','Jon Bockman,Allison Smith,Erika Alonso,Jacy Reese,Kieran Grieg','Animal Charity Evaluators,Vegan Outreach,Mercy For Animals,Direct Action Everywhere,The Humane League,Animal Equality,Farm Sanctuary,The Humane Society of the United States,Animal Equality,Nonhuman Rights Project,New Harvest,Charity Science,Schistosomiasis Control Initiative,Raising for Effective Giving','Periodic donation list documentation','Animal welfare','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2015');

# -- ('https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016','

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/134/where_i_am_donating_in_2016/','Where I Am Donating in 2016','2016-11-01',NULL,'Michael Dickens','Effective Altruism Forum','Michael Dickens','Animal Charity Evaluators,The Good Food Institute,Mercy For Animals,Raising for Effective Giving','Single donation documentation','Animal welfare, AI risk','Dickens described his evaluation of each of the four finalists and the reasoning behind his (tentatively) final decision to The Good Food Institute'),
  ('http://effective-altruism.com/ea/10t/why_the_open_philanthropy_project_should/','Why the Open Philanthropy Project Should Prioritize Wild Animal Suffering','2016-08-26',NULL,'Michael Dickens','Effective Altruism Forum','Open Philanthropy Project',NULL,'Unsolicited third-party suggestions for donor','Animal welfare/wild animals','Michael Dickens offers reasons that the Open Philanthropy Project should prioritize Wild Animal Suffering. He writes: "What we need is a large, committed source of funding to jump-start the cause. If the Open Philanthropy Project began funding work on wild animal suffering, it could stimulate new research efforts or small-scale interventions by offering grants. Specifically, Open Phil should probably create a new focus area for wild animal suffering and possibly hire dedicated staff. This problem has such large scale, and so many possible interventions, that it absolutely deserves to be a dedicated focus area. Open Phil might consider lumping WAS under its farm animal welfare program, but this would excessively constrain its budget and limit the amount of staff time that it could receive. Wild animal suffering is a massive problem, and easily deserves as much attention as most of Open Phil’s other focus areas."'),
  ('http://effective-altruism.com/ea/ns/my_cause_selection_michael_dickens/','My Cause Selection: Michael Dickens','2015-09-15',NULL,'Michael Dickens','Effective Altruism Forum','Michael Dickens','Machine Intelligence Research Institute,Future of Humanity Institute,Centre for the Study of Existential Risk,Future of Life Institute,Open Philanthropy Project,Animal Charity Evaluators,Animal Ethics,Foundational Research Institute,Giving What We Can,Charity Science,Raising for Effective Giving','Single donation documentation','Animal welfare,AI risk,Effective altruism','Explanation by Dickens of giving choice for 2015. After some consideration, narrows choice to three orgs: MIRI, ACE, and REG. Finally chooses REG due to weighted donation multiplier');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016','Donations for 2016','2016-12-28',NULL,'Jacob Steinhardt',NULL,'Jacob Steinhardt','Donor lottery,GiveWell top charities,GiveDirectly,Blue Ribbon Study Panel,Carnegie Endowment for International Peace','Periodic donation list documentation','Biosecurity and pandemic preparedness,International relations,Global health and global poverty','Explanation for donation choices, also mention experimental funding of smaller projects');

# -- documents related to SHIC
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/128/students_for_high_impact_charity_review_and_10k/','Students for High Impact Charity: Review and $10K Grant','2016-09-27',NULL,'Peter Hurford',NULL,'Peter Hurford','Students for High Impact Charity','Single donation documentation','Effective altruism/movement growth','Explanation of some of the investigative process that led the author to decide to donate to SHIC. The focus is on the investigation process and information revealed about SHIC rather than on the amount donated'),
  ('http://effective-altruism.com/ea/190/students_for_highimpact_charity_interim_report/','Students for High-Impact Charity Interim Report ','2017-04-03',NULL,'Baxter Bullock',NULL,NULL,'Students for High Impact Charity','Donee periodic update','Effective altruism/movement growth','Full report linked to is at https://drive.google.com/file/d/0B_YyyNcGXfb6ZVljWFVSdThVVjg/view (Google Drive)');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/','2017 AI Risk Literature Review and Charity Comparison','2016-12-13',NULL,'Ben Hoskin',NULL,'Ben Hoskin','Machine Intelligence Research Institute,Future of Humanity Institute,OpenAI,Center for Human-Compatible AI,Future of Life Institute,Centre for the Study of Existential Risk,Leverhulme Centre for the Future of Intelligence,Global Catastrophic Risks Institute,Global Priorities Project,AI Impacts,Xrisks Institute,X-Risks Net,Center for Applied Rationality,80000 Hours,Raising for Effective Giving','Review of current state of cause area','AI risk','The lengthy blog post covers all the published work of prominent organizations focused on AI risk. References http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#sources1007 for the MIRI part of it but notes the absence of information on the many other orgs'),
  ('http://effective-altruism.com/ea/14c/why_im_donating_to_miri_this_year/',"Why I'm donating to MIRI this year", #'
   '2016-11-30',NULL,'Owen Cotton-Barratt',NULL,'Owen Cotton-Barratt','Machine Intelligence Research Institute','Single donation documentation','AI risk','Primary interest is in existential risk. Cited CoI and other reasons for not donating to own employer, Centre for Effective Altruism. Notes disagreements with MIRI, citing http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#research but highlights need for epistemic humility'),
  ('http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support','Machine Intelligence Research Institute — General Support','2016-09-01',NULL,'Open Philanthropy Project','Open Philanthropy Project','Open Philanthropy Project','Machine Intelligence Research Institute','Evaluator review of donee','AI risk','Open Phil writes about the grant at considerable length, more than it usually does. This is because it says that it has found the investigation difficult and believes that others may benefit from its process. The writeup also links to reviews of MIRI research by AI researchers, commissioned by Open Phil: http://files.openphilanthropy.org/files/Grants/MIRI/consolidated_public_reviews.pdf'),
  ('https://www.centreforeffectivealtruism.org/blog/changes-in-funding-in-the-ai-safety-field','Changes in funding in the AI safety field','2017-02-01','2017-02-02','Sebastian Farquhar','Centre for Effective Altruism',NULL,'Machine Intelligence Research Institute,Center for Human-Compatible AI,Leverhulme Centre for the Future of Intelligence,Future of Life Institute,Future of Humanity Institute,OpenAI,MIT Media Lab','Review of current state of cause area','AI risk','The post reviews AI safety funding from 2014 to 2017 (projections for 2017). Cross-posted on EA Forum at http://effective-altruism.com/ea/16s/changes_in_funding_in_the_ai_safety_field/');

# -- OpenAI
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://slatestarcodex.com/2015/12/17/should-ai-be-open/','Should AI Be Open?','2015-12-17',NULL,'Scott Alexander','Slate Star Codex',NULL,'OpenAI','Evaluator review of donee','AI risk','Scott Alexander draws a parallel between "open" AI and open nuclear weapons, to highlight that openness is not necessarily good here. Plus a lot of general rambling'),
  ('http://lesswrong.com/r/discussion/lw/oul/openai_makes_humanity_less_safe/','OpenAI makes humanity less safe','2017-04-03',NULL,'Ben Hoffman','LessWrong','Open Philanthropy Project','OpenAI','Evaluator review of donee','AI risk','Hoffman argues that OpenAI is good intentions gone awry, and is critical of the Open Philanthropy Project donation to OpenAI');

# -- Older stuff on Deworm the World Initiative
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://endtheneglect.org/2011/01/spotlight-on-deworm-the-world/','Spotlight on Deworm the World','2011-01-26',NULL,'Alanna Shaikh','End the Neglect',NULL,'Deworm the World Initiative','Evaluator review of donee','Global health/deworming','Alanna Shaikh praises Deworm the World for working with existing groups rather than creating redundant, duplicative effort. This is still in the early days of the organization, before it goes under Innovations for Poverty Action and then Evidence Action');

# -- Effective Altruism Funds

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/174/introducing_the_ea_funds/','Introducing the EA Funds','2017-02-09',NULL,'William MacAskill','Centre for Effective Altruism','Effective Altruism Funds','Effective Altruism Funds','Launch','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','William MacAskill of the Centre for Effective Altruism (CEA) proposes EA Funds, inspired by the Shulman/Christiano donor lottery from 2016-12, while also incorporating elements of the EA Giving Group run by Nick Beckstead'),
  ('http://effective-altruism.com/ea/17v/ea_funds_beta_launch/','EA Funds Beta Launch','2017-02-28',NULL,'Tara MacAulay','Centre for Effective Altruism','Effective Altruism Funds','Effective Altruism Funds','Launch','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','Tara MacAulay of the Centre for Effective Altruism (CEA), the parent of Effective Altruism Funds, describes the beta launch of the project. CEA will revisit within three months to decide whether to make the EA Funds permanent'),
  ('http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','Update on Effective Altruism Funds','2017-04-20',NULL,'Kerry Vaughan','Centre for Effective Altruism','Effective Altruism Funds','Effective Altruism Funds','Periodic donation list documentation','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','Kerry Vaughan provides a progress report on the beta launch of EA Funds, and says it will go on beyond beta. The post includes information on reception of EA Funds so far, money donated to the funds, and fund allocations for the money donated so far'),
  ('http://effective-altruism.com/ea/1ax/discussion_adding_new_funds_to_ea_funds/','Discussion: Adding New Funds to EA Funds','2017-06-01',NULL,'Kerry Vaughan','Centre for Effective Altruism','Effective Altruism Funds',NULL,'Broad donor strategy','Animal welfare,global health,AI risk,global catastrophic risks,effective altruism','Kerry Vaughan of Effective Altruism Funds discusses the alternatives being considered regarding expanding the number of funds, and asks readers for opinions');
