/* Donor lottery Carl salesmanship */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/WvPEitTCM8ueYPeeH/donor-lotteries-demonstration-and-faq','Donor lotteries: demonstration and FAQ','2016-12-07','2017-01-11','Carl Shulman','Effective Altruism Forum','Timothy Telleen-Lawton|Gregory Lewis|Ajeya Cotra|Rohin Shah|Helen Toner|Nicole Ross|Howie Lempel|Rebecca Raible|Pablo Stafforini|Aaron Gertler|Brayden McLean|Benjamin Hoffman|Catherine Olsson|Eric Herboso|Ian David Moss|Glenn Willen|Jacob Steinhardt|Brandon Reinhart','Donor lottery','Donee donation case',NULL,'Carl Shulman announces a donor lottery coordinated/sponsored by Paul Christiano, and provides a FAQ discussing questions people might have for participating in the lottery'),
  ('https://forum.effectivealtruism.org/posts/BhvTMY7K7z97tbHgS/risk-neutral-donors-should-plan-to-make-bets-at-the-margin','Risk-neutral donors should plan to make bets at the margin at least as well as giga-donors in expectation','2016-12-31',NULL,'Carl Shulman','Effective Altruism Forum',NULL,'Donor lottery','Miscellaneous commentary',NULL,'Carl Shulman argues that using a "donate to a giga-donor or its marginal charities" approach, a donor should be able to do at least as well as a giga-donor, if risk-neutral. This post comes while Shulman has been promoting a donor lottery sponsored by Paul Christiano, which is inspired by thinking Shulman articulates in the post');

/* Donor lottery 2016 */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/QjFJKMSTbTpvsoMvh/donor-lottery-debrief','Donor Lottery Debrief','2020-08-04',NULL,'Timothy Telleen-Lawton','Effective Altruism Forum','Donor lottery','Czech Association for Effective Altruism|Epidemic Forecasting','Periodic donation list documentation','Effective altruism|Biosecurity and pandemic preparedness','Tim Telleen-Lawton describes his allocations so far of the $100,000 that he won in the donor lottery back in 2016/2017.');

/* Other comments on donor lottery */

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.lesswrong.com/posts/eSoqa8DEhTqyYEfsM/claim-explainer-donor-lotteries-and-returns-to-scale','Claim explainer: donor lotteries and returns to scale','2016-12-30',NULL,'Benjamin Hoffman','LessWrong',NULL,'Donor lottery','Miscellaneous commentary',NULL,'Hoffman explains donor lotteries, explaining both the "selfish" and "greater good" reasons for entering donor lotteries');

/* Donor lottery 2017 */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/3q3mPbrqZEWARjrgE/announcing-the-2017-donor-lottery','Announcing the 2017 donor lottery','2017-12-16',NULL,'Sam Deere','Centre for EFfective Altruism',NULL,'Donor lottery','Donee donation case',NULL,'Sam Deere of the Centre for Effective Altruism (CEA) announces the 2017 Effective Altruism donor lottery, and links to https://app.effectivealtruism.org/lotteries as the canonical page for all such donor lotteries'),
  ('https://forum.effectivealtruism.org/posts/SYeJnv9vYzq9oQMbQ/2017-donor-lottery-report','2017 Donor Lottery Report','2018-11-12',NULL,'Adam Gleave','Effective Altruism Forum','Donor lottery','Alliance to Feed the Earth in Disasters|Global Catastrophic Risk Institute|AI Impacts|Wild-Animal Suffering Research','Single donation documentation','Global catastrophic risks|AI safety|Animal welfare','The write-up documents Adam Gleave’s decision process for where he donated the money for the 2017 donor lottery. Adam won one of the two blocks of $100,000 for 2017');

/* Donor lottery 2018 */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/nuzcbhk2JYMkALHke/donor-lottery-2018-is-live','Donor Lottery 2018 is live','2018-12-06',NULL,'J. P. Addison','Effective Altruism Forum',NULL,'Donor lottery','Donee donation case',NULL,'J. P. Addison of the Centre for Effective Altruism (CEA) announces the 2018 Effective Altruism donor lottery, and links to https://app.effectivealtruism.org/lotteries as the canonical page for all such donor lotteries'),
  ('https://forum.effectivealtruism.org/posts/Zk9gz7yAdFiT2Mn9b/2018-19-donor-lottery-report-pt-1','2018-19 Donor Lottery Report, pt. 1','2020-12-13',NULL,'Ross Rheingans-Yoo','Effective Altruism Forum','Donor lottery','The Good Food Institute','Single donation documentation','Animal welfare/meat alternatives','The blog post documents the author''s allocation of $165,000 of the $500,000 that he won in the 2019-2020 donor lottery, in the form of two grants to The Good Food Institute.'),
  ('https://forum.effectivealtruism.org/posts/Y4s4MuYQpjfBBHdoR/2018-19-donor-lottery-report-pt-2','2018-19 Donor Lottery Report, pt. 2','2020-12-14',NULL,'Ross Rheingans-Yoo','Effective Altruism Forum','Donor lottery','Fast Grants|COVID-END|Bottleneck Fund|FRAPPE','Periodic donation list documentation','Global health/COVID-19','The blog post documents the author''s allocation of $201,400 of the $500,000 that he won in the 2019-2020 donor lottery, in the form of multiple grants to address COVID-19.');

/* Donor lottery 2019 */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/aFjSzKHRw5i2KPETw/announcing-the-2019-20-donor-lottery','Announcing the 2019-20 Donor Lottery','2019-12-02',NULL,'Sam Deere','Effective Altruism Forum',NULL,'Donor lottery','Donee donation case',NULL,'Sam Deere of the Centre for Effective Altruism (CEA) announces the 2019-20 Effective Altruism donor lottery, and links to https://app.effectivealtruism.org/lotteries as the canonical page for all such donor lotteries');

/* Donor lottery 2020 */
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/aui3fCcjXXpgXWjqr/what-would-you-do-if-you-had-half-a-million-dollars-2','What would you do if you had half a million dollars?','2021-07-17',NULL,'Patrick Brinich-Langlois','Effective Altruism Forum','Donor lottery|Effective Altruism Funds: Long-Term Future Fund|Longview Philanthropy|Effective Altruism Funds: Infrastructure Fund','Effective Altruism Funds: Long-Term Future Fund|Longview Philanthropy|Effective Altruism Funds: Infrastructure Fund','Request for proposals',NULL,'Patrick Brinich-Langlois announces that he won the 2020/2021 $500,000 donor lottery, and is looking for where best to donate. The post suggests that he is inclined to donating the money to an existing grantmaking body, such as the Long-Term Future Fund, Longview Philanthropy, the EA Infrastructure Fund, or the Patient Philanthropy Fund.');
