# -- Donor lottery Carl salesmanship
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/14d/donor_lotteries_demonstration_and_faq/','Donor lotteries: demonstration and FAQ','2016-12-07','2017-01-11','Carl Shulman','Effective Altruism Forum','Timothy Telleen-Lawton|Gregory Lewis|Ajeya Cotra|Rohin Shah|Helen Toner|Nicole Ross|Howie Lempel|Rebecca Raible|Pablo Stafforini|Aaron Gertler|Brayden McLean|Benjamin Hoffman|Catherine Olsson|Eric Herboso|Ian David Moss|Glenn Willen|Jacob Steinhardt|Brandon Reinhart','Donor lottery','Donee donation case',NULL,'Carl Shulman announces a donor lottery coordinated/sponsored by Paul Christiano, and provides a FAQ discussing questions people might have for participating in the lottery'),
  ('http://effective-altruism.com/ea/15g/small_donors_can_plan_to_make_better_bets_than/','Risk-neutral donors should plan to make bets at the margin at least as well as giga-donors in expectation','2016-12-31',NULL,'Carl Shulman','Effective Altruism Forum',NULL,'Donor lottery','Miscellaneous commentary',NULL,'Carl Shulman argues that using a "donate to a giga-donor or its marginal charities" approach, a donor should be able to do at least as well as a giga-donor, if risk-neutral. This post comes while Shulman has been promoting a donor lottery sponsored by Paul Christiano, which is inspired by thinking Shulman articulates in the post');

# -- Other comments on donor lottery

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://lesswrong.com/lw/oe4/claim_explainer_donor_lotteries_and_returns_to/','Claim explainer: donor lotteries and returns to scale','2016-12-30',NULL,'Benjamin Hoffman','LessWrong',NULL,'Donor lottery','Miscellaneous commentary',NULL,'Hoffman explains donor lotteries, explaining both the "selfish" and "greater good" reasons for entering donor lotteries');

# -- Donor lottery 2017
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1ip/announcing_the_2017_donor_lottery/','Announcing the 2017 donor lottery','2017-12-16',NULL,'Sam Deere','Centre for EFfective Altruism',NULL,'Donor lottery','Donee donation case',NULL,'Sam Deere of the Centre for Effective Altruism (CEA) announces the 2017 Effective Altruism donor lottery, and links to https://app.effectivealtruism.org/lotteries as the canonical page for all such donor lotteries');
