/* Semi-skeptical discussion of earning to give */

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://acritch.com/pledging/','Considerations against pledging donations for the rest of your life','2016-12-07',NULL,'Andrew Critch',NULL,NULL,'Center for Applied Rationality','Miscellaneous commentary',NULL,'In this post about earning to give, Andrew Critch argues against pledging to donate in perpetuity, even though he encourages people to donate during years when it makes sense. He writes: "If you either (1) make less than $100k/year, or (2) might be willing to make less than that at some future time in order to work directly on something the world needs you to do (besides giving), I would not be surprised to find myself recommending against you pledging to always donate 10% of your income every year." He talks about his own time spent on setting up the Center for Applied Rationality, and feels that donating money instead of spending resources creating CFAR would have been worse. He writes later: "Expecting variance + respecting your judgement = not pledging"'),
  ('http://shlegeris.com/2017/07/21/ea','Ways I''ve changed my mind about effective altruism over the past year','2017-07-21',NULL,'Buck Shlegeris',NULL,NULL,NULL,'Miscellaneous commentary',NULL,'Buck Shlegeris touches on earning to give and pledging in this post: "I’m concerned about having a norm that you should donate. I am somewhat more opposed to attitudes of frugality and self-sacrifice. I wish EA was closer to master morality than slave morality." Further, he writes: "I have a much more negative attitude towards the GWWC pledge than I used to. I think that signing it is a mistake for most young people who signed it. [...] I feel that encouraging the GWWC pledge discourages people from doing direct work or floundering without jobs, both of which are probably more valuable than 10% of a recent grad’s salary. I suspect that more than half of the people I know who signed the GWWC pledge while under 25 now believe that they made that decision badly." Also posted to Facebook at https://www.facebook.com/bshlgrs/posts/10211394414790814 where it attracts a lot of comments'),
  ('https://www.lesswrong.com/posts/3Ss29ihXsBb8tuoxK/earning-to-give-vs-altruistic-career-choice-revisited','Earning to Give vs. Altruistic Career Choice Revisited','2013-06-01',NULL,'Jonah Sinick',NULL,'Jonah Sinick|Willam MacAskill|Eliezer Yudkowsky','Against Malaria Foundation|Machine Intelligence Research Institute|GiveWell top charities','Miscellaneous commentary','Global health|AI safety','Jonah Sinick gives a number of arguments against the view that earning to give is likely to be the most socially valuable path. For contrast, he considers direct work in nonprofits and in other high-impact careers. He talks about the value of direct feedback and the significant difference between what a skilled person and a less skilled person can accomplish with direct work. Sinick draws extensively on his experience working at GiveWell where he evaluated the cost-effectiveness of charities');

/* Mainstream media coverage of earning to give */

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://qz.com/515655/this-couple-lives-on-6-of-their-income-so-they-can-give-100000-a-year-to-charity/','This couple lives on 6% of their income so they can give $100,000 a year to charity','2015-10-09',NULL,'William MacAskill','Quartz','Jeff Kaufman and Julia Wise',NULL,'Miscellaneous commentary','Global health','Willam MacAskill writes about the Boston-based couple Jeff Kaufman and Julia Wise, who give over $100,000 a year to charity, and live on only about $15,000 a year.'),
  ('https://www.washingtonpost.com/news/wonk/wp/2013/05/31/join-wall-street-save-the-world/','Join Wall Street. Save the world.','2013-03-31',NULL,'Dylan Matthews','Washington Post','Jason Trigg|Matt Wage|Peter Singer|Jeff Kaufman and Julia Wise','GiveWell top charities|Against Malaria Foundation|GiveDirectly','Miscellaneous commentary','Global health','The Washington Post article introduces the concept of "earning to give" to the general public, taking the examples of Jason Trigg and Matt Wage, who deliberately chose careers in finance in order to earn more, to give more. It discusses the philosophy of Peter Singer which has been inspirational to these individuals. The Boston-based couple Jeff Kaufman and Julia Wise, who donate a large amount of money every year to charity, are also discussed.'),
  ('https://www.swarthmore.edu/news-events/listen-software-engineer-jeff-kaufman-08-effective-altruism','Listen: Software Engineer Jeff Kaufman ''08 on Effective Altruism','2017-04-28',NULL,'Jeff Kaufman','Swarthmore College','Jeff Kaufman and Julia Wise','GiveWell top charities|Against Malaria Foundation','Miscellaneous commentary','Global health','In this talk with transcript, Jeff Kaufman, an alumnus of Swarthmore College, describes the "earning to give" practiced by him and his wife Julia Wise, as well as their membership in the effective altruism community. Kaufman also talks about his transition from Google to Wave, in order to have a direct impact in the mobile money space'),
  ('https://www.today.com/news/couple-donates-half-income-every-year-treat-world-health-t51916','Couple donates half of income every year to treat world health','2015-10-23',NULL,'Alexandra Zaslow','Today','Jeff Kaufman and Julia Wise','GiveWell top charities|Against Malaria Foundation','Miscellaneous commentary','Global health','The article describes the Boston-based couple Julia Wise and Jeff Kaufman, who give away half their income to charity every hour. It includes some quotes from Julia Wise about her motivation to give, excitement about the amount given so far, and values that she and her husband hope to instill in their children'),
  ('https://boston.cbslocal.com/2015/10/13/family-gives-away-half-their-income-to-help-others/','Family Gives Away Half Their Income To Help Others','2015-10-13',NULL,'Paul Burton','CBS Boston','Jeff Kaufman and Julia Wise','GiveWell top charities','Miscellaneous commentary','Global health','The article discusses the "earning to give" of Boston-based couple Jeff Kaufman and Julia Wise, who give more than half their income to charity. It includes quotes from both Wise and Kaufman about how they see their giving and what trade-offs they make to sustain that level of giving'),
  ('https://www.theguardian.com/money/2019/nov/09/i-give-away-half-to-three-quarters-of-my-income-every-year','‘I give away half to three-quarters of my income every year’ Allan Saldanha, 41, on how he achieved financial security and now hopes to help save lives','2019-11-09',NULL,'Suzanne Bearne','The Guardian','Allan Saldanha','GiveWell top charities|Against Malaria Foundation|Malaria Consortium|Schistosomiasis Control Initiative','Miscellaneous commentary','Global health','Allan Saldanha, an "earning to give" practitioner, describes how in 2014 he learned of the Giving What We Can (GWWC) pledge to donate 10% of one''s income every year, and how he increased his giving percentage frrom 10% to 20% to 50%, and now aims to give awy 75% of his income to charity. Saldanha donates mainly to GiveWell top charities through the Effective Altruism Funds. He first donated to Against Malaria Foundation in 2014, and in 2018, he donated to Malaria Consortium and the Schistosomiasis Control Initiative.');

/* Jeff Kaufman's discussion of earning to give */

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.jefftk.com/p/the-privilege-of-earning-to-give','The Privilege of Earning To Give','2015-01-14',NULL,'Jeff Kaufman',NULL,'Jeff Kaufman and Julia Wise',NULL,'Miscellaneous commentary',NULL,'Jeff Kaufman explains why he engages in earning to give. He writes: "If I look at my situation, my race, class, and gender privilege have been helpful, but my nationality privilege is by far my biggest unearned advantage. Someone at the poverty line in the US earns more than 90% of people in the world, even after adjusting for money going farther in poorer countries. [...] So I earn to give. I can''t reject my privilege, I can''t give it back, the best I can do is use it to give back.'),
  ('https://www.jefftk.com/p/how-much-should-you-give','How Much Should You Give?','2011-08-09',NULL,'Jeff Kaufman',NULL,'Jeff Kaufman and Julia Wise',NULL,'Miscellaneous commentary',NULL,'In this post related to earning to give, Jeff Kaufman discusses what percentage of one''s income one should donate to charity. He says that for general advocacy of a single percentage, 10% is probably best. At an individual level, he recommends: "do as much good as you can for the level of personal suffering you are willing to accept." He also discusses the practice of tithing (donating 10%) for Jews and Christians, and then discusses the distinction between actual income and potential income (how somebody with high earning potential might choose to take on a lower-paying but more pleasant job, thereby being obliged to donate less)'),
  ('https://forum.effectivealtruism.org/posts/PHF6N4yP2N7N5CETA/answering-some-questions-about-ea','Answering some questions about EA','2019-09-12',NULL,'Jeff Kaufman','Effective Altruism Forum','Jeff Kaufman and Julia Wise','Against Malaria Foundation','Miscellaneous commentary','Global health/malaria','Jeff Kaufman posts to the Effective Altruism Forum his replies to questions sent by students in a Social Issues class in Vienna. In the replies, he explains his history of donating, why he and his wife donate internationally, and whether tthey have any regrets about the amount that they have donated over the years');

