# -- GiveWell cost-effectiveness analysis docs

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://blog.givewell.org/2017/06/01/how-givewell-uses-cost-effectiveness-analyses/','How GiveWell uses cost-effectiveness analyses','2017-06-01','2017-06-01','Catherine Hollander','GiveWell',NULL,'Against Malaria Foundation,GiveDirectly,GiveWell top charities','Evaluator quantification approach',NULL,'Provides an in-depth lok at how GiveWell does cost-effectiveness analyses, including a list of the kinds of subjective inputs that go into the modeling. The later blog post https://blog.givewell.org/2017/11/07/how-givewell-and-mainstream-policymakers-compare-the-good-achieved-by-different-programs/ summarizing the report https://www.givewell.org/how-we-work/our-criteria/cost-effectiveness/comparing-moral-weights references this'),
  ('https://www.givewell.org/how-we-work/our-criteria/cost-effectiveness/comparing-moral-weights','Approaches to Moral Weights: How GiveWell Compares to Other Actors','2017-11-07',NULL,NULL,'GiveWell',NULL,'GiveWell top charities,Deworm the World Initiative,Schistosomiasis Control Initiative,Against Malaria Foundation,Malaria Consortium,GiveDirectly','Evaluator quantification approach',NULL,'In-depth look at how the way GiveWell uses moral weights in cost-effectiveness analyses (such as the value of saving lives) compares with the way governments and others in public policy use it. One difference is that the target population GiveWell deals with is often in low and middle income countries (LMIC) for which estimates of the value of a life saved are more murky. The document also talks of the different moral weights associated with saving people at different ages. See https://blog.givewell.org/2017/11/07/how-givewell-and-mainstream-policymakers-compare-the-good-achieved-by-different-programs/ for a blog post by Josh Rosenberg announcing and summarizing the report. The earlier blog post https://blog.givewell.org/2017/06/01/how-givewell-uses-cost-effectiveness-analyses/ is also referenced. Also see https://groups.google.com/forum/#!topic/newly-published-givewell-materials/xeSpZ512VFw (2017-11-07) for the mailing list announcement');

# -- GiveWell discretionary regranting

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/','Discretionary grant making and implications for donor agency','2016-12-19',NULL,'Andrew Martin','GiveWell','GiveWell discretionary regranting','Against Malaria Foundation, Schistosomiasis Control Initiative','Broad donor strategy',NULL,'Explains the difference between giving GiveWell money to grant at its own discretion and donating to current GiveWell top and standout charities');

# -- GiveWell discussions of potential future top charities and reviews of cause areas
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://blog.givewell.org/2017/05/11/update-on-our-views-on-cataract-surgery/','Update on our views on cataract surgery','2017-05-11',NULL,'Catherine Hollander','GiveWell',NULL,NULL,'Review of current state of cause area','Global health/cataracy surgery','The document discusses uncertainty around funding cataract surgery, specifically around whether it is talent-constrained or funding-constrained, and other questions around marginal impact and quantification');

# -- GiveWell annual top charity lists
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/','Allocation of discretionary funds and new recommendation for donors','2017-04-03','2017-04-04','Natalie Stone-Crispin','GiveWell','GiveWell discretionary regranting','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative','Periodic donation list documentation','Global health','GiveWell announces that it will allocate $4.9 million dollars of discretionary funds as follows: $4.4 million to the Against Malaria Foundation, and $0.5 million to the Deworm the World Initiative. Further, it updates its recommendation to donors, saying they should give all money at the margin to the Against Malaria Foundation. This updates the November 2016 recommendation to give to AMF and the Schistosomiasis Control Initiative in a 3:1 ratio'),
  ('http://www.openphilanthropy.org/blog/good-ventures-and-giving-now-vs-later-2016-update','Good Ventures and Giving Now vs. Later (2016 Update)','2016-12-28','2016-12-28','Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Malaria Consortium,Sightsavers,END Fund,Development Media International,Food Fortification Initiative,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods,Project Healthy Children','Reasoning supplement','Global health and global poverty','Explanation of reasoning that led to $50 million allocation to GiveWell top charities'),
  ('https://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/','Our updated top charities for giving season 2016','2016-11-28','2016-12-15','Natalie Stone-Crispin','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Malaria Consortium,Sightsavers,END Fund,Development Media International,Food Fortification Initiative,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods,Project Healthy Children','Evaluator consolidated recommendation list','Global health and global poverty','GiveWell annual top charity refresh, also announced amounts recommended for Good Ventures to donate to top charities. Added three new top charities'),
  ('https://blog.givewell.org/2016/06/23/top-charities-refresh/','Mid-year update to top charity recommendations','2016-06-23','2016-07-28','Natalie Stone-Crispin','GiveWell',NULL,'GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly','Evaluator consolidated recommendation list','Global health and global poverty','First mid-year refresh of top charities from GiveWell. No change to charity list, and no donation recommended for Good Ventures'),
  ('https://blog.givewell.org/2016/06/20/weve-learned-sci-year/','What we’ve learned about SCI this year','2016-06-20','2016-09-15','Andrew Martin','GiveWell',NULL,'Schistosomiasis Control Initiative','Evaluator update on donee','Global health/deworming','Discovery of some financial errors, but affirmed continued top charity status for now'),
  ('https://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/','Our updated top charities for giving season 2015','2015-11-20','2016-08-03','Elie Hassenfeld,Josh Rosenberg','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Development Media International,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods','Evaluator consolidated recommendation list','GLobal health and global poverty','No change to charity list; significant funding recommended from Good Ventures. This would be later classified as Open Philanthropy Project spending'),
  ('https://blog.givewell.org/2014/12/01/our-updated-top-charities/','Our updated top charities','2014-12-01','2015-05-04','Elie Hassenfeld','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Development Media International,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods','Evaluator consolidated recommendation list','Global health and global poverty','Against Malaria Foundation returned to top charities list. Amounts donated by Good Ventures would later be classified as Open Philanthropy Project spending'),
  ('https://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/','GiveWell’s top charities for giving season 2013','2013-12-01','2016-07-25','Holden Karnofsky','GiveWell','Open Philanthropy Project,Good Ventures','Against Malaria Foundation,GiveDirectly,Schistosomiasis Control Initiative,Deworm the World Initiative','Evaluator consolidated recommendation list','Global health and global poverty','Against Malaria Foundation not in top charities list (it was in 2013) due to room for more funding issues. Good Ventures allocations not included in this post'),
  ('http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans','Our Giving Season Plans','2013-12-03',NULL,'Cari Tuna','Good Ventures','Open Philanthropy Project,Good Ventures','GiveDirectly,Deworm the World Initiative,Schistosomiasis Control Initiative','Periodic donation list documentation','Global health and global poverty','Good Ventures announced $2 million to GiveDirectly, $1.5 million to DtWI, and $750000 to SCI. Also announced up to $5 million in matching funds for GiveDirectly, despite disagreement from GiveWell'),
  ('https://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/','Our top charities for the 2012 giving season','2012-11-26','2016-07-25','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,GiveDirectly,Schistosomiasis Control Initiative','Evaluator consolidated recommendation list','Global health and global poverty','GiveDirectly promoted from standout to top charity, other two charities same as for 2011'),
  ('https://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/','Top charities for holiday season 2011: Against Malaria Foundation and Schistosomiasis Control Initiative','2011-11-29','2011-12-08','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,GiveDirectly,Innovations for Poverty Action,Nyaya Health,Pratham,Small Enterprise Foundation','Evaluator consolidated recommendation list','Global health and global poverty','Against Malaria Foundation and Schistosomiasis Control Initiative were the top charities; the others were standouts'),
  ('https://blog.givewell.org/2011/12/08/deciding-between-two-outstanding-charities/','Deciding between two outstanding charities','2011-12-08','2011-12-08','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative','Reasoning supplement','Global health/malaria and deworming','Provided more in-depth coverage of tradeoffs between the two top charities, supplementing the announcement post at https://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/');

# -- Donation documentations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Staff members’ personal donations for giving season 2016','2016-12-09','2016-12-09','Natalie Stone-Crispin','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Timothy Telleen-Lawton,Josh Rosenberg,Rebecca Raible,Helen Toner,Sophie Monahan,Laura Muñoz,Catherine Hollander,Andrew Martin,Lewis Bollard,Chelsea Tabart,Sarah Ward,Chris Somerville,Ajeya Cotra,Chris Smith,Isabel Arjmand','A political campaign,GiveWell top charities,International Genetically Engineered Machine Foundation,UPMC Center for Health Security,Donor lottery,EA Giving Group,GiveDirectly,Center for Applied Rationality,Malaria Consortium,Animal Charity Evaluators,Northwest Health Law Advocates,Strong Minds,Against Malaria Foundation,Schistosomiasis Control Initiative,The Humane Society of the United States,The Humane League,Mercy For Animals,Humane Society International,Compassion in World Farming USA,The Good Food Institute,Citizens for Farm Animal Protection,END Fund,Causa Justa,Planned Parenthood,International Refugee Assistance Project','Periodic donation list documentation',NULL,'GiveWell and Open Philanthropy Project staff describe their annual donation plans for 2016. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('https://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Staff members’ personal donations for giving season 2015','2015-12-09','2016-12-09','Elie Hassenfeld','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Timothy Telleen-Lawton,Sean Conley,Josh Rosenberg,Jake Marcus,Rebecca Raible,Milan Griffes,Helen Toner,Sophie Monahan,Laura Muñoz,Catherine Hollander,Andrew Martin,Claire Zabel,Nicole Ross,Lewis Bollard','GiveWell top charities,Against Malaria Foundation,GiveWell,GiveDirectly,Wikimedia Foundation,Center for Global Development,Martha’s Table,Country Dance and Song Society,Northwest Health Law Advocates,Mercy For Animals,The Humane League,Animal Charity Evaluators,Raising for Effective Giving,Humane Society of te United States','Periodic donation list documentation',NULL,'GiveWell and Open Philanthropy Project staff describe their annual donation plans for 2015. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('https://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Staff members’ personal donations – giving season 2014','2014-12-17','2016-12-09','Holden Karnofsky','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Eliza Scheffler,Timothy Telleen-Lawton,Josh Rosenberg,Ben Rachbach,Jake Marcus,Rebecca Raible,Milan Griffes,Tyler Heishman','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveWell standout charities','Periodic donation list documentation',NULL,'GiveWell staff describe their annual donation plans for 2014. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('https://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Staff members’ personal donations','2013-12-12','2016-12-09','Holden Karnofsky','GiveWell','Holden Karnofsky,Elie Hassenfeld,Alexander Berger,Natalie Stone-Crispin,Eliza Scheffler,Timothy Telleen-Lawton,Sean Conley,Josh Rosenberg,Ben Rachbach,Howie Lempel,Jake Marcus','GiveDirectly,Mercy For Animals,Schistosomiasis Control Initiative,Against Malaria Foundation,Deworm the World Initiative,The Humane Society of the United States','Periodic donation list documentation',NULL,'GiveWell staff describe their annual donation plans for 2013. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell');
  
