insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.lesswrong.com/posts/HJDbyFFKf72F52edp/welcome-to-lesswrong-2-0','Welcome to Lesswrong 2.0','2017-06-18',NULL,'Oliver Habryka','LessWrong',NULL,'Lightcone Infrastructure','Launch','Epistemic institutions','Post outlines thinking for LessWrong 2.0, covering in part changes to the codebase, moderation, discourse norms.')
  ,('https://www.lesswrong.com/posts/rEHLk9nC5TtrNoAKT/lw-2-0-strategic-overview','LW 2.0 Strategic Overview','2017-09-14',NULL,'Oliver Habryka','LessWrong','Centre for Effective Altruism|Effective Altruism Grants|Eric Rogstad','Lightcone Infrastructure','Miscellaneous commentary','Epistemic institutions','Habryka describes his plans for LessWrong 2.0 as its primary developer.')
  ,('https://www.lesswrong.com/posts/qGyeouB9qwJtdLQ9J/lw-migration-announcement','LW Migration Announcement','2018-03-21',NULL,'Matthew Graves','LessWrong',NULL,'Lightcone Infrastructure','Donee periodic update','Epistemic institutions','Announcement that LessWrong 2.0 is coming out of beta and transitioning from lesserwrong.com to lesswrong.com, becoming the official LessWrong.')
  ,('https://www.lesswrong.com/posts/W8fkT278Fuaih86uy/lesswrong-is-hiring','LessWrong is hiring','2018-06-18',NULL,'Raymond Arnold','LessWrong',NULL,'Lightcone Infrastructure','Job advertisement','Epistemic institutions','Announcement that LessWrong 2.0 is looking for somebody to fill a Chief Technology Officer (CTO) role. Criteria are experience as a programmer and excitement about the long-term vision. The salary range is $70,000 to $120,000, though higher salaries are possible. The post and comments also reveal that the current employees are Oliver Habryka, Raymond Arnold, and Ben Pace, and they all make $60,000 a year. Comments also reiterate previously documented funding sources: Berkeley Existential Risk Initiative, EA Grants, and individual donors such as Eric Rogstad')
  ,('https://www.lesswrong.com/posts/JiMAMNAb55Qq24nES/announcing-alignmentforum-org-beta','Announcing AlignmentForum.org Beta','2018-07-10',NULL,'Raymond Arnold','LessWrong',NULL,'Lightcone Infrastructure','Launch','AI safety','Post describes the beta launch of alignmentforum.org, a forum devoted to questions of AI alignment, built on top of the same codebase and infrastructure as the new LessWrong. It is a natural successor to agentfoundations.org')
  ,('https://forum.effectivealtruism.org/posts/gNHFRWyo58cTQ8pe8/ea-forum-2-0-initial-announcement-1','EA Forum 2.0 Initial Announcement','2018-07-19',NULL,'Marek Duda','Effective Altruism Forum',NULL,'Lightcone Infrastructure','Launch','Effective altruism/movement growth','Post describes plans to move the Effective Altruism Forum to the same codebase and infrastructure as the new LessWrong (LessWrong 2.0, lesswrong.com). It describes the alternatives considered and the reasons for the decision')
  ,('https://www.lesswrong.com/posts/eR7Su77N2nK3e5YRZ/the-lesswrong-team-is-now-lightcone-infrastructure-come-work-3','The LessWrong Team is now Lightcone Infrastructure, come work with us!','2021-09-30',NULL,'Oliver Habryka','LessWrong',NULL,'Lightcone Infrastructure','Status change','Epistemic institutions','The LessWrong team announces a name change to Lightcone Infrastructure; the LessWrong website will continue to be called LessWrong. The renaming of the team reflects a wider scope than just work related to the LessWrong website, "Lightcone" refers to the light cone of humanity which essentially reflects the portion of spacetime that we can influence.')
;
