# -- Relationship disclosure policy change
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/about/relationship-disclosure-policy','Relationship Disclosure Policy','2017-08-30',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Miscellaneous commentary',NULL,'The document, announced on a mailing list at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/4-0KIw2aVmQ (2017-08-30) describes a change in relationship disclosure policy on grant pages published by the Open Philanthropy Project. Relationship disclosures would now no longer be included on grant pages. See https://www.facebook.com/vipulnaik.r/posts/10212973153219475 (cross-posted at https://github.com/vipulnaik/working-drafts/blob/master/open-phil/relationship-disclosure-policy.txt to GitHub) for a critique');

# -- Separation from GiveWell
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/blog/open-philanthropy-project-now-independent-organization','The Open Philanthropy Project Is Now an Independent Organization','2017-06-12',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project,Good Ventures',NULL,'Status change',NULL,'The Open Philanthropy Project announces that it is now a separate entity from GiveWell, and that it has incorporated as a LLC. The change was effective 2017-06-01. See https://blog.givewell.org/2017/06/12/separating-givewell-open-philanthropy-project/ for the complementary post on the GiveWell blog');

# -- Open Phil scientific research
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/blog/update-investigating-neglected-goals-biological-research','Update on Investigating Neglected Goals in Biological Research','2017-11-30',NULL,'Nick Beckstead','Open Philanthropy Project','Open Philanthropy Project,Good Ventures/not recommended by GiveWell or Open Philanthropy Project','Target Malaria','Broad donor strategy','Scientific research,Global health,Biosecurity and pandemic preparedness,Agriculture','The blog post describes the way the Open Philanthropy Project is identifying neglected goals in biological research. Previously the hope was to investigate sub-areas deeply and produce write-ups. Now, the approach is more "opportunistic": rather than do public write-ups, staff look out for good opportunities for shovel-ready or highly promising grants in the specific topics identified as having strong potential');
  
# -- Open Phil moral patienthood
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1c3/hi_im_luke_muehlhauser_ama_about_open/','Hi, I’m Luke Muehlhauser. AMA about Open Philanthropy’s new report on consciousness and moral patienthood','2017-06-28',NULL,'Luke Muehlhauser','Effective Altruism Forum','Open Philanthropy Project','Dyrevernalliansen,Albert Schweitzer Foundation for Our Contemporaries,Eurogroup for Animals','Reasoning supplement','Moral patienthood/animal welfare','Luke Muehlhauser hosts an Ask Me Anything (AMA) on the Effective Altruism Forum about his recently published report https://www.openphilanthropy.org/2017-report-consciousness-and-moral-patienthood (2017-06-06). The post gets 61 comments'),
  ('https://www.openphilanthropy.org/2017-report-consciousness-and-moral-patienthood','2017 Report on Consciousness and Moral Patienthood','2017-06-06',NULL,'Luke Muehlhauser','Open Philanthropy Project','Open Philanthropy Project','Dyrevernalliansen,Albert Schweitzer Foundation for Our Contemporaries,Eurogroup for Animals','Reasoning supplement','Moral patienthood/animal welfare','The writeup announced at https://www.openphilanthropy.org/blog/new-report-consciousness-and-moral-patienthood provides an overview of the findings of Luke Muehlhauser on moral patienthood -- a broad subject covering what creatures are the subject of moral concern. As described at https://www.openphilanthropy.org/blog/radical-empathy Open Phil identifies with radical empathy, extending concern to beings considered of moral concern, even if they are not traditionally subjects of empathy and concern. See https://www.facebook.com/groups/effective.altruists/permalink/1426329927423360/ for a discussion of the post on the Effective Altruism Facebook group, and see http://effective-altruism.com/ea/1c3/hi_im_luke_muehlhauser_ama_about_open/ for a related AMA. The writeup influenced the Open Philanthropy Project Farm Animal Welfare Officer Lewis Bollard to investigate and donate in the domain of fish welfare; see http://effective-altruism.com/ea/1c3/hi_im_luke_muehlhauser_ama_about_open/b8o for a comment clarifying this effect'),
  ('https://www.openphilanthropy.org/brian-tomasik-research-lead-foundational-research-institute-october-6-2016','Brian Tomasik, Research Lead, Foundational Research Institute on October 6, 2016','2016-10-06',NULL,'Brian Tomasik,Luke Muehlhauser','Open Philanthropy Project','Open Philanthropy Project',NULL,'Reasoning supplement','Moral patienthood/animal welfare','Conversation as part of research by Muehlhauser into moral patienthood, that would culminate in the writeup https://www.openphilanthropy.org/2017-report-consciousness-and-moral-patienthood published in 2017');


# -- Open Phil AI risk
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/open-philanthropy-project-ai-fellows-program','The Open Philanthropy Project AI Fellows Program','2017-09-12',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','AI risk','This annouces an AI Fellows Program to support students doing Ph.D. work in AI-related fields who have interest in AI safety. See https://www.facebook.com/vipulnaik.r/posts/10213116327718748 and https://groups.google.com/forum/#!topic/long-term-world-improvement/FeZ_h2HXJr0 for critical discussions'),
  ('https://www.openphilanthropy.org/blog/potential-risks-advanced-artificial-intelligence-philanthropic-opportunity','Potential Risks from Advanced Artificial Intelligence: The Philanthropic Opportunity','2016-05-06',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','AI risk','In this blog post that that the author says took him over over 70 hours to write (See https://www.openphilanthropy.org/blog/update-how-were-thinking-about-openness-and-information-sharing for the statistic), Holden Karnofsky explains the position of the Open Philanthropy Project on the potential risks and opportunities from AI, and why they are making funding in the area a priority');

# -- Open Phil farm animal welfare strategy
  
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://80000hours.org/2017/09/lewis-bollard-end-factory-farming/','How to end animal agriculture as soon as possible','2017-09-27',NULL,'Robert Wiblin,Lewis Bollard','80000 Hours','Open Philanthropy Project','Mercy For Animals, Compassion in World Farming,The Humane League,The Humane Society of the United States,Humane Society International,The Good Food Institute,Animal Equality,Animal Charity Evaluators','Broad donor strategy','Animal welfare/factory farming','Podcast with interview of Lewis Bollard (Farm Animal Welfare Program Officer at the Open Philanthropy Project) by Robert Wiblin of 80000 Hours, along with transcript. The podcast covers the strategy of the Open Philanthropy Project. 80000 Hours is an Open Philanthropy Project grant recipient and Wiblin was also on the board of Animal Charity Evaluators, an animal welfare-focused grant recipient that is discussed in the podcast'),
  ('https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/how-will-hen-welfare-be-impacted-transition-cage-free-housing','How Will Hen Welfare Be Impacted by the Transition to Cage-Free Housing?','2017-09-15',NULL,'Ajeya Cotra','Open Philanthropy Project','Open Philanthropy Project',NULL,'Reasoning supplement','Animal welfare/factory farming/chicken/cage-free campaign','A followup to https://www.openphilanthropy.org/blog/initial-grants-support-corporate-cage-free-reforms which described the original cage-free campaign funding strategy. This report compares aviaries (cage-free living environments) with cages for hens. It tempers original enthusiasm for cage-free by noting higher mortality rates, but continues to support the position that cage-free is likely better on net for hens. Described in blog post https://www.openphilanthropy.org/blog/new-report-welfare-differences-between-cage-and-cage-free-housing that expresses regret for not investigating this more thoroughly earlier, and thanks Direct Action Everywhere for highlighting the issue. See https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/cnK5yNlYHuc for the announcement'),
  ('https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/grants-support-farm-animal-welfare-work-china','Grants to Support Farm Animal Welfare Work in China','2017-08-09',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','Compassion in World Farming,WildAid,World Animal Protection,Royal Society for the Prevention of Cruelty to Animals,Humane Slaughter Association,Jeanne Marchig Centre,Animal Welfare Standards Project,Green Monday,Griffith University,Brighter Green','Broad donor strategy','Animal welfare/factory farming/China','The document describes the strategy of the Open Philanthropy Project to focus on farm animal welfare advocacy in China, and lists ten grants that are part of this strategy. It is announced 2017-08-09 at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/ngrjni1iKLg on the mailing list; this comes 9.5 months after the strategy was unofficially announced by Lewis Bollard at https://www.facebook.com/groups/EffectiveAnimalActivism/permalink/656583861179155/ (2016-10-25) on Facebook'),
  ('https://www.openphilanthropy.org/blog/why-are-us-corporate-cage-free-campaigns-succeeding','Why Are the US Corporate Cage-Free Campaigns Succeeding?','2017-04-11',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','The Humane League,Mercy For Animals,The Humane Society of the United States,Compassion in World Farming USA','Review of current state of cause area','Animal welfare/factory farming/cage-free campaign','Lewis Bollard, Open Philanthropy Project Program Officer for Animal Welfare, who brought passion about cage-free campaigns to the organization when he joined, provides a timeline of cage-free campaigns and an assessment of the success of these campaigns, and the role of the Open Philanthropy Project as a funder'),
  ('https://www.openphilanthropy.org/blog/incoming-program-officer-lewis-bollard','Incoming Program Officer: Lewis Bollard','2015-09-11',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','Animal welfare','Open Philanthropy Project announces that it is hiring Lewis Bollard, poaching him from the Humane Society of the United States (HSUS) via a referral from Howie Lempel. Bollard would direct tens of millions of dollars in funding in the area over the next few years, including massive spend on corporate cage-free campaigns in the United States and internationally. The post was originally published on the GiveWell blog at https://blog.givewell.org/2015/09/11/incoming-program-officer-lewis-bollard/ and has 6 comments there'),
  ('https://www.openphilanthropy.org/sites/default/files/Lewis_Bollard_02-23-17_%28public%29.pdf','A conversation with Lewis Bollard, February 23, 2017','2017-02-23',NULL,'Lewis Bollard,Luke Muehlhauser','Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Animal welfare','Farm animal welfare program officer Lewis Bollard speaks with Luke Muehlhauser, investigator into moral patienthood, on the history of the animal rights and welfare movements as well as recent developments'),
  ('http://www.huffingtonpost.com/entry/chickens-animal-abuse-video_us_57fac5c5e4b0e655eab5485d','Grisly Undercover Video Shows Chickens Being Starved To Produce More Eggs','2016-10-11',NULL,'Nico Pitney','Huffington Post','Open Philanthropy Project','Humane Society International,Mercy For Animals,Animal Equality,People for Animals,The Humane League','Third-party coverage of donor strategy','Animal welfare/factory farming/chicken/cage-free campaign/international','Provides some context for the move by the Open Philanthropy Project in mid-2016 to expand its cage-free campaign funding internationally'),
  ('https://www.facebook.com/groups/EffectiveAnimalActivism/permalink/656583861179155/','The Open Philanthropy Project just announced our latest grant to WildAid in China','2016-10-25',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','Green Monday,World Animal Protection,Brighter Green,WildAid','Broad donor strategy','Animal welfare/factory farming/China','Announcement of strategy on Facebook; official document https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/grants-support-farm-animal-welfare-work-china announced at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/ngrjni1iKLg (2017-08-09).'),
  ('https://www.facebook.com/groups/EffectiveAnimalActivism/search/?query=broiler%20chicken','Broiler chicken search in Effective Animal Activism group on Facebook','2016-08-27','2016-12-14','Brian Tomasik,Chris Byrd',NULL,'Third-party coverage of donor strategy','The Humane Society of the United States,Mercy For Animals','Third-party coverage of donor strategy','Animal welfare/factory farming/chicken','Just a few Facebook posts -- no coherent strategy articulation yet'),
  ('https://www.openphilanthropy.org/blog/initial-grants-support-corporate-cage-free-reforms','Initial Grants to Support Corporate Cage-free Reforms','2016-03-31',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','The Humane League,Mercy For Animals,The Humane Society of the United States','Broad donor strategy','Animal welfare/factory farming/chicken/cage-free campaign/international','Written to explain a bunch of grants already made in 2016-02 to support cage-free reforms in the United States for egg-laying chicken. The blog post had a heated comment section, potentially influencing future Open Phil communication on the subject'),
  ('https://www.openphilanthropy.org/research/cause-reports/treatment-animals-industrial-agriculture','Treatment of Animals in Industrial Agriculture','2013-09-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Animal welfare/factory farming/United States','Initial findings from a shallow investigation into the impact of industrial agriculture on animal welfare in the United States'),
  ('https://www.insidephilanthropy.com/home/2016/11/16/the-open-philanthropy-projects-rationalist-approach-to-farm-animal-welfare','Vast Suffering, Clear Solutions: The Logic Behind a Global Push to Help Farm Animals','2016-11-17',NULL,'Tate Williams','Inside Philanthropy','Open Philanthropy Project',NULL,'Broad donor strategy','Animal welfare/factory farming','The article reviews Open Philanthropy Project grants for animal welfare, primarily grants focused on cage-free campaigns, decided by program officer Lewis Bollard. The connection with the effective altruist movement is also highlighted'),
  ('http://www.ourhenhouse.org/2016/03/episode-324-lewis-bollard-from-the-open-philanthropy-project/','EPISODE 324: LEWIS BOLLARD FROM THE OPEN PHILANTHROPY PROJECT','2016-03-26',NULL,'Lewis Bollard,Jasmin Singer,Mariann Sullivan','Our Hen House','Open Philanthropy Project',NULL,'Broad donor strategy','Animal welfare/factory farming','Lewis Bollard, who recently joined the Open Philanthropy Project and has recently recommended a bunch of grants related to corporate campaigns, describes what he is working on'),
  ('https://nonprofitchronicles.com/2015/11/29/alleviating-animal-suffering-a-conversation-with-lewis-bullard/','ALLEVIATING ANIMAL SUFFERING: A CONVERSATION WITH LEWIS BOLLARD','2015-11-29',NULL,'Marc Gunther','Nonprofit Chronicles','Open Philanthropy Project',NULL,'Broad donor strategy','Animal welfare/factory farming','The author discusses takeaway from a recent lunch with Lewis Bollard, who has recently joined the Open Philanthropy Project as the Program Officer for Farm Animal Welfare');

# -- Open Phil biosecurity and pandemic preparedness
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.insidephilanthropy.com/home/2016/11/30/good-ventures-gives-big-to-back-biosecurity-efforts','Catastrophic Global Risks: A Silicon Valley Funder Thinks the Unthinkable','2016-11-30',NULL,'Sue Lynn-Moses','Inside Philanthropy','Open Philanthropy Project','Center for International Security and Cooperation','Third-party coverage of donor strategy','Biosecurity and pandemic preparedness','A discussion of the overall work done by the Open Philanthropy Project on global catastrophic risks, with a particular focus on biosecurity. Comparisons are made with the Skoll Global Threats Fund, and the historical work of the Rockefeller Foundation in disease surveillance (that it recently pulled out of) is referenced'),
  ('https://www.insidephilanthropy.com/funding-for-global-security/2017/1/24/open-philanthropy-project-fund-grants-for-global-security','Open Philanthropy Project: Grants for Global Security',NULL,NULL,NULL,'Inside Philanthropy','Open Philanthropy Project','Center for International Security and Cooperation','Third-party coverage of donor strategy','Biosecurity and pandemic preparedness','An overview by Inside Philanthropy of the Open Philanthropy Project and its work on biosecurity grants'),
  ('https://www.openphilanthropy.org/research/cause-reports/biosecurity','Biosecurity','2014-01-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Biosecurity and pandemic preparedness','Initial findings from a shallow investigation into the current state of biosecurity and its funding');

# -- Open Phil criminal justice strategy

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/blog/incoming-program-officer-criminal-justice-reform-chloe-cockburn','Incoming Program Officer for Criminal Justice Reform: Chloe Cockburn','2015-06-16',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','Criminal justice reform/United States','The post notes that the Open Philanthropy Project is hiring Chloe Cockburn as the Program Officer in criminal justice reform, poaching her from the American Civil Liberties Union. Cockburn would direct tens of millions of dollars in funding in criminal justice reform over the next few years. The post was originally published on the GiveWell blog at https://blog.givewell.org/2015/06/16/incoming-program-officer-for-criminal-justice-reform-chloe-cockburn/ and has 5 comemnts there'),
  ('https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/criminal-justice-reform-strategy','Criminal Justice Reform Strategy','2017-03-27',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','Criminal justice reform/United States','Explanation of the criminal justice reform strategy of the Open Philanthropy Project in the United States, under the leadership of Chloe Cockburn. Discusses broad goals, types of organizations funded, other funders in the space, and expected impact. Announced in email https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/_aKeLKRqtQY by Devin Jacob on 2017-03-27'),
  ('https://www.insidephilanthropy.com/home/2017/2/8/foundations-grants-criminal-justice-reform','Forget Washington. Criminal Justice Funders Have Big Plans at the Local Level','2017-02-08',NULL,'Philip Rojc','Inside Philanthropy','Open Philanthropy Project,Laura and John Arnold Foundation,MacArthur Foundation',NULL,'Third-party coverage of donor strategy','Criminal justice reform/United States','The post compares the criminal justice reform strategies followed by, on the one hand, the Arnold and MacArthur Foundation (working on the inside with government agencies and power players), on the other hand, the Open Philanthropy Project (keeping the pressure for reform from the outside). It says that the two strategies are complementary, and taken together, improve the expected amount of reform'),
  ('https://medium.com/@taylarnuevelle/an-open-letter-to-soze-and-the-open-philanthropy-project-the-right-of-return-fellowship-and-9bd7dacd8df0','An Open Letter to SOZE and the Open Philanthropy Project: The Right of Return Fellowship and Ethics in Funding','2017-04-27',NULL,'Taylar Nuevelle','Medium','Open Philanthropy Project','The Soze Agency','Third-party case against donation','Criminal justice reform/United States','The writer, a contestant for the Right of Return Fellowship, feels that the contest was rigged, and is writing to bring that to the attention of the Open Philanthropy Project, that funded the Soze Agency for this work'),
  ('http://www.centralfloridapost.com/2017/04/19/soros-connected-groups-dominate-ayalas-personal-professional-life/','Soros Connected Groups Dominate Ayala’s Personal & Professional Life','2017-04-19',NULL,'Jacob Engels','Central Florida Post','Open Philanthropy Project','Florida Rights Restoration Coalition,Fair and Just Prosecution','Third-party case against donation','Criminal justice reform/United States','The writer notes how the Open Philanthropy Project (that he mistakenly believes to be a Soros-funded group) has been attempting to influence Orange and Osceola County State Attorney Aramis Ayala, and argues for more openness. See https://www.facebook.com/vipulnaik.r/posts/10212752692588097 for a discussion'),
  ('http://www.sydsbirthdaychallenge.com/blog/2015/8/27/open-philanthropy-project','Open Philanthropy Project','2015-09-05',NULL,'Sydney Martin',NULL,'Open Philanthropy Project',NULL,'Third-party coverage of donor strategy','Criminal justice reform/United States','The blog post describes the Open Philanthropy Project and its broad strategy of selecting a few areas through cause prioritization, studying them in depth, and granting a lot in those areas. She particularly focuses on criminal justice reform and the hiring of Chloe Cockburn'),
  ('http://files.openphilanthropy.org/files/Focus_Areas/Criminal_Justice_Reform/The_impacts_of_incarceration_on_crime_10.pdf','The impacts of inacercation on crime','2017-09-25',NULL,'David Roodman','Open Philanthropy Project','Open Philanthropy Project',NULL,'Reasoning supplement','Criminal justice reform/United States','The document reviews three mechanisms through which incarceration might reduce crime: deterrence, incapacitation, and aftereffects. It is also published in the form of four blog posts https://www.openphilanthropy.org/blog/reasonable-doubt-new-look-whether-prison-growth-cuts-crime https://www.openphilanthropy.org/blog/deterrence-de-minimis https://www.openphilanthropy.org/blog/incapacitation-how-much-does-putting-people-inside-prison-cut-crime-outside https://www.openphilanthropy.org/blog/aftereffects-us-evidence-says-doing-more-time-typically-leads-more-crime-after and is also available as http://files.openphilanthropy.org/files/Focus_Areas/Criminal_Justice_Reform/impacts_of_incarceration_v4.mobi (Kindle) and http://files.openphilanthropy.org/files/Focus_Areas/Criminal_Justice_Reform/impacts_of_incarceration_v4.epub (Mobi)'),
  ('http://files.openphilanthropy.org/files/Focus_Areas/Criminal_Justice_Reform/Housing_and_Incarceration_Memo_2016.pdf','Housing and Incarceration Memorandum','2016-08-22',NULL,'Chelsea Tabart','Open Philanthropy Project','Open Philanthropy Project',NULL,'Reasoning supplement','Criminal justice reform/United States','An internal memorandum on the intersection between housing and incarceration written by Chelsea Tabart for Chloe Cockburn (the criminal justice program officer). The memorandum would be publicly announced and linked to from https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/jQyJCLBgenc (2017-10-25)');

# -- Open Phil labor mobility/migration policy strategy
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/research/cause-reports/labor-mobility','Migration policy/international labor mobility','2013-05-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Migration policy/international labor mobility','Initial findings from a shallow investigation into the current state of labor mobility, with more focus on the United States');

# -- Open Phil macroeconomic stabilization policy
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/research/cause-reports/macroeconomic-policy','Macroeconomic policy','2014-05-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Macroeconomic stabilization policy','Initial findings from a medium-depth investigation into the current state of macroeconomic stabilization policy');

# -- Open Phil global health
# -- insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
# -- ('https://www.openphilanthropy.org/research/cause-reports/advocacy-improved-or-increased-us-foreign-aid','Advocacy for Improved or Increased U.S. Foreign Aid

# -- Open Phil staff suggestions

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/blog/suggestions-individual-donors-open-philanthropy-project-staff-2016','Suggestions for Individual Donors from Open Philanthropy Project Staff - 2016','2016-12-14',NULL,'Holden Karnofsky','Open Philanthropy Project','Jaime Yassif,Chloe Cockburn,Lewis Bollard,Daniel Dewey,Nick Beckstead','Blue Ribbon Study Panel on Biodefense,Alliance for Safety and Justice,Cosecha,Animal Charity Evaluators,Compassion in World Farming USA,Machine Intelligence Research Institute,Future of Humanity Institute,80000 Hours,Ploughshares Fund','Donation suggestion list','Animal welfare,AI risk,Biosecurity and pandemic preparedness,Effective altruism,Migration policy','Open Philanthropy Project staff describe suggestions for best donation opportunities for individual donors in their specific areas'),
  ('https://blog.givewell.org/2015/12/23/suggestions-for-individual-donors-from-open-philanthropy-project-staff/','Suggestions for individual donors from Open Philanthropy Project staff','2015-12-23','2016-01-03','Holden Karnofsky','Open Philanthropy Project','Chloe Cockburn,Lewis Bollard,Alexander Berger,Nick Beckstead,Howie Lempel','Alliance for Safety and Justice,Bronx Freedom Fund,The Humane League,The Humane Society of the United States,Center for Global Development,Center for Popular Democracy,Ploughshares Fund','Donation suggestion list','Criminal justice reform,animal welfare,Global health','Open Philanthropy Project stff describe suggestions for best donation opportunities for individual donors in their specific areas. The post is originally published to the GiveWell blog');

# -- Open Phil staff donations (note: starts 2017 onward; till 2016, these were included in the GiveWell staff donations)

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://www.openphilanthropy.org/blog/staff-members-personal-donations-giving-season-2017','Staff Members’ Personal Donations for Giving Season 2017','2017-12-18',NULL,'Holden Jarnofsky','Open Philanthropy Project','Holden Karnofsky,Alexander Berger,Nick Beckstead,Helen Toner,Claire Zabel,Lewis Bollard,Ajeya Cotra,Morgan Davis,Michael Levine','GiveWell top charities,GiveWell,GiveDirectly,EA Giving Group,Effective Altruism Funds,Sentience Institute,Encompass,The Humane League,The Good Food Institute,Mercy For Animals,Compassion in World Farming USA,Animal Equality,Donor lottery,Against Malaria Foundation,GiveDirectly','Periodic donation list documentation',NULL,'Open Philanthropy Project staff members describe where they are donating this year, and the considerations that went into the donation decision. By policy, amounts are not disclosed. This is the first standalone blog post of this sort by the Open Philanthropy Project; in previous years, the corresponding donations were documented in the GiveWell staff members donation post');

