# -- Open Phil AI risk
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.openphilanthropy.org/blog/potential-risks-advanced-artificial-intelligence-philanthropic-opportunity','Potential Risks from Advanced Artificial Intelligence: The Philanthropic Opportunity','2016-05-06',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','AI risk','In this blog post that that the author says took him over over 70 hours to write (See http://www.openphilanthropy.org/blog/update-how-were-thinking-about-openness-and-information-sharing for the statistic), Holden Karnofsky explains the position of the Open Philanthropy Project on the potential risks and opportunities from AI, and why they are making funding in the area a priority');

# -- Open Phil farm animal welfare strategy
  
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.openphilanthropy.org/blog/incoming-program-officer-lewis-bollard','Incoming Program Officer: Lewis Bollard','2015-09-11',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','Animal welfare','Open Philanthropy Project announces that it is hiring Lewis Bollard, poaching him from the Humane Society of the United States (HSUS) via a referral from Howie Lempel. Bollard would direct tens of millions of dollars in funding in the area over the next few years, including massive spend on corporate cage-free campaigns in the United States and internationally. The post was originally published on the GiveWell blog at http://blog.givewell.org/2015/09/11/incoming-program-officer-lewis-bollard/ and has 6 comments there'),
  ('http://www.openphilanthropy.org/sites/default/files/Lewis_Bollard_02-23-17_%28public%29.pdf','A conversation with Lewis Bollard, February 23, 2017','2017-02-23',NULL,'Lewis Bollard,Luke Muehlhauser','Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Animal welfare','Farm animal welfare program officer Lewis Bollard speaks with Luke Muehlhauser, investigator into moral patienthood, on the history of the animal rights and welfare movements as well as recent developments'),
  ('http://www.huffingtonpost.com/entry/chickens-animal-abuse-video_us_57fac5c5e4b0e655eab5485d','Grisly Undercover Video Shows Chickens Being Starved To Produce More Eggs','2016-10-11',NULL,'Nico Pitney','Huffington Post','Open Philanthropy Project','Humane Society International,Mercy for Animals,Animal Equality,People for Animals,The Humane League','Third-party coverage of donor strategy','Animal welfare/factory farming/chicken/cage-free campaign/international','Provides some context for the move by the Open Philanthropy Project in mid-2016 to expand its cage-free campaign funding internationally'),
  ('https://www.facebook.com/groups/EffectiveAnimalActivism/permalink/656583861179155/','The Open Philanthropy Project just announced our latest grant to WildAid in China','2016-10-25',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','Green Monday,World Animal Protection,Brighter Green,WildAid','Broad donor strategy','Animal welfare/factory farming/China','Announcement of strategy on Facebook; might do an official blog post later'),
  ('https://www.facebook.com/groups/EffectiveAnimalActivism/search/?query=broiler%20chicken','Broiler chicken search in Effective Animal Activism group on Facebook','2016-08-27','2016-12-14','Brian Tomasik,Chris Byrd',NULL,'Third-party coverage of donor strategy','The Humane Society of the United States,Mercy for Animals','Third-party coverage of donor strategy','Animal welfare/factory farming/chicken','Just a few Facebook posts -- no coherent strategy articulation yet'),
  ('http://www.openphilanthropy.org/blog/initial-grants-support-corporate-cage-free-reforms','Initial Grants to Support Corporate Cage-free Reforms','2016-03-31',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','The Humane League,Mercy for Animals,The Humane Society of the United States','Broad donor strategy','Animal welfare/factory farming/chicken/cage-free campaign/international','Written to explain a bunch of grants already made in 2016-02 to support cage-free reforms in the United States for egg-laying chicken. The blog post had a heated comment section, potentially influencing future Open Phil communication on the subject'),
  ('http://www.openphilanthropy.org/research/cause-reports/treatment-animals-industrial-agriculture','Treatment of Animals in Industrial Agriculture','2013-09-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Animal welfare/factory farming/United States','Initial findings from a shallow investigation into the impact of industrial agriculture on animal welfare in the United States');

# -- Open Phil biosecurity and pandemic preparedness
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.openphilanthropy.org/research/cause-reports/biosecurity','Biosecurity','2014-01-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Biosecurity and pandemic preparedness','Initial findings from a shallow investigation into the current state of biosecurity and its funding');

# -- Open Phil criminal justice strategy

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.openphilanthropy.org/blog/incoming-program-officer-criminal-justice-reform-chloe-cockburn','Incoming Program Officer for Criminal Justice Reform: Chloe Cockburn','2015-06-16',NULL,'Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','Criminal justice reform/United States','The post notes that the Open Philanthropy Project is hiring Chloe Cockburn as the Program Officer in criminal justice reform, poaching her from the American Civil Liberties Union. Cockburn would direct tens of millions of dollars in funding in criminal justice reform over the next few years. The post was originally published on the GiveWell blog at http://blog.givewell.org/2015/06/16/incoming-program-officer-for-criminal-justice-reform-chloe-cockburn/ and has 5 comemnts there'),
  ('http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/criminal-justice-reform-strategy','Criminal Justice Reform Strategy','2017-03-27',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Broad donor strategy','Criminal justice reform/United States','Explanation of the criminal justice reform strategy of the Open Philanthropy Project in the United States, under the leadership of Chloe Cockburn. Discusses broad goals, types of organizations funded, other funders in the space, and expected impact. Announced in email https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/_aKeLKRqtQY by Devin Jacob on 2017-03-27');

# -- Open Phil labor mobility/migration policy strategy
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.openphilanthropy.org/research/cause-reports/labor-mobility','Migration policy/international labor mobility','2013-05-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Migration policy/international labor mobility','Initial findings from a shallow investigation into the current state of labor mobility, with more focus on the United States');

# -- Open Phil macroeconomic stabilization policy
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://www.openphilanthropy.org/research/cause-reports/macroeconomic-policy','Macroeconomic policy','2014-05-01',NULL,NULL,'Open Philanthropy Project','Open Philanthropy Project',NULL,'Review of current state of cause area','Macroeconomic stabilization policy','Initial findings from a medium-depth investigation into the current state of macroeconomic stabilization policy');

# -- Open Phil global health
# -- insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
# -- ('http://www.openphilanthropy.org/research/cause-reports/advocacy-improved-or-increased-us-foreign-aid','Advocacy for Improved or Increased U.S. Foreign Aid
