# -- Big .impact-SHIC merger to become Rethink Charity
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1au/impact_is_now_rethink_charity/','.impact is now Rethink Charity','2017-05-30',NULL,'Tee Barnett','Rethink Charity',NULL,'Rethink Charity','Status change','Effective altruism/movement growth','The blog post announces the merging of .impact and Students for High Impact Charity (SHIC) under a new brand called Rethink Charity. Prioritized projects of Rethink Charity include Local Effective Altruism Network (LEAN), peer-to-peer campaigns, and SHIC. Other projects include the EA Hub and EA Survey');

# -- Documents related to SHIC
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/128/students_for_high_impact_charity_review_and_10k/','Students for High Impact Charity: Review and $10K Grant','2016-09-27',NULL,'Peter Hurford',NULL,'Peter Hurford','Students for High Impact Charity','Single donation documentation','Effective altruism/movement growth','Explanation of some of the investigative process that led the author to decide to donate to SHIC. The focus is on the investigation process and information revealed about SHIC rather than on the amount donated'),
  ('http://effective-altruism.com/ea/190/students_for_highimpact_charity_interim_report/','Students for High-Impact Charity Interim Report','2017-04-03',NULL,'Baxter Bullock',NULL,NULL,'Students for High Impact Charity','Donee periodic update','Effective altruism/movement growth','Full report linked to is at https://drive.google.com/file/d/0B_YyyNcGXfb6ZVljWFVSdThVVjg/view (Google Drive)');

# -- Documents related to LEAN

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1ic/blah/','2017 LEAN Impact Assessment: Quantitative Findings','2017-12-08',NULL,'Richenda Herzig','Effective Altruism Forum',NULL,'Rethink Charity','Donee periodic update','Effective altruism/movement growth','First document in the 2017 Lean Impact Assessment Series, an evaluation of Local Effective Altruism Network (LEAN), a project of Rethink Charity. The document covers results from the 2017 Local Group Survey, conducted in collaboration with Effective Altruism Foundation (EAF) and the Centre for Effective Altruism (CEA)');

# -- Documents related to RC Forward

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('http://effective-altruism.com/ea/1id/rethink_charity_forward_giving_platform_for/','Rethink Charity Forward: Giving Platform for Canadian Donors','2017-12-09',NULL,'Baxter Bullock','Effective Altruism Forum',NULL,'Rethink Charity','Launch',NULL,'Rethink Charity announces the launch of RC Forward, to help Canadian donors make tax-deductible contributions to a wide range of charities in domains ranging from global health and development to animal welfare. This is a successor to Charity Science Outreach (CSO). The parent nonprofit for CSO, Charity Science, has moved to focus on Charity Science Health and related programs and is therefore handing over the donation processing piece to RC Forward, which is started by two former Charity Science employees');

# -- Documents related to Rethink Priorities
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,cause_area,notes) values
  ('https://forum.effectivealtruism.org/posts/6cgRR6fMyrC4cG3m2/rethink-priorities-plans-for-2019','Rethink Priorities Plans for 2019','2018-12-17',NULL,'Peter Hurford','Effective Altruism Forum',NULL,'Rethink Priorities','Donee periodic update','Cause prioritization|Animal welfare|Effective altruism|Global catastrophic risks','Peter Hurford outlines the budget and plans for the priorities research group Rethink Priorities for 2019. The budget is $447,000, of which $153,000 has been raised already. The blog post discusses the sort of research that Rethink Priorities plans to conduct: analysis of the impact of ballot initiatives on animal welfare, understanding corporate campaigns for animal welfare, identifying ways to improve wild animal welfare, doing surveys and polling, understanding EA movement growth, understanding mental health interventions, analysis of catastrophic risk reduction'); 
