# -- Global health and development
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, notes, affected_countries) values
  ('Effective Altruism Funds','Against Malaria Foundation',331126,'2017-06-27','day','donation log','Global health/malaria','https://app.effectivealtruism.org/funds/global-development/payouts/5usCuBFHQk2UcQ0WYOIUEk','https://app.effectivealtruism.org/funds/global-development','Elie Hassenfeld',331126,1.0,'Grant discussed at http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/ along with reasoning, though the amount at the time was not the full amount (just $311,562). Grant to AMF because Hassenfeld believes it is the highest expected value opportunity in the domain. Also, all funding opportunities in GiveWell Incubation Grants have been fully met to his satisfaction, so no need to use this fund for that money. Hassenfeld is allocating the money immediately as he does not expect the situation to change over the next six months',NULL),
  ('Effective Altruism Funds','No Lean Season',150000,'2017-10-17','day','donation log','Seasonal intracountry migration','https://app.effectivealtruism.org/funds/global-development/payouts/3xW9fK4U7YqMsKaQgGG8So','https://app.effectivealtruism.org/funds/global-development','Elie Hassenfeld',150000,1.0,'Elie Hassenfeld recommended No Lean Season on 2017-09-27 after receiving a phone call from Karen Levy saying that No Lean Season had failed to raise funds to meet the unexpectedly high demand for money from borrowers. Hassenfeld recommended the grant amount because Levy told him that would enable the program to continue operating uninterrupted. This was before No Lean Season became a GiveWell top charity','Bangladesh'),
  ('Effective Altruism Funds','Schistosomiasis Control Initiative',1500000,'2018-04-30','day','donation log','Global health/deworming','https://app.effectivealtruism.org/funds/global-development/payouts/6os9pZr9kcMaCgmMiUwMcU','https://app.effectivealtruism.org/funds/global-development','Elie Hassenfeld',1500000,1.0,'Grant made for the same reasons as the GiveWell discretionary regrant https://blog.givewell.org/2018/04/06/allocation-of-discretionary-funds-from-q4-2017/ made concurrently',NULL),
  ('Effective Altruism Funds','Innovation in Government Initiative',1000000,'2019-01-29','day','donation log','Global health and development','https://app.effectivealtruism.org/funds/global-development/payouts/39NNV4WFeKGsbrbHMZboHN','https://app.effectivealtruism.org/funds/global-development','James Snowden',1000000,1.0,'Grant recommended by GiveWell Incubation Grants in December 2018 https://www.givewell.org/research/incubation-grants/innovation-in-government-initiative/december-2018-grant It is not listed under GiveWell Incubation Grants on the Donations List Website because the grant is not financed by the typical funding source of GiveWell Incubation Grants (namely, Good Ventures). Rather, it was financed by the Effective Altruism Funds. The grant is of a more exploratory nature than GiveWell Incubation Grants generally are. Grantee was (from 2015 to December 2018) known as the Government Partnership Initiative (GPI).',NULL);

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, affected_countries, donation_earmark, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Effective Altruism Funds','Malaria Consortium',1705000,'2019-03-12','day','donation log','Global health/malaria','https://app.effectivealtruism.org/funds/global-development/payouts/659BJJ1NQSu4xWdZvjE1bB','https://app.effectivealtruism.org/funds/global-development','GiveWell|Elie Hassenfeld|Natalie Crispin|Andrew Martin|Isabel Arjmand',1705000,1.0,'Burkina Faso|Nigeria|Chad',NULL,
  /* donation_process */ 'GiveWell looked at the funding gap and value of marginal funds for each of its top charities. Two charities that competed closely for the discretionary regrant were Malaria Consortium and Against Malaria Foundation. The blog post https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/ has a lengthy section "Comparing Malaria Consortium and AMF" that applies the six principles in https://blog.givewell.org/2018/11/26/our-recommendation-to-good-ventures/#Principles to compare the two options, ultimately deciding on allocating 100% to Malaria Consortium. The funds held by the Effective Altruism Global Health and Development Fund were also granted to Malaria Consortium. There was discussion of holding funds for work investigating opportunities in public health regulation https://blog.givewell.org/2019/02/07/how-givewells-research-is-evolving/ but ultimately, the grant investigators decided to grant all the money to Malaria Consortium',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Malaria Consortium expects to use the funding (earmarked for seasonal malaria chemoprevention) on these projects, in decreasing order of priority: (1) Contribute to filling a potential funding gap in Burkina Faso, (2) Scale up further in Nigeria and Chad in 2020, (3) Fund the continuation of programs into 2021.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'Malaria Consortium is operating in a domain, seasonal malaria chemprevention, that GiveWell considers highly cost-effective, and is estimated at delivering 8.3x as much value per unit money as cash transfers. Reasons for selecting Malaria Consortium over the Against Malaria Foundation include: stronger organizational management at Malaria Consortium, and more cooperation from Malaria Consortium in helping with GiveWell''s evaluation process',
  /* donor_amount_reason */ 'The amount of $1.705 million is based on the funds available in the Effective Altruism Global Health and Development Fund. This money is on top of the $8.4 million being directly regranted by GiveWell',
  /* donor_timing_reason */ 'This discretionary regrant is done every quarter, for the completed quarter. This particular grant is for Q4 2018 (September to December) and would therefore be expected to be in Q1 2019. Also, grants from the EA Global Health and Development Fund are supposed to be made in March, which probably explains the timing',
  /* donor_next_donation_thoughts */ NULL,
  /* donot_retrospective */ NULL,
  /* notes */ 'The reasoning for the allocation is described in detail in the blog post https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/ (published 2019-03-29)'),
  ('Effective Altruism Funds','Instiglio',600000,'2019-04-29','day','donation log','Global health','https://app.effectivealtruism.org/funds/global-development/payouts/1qrRBknrSXGe4825arATUb','https://app.effectivealtruism.org/funds/global-development','GiveWell|Elie Hassenfeld|James Snowden',600000,1.0,NULL,NULL,
  /* donation_process */ 'GiveWell found an interesting donation opportunity with Instiglio that fit into GiveWell Incubation Grants and would normally be funded by Good Ventures. Since this is a more high-risk high-reward grant than typical for GiveWell Incubation Grants, they decided to use funds from the Global Health and Development Fund rather than request money from Good Ventures',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant is intended to cover a portion of the design costs for the initial technical specification of a new Health Outcomes Fund, intended to be between $50 million and $100 million, focused on primary health care. Partners working with Instiglio and likely contirbutors to the fund include GiveWell, UBS Optimus, and the Global Fund to Fight AIDS, Tuberculosis and Malaria. The fund should allow funders in global health and development to fund programs based on results, while reducing the transaction costs of a typical results-based contract. Design decisions include metric pricing, the selection of implementers and payment metrics, and verification and evaluation methodologies.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'GiveWell has four reason to recommend donating to the fund: (1) GiveWell can help push the fund to adopt its values of cost-effectiveness and transparency. (2) Participating in the fund may lead GiveWell to work with and influence international aid agencies toward GiveWell''s approach. (3) GiveWell may also learn and update its approach from working with the other agencies. (4) The result-based financing method being tried by this fund may be worthwhile. Reservations include (a) Skepticism of some arguments for results-based financing. (b) Uncertainty about whether GiveWell will contribute to the fund after initial scoping. (c) Lower cost-effectiveness than the top GiveWell-recommended charities. The reason for funding through EA Funds rather than Good Ventures is the greater risk and reward, making it more suited for the fund',
  /* donor_amount_reason */ 'Likely a sufficient amount for this initial phase of scoping. No explicit amount-related discussions are included',
  /* donor_timing_reason */ 'Likely determined by the stage of the fund',
  /* donor_next_donation_thoughts */ 'GiveWell writes: "We are uncertain whether we will contribute funding to the Outcomes Fund once the scope is finalized. We would guess that there is sufficient alignment between partners to co-design a fund which meets our minimum criteria for cost-effectiveness, but we are uncertain whether this is the case."',
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant is also listed under GiveWell Incubation Grants and has a page there: https://www.givewell.org/research/incubation-grants/april-2019-instiglio'
);

