insert into donors(donor, donor_type, country, facebook_username, website, donations_url, lesswrong_username, linkedin_username,affiliated_orgs,eaf_username, eahub_username,github_username,twitter_username, donations_data_update_regularity, donations_data_dlw_update_regularity, donations_data_update_lag, donations_data_dlw_update_lag, dlw_data_processing_script, wikipedia_page, best_overview_url, brief_history, brief_donor_focus_notes,grant_decision_logistics_notes, grant_financing_notes, notes) values
  ('Jeff Kaufman and Julia Wise', 'Couple', 'United States', 'jefftk', 'http://www.jefftk.com/', 'http://www.jefftk.com/donations', 'jkaufman','jeff-kaufman-28a8bab','Centre for Effective Altruism','Jeff_Kaufman','jeff-kaufman','jeffkaufman',NULL,'continuous updates','continuous updates','days','months', NULL,NULL,'https://www.jefftk.com/giving',
  'Jeff Kaufman and Julia Wise have been giving since 2003 and have been practicing "earning to give" -- giving about 50% of their annual income -- every year, except years when they were financially tighter because of working at startups or pursuing graduate school. The couple has been highlighted by Peter Singer, and discussed in the mainstream media, for instance https://www.nytimes.com/2015/10/11/books/review/strangers-drowning-by-larissa-macfarquhar.html',
  'The couple makes sure to donate about half of their donation budget for charities that have a direct impact in global health and development, usually based on GiveWell recommendations. See https://www.jefftk.com/p/2017-donations for the latest affirmation of this; and see https://www.jefftk.com/p/why-global-poverty for more explanation of the focus. The remaining half includes effective altruism/movement growth charities (such as the Centre for Effective Altruism) and more speculative charities',
  'The couple determines their charity budget by computing their adjusted gross income (AGI) with the help of their accountant and then calculating a fixed percentage (usually 50%) of that. See https://www.jefftk.com/p/what-should-income-mean-in-pledging for more details on why the AGI figure is used. They then do a 50-50 or similar split between GiveWell-recommended charities in global health and development, and other areas like effective altruism. The allocations in the GiveWell slice are informed by GiveWell recommendations, the allocations in the other slice are decided based on their own investigation. The actual pacing and modality of payments may depend on personal finances, available payment modalities, and donation matching options. As of late 2017, the couple have started using PayPal Giving Fund where possible because it can use a 2% cash-back credit card without charging either donor or donee any transaction fees, and also does a 1% matching, thus generating an extra 3% altogether. See https://www.jefftk.com/p/paypal-giving-fund and https://www.jefftk.com/p/2017-donations for more',
  'The couple generally finances grants from savings, but may in some cases borrow money against future earnings to make donations. The latter is the case in 2017: "This does mean borrowing some money. Modeling our cash flow I think we will have it paid back in March or April. Much of my current compensation is in stock, and I will not start getting that until I will have been back at Google for a year, which will be this September."',
  'It looks like the 50% of AGI became a target as a result of a compromise between Jeff and Julia: Jeff sought a little less and Julia sought a little more. In 2017, the couple targeted 30% initially, while Jeff was working at a lower-pay but potentially higher direct-impact job at money transfer company Wave. However, it went back up to 50% after he was fired from Wave and returned to Google. In 2011, the couple did not donate because Jeff was working at a startup and Julia was paying for graduate school out of pocket, see note [1] at https://www.jefftk.com/donations. Also, note that donations listed in italics are not included as separate line items in the donations list on the Donations List Website; however, the ones among these that are employer matches are noted as employer matches to the corresponding donation. Consistency of totals against the totals listed on top at http://www.jefftk.com/donations was last verified on 2017-12-30');

insert into donors(donor, donor_type, country, facebook_username, website, donations_url, lesswrong_username, linkedin_username,affiliated_orgs,eaf_username, eahub_username,github_username,twitter_username, donations_data_update_regularity, donations_data_dlw_update_regularity, donations_data_update_lag, donations_data_dlw_update_lag, dlw_data_processing_script, wikipedia_page, best_overview_url, brief_history, brief_donor_focus_notes,grant_decision_logistics_notes, grant_financing_notes, notes) values
  ('Peter Hurford','Individual','United States', 'peterhurford', 'http://peterhurford.com/', 'http://peterhurford.com/other/donations.html','peter_hurford','peterhurford8','.impact,Animal Charity Evaluators,Charity Science Health','Peter_Hurford','peter-hurford','peterhurford','peterhurford','continuous updates','continuous updates','days','months',NULL,NULL,NULL,
  'Peter Hurford was involved in effective altruism from his college days and started donating a significant share of his income as soon as he started earning. He has used his donations both to donate to established charities in global health and animal welfare, and to provide funds for new, fledgling charities in the domains of global health and effective altruism/movement growth',
  'Focus is a mix of global health and development, animal welfare, and effective altruism/movement growth. For the last of these, Hurford has historically focused on new charities, whereas for the first two, he has generally focused more on somewhat more established charities. Also some small donations to other causes, such as civil liberties and political campaigns, as a "good citizen"',
  'For larger grants, Hurford decides the grant amount based on discussion with the recipient charity, and often posts the amount with a TBD before actually making it. In many cases, he writes blog posts covering his reasons for the grant',
  'Hurford finances donations from his personal funds, and may make the actual donation several months after deciding, based on the arrangement of his finances and the needs of the donee. Where there are transaction fees, he may add to the donation amount so that the donee finally gets the amount he would like the donee to get',
  'Donations entered on Donations List Website are almost entirely a copy of http://peterhurford.com/other/donations.html with a few differences: $3,215 of donations to "Charity Entrepreneurship" in 2017 and $238 in 2018 are not included on the Donations List Website since these mostly cover contract work. See https://contractwork.vipulnaik.com/payer.php?payer=Peter+Hurford for $2,115 of that and a series of blog posts on mental health by Elizabeth Van Nostrand at http://effective-altruism.com/user/Elizabeth/ for some of the other spending. Similarly, $435 of donations to Charity Entrepreneurship for veg advocacy research on 2014-12-14 are not included. Also, $220 for "Help an EA go to EA Global" on 2017-08-03 is omitted. After accounting for these omissions, consistency of totals against the listed totals by year and by donee at http://peterhurford.com/other/donations.html was last verified on 2017-12-31'),
  ('Gordon Irlam','Individual','United States','gordon.irlam.7','http://www.gordoni.com/','http://www.gricf.org/annual-report.html',NULL,'gordon-irlam-8a284',NULL,NULL,'gordon-irlam',NULL,NULL,'annual refresh','annual refresh','months','months',NULL,NULL,
  'http://www.beguide.org/',
   NULL,
   'See http://www.beguide.org/ for an understanding of the main focus areas. This lists various cause areas and their associated leverage factors, which is the number of dollars of social value that we get for every dollar invested. AI risk is listed with a leverage factor of 1.5 to 12 million, and farm animal welfare has a leverage factor of 300,000 to 1.5 million with the caveat "if pain alone counts"',
   'The exact decision process is not clear. http://www.gordoni.com/effective-altruism/spending.html includes some details on the way Irlam approaches spending',
   'Financing of grants appears to be done through the Gordon R. Irlam Charitable Foundation (GRI Charitable Foundation), whose website is at http://www.gricf.org/ with http://www.gricf.org/legal/articles.html for the legal details and http://www.gricf.org/financial.html for the financial details. However, since this Foundation basically is just a vehicle for Irlam to donate money, we simply treat the donor as Gordon Irlam',
   'Irlam has created a number of websites exploring topics related to his charitable interest. Examples include http://wiki.aipolicies.org/ for AI policy, http://www.gordoni.com/thoughts/wwit.html for global poverty, and other stuff under "A Penny for my Thoughts?" on his homepage http://www.gordoni.com/');


insert into donors(donor, country, facebook_username, website, donations_url, lesswrong_username, linkedin_username,affiliated_orgs,eaf_username, eahub_username,github_username,twitter_username, instagram_username, reddit_username, wikipedia_page, notes) values
  ('Loren Merritt','United States',NULL,'http://akuvian.org/',NULL,'pengvado',NULL,NULL,NULL,NULL,'pengvado',NULL,NULL,NULL,NULL,'Loren Merritt is famous as the creator of x264 https://en.wikipedia.org/wiki/X264 a free software library for encoding video streams into the H.264/MPEG-4 AVC format, which has been the main way he got wealthy (see http://www.x264.nl/developers/Dark_Shikari/loren.html and https://news.ycombinator.com/item?id=320102 for some related discussion). See the comment http://lesswrong.com/lw/ftg/2012_winter_fundraiser_for_the_singularity/807l for the link between his LessWrong handle and his real name; also see https://mailman.videolan.org/pipermail/x264-devel/2008-March/004227.html for other evidence of his use of the pengvado handle'),
  ('Brandon Reinhart','United States','GreenMarine',NULL,NULL,'BrandonReinhart',NULL,NULL,NULL,NULL,NULL,'metal_hart','metal.hart', NULL, NULL, NULL),
  ('Jaan Tallinn','United States','jaan.tallinn',NULL, NULL, NULL, NULL, 'Centre for the Study of Existential Risk', NULL, NULL, NULL, NULL, NULL, 'jaantallinn', 'https://en.wikipedia.org/wiki/Jaan_Tallinn', 'Tallinn is a co-founder of Skype and Kazaa and one of the earlier wealthy supporters of organizations working in AI risk, along with Peter Thiel. In 2011, he had a conversation with Holden Karnofsky sharing his thoughts on AI risk and in particular the work of the Singularity Institute (SI), the former name of the Machine Intelligence Research Institute. See https://groups.yahoo.com/neo/groups/givewell/conversations/topics/287 and http://lesswrong.com/lw/cbs/thoughts_on_the_singularity_institute_si/'),
  ('Blake Borgeson','United States','blakeborgeson','http://www.blakeb.org/',NULL,NULL,'blakeborgeson',NULL,NULL,'blakeborgeson','blakeweb','blakeweb',NULL,NULL,NULL,NULL),
  ('Edwin Evans','United States','ektimo','http://edwinevans.me/',NULL,NULL,'edwinevans','Machine Intelligence Research Institute',NULL,NULL,'edwinevans',NULL, NULL, NULL, NULL,'Evans has worked as a software engineer since the early 1990s, and his philanthropic interests are largely in the AI risk and transhumanism space. Evans is Chairman of the Board of the Machine Intelligence Research Institute (see https://intelligence.org/team/ bottom). He participated in the Extropians mailing list http://extropians.weidai.com/extropians.3Q99/1926.html and was a MIRI supporter as early as late 2001'),
  ('Richard Schwall','United States','https://www.facebook.com/profile.php?id=527228159',NULL,NULL,NULL,'rick-schwall-63652226','Machine Intelligence Research Institute',NULL,'richard-schwall', NULL, NULL, NULL, NULL, NULL, NULL),
  ('Mark Barnes','United Kingdom','mark.barnes.79069',NULL,NULL,NULL,'mark-barnes-03458780',NULL,NULL,'mark-barnes',NULL,NULL,NULL,NULL,NULL, NULL),
  ('Jonathan Weissman','United States','JGWeissman',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL, NULL),
  ('Scott Dickey','United States','scottcdickey',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL, NULL),
  ('Ethan Dickinson','United States','ethancd',NULL,NULL,NULL,'ethancdickinson',NULL,NULL,'ethan-dickinson',NULL,NULL,NULL,NULL,NULL,NULL),
  ('Leif K-Brooks','United States','eurleif',NULL,NULL,NULL,'leif-k-brooks-a073b951',NULL,NULL,NULL,NULL,'leifkb',NULL,NULL,NULL,NULL),
  ('Alexei Andreev','United States','alexei.andreev.3',NULL,NULL,'Alexei','alexei-andreev-90079428',NULL,NULL,'alexei-andreev',NULL,'andreevalexei', NULL, NULL, NULL, 'Alexei Andreev is a MIRI supporter also famous for starting Arbital, a website intended for knowledge expositions, that was heavily promoted and used by Eliezer Yudkowsky'),
  ('Sebastian Hagen','Ireland','https://www.facebook.com/profile.php?id=100009727575538',NULL, NULL, NULL, 'sebastian-hagen-3244a7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
  
  
insert into donors(donor, country, facebook_username, website, donations_url, lesswrong_username, linkedin_username,affiliated_orgs,eaf_username, eahub_username,github_username,twitter_username) values
  ('Aaron Gertler', 'United States', 'aaron.gertler', 'http://aarongertler.net/', 'http://aarongertler.net/donations/','aarongertler','aarongertler',NULL,'aarongertler','aaron-gertler','aarongertler','aarongertler'),
  ('Ajeya Cotra', 'United States', 'https://www.facebook.com/profile.php?id=1638572396','https://ajeyac.wordpress.com', 'no single location; https://eahub.org/user/ajeya-cotra, https://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/, http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/',NULL,'ajeya-cotra-90942b8b','Open Philanthropy Project',NULL,'ajeya-cotra',NULL,NULL),
  ('Ben Kuhn', 'United States', 'ben.s.kuhn', 'http://www.benkuhn.net/', 'http://www.benkuhn.net/ea/','benkuhn', 'benskuhn',NULL,NULL,'ben-kuhn','benkuhn','benskuhn'),
  ('Benjamin Hoffman', 'United States', 'benjamin.r.hoffman', 'http://benjaminrosshoffman.com/', NULL,'Benquo','benjaminrhoffman','GiveWell','BenHoffman','ben-hoffman',NULL, NULL),
  ('Brayden McLean', 'United States', 'brayden.mclean', 'http://brayden.strikingly.com/',NULL,'BraydenM','braydenmclean',NULL,NULL,'brayden-mclean','braydenm','brayden_mclean'),
  ('Catherine Olsson', 'United States', 'catherio', NULL, NULL,'catherio','catherineolsson','OpenAI',NULL,NULL,'catherio','catherineols'),
  ('Eric Herboso', 'United States', 'EricHerboso','http://www.ericherboso.org', NULL,'EricHerboso','ericherboso','Animal Charity Evaluators','EricHerboso','eric-herboso',NULL,'ericherboso'),
  ('Glenn Willen', 'United States', 'gwillen', NULL, NULL,'gwillen', NULL,NULL,'gwillen',NULL,'gwillen',NULL),
  ('Gregory Lewis', 'United Kingdom', 'gjlewis37', NULL, NULL,NULL,'gregoryjlewis','Giving What We Can','Gregory_Lewis','gregory-lewis',NULL,NULL),
  ('Helen Toner', 'United States', 'helen.toner', NULL, NULL, NULL,'helen-toner-4162439a','Open Philanthropy Project','HelenToner','helen-toner',NULL,'hlntnr'),
  ('Howie Lempel', 'United States', 'hlempel', NULL, NULL, NULL,'howie-lempel-201a6378','Open Philanthropy Project',NULL,NULL,NULL,'howielempel'),
  ('Ian David Moss', 'United States', 'iandavidmoss', NULL, NULL, NULL,'mossinator',NULL,NULL,'david-moss',NULL,NULL),
  ('Jacob Steinhardt', 'United States', 'jacob.steinhardt', NULL, NULL, 'jsteinhardt','jacob-steinhardt-a30437bb',NULL,'jsteinhardt',NULL,'jsteinha','jacobsteinhardt'),
  ('Michael Dickens', 'United States', 'michael.j.dickens', 'http://mdickens.me/', 'http://mdickens.me/donations/', 'MTGandP','michael-dickens-a4173255',NULL, 'MichaelDickens','michael-dickens','michaeldickens',NULL),
  ('Nicole Ross', 'United States', 'nicolejamesross', NULL, NULL, NULL,'nicole-ross-184a6142','GiveWell,Open Philanthropy Project', NULL, NULL, NULL, NULL),
  ('Pablo Stafforini', 'United Kingdom', 'stafforini', 'http://www.stafforini.com', 'http://www.stafforini.com/blog/donations/', NULL,'stafforini','Centre for Effective Altruism,80,000 Hours',NULL,'pablo-stafforini', NULL,'stafforini'),
  ('Rebecca Raible', 'United States', 'rebecca.paobur.raible', NULL, NULL, NULL,'rebeccaraible','GiveWell','rebecca_raible','rebecca-raible',NULL,'RebeccaRaible'),
  ('Rohin Shah', 'United States', 'rohinmshah', 'http://rohinshah.com/', NULL, NULL,'rohin-shah-76405832',NULL,'rohinmshah','rohin-shah','rohinmshah', NULL), 
  ('Timothy Telleen-Lawton', 'United States', 'TimTL', NULL, NULL, NULL,'timothytl','GiveWell',NULL,'timothy-telleen-lawton',NULL,'timtl'),
  ('Brian Tomasik','United States','brian.tomasik','http://briantomasik.com/','http://reducing-suffering.org/my-donations-past-and-present/',NULL,'briantomasik','Foundational Research Institute',NULL,'brian-tomasik','Brian-Tomasik','reducesuffering'),
  ('Patrick Brinich-Langlois','United States','pbrinichlanglois','http://www.patbl.com/','http://www.patbl.com/misc/other/donations/',NULL,'patbl',NULL,NULL,'patrick-brinich-langlois','patbl','notnotpat'),
  ('Ozy Brennan','United States','https://www.facebook.com/profile.php?id=100007139566626','https://thingofthings.wordpress.com/','https://thingofthings.wordpress.com/2016/12/22/donations-post-2016/',NULL,'ozy-brennan-1b86b3b2','Foundational Research Institute',NULL,NULL,'ozybrennan',NULL),
  ('Elizabeth Van Nostrand','United States','li.van.nostrand','http://acesounderglass.com/','Multiple posts: https://acesounderglass.com/2016/12/01/5167/,https://acesounderglass.com/2015/12/31/2015-donations/,https://acesounderglass.com/2014/12/29/how-to-figure-out-how-much-to-donate/',NULL,'elizabethvannostrand',NULL,'Elizabeth','elizabeth-van-nostrand','AcesoUnderGlass','AcesoUnderGlass'),
  ('Neil Sinhababu','Singapore','neilsinhababu','http://www.neilsinhababu.com/','http://neilsinhababu.blogspot.com/2016/12/2016-utilitarian-financial-activity.html',NULL,'neil-sinhababu-21a7a3b',NULL,NULL,'neil-sinhababu',NULL,'neilsinhababu'),
  ('Eric Friedman','United States','friedman.eric','http://reinventingphilanthropy.com/',NULL,NULL,'ericfriedman',NULL,NULL,'eric-friedman',NULL,NULL),
  ('Haseeb Qureshi','United States','someguynamedhaseeb','http://haseebq.com/',NULL,NULL,'imhaseeb',NULL,NULL,'haseeb-qureshi','Haseeb-Qureshi','hosseeb'),
  ('Jacob Trefethen','United States','jacob.trefethen','https://jacobtrefethen.com/',NULL,NULL,'jacob-trefethen-82105350',NULL,'JacobTref',NULL,'jacobtref','JacobTref'),
  ('Ben Hoskin','United States','ben.944',NULL,NULL,'Larks','ben-hoskin-024b9021','Machine Intelligence Research Institute,Giving What We Can','Larks',NULL,NULL,NULL),
  ('Eva Vivalt','United States','eva.vivalt','http://evavivalt.com/',NULL,NULL,'eva-vivalt-a1579b54','AidGrade',NULL,'eva-vivalt',NULL,'evavivalt'),
  ('Holden Karnofsky','United States','holden.karnofsky','https://medium.com/@holden0',NULL,'HoldenKarnofsky','holden-karnofsky-75970b7','GiveWell,Open Philanthropy Project','HoldenKarnofsky',NULL,NULL,'holdenkarnofsky'),
  ('Elie Hassenfeld','United States','elie.hassenfeld',NULL,NULL,NULL,'elie-hassenfeld-92072a9','GiveWell,Open Philanthropy Project',NULL,NULL,NULL,'eliehassenfeld'),
  ('Alexander Berger','United States','alexander.is','http://marginalchange.blogspot.com/',NULL,NULL,'alexander-berger-58906098','GiveWell,Open Philanthropy Project',NULL,NULL,NULL,'albrgr'),
  ('Josh Rosenberg','United States','jhrosenberg',NULL,NULL,NULL,'josh-rosenberg-07590626','GiveWell,Open Philanthropy Project',NULL,NULL,NULL,NULL),
  ('Sophie Monahan','United States','sophical',NULL,NULL,NULL,'sophie-monahan-8160a9a2','GiveWell,Open Philanthropy Project',NULL,NULL,NULL,NULL);

# -- insert into donors(donor, country, facebook_username, website, donations_url, lesswrong_username, linkedin_username,affiliated_orgs,eaf_username, eahub_username,github_username,twitter_username) values

insert into donors(donor, country, facebook_username, website, donations_url, income, notes, twitter_username,lesswrong_username,eaf_username,eahub_username,gratipay_username,patreon_username,predictionbook_username,github_username) values

  ('Vipul Naik', 'United States', 'vipulnaik.r', 'https://vipulnaik.com/',
      'https://vipulnaik.com/donation-history/', 90000, 'Disclosure: creator of the site', 'vipulnaik_r',
      'VipulNaik', 'vipulnaik', 'vipul-naik', NULL, NULL, 'vipulnaik', 'vipulnaik');
