/* Dezernat Zukunft */

insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes, amount_original_currency, original_currency, currency_conversion_basis) values
  ('Open Philanthropy','Dezernat Zukunft',100000,'2019-12-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/dezernat-zukunft-macroeconomic-stabilization','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','Europe',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support "work on monetary and fiscal policy in Europe. Currently run by volunteers, Dezernat Zukunft is a nonpartisan German think tank that seeks to gear European monetary and fiscal policies towards encouraging employment gains and sharing prosperity more widely. Dezernat Zukunft plans to use these funds to increase its organizational capacity, specifically by hiring a full-time staff person, and to support its ability to disseminate innovative macroeconomic policy proposals among policymakers, the press, and the general public."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup grants https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/dezernat-zukunft-monetary-and-fiscal-policy-2020 (2020-11) and https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/dezernat-zukunft-general-support-and-regranting (2021-07) suggest continued satisfaction with the grantee.',
  /* notes */ NULL,
  /* amount_original_currency */ 91000,
  /* original_currency */ 'EUR',
  /* currency_conversion_basis */ 'donor calculation'),

  ('Open Philanthropy','Dezernat Zukunft',202079,'2020-11-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/dezernat-zukunft-monetary-and-fiscal-policy-2020','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','Germany',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support "work on monetary and fiscal policy in Europe. Dezernat Zukunft is a nonpartisan German think tank that seeks to gear European monetary and fiscal policies toward encouraging employment gains and sharing prosperity more widely. Dezernat Zukunft plans to use these funds to hire staff to encourage fiscal expansion in Germany."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/dezernat-zukunft-general-support-and-regranting (2021-07) suggests continued satisfaction with the grantee.',
  /* notes */ NULL,
  /* amount_original_currency */ 170000,
  /* original_currency */ 'EUR',
  /* currency_conversion_basis */ 'donor calculation'),

  ('Open Philanthropy','Dezernat Zukunft',4000000,'2021-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/dezernat-zukunft-general-support-and-regranting','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Peter Favaloro','Europe',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support|Regranting',
  /* intended_use_of_funds */ 'Grant "for general support and re-granting to budding and established organizations working on monetary and fiscal policy throughout Europe. Dezernat Zukunft is a nonpartisan German think tank that focuses on European monetary and fiscal policy, prioritizing employment gains, widely shared prosperity, and a more sustainable macroeconomic environment."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ NULL,
  /* original_currency */ NULL,
  /* currency_conversion_basis */ NULL);

/* Peterson Institute for International Economics */
insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Peterson Institute for International Economics',250000,'2016-04-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/peterson-institute-international-economics-macroeconomic-stabilization','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2016-04-29','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/UeMetwk5b74',NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support work  on macroeconomic stabilization',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page says: "We are considering making a larger grant to support PIIE to do substantially more work in this area (which is a focus area of ours), and are thinking of the present funding as an opportunity to try working with the organization while we (and they) think more about potential future engagement."',
  /* donor_amount_reason */ 'The grant is a relatively small one and is intended to kickstart a relationship with the donee, to decide on whether to make a bigger grant later',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Open Philanthropy','Peterson Institute for International Economics',400000,'2019-01-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/peterson-institute-international-economics-macroeconomic-projects','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2019-05-18','day',NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to support research by non-resident fellows Karen Dynan and Jason Furman on key questions in macroeconomic stabilization policy. Karen Dynan will study the optimal design of automatic stabilizer programs — taxes and government programs that respond automatically to changing economic conditions. Jason Furman will study the costs and benefits of allowing employment to exceed some estimates of full employment.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page says: "We see these both as crucially important questions in macroeconomic stabilization policy and believe Dynan and Furman are especially well-placed to address them in an influential and informative fashion."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donattion_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Employ America */

insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Employ America',300000,'2019-04-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-start-up','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2019-05-29','day',NULL,NULL,
  /* donation_process */ 'This is a total across two grants, one of which is being made by the Open Philanthropy Action Fund.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant "to help launch Employ America and cover a six-month pilot period." The grant page says: "Employ America will focus on making the public and intellectual case for policies that support full employment and building a broader set of allies to further that goal, especially with an eye to the next economic downturn. In order to do so, it will produce research and analysis on the state of the labor market and current and potential macroeconomic policies and policymakers. It will be led by Sam Bell, who has previously consulted for us and our grantee Fed Up."',
  /* intended_funding_timeframe_in_months */ 6,
  /* donor_donee_reason */ 'The grant page says: "As labor market conditions have improved over the last few years, we’ve become less confident about the appropriate short term stance of monetary policy, but we continue to believe it is worthwhile to support research and advocacy like this, at least through the next recession."',
  /* donor_amount_reason */ 'The amount is likely determined based on how much is needed for an initial 6-month startup.',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Several followup grants starting with https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-general-support-october-2019 (2019-10) suggest continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','Employ America',1000000,'2019-10-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-general-support-october-2019','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ 'This is a total across two grants.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'The grant page says: "Employ America makes the public and intellectual case for policies that support full employment and seeks to build a broad set of allies to further that goal. It produces research and analysis on the state of the labor market and current and potential macroeconomic policies and policymakers. Employ America is led by Sam Bell, who has consulted for us and our grantee Fed Up."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup grants such as https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-general-support-2020 (2020-07) suggest continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','Employ America',1250000,'2020-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-general-support-2020','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ 'This is a total across two grants.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'The grant page says: "Employ America makes the public and intellectual case for policies that support full employment and seeks to build a broad set of allies to further that goal. It produces research and analysis on the state of the labor market and current and potential macroeconomic policies and policymakers. Employ America is led by Sam Bell, who has consulted for us and our grantee Fed Up."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-general-support-2021 (2021-05) suggests continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','Employ America',1000000,'2021-05-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/employ-america-general-support-2021','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ 'This is a total across two grants.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'The grant page says: "Employ America makes the public and intellectual case for policies that support full employment and seeks to build a broad set of allies to further that goal. It produces research and analysis on the state of the labor market and current and potential macroeconomic policies and policymakers. Employ America was founded by Sam Bell, who has consulted for us and our grantee Fed Up."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Economic Policy Institute */

insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Economic Policy Institute',500000,'2016-06-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2016-10-25','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/vAPhHDgenvY',NULL,
  /* donation_process */ 'The grantee submitted a proposal available at https://www.openphilanthropy.org/files/Grants/EPI/EPI_Open_Phil.pdf that includes proposed research investigations and activities.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant page describes two main areas supported by the grant: (1) "Preparing for the next U.S. recession, which we would guess is likely to occur before interest rates return to “normal” levels." (2) "Making the case for the importance of continued focus on reducing unemployment and against premature monetary tightening today." https://www.openphilanthropy.org/files/Grants/EPI/EPI_Open_Phil.pdf has more details on proposed activities.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup grants https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2018 (2018-07) and https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2020 (2020-08) suggest continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','Economic Policy Institute',700000,'2018-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2018-08-15','day',NULL,NULL, /* date adjusted */
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant page says: "EPI plans to use these funds primarily to continue producing policy-relevant research on the ways in which macroeconomic policy can boost living standards for working Americans, including work on different aspects of the relationships between unemployment, wage growth, inflation, and productivity."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2020 (2020-08) suggests continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','Economic Policy Institute',550000,'2020-08-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2020','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant page says: "EPI plans to use these funds to continue to produce policy-relevant research on the ways in which macroeconomic policy can boost living standards for working Americans, including work on different aspects of the relationships between unemployment, wage growth, inflation, and productivity."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'No explicit reasons are given for the amount; it is a little less than the amount ($700,000) of the previous two-year grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2018 (2018-07).',
  /* donor_timing_reason */ 'The grant is made right around the end of the timeframe of the previous two-year grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/economic-policy-institute-macroeconomic-policy-research-2018 (2018-07).',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Center for Popular Democracy Action Fund */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Center for Popular Democracy Action Fund',31500,'2016-10-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-october-2016','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2018-01-19','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/FrHyHKPNy-M',NULL,
  /* donation_process */ 'Discretionary grant made via the Open Philanthropy Action Fund; this complements grants made by Open Philanthropy directly to the Center for Popular Democracy (the associated 501(c)(3)) such as https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016 (2015-12).',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve, and specifically in the selection of regional Federal Reserve Bank presidents and leaders. [...] CPD Action expects to use this funding primarily for lobbying activities associated with the campaign."',
  /* intended_funding_timeframe_in_months */ 4,
  /* donor_donee_reason */ 'The grant page says: "We have written in more detail about our rationale for supporting this campaign on our 2014, 2015, and 2016 grant pages to the Center for Popular Democracy, a 501(c)(3) affiliated with CPD Action." The rationale for the most recent grant to CPD as of that time is provided at https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016#Case_for_this_grant and includes details on why Open Phil thinks the Fed is too focused on the risk of inflation and not enough on unemployment, and that the campaign being funded can help shift the balance.',
  /* donor_amount_reason */ 'No specific reasons are given for the amount; for context, it is only about 2% of the corresponding grant to CPD ($1,429,000) and likely reflects the expected costs of lobbying activities to properly complement the campaign. Note that since the grant is made late in te year compared to the CPD grant, it likely only covers 4 months of the year, so after normalizing for time it is about 6% of the CPD grant.',
  /* donor_timing_reason */ 'The timing is likely partly determined by the timing of the Fed Up campaign, but the campaign is ongoing so this doesn''t really help narrow down the timing much.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Larger followup grants https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2017 (2017-02) and https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 (2018-02) suggest continued satisfaction with the grantee.',
  /* notes */ 'As explained at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/FrHyHKPNy-M the grant announcement was delayed till Open Philanthropy was completely separate from GiveWell.'),

  ('Open Philanthropy','Center for Popular Democracy Action Fund',305000,'2017-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2017','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy',,'Alexander Berger','United States','2017-12-28','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg',NULL,
  /* donation_process */ 'Grant made via the Open Philanthropy Action Fund; this complements the grant made by Open Philanthropy directly to the Center for Popular Democracy (the associated 501(c)(3)) at https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 (2017-02).',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve, and specifically in the selection of regional Federal Reserve Bank presidents and leaders. [...] CPD Action expects to use this funding primarily for lobbying activities associated with the campaign."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'The grant page links to the corresponding CPD grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 that says: "We decided to renew our support based primarily on CPD’s continued success drawing attention for its agenda from the press, Congress, and the Fed; ongoing opportunities to potentially influence the appointment or priorities of new Federal Reserve governors and regional Fed presidents; and our intention to provide the campaign with enough sustainable funding to last through the next recession, when CPD’s advocacy might be especially useful and when we could better evaluate its performance."',
  /* donor_amount_reason */ 'No explicit reasons are given for the amount; it is about 27% of the amount ($1,100,000) for the corresponding CPD grant, and likely reflects the expected amount of lobbying costs to support the campaign''s other costs.',
  /* donor_timing_reason */ 'The timing is coordinated with the corresponding CPD grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 whose timing in turn is based on an annual cadence of granting.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 (2018-02, $100,000) suggests continued satisfaction with the grantee, though the size of the followup grant (both absolute and in proportion to the CPD grant) is substantially smaller.',
  /* notes */ 'As explained at https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg the grant announcement was delayed till Open Philanthropy was completely separate from GiveWell.'),

  ('Open Philanthropy','Center for Popular Democracy Action Fund',100000,'2018-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2018-03-23','day',NULL,NULL, /* date adjusted */
  /* donation_process */ 'Grant made via the Open Philanthropy Action Fund; this complements the grant made by Open Philanthropy directly to the Center for Popular Democracy (the associated 501(c)(3)) at https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 (2018-02).',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve. [...] CPD Action expects to use this funding primarily for lobbying activities associated with the campaign."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'The grant page says: "As labor market conditions have improved, we’ve become less confident about the appropriate short term stance of monetary policy, but we continue to believe it to be worthwhile to support the campaign through the next recession, when its advocacy might be especially useful and when we could better evaluate its impact." It also links to the corresponding CPD grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 for more context.',
  /* donor_amount_reason */ 'No explicit reasons are given for the amount; it is 1/12 of the amount for the corresponding CPD grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 (2018-02) of about $1.2 million.',
  /* donor_timing_reason */ 'The timing is coordinated with the corresponding CPD grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 whose timing in turn is based on an annual cadence of granting.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'As of November 2021, Open Philanthropy has made no further grants to the CPD Action Fund, though it has made two further grants to CPD. The reasons for ending the practice of complementary graants to the Action Fund are not clear.',
  /* notes */ NULL);

/* Center for Popular Democracy */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Center for Popular Democracy',100000,'2014-08-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-federal-reserve-campaign','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2014-09-25','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/1akCOFYWWOM',NULL,
  /* donation_process */ 'Grantee submitted a proposal at https://files.givewell.org/files/labs/macroeconomic-policy/CPD%20Federal%20Reserve%20Campaign%20Paper%20v2.pdf for the Fed Up Campaign, and Open Philanthropy reviewed it and ultimately decided to provide funds to help kickstart the campaign.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to launch a campaign to educate the public about monetary policy and encourage the Federal Reserve to give more attention to the full employment portion of its mandate." The campaign would later become known as the Fed Up campaign. The stated rimary goals of the campaign are: (1) Ensure that monetary policy contributes to sustained growth and prosperity. (2) Engage Fed officials in a discussion of the meaning of its “dual mandate.” (3) Ensure that the American public is properly represented on the Boards of Directors of the regional Feds.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page gives reasons for supporting a shift toward focus on unemployment, also called a "dovish" stance compared to the "hawkish" stance of caring primarily about inflation. It gives two reasons: (a) this stance is better suited to the state of the economy, and (b) current advocacy influencing the Federal Open Market Committee (FOMC) is significantly hawkish since it comes mostly from corporations and the financial industry. The grant page also is more in favor of the third primary goal of more representation of the American public: "there seems to be a strong procedural presumption in favor of a more credible, transparent selection process for regional Federal Reserve Bank board members and, in turn, presidents." The grant is also viewed as a learning grant for Open Philanthropy''s exploration of macroeconomic stabilization policy.',
  /* donor_amount_reason */ 'The grant amount seems to have been chosen on the low end ($100,000) and the grant page says "We’re unusually uncertain about this grant" suggesting that this uncertainty was a reason for not making a larger upfront commitment to the campaign.',
  /* donor_timing_reason */ 'The timing seems to have been determined by a mix of the grantee shopping the grant proposal around and Open Phil becoming interested in grantmaking in the macroeconomic stabilization policy space.',
  /* donor_next_donation_thoughts */ 'The grant page says: "we’re planning to investigate the considerations above in more depth in the coming months (conditional on retaining macroeconomic policy as a high-priority cause) to reach a decision about whether to contribute a more significant portion of the campaign’s overall budget."',
  /* donor_retrospective */ 'A followup conversation https://files.givewell.org/files/conversations/Brian%20Kettenring%2010-16-14%20(public).pdf is published with Brian Kettenring of the grantee organization. Open Phil ultimately decides to fund the Fed Up Campaign at a much larger level starting 2015 with https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015 (2015-01, $750,000) and writes at https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Campaign_progress_to_date about the campaign progress. Open Phil continues with this funding for several years.',
  /* notes */ 'The grant was made and the grant page published before the launch of the Open Philanthropy website, and was originally written on the GiveWell website. It includes extensive discussion of the grant and links to several sources that informed the thinking behind the grant.'),

  ('Open Philanthropy','Center for Popular Democracy',750000,'2015-01-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2015-02-27','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Tuu9P250vVQ',NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Our_process refers to the previous grant https://www.openphilanthropy.org/giving/grants/center-popular-democracy-federal-reserve-campaign that helped the Fed Up campaign get started. It says: "Prior to deciding about this grant, we had a number of further conversations with Ady Barkan of CPD about the campaign’s plans, followed the initial progress of the campaign in drawing press attention, and looked more deeply into research on monetary policy." https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Process_for_forming_and_vetting_views_on_monetary_policy includes some of the influences in Open Phil''s formation of views on monetary policy.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant for the "campaign (“Fed Up”) that aims to prevent premature tightening of monetary policy and encourage greater transparency and public engagement in the governance of the Federal Reserve." It supports 75% of the campaign''s 1-year $1 million budget.',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Case_for_this_grant gives three parts to the case for the grant: (1) "A slim probability of moving monetary policy in a marginally more dovish (i.e., lower unemployment, higher inflation) direction." (2) "A reasonable chance of achieving some of the campaign’s procedural goals, including raising the level of transparency around how regional Fed presidents and board member are selected." (3) "Enabling CPD to experiment with an advocacy campaign in this area, potentially laying the groundwork for future advocacy efforts in the area, and testing our hypothesis that advocacy around macroeconomic policy is a promising and relatively neglected philanthropic area." The first consideration dominates the decision to make the grant.',
  /* donor_amount_reason */ 'The grant page says: "We anticipate that this grant will make up roughly 75% of the campaign’s overall funding for the year." https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Room_for_more_funding_and_fungibility says: "The initial budget we saw projected expenses of around $1.5 million, and we decided to contribute roughly half that amount. [...] We take the fact that the budget was revised downward [to $1 million] after our commitment to support the notion that CPD wouldn’t be able to find the amount of funding that we’ve contributed from other sources, and that accordingly our contribution is largely non-fungible.',
  /* donor_timing_reason */ 'The timing seems largely determined by the initial seed funding grant https://www.openphilanthropy.org/giving/grants/center-popular-democracy-federal-reserve-campaign running out and the need to finance the continuation of the campaign.',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Plans_for_learning_and_follow-up lists follow-up questions and says: "Towards the end of the duration of the grant, we plan to attempt a more holistic and detailed evaluation of the grant’s performance, aiming to answer the questions above. As mentioned above, we may check the transcripts of 2015 FOMC meetings after they are released in 2021 to see whether any of the FOMC members discuss meetings with workers that inform their perspectives on policy."',
  /* donor_retrospective */ 'Continued funding by Open Phil of the Fed Up campaign in the later years, starting with https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016 (2015-12) suggests continued satisfaction with the grantee.',
  /* notes */ 'The grant page says: "Unlike much of our other output, the complexity of the debates in this area has made it impractical for other GiveWell staff to construct and check a complete trail of evidence and counterarguments for each claim in this review." It also lists https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015#Process_for_forming_and_vetting_views_on_monetary_policy lists the following economists whose blogs influenced Open Phil''s initial impressions on the issue: Paul Krugman, Brad DeLong, Tim Duy, Scott Sumner, and Tyler Cowen.'),

  ('Open Philanthropy','Center for Popular Democracy',1429000,'2015-12-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States', '2016-04-06','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/JKm8ZFwuPlk',NULL,
  /* donation_process */ 'The grant page says: "We monitored the campaign throughout 2015 and had conversations with Ady Barkan of CPD about the campaign’s plans and progress. We followed the media surrounding Fed Up and its interactions with policymakers. Karl Smith, who worked with us in 2015 as a consultant, attended the Jackson Hole Symposium and reviewed some of the campaign’s 2015 activities with us." Elsewhere, it says: "The initial 2016 budget given to us by Fed Up was for $4 million, but we also requested budgets for $2 million and $3 million"',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant supports about half the cost of the Fed Up campaign for 2016. https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016#Budget_and_proposed_activities says: "We expect Fed Up would spend a $3 million budget approximately as follows: $1.5 million regranted to local partners, $650,000 for national staff, $250,000 to national partners, $600,000 for other costs, including events, polling, lobbying, and overhead."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016#Case_for_this_grant describes reasons for the grant, centered mostly around the Federal Reserve''s heavy focus on reducing inflation in the inflation-unemployment tradeoff, and the desire to shift to having it care more about unemployment. It also talks about the benefits of increasing transparency and accountability in the regional Federal Reserve Banks, one of the other areas the Fed Up campaign focuses on.',
  /* donor_amount_reason */ 'The amount is about half of the planned $3 million budget for the campaign in 2016. https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016#Budget_and_proposed_activities says: "The initial 2016 budget given to us by Fed Up was for $4 million, but we also requested budgets for $2 million and $3 million. Each of these budgets would be a substantial increase from 2015. [...] After discussion with CPD, we don’t believe the support from these funders is likely to dramatically increase in the near future."',
  /* donor_timing_reason */ 'The previous grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2015 was for the 2015 year, so with the end of the year, funds are needed for 2016''s Fed Up campaign.',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016#Plans_for_learning_and_follow-up lists follow-up questions, and says: "When the next recession occurs, we plan to attempt a more holistic and detailed evaluation of the grant’s performance. We may check the transcripts of 2016 FOMC meetings after they are released in 2022 to see whether any of the FOMC members discuss meetings with workers that inform their perspectives on policy."',
  /* door_retrospective */ 'Followup conversations with Ady Barkan and Shawn Sebastian of grantee organization at https://www.openphilanthropy.org/sites/default/files/Fed_Up_07-14-16_and_08_31_16_and_09_02_16_%28public%29.pdf on 2016-07-14, 2016-08-31, and 2016-09-02. A followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 (2017) and further grants in later years suggest continued satisfaction with the grantee, though these followup grant writeups reflect more reservations as a result of further improvements in labor market conditions.',
  /* notes */ 'Conversation with Ady Barkman of grantee organization around the time of the grant allocation at https://www.openphilanthropy.org/sites/default/files/Ady_Barkan_12-8-15_%28public%29.pdf on 2015-12-08.'),

  ('Open Philanthropy','Center for Popular Democracy',1100000,'2017-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2017-12-28','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/F-AE_gVn6Zg',NULL,
  /* donation_process */ 'This renewal grant for CPD''s Fed Up campaign is based on a review of the campaign''s performance so far as well as changes to the political and economic environment.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve, and specifically in the selection of regional Federal Reserve Bank presidents and leaders. [...] CPD expects to use this funding toward campaign expenses such as salaries, travel, sub-grants, and overhead."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'The grant page says: "We decided to renew our support based primarily on CPD’s continued success drawing attention for its agenda from the press, Congress, and the Fed; ongoing opportunities to potentially influence the appointment or priorities of new Federal Reserve governors and regional Fed presidents; and our intention to provide the campaign with enough sustainable funding to last through the next recession, when CPD’s advocacy might be especially useful and when we could better evaluate its performance. [...] However, our primary reason for continuing to support the campaign is that we believe it may be able to potentially prevent extraordinary harm during the next recession, when we think it will be more likely to have a meaningful short-term influence (as compared to the current gradual tightening cycle)."',
  /* donor_amount_reason */ 'No specific reasons are given for the amount; it is less than the $1,429,000 given the previous year.',
  /* donor_timing_reason */ 'The previous grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2016 was for the 2016 year, so with the end of the year, funds are needed for 2017''s Fed Up campaign.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'A followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2018 suggests continued satisfaction with the grantee, though it notes: "As labor market conditions have improved, we’ve become less confident about the appropriate short term stance of monetary policy." There are further followup grants in 2019 and 2020.',
  /* notes */ 'The grant page says: "Since our last grant, one new area of uncertainty introduced for the campaign is the degree to which the Trump administration and a unified Republican Congress might support policies that reduce the need for expansionary monetary policy. Additionally, as unemployment rates have declined, we have become less confident in the appropriate short-term stance of monetary policy, and could imagine disagreeing with the Fed Up campaign about the appropriate direction for interest rates to move." An associated grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2017 is made to the CPD Action Fund by the Open Philanthropy Action Fund.'),
  
  ('Open Philanthropy','Center for Popular Democracy',1200000,'2018-02-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States','2018-03-23','day',NULL,NULL, /* date adjusted */
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'The grant page says: "As labor market conditions have improved, we’ve become less confident about the appropriate short term stance of monetary policy, but we continue to believe it to be worthwhile to support the campaign through the next recession, when its advocacy might be especially useful and when we could better evaluate its impact."',
  /* donor_amount_reason */ 'No specific reasons are given for the amount, but it roughly matches the amounts of the previous years: $1,100,000 for 2017 and $1,429,000 for 2016.',
  /* donor_timing_reason */ 'The previous grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-campaign-2017 was for the 2017 year, so with the end of the year, funds are needed for 2017''s Fed Up campaign.',
  /* donor_next_donation_thoughts */ 'The grant page notes that the next recession would be an occasion to better evaluate the impact of the Fed Up campaign.',
  /* donor_retrospective */ 'Followup grants include https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2019 (2019-11) and https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2020 (2020-06). The latter grant is made in light of the recession induced by the COVID-19 pandemic.',
  /* notes */ 'An associated grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-action-fund-fed-campaign-2018 is made to the CPD Action Fund by the Open Philanthropy Action Fund.'),

  ('Open Philanthropy','Center for Popular Democracy',600000,'2019-11-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2019','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'The grant page says: "As labor market conditions have improved, we’ve become less confident about the appropriate short term stance of monetary policy, but we continue to believe it to be worthwhile to support the campaign through the next recession, when its advocacy might be especially useful and when we could better evaluate its impact."',
  /* donor_amount_reason */ 'The amount, this time for two years, is significantly less than the amounts of previous one-year grants in 2016, 2017, and 2018 (over $1 million each).',
  /* donor_timing_reason */ 'The grant is made after the end of the 2018 grant, but not immediately afterward; it is made in late 2019. The reasons for the gap in timing are unclear.',
  /* donor_next_donation_thoughts */ 'The grant page notes that the next recession would be an occasion to better evaluate the impact of the Fed Up campaign.',
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2020 (2020-06) is made in light of the recession induced by the COVID-19 pandemic.',
  /* notes */ 'Unlike the two preceding grants to CPD, this grant is not accompanied by any (publicly announced) grant to CPD Action.'),

  ('Open Philanthropy','Center for Popular Democracy',465000,'2020-06-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2020','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the “Fed Up” campaign. The campaign aims to encourage more accommodative monetary policies and greater transparency and public engagement in the governance of the Federal Reserve. Fed Up plans to use this funding to build up grassroots support for policies that prioritize full employment during and following the current economic crisis."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page does not discuss reasons, but a reasonable inference based on the information on the page as well as the previous grant page https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2019 is that the recession caused by the COVID-19 pandemic motivated the grant. A goal of the Fed Up campaign is to make the Fed care more about unemployment, and the COVID-19-induced recession is a time when this concern becomes particularly salient.',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'This is not a renewal grant; the time period for the preceding two-year grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-popular-democracy-fed-up-campaign-2019 (2019-11) is still ongoing. Based on the grant description, the timing of this grant seems to be due to the COVID-19-induced economic recession; the grant is made about three months after the COVID-19-induced decline in economic activity.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Positive Money Europe */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes, amount_original_currency, original_currency, currency_conversion_basis) values
  ('Open Philanthropy','Positive Money Europe',73368,'2021-01-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/positive-money-europe','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','Europe',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support research and advocacy on macroeconomic policy in the Eurozone."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ 60000,
  /* original_currency */ 'EUR',
  /* notes */ NULL);

/* Urban Institute; note that there are also grants to Urban Institute in land use reform */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Urban Institute',50000,'2020-11-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/urban-institute-counter-cyclical-state-funding-mechanisms','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support a report on implementing countercyclical state funding mechanisms as a means to support states and localities in managing the effects of economic shocks like the COVID-19 pandemic and recession."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* The Center on Poverty and Inequality */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, affected_countries, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','The Center on Poverty and Inequality',50000,'2020-01-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/georgetown-university-center-on-poverty-and-inequality','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Alexander Berger','United States',NULL,NULL,NULL,NULL,
  /* donation_process */ 'The grant is via Georgetown University, where the Center on Poverty ad Inequality is housed.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support the Center on Poverty and Inequality’s work on enhancing automatic fiscal stabilizers. Automatic fiscal stabilizers are taxes and government programs that respond automatically to changing economic conditions, and do not require additional Congressional action."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant page says, of the research topic: "We believe [automatic fiscal stabilizers] are important for mitigating the effects of economic downturns."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Macroeconomic stabilization policy */
insert into donations(donor, donee, amount, donation_date,donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, influencer, affected_countries,donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions) values
  ('Open Philanthropy','Roosevelt Institute',200000,'2016-06-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/roosevelt-institute-macroeconomic-policy-research','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant supports work on macroeconomic policy. Includes exploring monetary policy tools, automatic stabilizes, novel fiscal stimulus measures, also making the case for importance of continued focus on reducing unemployment and against premature monetary tightening today','Alexander Berger','United States', '2016-10-25', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/vAPhHDgenvY',NULL),
  ('Open Philanthropy','Center on Budget and Policy Priorities',425000,'2016-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project-2016','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant supports the Full Employment Project, and renews a previous grant to CBPP made in 2014','Alexander Berger','United States', '2016-10-25', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/vAPhHDgenvY',NULL),
  ('Open Philanthropy','Center for American Progress',500000,'2016-03-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-american-progress-macroeconomic-stabilization','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant for macroeconomic stabilization policy: convenings, research reports on impacts (e.g., impact of Taylor rule on income distribution), policy proposals, and network and outreach capacity to share research and proposals with media, politicians, and Federal Reserve','Alexander Berger','United States','2016-04-19','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/Br6kCBlTAkg',NULL),
  ('Open Philanthropy','Center on Budget and Policy Priorities',335000,'2014-09-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant is for the Full Employment Project. Open Phil is impressed by the track record of CBPP. Followup conversation with Jared Bernstein and Ben Spielberg of grantee organization at https://www.openphilanthropy.org/sites/default/files/Jared_Bernstein_and_Ben_Spielberg_10-21-15_%28public%29.pdf on 2015-10-21','Alexander Berger','United States', '2014-09-19', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/HWCQwDbQhks',NULL),
  ('Open Philanthropy','Center on Budget and Policy Priorities',100000,'2018-05-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-automatic-stabilizers','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to support work on enhancing automatic fiscal stabilizers. Automatic fiscal stabilizers are taxes and government programs that respond automatically to changing economic conditions, and do not require additional Congressional action.','Alexander Berger','United States','2018-06-21','day',NULL,NULL),
  ('Open Philanthropy','Center on Budget and Policy Priorities',250000,'2018-07-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project-2018','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Exit grant to support the Full Employment Project. Renewal of July 2016 grant https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/center-budget-and-policy-priorities-full-employment-project-2016 Open Phil will discontinue support after this grant, which completes five years of support for the project. The reason for not continuing further is the unclear impact of marginal funding and the desire to give space to other funders','Alexander Berger','United States','2018-08-02','day',NULL,NULL),
  ('Open Philanthropy','Washington Center for Equitable Growth',100000,'2018-10-01','month','donation log','Macroeconomic stabilization policy','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy/washington-center-for-equitable-growth-automatic-stabilizers-conference','https://www.openphilanthropy.org/focus/us-policy/macroeconomic-policy','Grant to host a conference, in partnership with the Hamilton Project, on a framework for thinking about optimal design of automatic stabilizer programs as well as specific suggestions for reforms. Automatic fiscal stabilizers are taxes and government programs that respond automatically to changing economic conditions, and do not require additional Congressional action, and the Open Philanthropy Project believes they are important for mitigating the effects of economic downturns.','Alexander Berger','United States','2018-11-27','day',NULL,NULL);
