/* Grants to International Refugee Assistance Project */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','International Refugee Assistance Project',700000,'2016-05-01','month','donation log','Migration policy/refugee migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States',NULL,'Alexander Berger','2016-06-16', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/KcYTzaU6w2I',NULL),
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support#Our_process says: "After meeting with Becca Heller, we investigated IRAP’s track record by talking to one of their funders, several other organizations that work with them on refugee issues, and by reviewing documents about their historical role in increasing the number of SIVs. We then requested a proposal for how IRAP would use additional funds for advocacy and decided to contribute unrestricted funds instead." The proposal is at https://www.openphilanthropy.org/files/Grants/IRAP/International_Refugee_Assistance_Project_Proposal_Open_Philanthropy_2016.pdf',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support#Proposed_activities says: "IRAP plans to hire two new policy staff and one communications person. Focus areas for the policy hires will likely include: (1) Expanding its advocacy for eligible refugees to receive Special Immigrant Visas (SIVs) (2) Creating new resettlement processes and pipelines to ensure that existing visas are effectively distributed [...] (3) Advocating for private refugee resettlement. IRAP does not plan to focus on advocating for higher refugee resettlement commitments from the United States [...]. Instead, IRAP believes its comparative advantage lies in identifying and fixing visa and refugee admission processes that might otherwise prevent current resettlement targets from being met." https://www.openphilanthropy.org/files/Grants/IRAP/International_Refugee_Assistance_Project_Proposal_Open_Philanthropy_2016.pdf has more details.',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support#Case_for_the_grant cites IRAP''s "fairly strong track record of getting more refugees admitted and resettled with fairly limited staff capacity." It attributes a causal role to IRAP in "expanding access to SIVs for tens of thousands of Iraqis and Afghans who worked with the U.S. military (and their families). These visas do not count against the U.S.’s annual cap on refugee admissions." It mentions being impressed with IRAP''s impact in the policy sphere, and in particular with its director Becca Heller; this grant is partly a bet on her.',
  /* donor_amount_reason */ 'The funding proposal https://www.openphilanthropy.org/files/Grants/IRAP/International_Refugee_Assistance_Project_Proposal_Open_Philanthropy_2016.pdf includes a request for $267,250; however, the amount actually granted is substantially higher ($700,000).',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup conversations with Becca Heller, director of grantee organization at https://www.openphilanthropy.org/sites/default/files/Becca_Heller_05-09-16_%28public%29.pdf (2016-05-09), https://www.openphilanthropy.org/sites/default/files/Becca_Heller_07-06-16_%28public%29.pdf (2016-07-06), https://www.openphilanthropy.org/sites/default/files/Becca_Heller_10-05-17_%28public%29.pdf (2017-10-05), and https://www.openphilanthropy.org/sites/default/files/Becca_Heller_03-15-18_%28public%29.pdf (2018-03-15). The followup grants https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2018 (2019-01) and https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2020 (2020-11) suggest continued satisfaction with the grantee.',
  /* notes */ NULL);

  /* pending addition/migration of more grants */

/* Grants to Free Migration Project */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Free Migration Project',24000,'2016-05-01','month','donation log','Migration policy/humanitarian migration/free migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/free-migration-project-planning-grant','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','David Bennion','Alexander Berger','2017-01-10', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/uG8PJ4hjgZ4',NULL,
  /* donation_process */ 'The grantee was introduced to Alexander Berger of Open Philanthropy via an email from Vipul Naik. After that, a funding proposal https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf was submitted by David Bennion, the founder of the grantee organization being started up.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant is a planning grant for the Free Migration Project, a nonprofit organization formed on May 7, 2016 by David Bennion. The funding proposal https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf says the grant is " to engage in a planning and visioning process during Free Migration Project’s start-up phase. This process will involve soliciting feedback from immigrant rights organizers and migration policy thinkers, identifying and analyzing potential obstacles to the organization’s mission, and formulating broad-stroke strategies based on that feedback and analysis." The proposed timeframe of the planning process is May 15, 2016, to November 15, 2016.',
  /* intended_funding_timeframe_in_months */ 6,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'The amount is as requested in https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf (the funding proposal).',
  /* donor_timing_reason */ 'The funding happens shortly after the organization is started, and its timing is influenced by the organization''s start time.',
  /* donor_next_donation_thoughts */ 'Open Philanthropy does not publicly outline its thoughts on followup donations, but the funding proposal https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf (submitted by the grantee) says: "This planning process will [...] help the Open Philanthropy Project determine whether additional funding would further its own objectives."',
  /* donor_retrospective */ 'No followup grants are made by Open Philanthropy, despite the possibility of followup grants being mentioned in the funding proposal. A conversation https://www.openphilanthropy.org/sites/default/files/David_Bennion_11-07-16_%28public%29.pdf is conducted between Open Philanthropy and David Bennion on 2016-11-07, around the end of the timeframe for the planning. No explicit retrospective is published by Open Philanthropy.',
  /* notes */ NULL);

/* Other grants */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, predictions) values
  ('Open Philanthropy','New York University',30000,'2015-08-01','month','donation log','Migration policy/labor mobility/RCT','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/new-york-university-support-labor-mobility-rct','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grantee represented by Suresh Naidu and Yaw Nyarko; grant references cause page https://www.openphilanthropy.org/research/cause-reports/labor-mobility',NULL,NULL,'2015-09-23', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/_m_jhh_KTko',NULL),
  ('Open Philanthropy','Protect the People',550000,'2016-02-01','month','donation log','Migration policy/Haiti/US agricultural migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','A second grant in the area; after a 2014 grant described at https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti to other organizations. New grant builds on positive and negative lessons from earlier grant. Followup conversation with Sarah Williamson of grantee organization at https://www.openphilanthropy.org/sites/default/files/Sarah_Williamson_09-09-16_%28public%29.pdf on 2016-09-09',NULL,NULL,'2016-02-29', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/MbeaAn2aLXE',NULL),
  ('Open Philanthropy','U.S. Association for International Migration',1310483,'2014-07-01','month','donation log','Migration policy/Haiti/US agricultural migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant first published in August 2014; updated with progress report. Grantee was USAIM but project was carried out by it along with International Organization for Migration (IOM). Grant was not repeated next year, but a new grant was made to Protect the People for a similar purpose. On November 1, 2018, the grant amount on the website was reduced from the original of $1,490,505 to an updated value $1,310,483, but no explanation was added',NULL, NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy','ImmigrationWorks Foundation',285000,'2014-07-01','month','donation log','Migration policy/low-skilled migration promotion','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','First major grant to an advocacy group related to promoting more low-skilled migration from the perspective of interests of potential employers of low-skilled workers',NULL, NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy','Center for Global Development',1184720,'2014-03-01','month','donation log','Migration policy/international labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant supports the CGD research agenda on labor mobility, including 75% of the time of Michael Clemens. Followup conversation with Michael Clemens and Cynthis Rathinasamy of grantee organization at https://www.openphilanthropy.org/sites/default/files/Michael_Clemens_and_Cynthia_Rathinasamy_12-15-2015_%28public%29.pdf on 2015-12-15 and again at https://www.openphilanthropy.org/sites/default/files/Michael_Clemens_Cynthia_Rathinasamy_06-21-16_%28public%29.pdf on 2016-06-21','Michael Clemens', NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy','ImmigrationWorks Foundation',150000,'2015-12-01','month','donation log','Migration policy/low-skilled migration promotion','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Second grant; previous grant made in July 2014. New grant provided based on satisfaction with first grant and review of grantee situation. Followup conversation with Tamar Jacoby of grantee organization at https://www.openphilanthropy.org/sites/default/files/Tamar_Jacoby_03-31-16_%28public%29.pdf on 2016-03-31',NULL, NULL, '2015-12-14', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/G1_h0arIB1Y',NULL),
  ('Open Philanthropy','Niskanen Center',360000,'2015-10-01','month','donation log','Migration policy/politics','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grantee is a libertarian think tank looking to hire legal counsel. Followup conversation with grantee organization at https://www.openphilanthropy.org/sites/default/files/David_Bier_12-14-2015_%28public%29.pdf on 2015-12-14 and again at https://www.openphilanthropy.org/sites/default/files/Niskanen_Center_07-22-16_%28public%29.pdf on 2016-07-22',NULL, NULL, '2015-10-29', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/tGWpy5thvRY',NULL),
  ('Open Philanthropy','Center for Global Development',1800000,'2017-03-01','month','donation log','Migration policy/international labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant supports work at CGD of Michael Clemens and his team. Continues a 2014 grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research for the same purpose','Michael Clemens','Alexander Berger','2017-06-27','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/DBMCmQJz1Pc',NULL),
  ('Open Philanthropy','Protect the People',50000,'2016-10-01','month','donation log','Migration policy/Haiti/US agricultural migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-exit-grant','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Exit grant to close out support for helping workers from Haiti access season work in the US. See https://www.openphilanthropy.org/may-2017-update-protect-people-grant for a grant update',NULL,'Alexander Berger','2017-10-20','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/jW3KjxVUOOA',NULL),
  ('Open Philanthropy','Niskanen Center',400000,'2018-01-01','month','donation log','Migration policy/politics','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration-2018','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant over two years to continue to support work on immigration policy. Grant is a renewal of https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration and is in recognition of the Niskanen Center growing its immigration program to $1 million/year, while also keeping in mind the expectation of no significant positive movement on immigration at the federal level',NULL,'Alexander Berger','2018-01-30','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/5XHsBDrlA3Q',NULL),
  ('Open Philanthropy','MoveOn.org Civic Action',375000,'2015-10-01','month','donation log','Migration policy','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/moveon-civic-action-syrian-refugee-advocacy','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant to support work on Syrian refugee resettlement in the United States. Grant recommended for Cari Tuna to make personally; grantee is a 501(c)(4) organization',NULL,'Alexander Berger','2018-06-09','day',NULL,NULL),
  ('Open Philanthropy','International Refugee Assistance Project',1000000,'2019-01-01','month','donation log','Migration policy/refugee migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2018','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant renews May 2016 grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support Grantee plans to expand its work to Europe, focusing on family reunification, asylum, and humanitarian visas. In the grant writeup, the donor notes: "our immigration policy work has not focused much on refugee resettlement, which we had assumed would be more crowded than other aspects of immigration policy with funders aimed at supporting increased opportunities for people to move to the U.S. for humanitarian reasons. While we continue to believe that is directionally correct, our increased interest in supporting advocacy around refugee resettlement is partially based on learning more about the fairly limited foundation funding for advocacy around refugee resettlement."',NULL,'Alexander Berger','2019-03-30','day',NULL,NULL),
  ('Open Philanthropy','Center for Global Development',709888,'2019-03-01','month','donation log','Migration policy/international labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-partnerships','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant over 1.5 years to the Center for Global Development to support a working group on and incubation of a new organization aimed at enhancing international labor mobility. The new organization, called LaMP (Labor Mobility Partnerships), hopes to assist countries negotiating new legal channels for migration on terms of mutual benefit and to generate research and evidence on effective labor mobility regimes, in the ultimate service of reducing global poverty and inequality. Rebekah Smith and Lant Pritchett, who will be working together on the incubation and launch, proposed the idea for this type of organization in a 2016 CGD working paper https://www.cgdev.org/sites/default/files/goldilocks-solution-just-right-promotion-labor-mobility.pdf',NULL,'Alexander Berger','2019-04-19','day',NULL,NULL);
