/* Grants to International Refugee Assistance Project */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','International Refugee Assistance Project',700000,'2016-05-01','month','donation log','Migration policy/refugee migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','Becca Heller','Alexander Berger','2016-06-16', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/KcYTzaU6w2I',NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support#Our_process says: "After meeting with Becca Heller, we investigated IRAP’s track record by talking to one of their funders, several other organizations that work with them on refugee issues, and by reviewing documents about their historical role in increasing the number of SIVs. We then requested a proposal for how IRAP would use additional funds for advocacy and decided to contribute unrestricted funds instead." The proposal is at https://www.openphilanthropy.org/files/Grants/IRAP/International_Refugee_Assistance_Project_Proposal_Open_Philanthropy_2016.pdf',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support#Proposed_activities says: "IRAP plans to hire two new policy staff and one communications person. Focus areas for the policy hires will likely include: (1) Expanding its advocacy for eligible refugees to receive Special Immigrant Visas (SIVs) (2) Creating new resettlement processes and pipelines to ensure that existing visas are effectively distributed [...] (3) Advocating for private refugee resettlement. IRAP does not plan to focus on advocating for higher refugee resettlement commitments from the United States [...]. Instead, IRAP believes its comparative advantage lies in identifying and fixing visa and refugee admission processes that might otherwise prevent current resettlement targets from being met." https://www.openphilanthropy.org/files/Grants/IRAP/International_Refugee_Assistance_Project_Proposal_Open_Philanthropy_2016.pdf has more details.',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support#Case_for_the_grant cites IRAP''s "fairly strong track record of getting more refugees admitted and resettled with fairly limited staff capacity." It attributes a causal role to IRAP in "expanding access to SIVs for tens of thousands of Iraqis and Afghans who worked with the U.S. military (and their families). These visas do not count against the U.S.’s annual cap on refugee admissions." It mentions being impressed with IRAP''s impact in the policy sphere, and in particular with its director Becca Heller; this grant is partly a bet on her.',
  /* donor_amount_reason */ 'The funding proposal https://www.openphilanthropy.org/files/Grants/IRAP/International_Refugee_Assistance_Project_Proposal_Open_Philanthropy_2016.pdf includes a request for $267,250; however, the amount actually granted is substantially higher ($700,000).',
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Followup conversations with Becca Heller, director of grantee organization at https://www.openphilanthropy.org/sites/default/files/Becca_Heller_05-09-16_%28public%29.pdf (2016-05-09), https://www.openphilanthropy.org/sites/default/files/Becca_Heller_07-06-16_%28public%29.pdf (2016-07-06), https://www.openphilanthropy.org/sites/default/files/Becca_Heller_10-05-17_%28public%29.pdf (2017-10-05), and https://www.openphilanthropy.org/sites/default/files/Becca_Heller_03-15-18_%28public%29.pdf (2018-03-15). The followup grants https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2018 (2019-01) and https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2020 (2020-11) suggest continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','International Refugee Assistance Project',1000000,'2019-01-01','month','donation log','Migration policy/refugee migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2019','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,NULL,'Alexander Berger','2019-03-29','day',NULL,NULL, /* date adjusted */
  /* donation_process */ 'Between the previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support (2016-05) and this grant, Open Philanthropy had four conversations with Becca Heller, director of the grantee organization:  https://www.openphilanthropy.org/sites/default/files/Becca_Heller_05-09-16_%28public%29.pdf (2016-05-09), https://www.openphilanthropy.org/sites/default/files/Becca_Heller_07-06-16_%28public%29.pdf (2016-07-06), https://www.openphilanthropy.org/sites/default/files/Becca_Heller_10-05-17_%28public%29.pdf (2017-10-05), and https://www.openphilanthropy.org/sites/default/files/Becca_Heller_03-15-18_%28public%29.pdf (2018-03-15).',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant "for general support. IRAP plans to expand its work to Europe, focusing on family reunification, asylum, and humanitarian visas."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'The grant page says: "In the past, our immigration policy work has not focused much on refugee resettlement, which we had assumed would be more crowded than other aspects of immigration policy with funders aimed at supporting increased opportunities for people to move to the U.S. for humanitarian reasons. While we continue to believe that is directionally correct, our increased interest in supporting advocacy around refugee resettlement is partially based on learning more about the fairly limited foundation funding for advocacy around refugee resettlement."',
  /* donor_amount_reason */ 'No explicit reasons for the amount are given; the amount is slightly larger than the previous two-year grant of $700,000.',
  /* donor_timing_reason */ 'The grant is made a few months after the end of the timeframe for the previous two-year grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support (2016-05).',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2020 (2020-11) suggests continued satisfaction with the grantee.',
  /* notes */ NULL),

  ('Open Philanthropy','International Refugee Assistance Project',75000,'2019-05-01','month','donation log','Migration policy/refugee migration/family reunification','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-family-reunification','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,NULL,'Alexander Berger',NULL,NULL,NULL,NULL,
  /* donation_process */ 'Discretionary grant',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support a family reunification pilot project. IRAP intends to try to reunite approximately 125 refugee children with their families."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Open Philanthropy','International Refugee Assistance Project',1000000,'2020-11-01','month','donation log','Migration policy/refugee migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2020','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,NULL,'Alexander Berger',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'The grant page links to the grant page for the first grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support (2016-05) for the rationale for supporting the grantee.',
  /* donor_amount_reason */ 'No explicit reason is given for the amount, but both the amount and the timeframe match the previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2019 (2019-01).',
  /* donor_timing_reason */ 'The grant is made right around the end of the timeframe of the previous two-year grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support-2019 (2019-01).',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Grants to Niskanen Center */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Niskanen Center',360000,'2015-10-01','month','donation log','Migration policy/politics','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','Alexander Berger','2015-10-29','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/tGWpy5thvRY',NULL,
  /* doonation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration#Our_review_process says: "We approached Niskanen in June 2015 to discuss funding opportunities relating to advocacy for lower-skill immigration, and a series of conversations about its work culminated in a request for funding. We solicited background feedback about the Center from a few other sources prior to making a decision about funding it." The immigration policy counsel proposal https://files.givewell.org/files/shallow/international-migration/grants/Niskanen-Immigration-Policy-Counsel-Proposal.pdf is what the grant would ultimately fund; the Sources section includes links to that and to many conversations in the "series of conversations" mentioned.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration#Budget_and_proposed_activities says: "Niskanen asked us for $360,000 over two years, which would be enough to pay for an additional full-time Immigration Policy Counsel along with associated costs." https://files.givewell.org/files/shallow/international-migration/grants/Niskanen-Immigration-Policy-Counsel-Proposal.pdf is the full Immigration Policy Counsel Proposal.',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration#Case_for_the_grant says: "Our conversations with staff from the Niskanen Center gave us the sense that they share our goal of allowing significantly more migration, including by lower-skilled people and those from low-income countries. [...] The Niskanen Center’s strategy is to try to get information, arguments, and new policy ideas directly into the hands of key decision-makers, rather than building long-term interest group alignment or changing public opinion. [...] We can imagine a scenario in which Niskanen is able to popularize a proposal that ends up as part of comprehensive immigration reform package in 2017, or is able to provide information that leads to a tweak in enacted legislation, and believe that the grant is likely to be very worthwhile in such a case. Our impression is that the Niskanen Center is plausibly well-positioned to execute this strategy successfully [...]."',
  /* donor_amount_reason */ 'The amount is as requested in the immigration policy counsel proposal https://files.givewell.org/files/shallow/international-migration/grants/Niskanen-Immigration-Policy-Counsel-Proposal.pdf that also includes a breakdown.',
  /* donor_timing_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration#Our_review_process gives a hint about the timing by giving the start of investigation and the process: "We approached Niskanen in June 2015 to discuss funding opportunities [...] We solicited background feedback about the Center from a few other sources prior to making a decision about funding it."',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration#Plans_for_learning_and_follow-up includes goals for learning and follow-up, key folllow-up questions, and follow-up expectations. It ends with: "We expect to provide an update on this grant after one year either by publishing public notes or by producing a brief writeup. After the grant is spent down, we plan to attempt a more holistic and detailed evaluation of the grant’s performance. However, we may abandon either or both of these follow-up expectations or perform more follow-up than planned if the circumstances call for it."',
  /* donor_retrospective */ 'Followup conversations with the grantee include: https://www.openphilanthropy.org/sites/default/files/David_Bier_12-14-2015_%28public%29.pdf (David Bier, 2015-12-14), https://www.openphilanthropy.org/sites/default/files/Niskanen_Center_07-22-16_%28public%29.pdf (many people, 2016-07-22), https://www.openphilanthropy.org/files/Conversations/Niskanen_Center_02-14-17_(public).pdf (many people, 2017-02-14), and https://www.openphilanthropy.org/sites/default/files/Niskanen_Center_06-22-17_%28public%29.pdf (Kristie De Peña and Matthew La Corte, 2017-06-22). Followup grants would be made: https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration-2018 (2018-01) and https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-center-research-on-immigration-policy-2020 (2020-01) with the latter being an exit grant.',
  /* notes */ NULL),

  ('Open Philanthropy','Niskanen Center',400000,'2018-01-01','month','donation log','Migration policy/politics','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration-2018','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','Alexander Berger','2018-01-30','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/5XHsBDrlA3Q',NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support [grantee''s] work on immigration policy. [...] Niskanen has grown its immigration program to approximately $1M/year."',
  /* intended_funding_timeframe_in_months */ 24,
  /* donor_donee_reason */ 'The grant page says: "Because we do not expect significant positive movement on immigration at the federal level over the next few years [a likely reference to the Trump presidency at the time], we view this support primarily as a way to ensure the Niskanen Center is able to continue developing relationships and policy ideas in advance of any future opportunities for progress."',
  /* donor_amount_reason */ 'The previous grant was $360,000 for two years; this grant amount is pretty comparable. The grant page says: "Niskanen has grown its immigration program to approximately $1M/year." So this grant now accounts for only 20% of the cost of the program.',
  /* donor_timing_reason */ 'The grant is made around the end of the timeframe for the previous two-year grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration (2015-10).',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'The followup grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-center-research-on-immigration-policy-2020 (2020-01) would be an exit grant. Open Philanthropy does not provide reasons for the exit, so its retrospective evaluation of this grant isn''t clear.',
  /* notes */ NULL),

  ('Open Philanthropy','Niskanen Center',200000,'2020-01-01','month','donation log','Migration policy/politics','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-center-research-on-immigration-policy-2020','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','Alexander Berger',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support [grantee''s] work on immigration policy. The Niskanen Center, a libertarian think tank, seeks to reduce barriers to immigration by developing and disseminating information, arguments, and policy ideas."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'This is a renewal of a previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration-2018 (2018-01) and is being offered as an exit grant to give the grantee time to transition out.',
  /* donor_amount_reason */ 'The amount is at the same rate per year ($200,000) as the previous grant, that was $400,000 over two years. The shorter timeframe (and hence lower amount) is a reflection of the "exit grant" nature.',
  /* donor_timing_reason */ 'The grant is made at the end of the timeframe foor the previous two-year grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/niskanen-immigration-2018 (2018-01).',
  /* donor_next_donation_thoughts */ 'This is an exit grant, so there are no plans for further grants.',
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Grants to Free Migration Project */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Free Migration Project',24000,'2016-05-01','month','donation log','Migration policy/humanitarian migration/free migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/free-migration-project-planning-grant','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','David Bennion','Alexander Berger','2017-01-10', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/uG8PJ4hjgZ4',NULL,
  /* donation_process */ 'The grantee was introduced to Alexander Berger of Open Philanthropy via an email from Vipul Naik. After that, a funding proposal https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf was submitted by David Bennion, the founder of the grantee organization being started up.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The grant is a planning grant for the Free Migration Project, a nonprofit organization formed on May 7, 2016 by David Bennion. The funding proposal https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf says the grant is " to engage in a planning and visioning process during Free Migration Project’s start-up phase. This process will involve soliciting feedback from immigrant rights organizers and migration policy thinkers, identifying and analyzing potential obstacles to the organization’s mission, and formulating broad-stroke strategies based on that feedback and analysis." The proposed timeframe of the planning process is May 15, 2016, to November 15, 2016.',
  /* intended_funding_timeframe_in_months */ 6,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'The amount is as requested in https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf (the funding proposal).',
  /* donor_timing_reason */ 'The funding happens shortly after the organization is started, and its timing is influenced by the organization''s start time.',
  /* donor_next_donation_thoughts */ 'Open Philanthropy does not publicly outline its thoughts on followup donations, but the funding proposal https://www.openphilanthropy.org/files/Grants/Free_Migration_Project/Free_Migration_Project_funding_proposal_(OPP)_final.pdf (submitted by the grantee) says: "This planning process will [...] help the Open Philanthropy Project determine whether additional funding would further its own objectives."',
  /* donor_retrospective */ 'No followup grants are made by Open Philanthropy, despite the possibility of followup grants being mentioned in the funding proposal. A conversation https://www.openphilanthropy.org/sites/default/files/David_Bennion_11-07-16_%28public%29.pdf is conducted between Open Philanthropy and David Bennion on 2016-11-07, around the end of the timeframe for the planning. No explicit retrospective is published by Open Philanthropy.',
  /* notes */ NULL);

/* Grants to Protect the People */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Protect the People',550000,'2016-02-01','month','donation log','Migration policy/labor mobility/seasonal migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States|Haiti','Alexander Berger','2016-02-29','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/MbeaAn2aLXE',NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti#Process refers to a previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti#Case_for_this_grant (2014-07) to support seasonal migration from Haiti. The idea for the current grant arose from discussions with the current grantee, Protect the People, that had provideed support on the project funded by the previous grant. The grant page says: "We negotiated the grant structure described above to ensure that PTP would have adequate funds to attempt the project but to limit our downside in case PTP faces barriers and is unable to reach the desired number of participants." https://files.givewell.org/files/shallow/international-migration/grants/ptp_gv_qa.pdf has a Q&A with Protect the People about the program. $50,000 of the grant was made personally by Cari Tuna due to urgency.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti#Grant_structure says the grant is "to continue to try to facilitate Haitian access to the H-2A program for another year. [...] The grant is structured conditionally, such that if the project enables more than 75 Haitian workers to use H-2A visas to work in the U.S., we will provide PTP with additional funding to cover costs for the additional workers. This support will scale up proportionally with the number of workers participating in the project, up to a maximum grant total of $1,000,000 for 2016. PTP currently projects that around 150 Haitian workers will be able to participate in the program in 2016, though our best guess is that the total is likely to be lower (because we anticipate that some of the problems previously encountered in the visa process may recur)."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti#Case_for_the_grant says: "We estimate that each Haitian worker in the U.S. earns about $5,000 for about 3 months of work. Since agricultural workers in Haiti earn around $1,000 per year, this increase in income is substantial. Although the pilot project failed to enable many Haitians to work in the U.S., we think that this could have been due to bad luck more than fundamental problems in the program design." The section further details challenges with the earlier grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti (2014-07) and updates the potential upside estimate from $50 million to $25 million.',
  /* donor_amount_reason */ 'The amount is about 1/3 the amountof the previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti (2014-07), with the reduction reflective of the desire to take a more cautious approach after the previous grant underperformed.',
  /* donor_timing_reason */ 'The grant happens after sufficient evaluation time has passed for the previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti (2014-07), and after discussions between Open Philanthropy and Protect the People on the grant structure.',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti#Plans_for_learning_and_follow-up says that further funding is unlikely if the grant enables fewer than 75 workers to participate. Future funding is uncertain if the grant enables between 75 and 150 workers. Future funding is highy likely if more than 150 workers participate, with a goal of transition to sustainability without philanthropic support.',
  /* donor_retrospective */ 'Followup conversation with Sarah Williamson at https://www.openphilanthropy.org/sites/default/files/Sarah_Williamson_09-09-16_%28public%29.pdf (2016-09-09). 58 workers would participate in the program in 2016, leading Open Philanthropy to provide a $50,000 exit grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-exit-grant (2016-10). https://www.openphilanthropy.org/focus/us-policy/immigration-policy/october-2017-update-protect-people-seasonal-migration-haiti has a detailed retrospective of the whole effort.',
  /* notes */ 'The program funded by the grant would be covered by The Economist in https://www.economist.com/finance-and-economics/2017/01/26/visas-as-aid (January 2017).'),

  ('Open Philanthropy','Protect the People',50000,'2016-10-01','month','donation log','Migration policy/labor mobility/seasonal migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-exit-grant','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States|Haiti','Alexander Berger','2017-10-20','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/jW3KjxVUOOA',NULL,
  /* donation_process */ 'This exit grant came out of the evaluation process for the previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti (2016-02) including a conversation https://www.openphilanthropy.org/sites/default/files/Sarah_Williamson_09-09-16_%28public%29.pdf (2016-09-09).',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant is an exit grant to "to close out [Open Philanthropy''s] support of its program helping workers from Haiti to access seasonal work in the U.S." https://www.openphilanthropy.org/focus/us-policy/immigration-policy/october-2017-update-protect-people-seasonal-migration-haiti more specifically says it was to "ensure a safe return to Haiti for the workers whose travel they had facilitated, and to continue pursuing funding from other sources."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/october-2017-update-protect-people-seasonal-migration-haiti gives more background on the reasons for the original grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/protect-people-seasonal-migration-haiti (2016-02) and the grant outcomes. The original grant write-up already indicated plans to not renew if fewer than 75 workers participated in 2016, and only 58 participated, explaining the "exit" part. The reason the grant was made at all despite the reduced participation was due to unexpected costs incurred by the grantee running the program, and Open Phil''s desire to help the grantee smoothly continue the 2016 program.',
  /* donor_amount_reason */ 'The relatively small amount was likely chosen to be enough to support the intended uses of funds to close out the program and seek additional funding.',
  /* donor_timing_reason */ 'The grant timing is near the end of 2016, by which time the performance of the original grant is known, and the need for additional funds to facilitate the safe return of workers is also known.',
  /* donor_next_donation_thoughts */ 'This is an exit grant so there are no plans for further donations.',
  /* donor_retrospective */ 'The October 2017 update https://www.openphilanthropy.org/focus/us-policy/immigration-policy/october-2017-update-protect-people-seasonal-migration-haiti#Updates_since_deciding_not_to_renew mentions that two of the farms participating in the 2016 program ended up using 59 Haitian H-2As in 2017, suggesting a possibility that the work done in 2016 had already created a small sustainable flow, something that they had not expected when deciding to exit. Open Phil says: "We hope to monitor the flow of Haitian workers to U.S. farms in future years, and we acknowledge that we may turn out to have been mistaken in withdrawing funding at the point when we did."',
  /* notes */ 'The program funded by the grant would be covered by The Economist in https://www.economist.com/finance-and-economics/2017/01/26/visas-as-aid (January 2017).');

/* Grants to ImmigrationWorks Foundation */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','ImmigrationWorks Foundation',285000,'2014-07-01','month','donation log','Migration policy/low-skilled migration promotion','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','Alexander Berger',NULL,NULL,NULL,NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Our_process says: "GiveWell approached IW in March 2014 to discuss funding opportunities relating to advocacy for lower-skill immigration and learned that IW was seeking philanthropic funding. A series of conversations about IW’s work culminated in a request for funding. We shared a draft version of this page with IW staff prior to the grant being finalized."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grantee prepared funding options at https://files.givewell.org/files/shallow/international-migration/grants/IW%20menu%20of%20funding%20options.pdf and https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Proposed_activities provides a summary: $55,000 funding gap for 2014 (funded), $40,000 for a grassroots coordinator in Washington (funded), $180,000 for campaigns in the states (not funded), $150,000 for public opinion research (funded), and $40,000 for building consensus around policy (funded). The funding is unrestricted even though the intended use funds specific programs.',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Case_for_the_grant links to https://www.openphilanthropy.org/research/cause-reports/policy/labor-mobility#What_is_the_problem for the importance of funding low-skilled immigration, the focus of ImmigrationWorks and not a focus of most organizations. Also: "One positive feature of the public opinion research may be that it is less time-sensitive than the advocacy work: messages that are found to work today may continue to be helpful if immigration reform appears on the national agenda again in a few years." A learning goal is also cited: "In addition to the potential for impact, we also see this grant as a good way to learn more about advocacy opportunities around immigration reform in the U.S."',
  /* donor_amount_reason */ 'The amount is the total of activities that Open Philanthropy chose to fund oof https://files.givewell.org/files/shallow/international-migration/grants/IW%20menu%20of%20funding%20options.pdf at https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Proposed_activities namely $55,000 funding gap for 2014, $40,000 for a grassroots coordinator in Washington, $150,000 for public opinion research, and $40,000 for building consensus around policy.',
  /* donor_timing_reason */ 'The timing seems to be a result of when Open Philanthropy started the process and how long the due diligence took. https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Our_process says: "says: "GiveWell approached IW in March 2014 to discuss funding opportunities [...] A series of conversations about IW’s work culminated in a request for funding."',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Plans_for_learning_and_follow-up has details on questions that Open Philanthropy will continue investigating, and plans for continued conversations with Tamar Jacoby every 2-3 months over the course of the year-long grant.',
 /* donor_retrospective */ 'The renewal grant write-up https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#Previous_grant has a detailed evaluation of the outcome of the grant. The grant was mostly to maintain existing expenses rather than expand significantly; one form of impact is described: "Jacoby has considered shifting focus away from immigration policy to prioritize her work with Opportunity America, and we believe there is a reasonable probability that Open Philanthropy’s grant played a role in keeping Jacoby active in the area of immigration."',
 /* notes */ 'The grant page https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-foundation-general-support#Plans_for_learning_and_follow-up is fairly detailed; in particular, it includes details on ImmigrationWorks'' past track record and has a section on risks to the success of the grant.'),

  ('Open Philanthropy','ImmigrationWorks Foundation',150000,'2015-12-01','month','donation log','Migration policy/low-skilled migration promotion','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','United States','Alexander Berger','2015-12-14','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/G1_h0arIB1Y',NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#Our_process says: "We began discussing the possibility of renewing our support of ImmigrationWorks as the previous grant period drew to a close. Tamar Jacoby spoke with us about potential activities for ImmigrationWorks over the next 18 months, and about ImmigrationWorks’ current funding situation."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'A list of proposed activities is submitted by the granteee at https://files.givewell.org/files/shallow/international-migration/grants/IW-2015-2017-memo.pdf (2015-10-23) and summarized at https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#footnoteref6_elw4mih including activities such as: mobilize a donor collaborative, develop a strategy for future Congressional advocacy, advance a worker-visa pilot program, develop a communications strategy, and colllaboration with the Niskanen Center.',
  /* intended_funding_timeframe_in_months */ 18,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#Case_for_the_new_grant says: "We see IW as a small organization which shares the Open Philanthropy Project’s goal of increasing lower-skill immigration, an aspect of immigration policy that does not receive much other support. IW is experiencing a funding shortfall while focus has shifted away from immigration reform in Congress, and we believe that this grant could play a significant role in keeping IW operating at its current capacity. In particular, we believe that our grant will allow IW to continue to do more work on immigration, rather than shift resources partially or entirely to Opportunity America (or close down)."',
  /* donor_amount_reason */ 'The amount was chosen to meet the limited goal of continuing to keep ImmigrationWorks running during a lean time when prospects for immigration reform in Congress are limited. It is about half the size of the pre vious one-year grant. https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#Case_for_the_new_grant says: "[W]we believe that this grant could play a significant role in keeping IW operating at its current capacity. In particular, we believe that our grant will allow IW to continue to do more work on immigration, rather than shift resources partially or entirely to Opportunity America (or close down). [...] [W]e are hopeful that our grant will allow IW to continue operations and maintain good relationships with policymakers and others so that it can be present and involved when the issue of CIR is raised again in Congress (likely in 2017)"',
  /* donor_timing_reason */ 'The timing is based on the end of the timeframe for the previous grant and the progress of conversations with the grantee, as https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#Our_process explains.',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016#Plans_for_learning_and_follow-up includes details on expectations from the grant and plans for a more holistic evaluation.',
  /* donor_retrospective */ 'https://www.openphilanthropy.org/sites/default/files/Tamar_Jacoby_03-31-16_%28public%29.pdf (2016-03-31) has a followup conversation with Tamar Jacoby of the grantee organization. No followup grants are made as of 2021.',
  /* notes */ 'The grant page https://www.openphilanthropy.org/focus/us-policy/immigration-policy/immigrationworks-general-support-2016 has several sections including a section reviewing the previous grant and a section on risks.');

/* Grants to Center for Global Development */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Center for Global Development',1184720,'2014-03-01','month','donation log','Migration policy/labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,'Michael Clemens','Alexander Berger',NULL,NULL,NULL,NULL,
  /* donation_process */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research#Our_process says: "The Center for Global Development submitted a proposal for this grant to Good Ventures in January 2014, following several conversations between GiveWell and Good Ventures staff and CGD Senior Fellow Michael Clemens about philanthropic opportunities related to labor mobility. We shared a draft version of this page with Center for Global Development staff prior to the grant being finalized."',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research#Grant_documents links to various grant documents: https://www.givewell.org/files/shallow/international-migration/grants/CGD%20Proposal%20to%20Good%20Ventures_General%20Support%20and%20Migration%20Policy%20Research_2.6.14.pdf (concept note), https://www.givewell.org/files/shallow/international-migration/grants/CGD%20Migration%20Budget_Good%20Ventures%20Proposal%20Final.xlsx (budget proposal), and https://www.givewell.org/files/shallow/international-migration/grants/CGD%20Projected%20Statement%20of%20Expenditures%20and%20Good%20Ventures%20for%202014.xlsx (overall CGD budget).',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ 'Listed reasons include: (1) priority for the cause cf. https://www.openphilanthropy.org/research/cause-reports/policy/labor-mobility and its selection for learning grants https://www.openphilanthropy.org/blog/givewell-labs-update (2) being impressed with the past work of Michael Clemens, (3) room for more funding -- the past work was funded by the MacArthur Foundation and there is no ongoing support for the full portfolio of work Clemens plans to do.',
  /* donor_amount_reason */ 'The amount is based on the budget proposal https://www.givewell.org/files/shallow/international-migration/grants/CGD%20Migration%20Budget_Good%20Ventures%20Proposal%20Final.xlsx submitted by Michael Clemens.',
  /* donor_timing_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research#Our_process indicates that the timing was based on the timing of the grant proposal and the due diligence that followed: "The Center for Global Development submitted a proposal for this grant to Good Ventures in January 2014, following several conversations between GiveWell and Good Ventures staff and CGD Senior Fellow Michael Clemens about philanthropic opportunities related to labor mobility."',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research#Plans_for_learning_and_follow-up lists key follow-up questions and expectations. It says: "Towards the end of the duration of the grant (i.e. in the third year), we plan to attempt a more holistic and detailed evaluation of the grant’s performance, aiming to answer the questions above. We may abandon either or both of these follow-up expectations if labor mobility ceases to be a focus area, or perform more follow-up than planned if this work becomes a key part of our priorities."',
  /* donor_retrospective */ 'There are three published followup conversations between this grant and the next. The writeup for the followup grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program (2017-03) includes a positive assessment of the outcome of the grant, saying "the team has taken on some promising research projects" and "Our expectation is that this type of work may take a fairly long time to have noticeable effects, so even without concrete evidence of impact at this stage, extending our support seems to us like a worthwhile bet, and the immediate projects that Dr. Clemens’ team has proposed seem reasonable and potentially promising to us, though it is difficult for us to assess the value of the projects individually."',
  /* notes */ 'The grant page https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research#Plans_for_learning_and_follow-up has several more details including an extensive discussion of room for more funding and fungibility, and a section on risks. Followup grants: https://www.openphilanthropy.org/dr-michael-clemens-senior-fellow-center-global-development-cgd-and-cynthia-rathinasamy-program (2015-12-15), https://www.openphilanthropy.org/sites/default/files/Michael_Clemens_Cynthia_Rathinasamy_06-21-16_%28public%29.pdf (2016-06-21), and https://www.openphilanthropy.org/sites/default/files/Center_for_Global_Development_11-22-16_%28public%29.pdf (2016-11-22).'),

  ('Open Philanthropy','Center for Global Development',1800000,'2017-03-01','month','donation log','Migration policy/labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,'Michael Clemens','Alexander Berger','2017-06-27','day','https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/DBMCmQJz1Pc',NULL,
  /* donation_process */ 'The grant page does not discuss the process explicitly, but it''s likely based on the follow-up exeecuted as part of https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research#Follow-up_expectations for the previous grant.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to fund the CGD 2017-2019 Migration Program. https://www.openphilanthropy.org/files/Grants/CGD/CGD_Migration_Program_Description.pdf has some details of activities funded. https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program#Budget_and_room_for_more_funding says: "Our funding will continue to support Dr. Clemens’ salary, as well as costs of travel and working with consultants. Most of the increase in funding will cover the hiring of a full-time research fellow, plus additional support from administrative, communications, and policy staff."',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program#About_the_grant gives the reasons for the grant, mostly centered around a positive evaluation of the outcome of the previous grant. Relevant excerpts include "the team has taken on some promising research projects" and "Our expectation is that this type of work may take a fairly long time to have noticeable effects, so even without concrete evidence of impact at this stage, extending our support seems to us like a worthwhile bet, and the immediate projects that Dr. Clemens’ team has proposed seem reasonable and potentially promising to us, though it is difficult for us to assess the value of the projects individually."',
  /* donor_amount_reason */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program#Budget_and_room_for_more_funding says: "This grant represents an increase in our yearly funding for CGD over our previous grant, from roughly $400,000 to roughly $600,000 per year. Our funding will continue to support Dr. Clemens’ salary, as well as costs of travel and working with consultants. Most of the increase in funding will cover the hiring of a full-time research fellow, plus additional support from administrative, communications, and policy staff."',
  /* donor_timing_reason */ 'The grant is made right at the end of the timeframe for the previous three-year grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-research (2014-03).',
  /* donor_next_donation_thoughts */ 'https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program#Plans_for_learning_and_follow-up lists key questions and follow-up expectations. It also says: "We will likely consider it successful if Dr. Clemens’ upcoming book is extremely well-received (which we do not anticipate, just because of the prior unlikelihood of any given book selling especially well), if any of the team’s initiatives have an impact such that a rough cost-effectiveness estimate suggests a good return on our investment, or if ambitious plans lead us to significantly increase our support in the future. We believe there is only a roughly 50% chance that at least one of the above happens, but that the grant is still justified in expected value terms."',
  /* donor_retrospective */ 'A followup conversation with Michael Clemens happens at https://www.openphilanthropy.org/sites/default/files/Michael_Clemens_11-29-17_%28public%29.pdf (2017-11-29). The grant gets renewed at https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program-2020 (2020-03) though with a reduced funding level.',
  /* notes */ NULL),

  ('Open Philanthropy','Center for Global Development',1000000,'2020-03-01','month','donation log','Migration policy/labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program-2020','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,'Michael Clemens','Alexander Berger|Zachary Robinson',NULL,NULL,NULL,NULL,
  /* donation_process */ 'This renews a previous grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program (2017-03). A conversation https://www.openphilanthropy.org/sites/default/files/Michael_Clemens_11-29-17_%28public%29.pdf (2017-11-29) with Michael Clemens happens between the two grants.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant "to support its migration program, led by Dr. Michael Clemens. [...] this funding includes one additional year at the previous funding level and two subsequent years at a funding level that we believe may be more sustainable for the long run. This funding is intended to support Dr. Clemens’s ongoing research and policy work on immigration." https://www.openphilanthropy.org/files/Grants/CGD/CGD_Migration_Program_Description.pdf describes the activities that the previous grant (renewed by this) funded; this grant is likely similar.',
  /* intended_funding_timeframe_in_months */ 36,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'The grant page says: "this funding includes one additional year at the previous funding level and two subsequent years at a funding level that we believe may be more sustainable for the long run." The previous funding level was $600,000 per year, so this breaks down to $600,000 for one year and $200,000 each for the next two years.',
  /* donor_timing_reason */ 'The grant is made right at the end of the timeframe for the previous three-year grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-migration-program#About_the_grant (2017-03).',
  /* donor_next_donation_thoughts */ 'The framing "funding level that we believe may be more sustainable for the long run" in the grant page suggests that Open Philanthropy is planning to renew funding at the reduced level ($200,000/year) after this three-year grant ends.',
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Grants to Labor Mobility Partnerships */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, affected_countries, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Open Philanthropy','Labor Mobility Partnerships',709888,'2019-03-01','month','donation log','Migration policy/labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-partnerships','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,'Lant Pritchett|Rebekah Smith','Alexander Berger','2019-04-18','day',NULL,NULL, /* date adjusted */
  /* donation_process */ 'The grant page cites https://www.cgdev.org/sites/default/files/goldilocks-solution-just-right-promotion-labor-mobility.pdf as the working paper that led to the idea of the organizattion being incubated by the grant.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant "to the Center for Global Development to	support a working group on and incubation of a new organization aimed at enhancing international labor mobility. The new organization, called LaMP (Labor Mobility Partnerships), hopes to assist countries negotiating new legal channels for migration on terms of mutual benefit and to generate research and evidence on effective labor mobility regimes, in the ultimate service of reducing global poverty and inequality. Rebekah Smith and Lant Pritchett, who will be working together on the incubation and launch, proposed the idea for this type of organization in a 2016 CGD working paper."',
  /* intended_funding_timeframe_in_months */ 18,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'The timing seems related to the timing of the incubated organization''s start, and is dependent on the release of the 2016 working paper https://www.cgdev.org/sites/default/files/goldilocks-solution-just-right-promotion-labor-mobility.pdf that proposed the idea.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Labor Mobility Partnerships would get off the ground and Open Philanthropy would make a followup grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/labor-mobility-partnerships-international-labor-mobility (2020-08) to Labor Mobility Partnerships that would also serve as an exit grant.',
  /* notes */ 'The grant was made to the Center for Global Development to incorporate Labor Mobility Partnerships, but we''re listing it as a grant to Labor Mobility Partnerships here.'),

  ('Open Philanthropy','Labor Mobility Partnerships',500000,'2020-08-01','month','donation log','Migration policy/labor mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/labor-mobility-partnerships-international-labor-mobility','https://www.openphilanthropy.org/focus/us-policy/immigration-policy',NULL,NULL,'Zachary Robinson|Alexander Berger',NULL,NULL,NULL,NULL,
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant "to support work to enhance international labor mobility. LaMP aims to ensure workers can access employment opportunities abroad. It focuses on connecting governments, employers, researchers, and advocates to bridge gaps in international labor markets, and creating and curating resources to design and implement mobility partnerships."',
  /* intended_funding_timeframe_in_months */ 12,
  /* donor_donee_reason */ 'Open Philanthropy had provided the original grant https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-partnerships (2019-03) to incubate the organization. This is a renewal of that grant and also an exit grant.',
  /* donor_amount_reason */ 'The amount was chosen to provide a year of operating support, which is a typical amount for an exit grant.',
  /* donor_timing_reason */ 'The grant is made at around the end of the timeframe of the previous grant (the incubation grant) https://www.openphilanthropy.org/focus/us-policy/immigration-policy/center-global-development-labor-mobility-partnerships (2019-03).',
  /* donor_next_donation_thoughts */ 'This is an exit grant; there are no plans for followup grants.',
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

/* Other grants */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, predictions) values
  ('Open Philanthropy','New York University',30000,'2015-08-01','month','donation log','Migration policy/labor mobility/RCT','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/new-york-university-support-labor-mobility-rct','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grantee represented by Suresh Naidu and Yaw Nyarko; grant references cause page https://www.openphilanthropy.org/research/cause-reports/labor-mobility',NULL,NULL,'2015-09-23', 'day', 'https://groups.google.com/a/openphilanthropy.org/forum/#!topic/newly.published/_m_jhh_KTko',NULL),
  ('Open Philanthropy','U.S. Association for International Migration',1310483,'2014-07-01','month','donation log','Migration policy/Haiti/US agricultural migration','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/usaim-seasonal-migration-haiti','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant first published in August 2014; updated with progress report. Grantee was USAIM but project was carried out by it along with International Organization for Migration (IOM). Grant was not repeated next year, but a new grant was made to Protect the People for a similar purpose. On November 1, 2018, the grant amount on the website was reduced from the original of $1,490,505 to an updated value $1,310,483, but no explanation was added',NULL, NULL, NULL, NULL, NULL,NULL),
  ('Open Philanthropy','MoveOn.org Civic Action',375000,'2015-10-01','month','donation log','Migration policy','https://www.openphilanthropy.org/focus/us-policy/immigration-policy/moveon-civic-action-syrian-refugee-advocacy','https://www.openphilanthropy.org/focus/us-policy/immigration-policy','Grant to support work on Syrian refugee resettlement in the United States. Grant recommended for Cari Tuna to make personally; grantee is a 501(c)(4) organization',NULL,'Alexander Berger','2018-06-09','day',NULL,NULL),
