insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('FTX Future Fund','Effective Ideas Blog Prize',900000,'2022-01-01','month','donation log','Effective altruism','https://ftxfuturefund.org/our-grants/?_funding_stream=ad-hoc','https://ftxfuturefund.org/area-of-interest/effective-altruism/',NULL,'Longview Philanthropy',NULL,NULL,NULL,NULL,
  /* donation_process */ 'This grant is part of staff-led grantmaking by FTX Future Fund.  https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Staff_led_grantmaking_in_more_detail says: "Unlike the open call and regranting, these grants and investments are not a test of a particular potentially highly scalable funding model. These are projects we funded because we became aware of them and thought they were good ideas." This particular grant is co-recommended by LongView Philanthropy and the funding is to be administered by Longview Media.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to "support prizes for outstanding writing which encourages a broader public conversation around effective altruism and longtermism."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('FTX Future Fund','Lightcone Infrastructure',2000000,'2022-02-01','month','donation log','Effective altruism|AI safety','https://ftxfuturefund.org/our-grants/?_funding_stream=ad-hoc','https://ftxfuturefund.org/area-of-interest/effective-altruism/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_process */ 'This grant is part of staff-led grantmaking by FTX Future Fund. https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Staff_led_grantmaking_in_more_detail says: "Unlike the open call and regranting, these grants and investments are not a test of a particular potentially highly scalable funding model. These are projects we funded because we became aware of them and thought they were good ideas."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant to "support Lightcone’s ongoing projects including running the LessWrong forum, hosting conferences and events, and maintaining an office space for Effective Altruist organizations."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('FTX Future Fund','Centre for Effective Altruism',13940000,'2022-03-01','month','donation log','Effective altruism','https://ftxfuturefund.org/our-grants/?_funding_stream=ad-hoc','https://ftxfuturefund.org/area-of-interest/effective-altruism/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_process */ 'This grant is part of staff-led grantmaking by FTX Future Fund. https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Staff_led_grantmaking_in_more_detail says: "Unlike the open call and regranting, these grants and investments are not a test of a particular potentially highly scalable funding model. These are projects we funded because we became aware of them and thought they were good ideas."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'Grant for "general support for their activities, including running conferences, supporting student groups, and maintaining online resources."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);
