insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('FTX Future Fund','Sherlock Biosciences',2000000,'2022-02-01','month','donation log','Biosecurity and pandemic preparedness','https://ftxfuturefund.org/our-grants/?_funding_stream=ad-hoc','https://ftxfuturefund.org/area-of-interest/biorisk-and-recovery-from-catastrophe/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_process */ 'This investment is part of staff-led grantmaking by FTX Future Fund. https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Staff_led_grantmaking_in_more_detail says: "Unlike the open call and regranting, these grants and investments are not a test of a particular potentially highly scalable funding model. These are projects we funded because we became aware of them and thought they were good ideas."',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to "support the development of universal CRISPR-based diagnostics, including paper-based diagnostics that can be used in developing-country settings without electricity."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('FTX Future Fund','HelixNano',10000000,'2022-01-01','month','donation log','Biosecurity and pandemic preparedness/COVID-19/COVID-19 vaccine','https://ftxfuturefund.org/our-grants/?_funding_stream=ad-hoc','https://ftxfuturefund.org/area-of-interest/biorisk-and-recovery-from-catastrophe/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_process */ 'This investment is part of staff-led grantmaking by FTX Future Fund. https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Staff_led_grantmaking_in_more_detail says: "Unlike the open call and regranting, these grants and investments are not a test of a particular potentially highly scalable funding model. These are projects we funded because we became aware of them and thought they were good ideas."',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to "support Helix Nano running preclinical and Phase 1 trials of a pan-variant Covid-19 vaccine."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);
