insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, donation_earmark, influencer, donation_announcement_date, donation_announcement_date_precision, donation_announcement_url, predictions, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('FTX Future Fund','Manifold Markets',1000000,'2022-03-01','month','donation log','Epistemic institutions/forecasting','https://ftxfuturefund.org/our-regrants/','https://ftxfuturefund.org/area-of-interest/epistemic-institutions/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_prcess */ 'The grant is made as part of the Future Fund''s regranting program. See https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Regranting_program_in_more_detail for more detail on the regranting program.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to "support Manifold Markets in building a play-money prediction market platform. The platform is also experimenting with impact certificates and charity prediction markets."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The Future Fund makes another grant to Manifold Markets of $500,000 for a related purpose at about the same time; this other grant is a result of the open call.'),

  ('FTX Future Fund','Legal Priorities Project',137500,'2022-05-01','month','donation log','Epistemic institutions','https://ftxfuturefund.org/our-regrants/','https://ftxfuturefund.org/area-of-interest/epistemic-institutions/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_prcess */ 'The grant is made as part of the Future Fund''s regranting program. See https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Regranting_program_in_more_detail for more detail on the regranting program.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to "support an essay contest on “Accounting for Existential Risks in US Cost-Benefit Analysis,” with the aim of contributing to the revision of OMB Circular-A4, a document which guides US government cost-benefit analysis. The Legal Priorities Project is administering the contest."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The Future Fund makes two other grants to support Legal Priorities Project around the same time, but these grants are staff-led.'),

  ('FTX Future Fund','Quantified Uncertainty Research Institute',200000,'2022-05-01','month','donation log','Epistemic institutions','https://ftxfuturefund.org/our-regrants/','https://ftxfuturefund.org/area-of-interest/epistemic-institutions/',NULL,NULL,NULL,NULL,NULL,NULL,
  /* donation_prcess */ 'The grant is made as part of the Future Fund''s regranting program. See https://forum.effectivealtruism.org/posts/paMYXYFYbbjpdjgbt/future-fund-june-2022-update#Regranting_program_in_more_detail for more detail on the regranting program.',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Grant to "support QURI to develop a programming language called "Squiggle" as a tool for probabilistic estimation."',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant description says: "The hope is this will be a useful tool for forecasting and fermi estimates."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);
