insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', '80,000 Hours', 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Beckstead is a board member of Centre for Effective Altruism, the parent organization of 80,000 Hours.', 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Centre for Effective Altruism) ↔ (80,000 Hours)')
    ,('Open Philanthropy', '80,000 Hours', 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', NULL, NULL, 'Professional', 'A number of professional ties.', NULL)
    ,('Open Philanthropy', '80,000 Hours', 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', NULL, NULL, 'Social', 'A number of social ties.', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Accountable Justice Project', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/accountable-justice-project-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/accountable-justice-project-general-support', '2016-04-01', 'Chloe Cockburn', 'Rob Smith', 'Academic', 'Attended the same law school together, but had not maintained contact prior to grant.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'American Civil Liberties Union of Northern California', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/aclu-nor-cal-prosecutorial-accountability', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/aclu-nor-cal-prosecutorial-accountability', '2017-02-01', 'Chloe Cockburn', 'Chloe Cockburn', 'Professional', 'Chloe previously worked at the national ACLU, but has no special relationship to the ACLU of Northern California.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'American Civil Liberties Union Foundation of Oregon', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/american-civil-liberties-union-foundation-oregon-prosecutorial-accountability', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/american-civil-liberties-union-foundation-oregon-prosecutorial-accountability', '2017-03-01', 'Chloe Cockburn', 'Chloe Cockburn', 'Professional', 'Chloe previously worked at the national ACLU.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'California Renters Legal Advocacy and Education Fund', 'https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support', '2016-06-01', 'Alexander Berger', NULL, 'Personal', 'Alexander has been somewhat involved with SF Bay Area Renters’ Federation in a personal capacity.', 'Alexander Berger (Open Philanthropy Project) ↔ Alexander Berger (SF Bay Area Renters’ Federation) ↔ (California Renters Legal Advocacy and Education Fund)')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Luke Muehlhauser', 'Julia Galef', 'Romantic relationship', 'Luke and Julia both previously worked at MIRI. Luke recused himself from this grant investigation.', NULL)
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Luke Muehlhauser', 'Julia Galef', 'Professional', 'Julia Galef previously worked at MIRI when CFAR was still part of MIRI.', '(Open Philanthropy Project) ↔ Julia Galef (Machine Intelligence Research Institute) ↔ Julia Galef (Center for Applied Rationality)')
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', NULL, 'Anna Salamon', 'Professional', 'Anna Salamon previously worked at MIRI.', '(Open Philanthropy Project) ↔ Anna Salamon (Machine Intelligence Research Institute) ↔ Anna Salamon (Center for Applied Rationality)')
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Carl Shulman', 'Anna Salamon', 'Marriage', NULL, 'Carl Shulman consults for Open Philanthropy, previously worked for MIRI, and is a Research Fellow at Future of Humanity Institute (FHI). Nick Beckstead (Open Philanthropy’s Program Officer for Scientific Research) and Daniel Dewey (Open Philanthropy’s Program Officer for Potential Risks from Advanced Artificial Intelligence) are both former Research Fellows for FHI.')
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', NULL, NULL, 'Personal', 'A number of GiveWell or Open Philanthropy Project employees have attended CFAR workshops.', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Jacob Steinhardt', 'Jacob Steinhardt', 'Professional', 'Jacob is a technical advisor to Open Philanthropy’s program on potential risks from advanced artificial intelligence and one of the key people involved in running SPARC.', NULL)
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy’s program on potential risks from advanced artificial intelligence and one of the key people involved in running SPARC.', NULL)
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Nick Beckstead', NULL, 'Friendship', 'Friendships with some SPARC instructors.', NULL)
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Holden Karnofsky', NULL, 'Friendship', 'Friendships with some SPARC instructors.', NULL)
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Luke Muehlhauser', NULL, 'Professional', 'Luke was previously Executive Director of Machine Intelligence Research Institute and approved funding from MIRI to SPARC multiple times (including the seed funding). Luke was not involved in the decision-making of the grant.', 'Luke Muehlhauser (Open Philanthropy Project) ↔ Luke Muehlhauser (Machine Intelligence Research Institute) ↔ (Center for Applied Rationality)')
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Luke Muehlhauser', 'Julia Galef', 'Romantic relationship', 'Luke was not involved in the decision-making of the grant.', NULL)
    ,('Open Philanthropy', 'Center for Applied Rationality', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'https://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Helen Toner', 'Paul Christiano', 'Personal', 'Lives in a shared house.', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Johns Hopkins Center for Health Security', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic', '2017-01-01', 'Jaime Yassif', 'Tom Inglesby', 'Professional', 'Tom Inglesby was one of Jaime Yassif’s references when applying for her job at Open Philanthropy.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'Future of Humanity Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Nick previously worked as a Research Fellow at FHI.', NULL)
    ,('Open Philanthropy', 'Future of Humanity Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Daniel Dewey', NULL, 'Professional', 'Daniel previously worked as a Research Fellow at FHI.', NULL)
    ,('Open Philanthropy', 'Future of Humanity Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Nick is an FHI Research Associate (unpaid).', NULL)
    ,('Open Philanthropy', 'Future of Humanity Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', 'Toby Ord', 'Professional', 'Nick is a trustee of the Center for Effective Altruism along with Toby Ord (who is a Research Fellow at FHI).', 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Center for Effective Altruism) ↔ Toby Ord (Center for Effective Altruism) ↔ Toby Ord (Future of Humanity Institute)')
    ,('Open Philanthropy', 'Future of Humanity Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', 'Niel Bowerman', 'Professional', 'Nick is a trustee of the Center for Effective Altruism (CEA); Niel Bowerman is FHI’s Assistant Director and used to work for CEA.', 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Center for Effective Altruism) ↔ Niel Bowerman (Center for Effective Altruism) ↔ Niel Bowerman (Future of Humanity Institute)')
    ,('Open Philanthropy', 'Future of Humanity Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Carl Shulman', 'Carl Shulman', 'Professional', 'Carl consults for Open Philanthropy and is a Research Associate (paid) at FHI. Carl is friends with Nick Beckstead. Carl also previously worked with Open Philanthropy Research Analyst Luke Muehlhauser while at the Machine Intelligence Research Institute. Carl and Luke were not involved in the decision-making of this grant.', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship, cardinality) values
    ('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', 'Daniel Dewey', 'Friendship', NULL, NULL, 1)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', 'Daniel Dewey', 'Professional', 'The two are former coworkers.', NULL, 1)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Personal', 'This applicant to the RFP is a long-time donor and fan of GiveWell.', NULL, 1)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', NULL, 'Professional', 'Five applicants are or have been associated with Future of Humanity Institute as employees or Research Associates. Nick Beckstead was an FHI employee and is now an FHI Research Associate and has social ties with many of FHI’s staff.', 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Future of Humanity Institute) ↔ Applicants (Future of Humanity Institute) ↔ Applicants (Future of Life Institute)', 5)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Helen Toner', NULL, 'Hybrid', 'Two proposals were submitted on behalf of Machine Intelligence Research Institute, where Nate Soares is Executive Director. Nate Soares lives in a shared house with Helen Toner.', 'Helen Toner (Open Philanthropy Project) ↔ Nate Soares (Machine Intelligence Research Institute) ↔ Proposals (Machine Intelligence Research Institute) ↔ Proposals (Future of Life Institute)', 2)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Ben Hoffman', NULL, 'Hybrid', 'Two proposals were submitted on behalf of Machine Intelligence Research Institute, where Nate Soares is Executive Director. Nate Soares lives in a shared house with Ben Hoffman.', 'Ben Hoffman (Open Philanthropy Project) ↔ Nate Soares (Machine Intelligence Research Institute) ↔ Proposals (Machine Intelligence Research Institute) ↔ Proposals (Future of Life Institute)', 2)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Hybrid', 'Two proposals were submitted on behalf of Machine Intelligence Research Institute, where Nate Soares is Executive Director. Nate Soares has social ties to several GiveWell staff.', '(Open Philanthropy Project) ↔ Nate Soares (Machine Intelligence Research Institute) ↔ Proposals (Machine Intelligence Research Institute) ↔ Proposals (Future of Life Institute)', 2)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Luke Muehlhauser', NULL, 'Professional', 'Two proposals were submitted on behalf of Machine Intelligence Research Institute, where Luke Muehlhauser was Executive Director.', 'Luke Muehlhauser (Open Philanthropy Project) ↔ Luke Muehlhauser (Machine Intelligence Research Institute) ↔ Proposals (Machine Intelligence Research Institute) ↔ Proposals (Future of Life Institute)', 2)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', NULL, 'Professional', 'Two proposals were submitted on behalf of the Centre for Effective Altruism where Nick Beckstead is a trustee.', 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Centre for Effective Altruism) ↔ Proposals (Centre for Effective Altruism) ↔ Proposals (Future of Life Institute)', 2)
    ,('Open Philanthropy', 'Future of Life Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Hybrid', 'Minor cases where proposals are submitted by people with social ties to GiveWell staff.', '(Open Philanthropy Project) ↔ Proposals () ↔ Proposals (Future of Life Institute)', 1)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'George Mason University', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios', '2016-06-01', 'Nick Beckstead', 'Robin Hanson', 'Professional', NULL, 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Future of Humanity Institute) ↔ Robin Hanson (Future of Humanity Institute) ↔ Robin Hanson (George Mason University)')
    ,('Open Philanthropy', 'George Mason University', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios', '2016-06-01', 'Daniel Dewey', 'Robin Hanson', 'Professional', NULL, 'Daniel Dewey (Open Philanthropy Project) ↔ Daniel Dewey (Future of Humanity Institute) ↔ Robin Hanson (Future of Humanity Institute) ↔ Robin Hanson (George Mason University)')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Global Animal Partnership', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support', '2016-04-01', 'Lewis Bollard', 'Wayne Pacelle', 'Friendship', NULL)
    ,('Open Philanthropy', 'Global Animal Partnership', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support', '2016-04-01', 'Lewis Bollard', 'Wayne Pacelle', 'Professional', 'Lewis previously worked for Wayne.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Harvard University Program in Criminal Justice Policy and Management', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/harvard-university-program-criminal-justice-policy-and-management#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/harvard-university-program-criminal-justice-policy-and-management', '2016-07-01', 'Chloe Cockburn', 'Vincent Schiraldi', 'Professional', 'Regular contact as colleagues in the field.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Harvard University', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/miscellaneous/harvard-university-solar-geoengineering-research-program#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/miscellaneous/harvard-university-solar-geoengineering-research-program', '2016-12-01', 'Claire Zabel', 'David Keith', 'Professional', 'Intermittent collaboration since 2014, including Claire’s employment at David Keith’s lab and collaboration on a small research project.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Humane Society International', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-east-asian-and-oie-projects', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-east-asian-and-oie-projects', '2017-03-01', 'Lewis Bollard', 'Lewis Bollard', 'Professional', 'Lewis previously worked for the Humane Society of the United States.')

    ,('Open Philanthropy', 'Humane Society International', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-india-animal-welfare-reform', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-india-animal-welfare-reform', '2017-05-01', 'Lewis Bollard', 'Lewis Bollard', 'Professional', 'Lewis previously worked for the Humane Society of the United States.')

    ,('Open Philanthropy', 'The Humane Society of the United States', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns', '2016-02-01', 'Lewis Bollard', NULL, 'Professional', 'Lewis previously worked for the Humane Society of the United States.')
    ,('Open Philanthropy', 'The Humane Society of the United States', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns', '2016-02-01', 'Lewis Bollard', 'Paul Shapiro', 'Friendship', 'The two are close friends.')
    ,('Open Philanthropy', 'The Humane Society of the United States', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns', '2016-02-01', 'Lewis Bollard', 'Josh Balk', 'Friendship', 'The two are close friends.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'International Genetically Engineered Machine Foundation', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/igem-synthetic-biology-safety-and-security#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/igem-synthetic-biology-safety-and-security', '2016-05-01', 'Kevin Esvelt', 'Kevin Esvelt', 'Professional', 'Advisor to both organizations.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy, was a MIRI Research Associate (unpaid), and has collaborated with MIRI.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Paul Christiano', 'Nate Soares', 'Personal', 'The two live in the same house.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Paul Christiano', NULL, 'Professional', 'Paul helps to run SPARC, a summer camp for which MIRI provided early funding.', 'Paul Christiano (Open Philanthropy Project) ↔ Paul Christiano (Center for Applied Rationality) ↔ Paul Christiano (Machine Intelligence Research Institute)')
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Jacob Steinhardt', 'Jacob Steinhardt', 'Professional', 'Jacob is a technical advisor to Open Philanthropy and received financial support from MIRI for a reading group he ran on Nick Bostrom’s book.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Jacob Steinhardt', NULL, 'Professional', 'Jacob Steinhardt helps to run SPARC, a summer camp for which MIRI provided early funding.', 'Jacob Steinhardt (Open Philanthropy Project) ↔ Jacob Steinhardt (Center for Applied Rationality) ↔ Jacob Steinhardt (Machine Intelligence Research Institute)')
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Nick Beckstead', NULL, 'Friendship', 'Nick is friends with a number of former MIRI staff members.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Daniel Dewey', 'Daniel Dewey', 'Professional', 'Daniel is Program Officer for Potential Risks from Advanced Artificial Intelligence for Open Philanthropy and was a MIRI Research Associate (unpaid).', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Luke Muehlhauser', 'Luke Muehlhauser', 'Professional', 'Luke is a Research Analyst at Open Philanthropy and was Executive Director of MIRI. Luke was not involved in the grant investigation.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Helen Toner', 'Nate Soares', 'Personal', 'The two live in the same house. Helen was not involved in the grant investigation but reviewed the grant writeup.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', NULL, 'Nate Soares', 'Romantic relationship', 'Nate is dating a staff member at Open Philanthropy who was not involved in the grant investigation.', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', NULL, NULL, 'Romantic relationship', 'Open Philanthropy quotes MIRI as stating that "at least one other MIRI employee [i.e. other than Nate Soares] was dating at least one GiveWell/Open Phil employee for part of the year".', NULL)
    ,('Open Philanthropy', 'Machine Intelligence Research Institute', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', NULL, NULL, 'Friendship', 'Open Philanthropy states "There are likely other friendships between staff members at the Open Philanthropy Project, particularly those who are members of the effective altruism community, and current or former staff at MIRI."', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'MIT Synthetic Neurobiology Group', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Dario Amodei', 'Ed Boyden', 'Professional', '"Dario’s relationship with Professor Boyden was relatively arm’s-length, based on their mutual involvement in neuroscience research".', NULL)
    ,('Open Philanthropy', 'MIT Synthetic Neurobiology Group', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Dario Amodei', 'Adam Marblestone', 'Professional', NULL, NULL)
    ,('Open Philanthropy', 'MIT Synthetic Neurobiology Group', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Adam Marblestone', 'Adam Marblestone', 'Professional', 'Adam Marblestone "consulted part-time as a junior scientific advisor for independent evaluations by GiveWell in 2014" and is director of Boyden’s group. However, he recused himself from active work for GiveWell and Open Philanthropy during investigation for this grant.', NULL)
    ,('Open Philanthropy', 'MIT Synthetic Neurobiology Group', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Holden Karnofsky', NULL, 'Hybrid', 'Holden was a key decision-maker for this gift.', 'Holden Karnofsky (Open Philanthropy Project) ↔ Dario Amodei () ↔ {Ed Boyden, Adam Marblestone} (MIT Synthetic Neurobiology Group)')
    ,('Open Philanthropy', 'MIT Synthetic Neurobiology Group', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Holden Karnofsky', NULL, 'Hybrid', 'Holden was a key decision-maker for this gift.', 'Holden Karnofsky (Open Philanthropy Project) ↔ Daniela Amodei ↔ Dario Amodei () ↔ {Ed Boyden, Adam Marblestone} (MIT Synthetic Neurobiology Group)')
    ,('Open Philanthropy', 'MIT Synthetic Neurobiology Group', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Nick Beckstead', NULL, 'Hybrid', 'Nick lives in the same house as Dario and Holden. Nick played a major role in this investigation.', 'Nick Beckstead (Open Philanthropy Project) ↔ Dario Amodei () ↔ {Ed Boyden, Adam Marblestone} (MIT Synthetic Neurobiology Group)')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Mila', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research', '2017-07-01', 'Chris Olah', 'Yoshua Bengio', 'Friendship', NULL)
    ,('Open Philanthropy', 'Mila', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research', '2017-07-01', 'Daniel Dewey', 'David Krueger', 'Friendship', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy', 'OpenAI', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Dario Amodei', 'Dario Amodei', 'Professional', 'Dario is a technical advisor to Open Philanthropy and a researcher at OpenAI.', NULL)
    ,('Open Philanthropy', 'OpenAI', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy and a researcher at OpenAI.', NULL)
    ,('Open Philanthropy', 'OpenAI', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Holden Karnofsky', 'Dario Amodei', 'Personal', 'The two live in the same house.', NULL)
    ,('Open Philanthropy', 'OpenAI', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Holden Karnofsky', 'Paul Christiano', 'Personal', 'The two live in the same house.', NULL)
    ,('Open Philanthropy', 'OpenAI', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Holden Karnofsky', 'Dario Amodei', 'Hybrid', 'Holden is engaged to Dario’s sister.', 'Holden Karnofsky (Open Philanthropy Project) ↔ Daniela Amodei () ↔ Dario Amodei (OpenAI)')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Target Malaria', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support', '2017-05-01', 'Kevin Esvelt', NULL, 'Professional', 'Kevin works on gene drives and brought the field to Open Philanthropy’s attention, but will not work with Target Malaria and does not stand to benefit from the grant.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Vera Institute of Justice', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice', '2016-02-01', 'Chloe Cockburn', 'Chloe Cockburn', 'Professional', 'Chloe worked in a fellowship position at the Vera Institute.')
    ,('Open Philanthropy', 'Vera Institute of Justice', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice#Relationship_disclosures', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice', '2016-02-01', 'Chloe Cockburn', 'Danielle Sered', 'Professional', 'Chloe knows Danielle from her time at the Vera Institute.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Vera Institute of Justice', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', '2016-07-01', 'Chloe Cockburn', 'Chloe Cockburn', 'Professional', 'Chloe worked in a fellowship position at the Vera Institute.')
    ,('Open Philanthropy', 'Vera Institute of Justice', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', 'https://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', '2016-07-01', 'Chloe Cockburn', 'Jon Wool', 'Professional', 'Chloe worked closely with Jon Wool while she was at the Vera Institute.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', NULL, 'Personal', 'Alexander donated a kidney and publicly argued for incentives for kidney donors in 2011.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', NULL, 'Personal', 'Alexander has financially supported the organization.')

    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Thomas Kelly', 'Professional', 'Alexander informally advised Thomas and Josh.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Josh Morrison', 'Professional', 'Alexander informally advised Thomas and Josh.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Thomas Kelly', 'Professional', 'Howie informally advised Thomas and Josh.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Josh Morrison', 'Professional', 'Howie informally advised Thomas and Josh.')

    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Thomas Kelly', 'Social', 'Social relationship based on informal advisory relationship.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Josh Morrison', 'Social', 'Social relationship based on informal advisory relationship. Josh has stayed at Alexander’s house while visiting San Francisco.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Thomas Kelly', 'Social', 'Social relationship based on informal advisory relationship.')
    ,('Open Philanthropy', 'Waitlist Zero', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'https://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Josh Morrison', 'Social', 'Social relationship based on informal advisory relationship.')
;
