insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', '80,000 Hours', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Beckstead is a board member of Centre for Effective Altruism, the parent organization of 80,000 Hours.')
    ,('Open Philanthropy Project', '80,000 Hours', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', NULL, NULL, 'Professional', 'A number of professional ties.')
    ,('Open Philanthropy Project', '80,000 Hours', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', NULL, NULL, 'Social', 'A number of social ties.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Accountable Justice Project', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/accountable-justice-project-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/accountable-justice-project-general-support', '2016-04-01', 'Chloe Cockburn', 'Rob Smith', 'Academic', 'Attended the same law school together, but had not maintained contact prior to grant.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'American Civil Liberties Union of Northern California', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/aclu-nor-cal-prosecutorial-accountability', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/aclu-nor-cal-prosecutorial-accountability', '2017-02-01', 'Chloe Cockburn', NULL, 'Professional', 'Chloe previously worked at the national ACLU, but has no special relationship to the ACLU of Northern California.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'American Civil Liberties Union Foundation of Oregon', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/american-civil-liberties-union-foundation-oregon-prosecutorial-accountability', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/american-civil-liberties-union-foundation-oregon-prosecutorial-accountability', '2017-03-01', 'Chloe Cockburn', NULL, 'Professional', 'Chloe previously worked at the national ACLU.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'California Renters Legal Advocacy and Education Fund', 'http://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support', '2016-06-01', 'Alexander Berger', NULL, 'Personal', 'Alexander has been somewhat involved with SF Bay Area Renters’ Federation in a personal capacity.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Luke Muehlhauser', 'Julia Galef', 'Romantic relationship', NULL)
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Carl Shulman', 'Anna Salamon', 'Marriage', NULL)
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', NULL, NULL, 'Personal', 'A number of GiveWell or Open Philanthropy Project employees have attended CFAR workshops.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Jacob Steinhardt', 'Jacob Steinhardt', 'Professional', 'Jacob is a technical advisor to Open Philanthropy''s program on potential risks from advanced artificial intelligence and one of the key people involved in running SPARC.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy''s program on potential risks from advanced artificial intelligence and one of the key people involved in running SPARC.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Nick Beckstead', NULL, 'Friendship', 'Friendships with some SPARC instructors.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Holden Karnofsky', NULL, 'Friendship', 'Friendships with some SPARC instructors.')
    -- "Luke Muehlhauser (an Open Philanthropy Research Analyst) was previously Executive Director of the Machine Intelligence Research Institute (MIRI), and during that time he approved funding from MIRI to SPARC multiple times, including the program’s seed funding."
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Luke Muehlhauser', 'Julia Galef', 'Romantic relationship', 'Luke was not involved in the decision-making of the grant.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Helen Toner', 'Paul Christiano', 'Personal', 'Lives in a shared house.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Johns Hopkins Center for Health Security', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic', '2017-01-01', 'Jaime Yassif', 'Tom Inglesby', 'Professional', 'Lives in a shared house.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Nick previously worked as a Research Fellow at FHI.')
    ,('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Daniel Dewey', NULL, 'Professional', 'Daniel previously worked as a Research Fellow at FHI.')
    ,('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Nick is an FHI Research Associate (unpaid).')
    -- Nick (Open Phil) <-> CEA <-> Toby Ord (FHI)
    -- Nick (Open Phil) <-> CEA <-> Niel Bowerman (FHI)
    ,('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Carl Shulman', 'Carl Shulman', 'Professional', 'Carl consults for Open Philanthropy and is a Research Associate (paid) at FHI.')
    -- Luke <-> MIRI <-> FHI
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', 'Daniel Dewey', 'Friendship', NULL)
    ,('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', 'Daniel Dewey', 'Professional', 'The two are former coworkers.')
    ,('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Personal', 'This applicant to the RFP is a long-time donor and fan of GiveWell.')
    ,('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Personal', 'This applicant to the RFP is a long-time donor and fan of GiveWell.')
    -- TODO there's more here
;

-- insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    -- Nick <-> FHI <-> Hanson
    -- Daniel <-> FHI <-> Hanson
    -- ('Open Philanthropy Project', 'George Mason University', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios', '2016-06-01', 'Nick Beckstead', NULL, 'Personal', 'This applicant to the RFP is a long-time donor and fan of GiveWell.')
-- ;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Global Animal Partnership', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support', '2016-04-01', 'Lewis Bollard', 'Wayne Pacelle', 'Friendship', NULL)
    ,('Open Philanthropy Project', 'Global Animal Partnership', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support', '2016-04-01', 'Lewis Bollard', 'Wayne Pacelle', 'Professional', 'Lewis previously worked for Wayne.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Harvard University', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/harvard-university-program-criminal-justice-policy-and-management#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/harvard-university-program-criminal-justice-policy-and-management', '2016-07-01', 'Chloe Cockburn', 'Vincent Schiraldi', 'Professional', 'Regular contact as colleagues in the field.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Harvard University', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/miscellaneous/harvard-university-solar-geoengineering-research-program#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/miscellaneous/harvard-university-solar-geoengineering-research-program', '2016-12-01', 'Claire Zabel', 'David Keith', 'Professional', 'Intermittent collaboration since 2014, including Claire''s employment at David Keith''s lab and collaboration on a small research project.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Humane Society International', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-east-asian-and-oie-projects', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-east-asian-and-oie-projects', '2017-03-01', 'Lewis Bollard', NULL, 'Professional', 'Lewis previously worked for the Humane Society of the United States.')
;
