-- Each chain in the relationship is of the form:
--     A (B) ↔ C (D)
-- Where A and C are individuals and B and D are organizations. The chain means
-- that a relationship extends between B and D because of the relationship
-- between A and C. This can happen in one of the following ways:
-- 1. A=C. This means that the same individual is or was part of both
--    organizations.
-- 2. B=D. This means that A and C have a relationship by virtue of being part
--    of the same organization.
-- 3. A has a relationship with C for some other reason than merely being part
--    of the same organization.
-- 4. B and D are organizations that are close for some reason other than a
--    relationship between individuals, or because there are many relationships
--    between individuals. For instance, one organization could be the parent
--    of the other.
-- When full_relationship is NULL, it is the trivial relationship:
--     donor_side_name (donor) ↔ donee_side_name (donee)

-- Below, "POLGTO" means "path of length greater than one". It means a
-- disclosure entry should be added in place of the comment, but because the
-- existing relationship is a path of length greater than one (which we haven't
-- decided how to deal with), only a comment is added for now.

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy Project', '80,000 Hours', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Beckstead is a board member of Centre for Effective Altruism, the parent organization of 80,000 Hours.', 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Centre for Effective Altruism) ↔ (80,000 Hours)')
    ,('Open Philanthropy Project', '80,000 Hours', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', NULL, NULL, 'Professional', 'A number of professional ties.', NULL)
    ,('Open Philanthropy Project', '80,000 Hours', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/80000-hours-general-support', '2017-03-01', NULL, NULL, 'Social', 'A number of social ties.', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Accountable Justice Project', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/accountable-justice-project-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/accountable-justice-project-general-support', '2016-04-01', 'Chloe Cockburn', 'Rob Smith', 'Academic', 'Attended the same law school together, but had not maintained contact prior to grant.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'American Civil Liberties Union of Northern California', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/aclu-nor-cal-prosecutorial-accountability', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/aclu-nor-cal-prosecutorial-accountability', '2017-02-01', 'Chloe Cockburn', NULL, 'Professional', 'Chloe previously worked at the national ACLU, but has no special relationship to the ACLU of Northern California.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'American Civil Liberties Union Foundation of Oregon', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/american-civil-liberties-union-foundation-oregon-prosecutorial-accountability', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/american-civil-liberties-union-foundation-oregon-prosecutorial-accountability', '2017-03-01', 'Chloe Cockburn', NULL, 'Professional', 'Chloe previously worked at the national ACLU.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'California Renters Legal Advocacy and Education Fund', 'http://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/land-use-reform/california-renters-legal-advocacy-and-education-fund-general-support', '2016-06-01', 'Alexander Berger', NULL, 'Personal', 'Alexander has been somewhat involved with SF Bay Area Renters’ Federation in a personal capacity.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Luke Muehlhauser', 'Julia Galef', 'Romantic relationship', NULL, NULL)
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', NULL, 'Julia Galef', 'Professional', NULL, '(Open Philanthropy Project) ↔ (Machine Intelligence Research Institute) ↔ Julia Galef (Machine Intelligence Research Institute) ↔ Julia Galef (Center for Applied Rationality)')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', NULL, 'Anna Salamon', 'Professional', NULL, '(Open Philanthropy Project) ↔ (Machine Intelligence Research Institute) ↔ Anna Salamon (Machine Intelligence Research Institute) ↔ Anna Salamon (Center for Applied Rationality)')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', 'Carl Shulman', 'Anna Salamon', 'Marriage', NULL)
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support', '2016-07-01', NULL, NULL, 'Personal', 'A number of GiveWell or Open Philanthropy Project employees have attended CFAR workshops.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Jacob Steinhardt', 'Jacob Steinhardt', 'Professional', 'Jacob is a technical advisor to Open Philanthropy''s program on potential risks from advanced artificial intelligence and one of the key people involved in running SPARC.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy''s program on potential risks from advanced artificial intelligence and one of the key people involved in running SPARC.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Nick Beckstead', NULL, 'Friendship', 'Friendships with some SPARC instructors.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Holden Karnofsky', NULL, 'Friendship', 'Friendships with some SPARC instructors.')
    -- "Luke Muehlhauser (an Open Philanthropy Research Analyst) was previously Executive Director of the Machine Intelligence Research Institute (MIRI), and during that time he approved funding from MIRI to SPARC multiple times, including the program’s seed funding."
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Luke Muehlhauser', 'Julia Galef', 'Romantic relationship', 'Luke was not involved in the decision-making of the grant.')
    ,('Open Philanthropy Project', 'Center for Applied Rationality', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc#Relationship_disclosures', 'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-sparc', '2016-05-01', 'Helen Toner', 'Paul Christiano', 'Personal', 'Lives in a shared house.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Johns Hopkins Center for Health Security', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic', '2017-01-01', 'Jaime Yassif', 'Tom Inglesby', 'Professional', 'Lives in a shared house.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Nick previously worked as a Research Fellow at FHI.')
    ,('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Daniel Dewey', NULL, 'Professional', 'Daniel previously worked as a Research Fellow at FHI.')
    ,('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Nick Beckstead', NULL, 'Professional', 'Nick is an FHI Research Associate (unpaid).')
    -- POLGTO: Nick (Open Phil) <-> CEA <-> Toby Ord (FHI)
    -- POLGTO: Nick (Open Phil) <-> CEA <-> Niel Bowerman (FHI)
    ,('Open Philanthropy Project', 'Future of Humanity Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-humanity-institute-general-support', '2017-03-01', 'Carl Shulman', 'Carl Shulman', 'Professional', 'Carl consults for Open Philanthropy and is a Research Associate (paid) at FHI.')
    -- POLGTO: Luke <-> MIRI <-> FHI
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', 'Daniel Dewey', 'Friendship', NULL)
    ,('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', 'Nick Beckstead', 'Daniel Dewey', 'Professional', 'The two are former coworkers.')
    ,('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Personal', 'This applicant to the RFP is a long-time donor and fan of GiveWell.')
    ,('Open Philanthropy Project', 'Future of Life Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction', '2015-08-01', NULL, NULL, 'Personal', 'This applicant to the RFP is a long-time donor and fan of GiveWell.')
    -- POLGTO: Five applicants (FHI) <-> Nick Beckstead (FHI) <-> Nick Beckstead (FLI) <-> Nick Beckstead (Open Phil)
    -- POLGTO: Nick (Open Phil) <-> Nick (CEA) <-> Two proposals (CEA) <-> Two proposals (FLI)
    -- POLGTO: Helen (Open Phil) <-[same house]-> Nate (MIRI) <-> Two proposals (MIRI) <-> Two proposals (FLI)
    -- POLGTO: Ben Hoffman (Open Phil) <-[same house]-> Nate (MIRI) <-> Two proposals (MIRI) <-> Two proposals (FLI)
    -- POLGTO: Luke (Open Phil) <-> Luke (MIRI) <-> Two proposals (MIRI) <-> Two proposals (FLI)
    -- POLGTO: Proposals (Y) <-> X (Y) <-> X <-> Z (Open Phil)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes, full_relationship) values
    ('Open Philanthropy Project', 'George Mason University', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios', '2016-06-01', 'Nick Beckstead', 'Robin Hanson', 'Professional', NULL, 'Nick Beckstead (Open Philanthropy Project) ↔ Nick Beckstead (Future of Humanity Institute) ↔ Robin Hanson (Future of Humanity Institute)')
    ,('Open Philanthropy Project', 'George Mason University', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/george-mason-university-research-future-artificial-intelligence-scenarios', '2016-06-01', 'Daniel Dewey', 'Robin Hanson', 'Professional', NULL, 'Daniel Dewey (Open Philanthropy Project) ↔ Daniel Dewey (Future of Humanity Institute) ↔ Robin Hanson (Future of Humanity Institute)')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Global Animal Partnership', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support', '2016-04-01', 'Lewis Bollard', 'Wayne Pacelle', 'Friendship', NULL)
    ,('Open Philanthropy Project', 'Global Animal Partnership', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/global-animal-partnership-general-support', '2016-04-01', 'Lewis Bollard', 'Wayne Pacelle', 'Professional', 'Lewis previously worked for Wayne.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Harvard University', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/harvard-university-program-criminal-justice-policy-and-management#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/harvard-university-program-criminal-justice-policy-and-management', '2016-07-01', 'Chloe Cockburn', 'Vincent Schiraldi', 'Professional', 'Regular contact as colleagues in the field.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Harvard University', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/miscellaneous/harvard-university-solar-geoengineering-research-program#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/miscellaneous/harvard-university-solar-geoengineering-research-program', '2016-12-01', 'Claire Zabel', 'David Keith', 'Professional', 'Intermittent collaboration since 2014, including Claire''s employment at David Keith''s lab and collaboration on a small research project.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Humane Society International', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-east-asian-and-oie-projects', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-east-asian-and-oie-projects', '2017-03-01', 'Lewis Bollard', NULL, 'Professional', 'Lewis previously worked for the Humane Society of the United States.')

    ,('Open Philanthropy Project', 'Humane Society International', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-india-animal-welfare-reform', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-international-india-animal-welfare-reform', '2017-05-01', 'Lewis Bollard', NULL, 'Professional', 'Lewis previously worked for the Humane Society of the United States.')

    ,('Open Philanthropy Project', 'Humane Society International', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns', '2016-02-01', 'Lewis Bollard', NULL, 'Professional', 'Lewis previously worked for the Humane Society of the United States.')
    ,('Open Philanthropy Project', 'Humane Society International', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns', '2016-02-01', 'Lewis Bollard', 'Paul Shapiro', 'Friendship', 'The two are close friends.')
    ,('Open Philanthropy Project', 'Humane Society International', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/humane-society-united-states-corporate-cage-free-campaigns', '2016-02-01', 'Lewis Bollard', 'Josh Balk', 'Friendship', 'The two are close friends.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'International Genetically Engineered Machine Foundation', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/igem-synthetic-biology-safety-and-security#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/igem-synthetic-biology-safety-and-security', '2016-05-01', 'Kevin Esvelt', 'Kevin Esvelt', 'Professional', 'Advisor to both organizations.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy, was a MIRI Research Associate (unpaid), and has collaborated with MIRI.')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Paul Christiano', 'Nate Soares', 'Personal', 'The two live in the same house.')
    -- POLGTO: Paul <-> SPARC <-> MIRI
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Jacob Steinhardt', 'Jacob Steinhardt', 'Professional', 'Jacob is a technical advisor to Open Philanthropy and received financial support from MIRI for a reading group he ran on Nick Bostrom''s book.')
    -- POLGTO: Jacob <-> SPARC <-> MIRI
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Nick Beckstead', NULL, 'Friendship', 'Nick is friends with a number of former MIRI staff members.')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Daniel Dewey', 'Daniel Dewey', 'Professional', 'Daniel is Program Officer for Potential Risks from Advanced Artificial Intelligence for Open Philanthropy and was a MIRI Research Associate (unpaid).')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Luke Muehlhauser', 'Luke Muehlhauser', 'Professional', 'Luke is a Research Analyst at Open Philanthropy and was Executive Director of MIRI. Luke was not involved in the grant investigation.')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', 'Helen Toner', 'Nate Soares', 'Personal', 'The two live in the same house. Helen was not involved in the grant investigation.')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', NULL, 'Nate Soares', 'Romantic relationship', 'Nate is dating a staff member at Open Philanthropy who was not involved in the grant investigation.')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', NULL, NULL, 'Romantic relationship', 'Open Philanthropy quotes MIRI as stating that "at least one other MIRI employee [i.e. other than Nate Soares] was dating at least one GiveWell/Open Phil employee for part of the year".')
    ,('Open Philanthropy Project', 'Machine Intelligence Research Institute', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support', '2016-08-01', NULL, NULL, 'Friendship', 'Open Philanthropy states "There are likely other friendships between staff members at the Open Philanthropy Project, particularly those who are members of the effective altruism community, and current or former staff at MIRI."')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'MIT Synthetic Neurobiology Group', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Dario Amodei', 'Ed Boyden', 'Professional', '"Dario’s relationship with Professor Boyden was relatively arm’s-length, based on their mutual involvement in neuroscience research"')
    ,('Open Philanthropy Project', 'MIT Synthetic Neurobiology Group', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Dario Amodei', 'Adam Marblestone', 'Professional', NULL)
    ,('Open Philanthropy Project', 'MIT Synthetic Neurobiology Group', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/massachusetts-institute-technology-synthetic-neurobiology-group', '2016-03-01', 'Adam Marblestone', 'Adam Marblestone', 'Professional', 'Adam Marblestone "consulted part-time as a junior scientific advisor for independent evaluations by GiveWell in 2014" and is director of Boyden''s group. However, he recused himself from active work for GiveWell and Open Philanthropy during investigation for this grant.')
    -- POLGTO: Holden <-> Dario <-> Boyden
    -- POLGTO: Holden <-> Dario's sister <-> Dario <-> Boyden
    -- POLGTO: Nick Beckstead <-> Dario <-> Boyden
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Montreal Institute for Learning Algorithms', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research', '2017-07-01', 'Chris Olah', 'Yoshua Bengio', 'Friendship', NULL)
    ,('Open Philanthropy Project', 'Montreal Institute for Learning Algorithms', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/montreal-institute-learning-algorithms-ai-safety-research', '2017-07-01', 'Daniel Dewey', 'David Krueger', 'Friendship', NULL)
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'OpenAI', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Dario Amodei', 'Dario Amodei', 'Professional', 'Dario is a technical advisor to Open Philanthropy and a researcher at OpenAI.')
    ,('Open Philanthropy Project', 'OpenAI', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Paul Christiano', 'Paul Christiano', 'Professional', 'Paul is a technical advisor to Open Philanthropy and a researcher at OpenAI.')
    ,('Open Philanthropy Project', 'OpenAI', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Holden Karnofsky', 'Dario Amodei', 'Personal', 'The two live in the same house.')
    ,('Open Philanthropy Project', 'OpenAI', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support', '2017-03-01', 'Holden Karnofsky', 'Paul Christiano', 'Personal', 'The two live in the same house.')
    -- POLGTO: Holden <-> Daniela <-> Dario
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Target Malaria', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/scientific-research/miscellaneous/target-malaria-general-support', '2017-05-01', 'Kevin Esvelt', NULL, 'Professional', 'Kevin works on gene drives and brought the field to Open Philanthropy''s attention, but will not work with Target Malaria and does not stand to benefit from the grant.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Vera Institute of Justice', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice', '2016-02-01', 'Chloe Cockburn', 'Chloe Cockburn', 'Professional', 'Chloe worked in a fellowship position at the Vera Institute.')
    ,('Open Philanthropy Project', 'Vera Institute of Justice', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice#Relationship_disclosures', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-common-justice', '2016-02-01', 'Chloe Cockburn', 'Danielle Sered', 'Professional', 'Chloe knows Danielle from her time at the Vera Institute.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    ('Open Philanthropy Project', 'Vera Institute of Justice', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', '2016-07-01', 'Chloe Cockburn', 'Chloe Cockburn', 'Professional', 'Chloe worked in a fellowship position at the Vera Institute.')
    ,('Open Philanthropy Project', 'Vera Institute of Justice', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', 'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/vera-institute-justice-new-orleans-user-funded-justice-system', '2016-07-01', 'Chloe Cockburn', 'Jon Wool', 'Professional', 'Chloe worked closely with Jon Wool while she was at the Vera Institute.')
;

insert into disclosures(donor, donee, url, donation_url, donation_date, donor_side_name, donee_side_name, relationship_nature, notes) values
    -- POLGTO: Alexander <-> kidney donation <-> WLZ
    ('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', NULL, 'Personal', 'Alexander has financially supported the organization.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Thomas Kelly', 'Professional', 'Alexander informally advised Thomas and Josh.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Josh Morrison', 'Professional', 'Alexander informally advised Thomas and Josh.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Thomas Kelly', 'Professional', 'Howie informally advised Thomas and Josh.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Josh Morrison', 'Professional', 'Howie informally advised Thomas and Josh.')

    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Thomas Kelly', 'Social', 'Social relationship based on informal advisory relationship.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Alexander Berger', 'Josh Morrison', 'Social', 'Social relationship based on informal advisory relationship. Josh has stayed at Alexander''s house while visiting San Francisco.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Thomas Kelly', 'Social', 'Social relationship based on informal advisory relationship.')
    ,('Open Philanthropy Project', 'Waitlist Zero', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support#Disclosure', 'http://www.openphilanthropy.org/focus/us-policy/miscellaneous/waitlist-zero-general-support', '2015-08-01', 'Howie Lempel', 'Josh Morrison', 'Social', 'Social relationship based on informal advisory relationship.')
;
