insert into donations (donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url,
    donor_cause_area_url, notes, affected_countries,
    affected_regions) values
    ('Pineapple Fund','Watsi',1000000,'2017-12-08','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','The Water Project',1000000,'2017-12-08','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','BitGive Foundation',1000000,'2017-12-12','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Electronic Frontier Foundation',1000000,'2017-12-13','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Multidisciplinary Association for Psychedelic Studies',1000000,'2017-12-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','OpenBSD Foundation',50000,'2017-12-13','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','SENS Research Foundation',2000000,'2017-12-15','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','charity: water',1000000,'2017-12-15','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Mona Foundation',1000000,'2017-12-20','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','New Story',1000000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Internet Archive',1000000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Pencils of Promise',1000000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Greensteps',100000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','GiveDirectly',5000000,'2017-12-27','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Professional Transformation Sports Development',50000,'2018-01-01','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Quill',1000000,'2018-01-01','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Possible',1000000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Hearts and Homes for Refugees',100000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','The Focus Foundation',1000000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Erowid',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','OpenStreetMap',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Software Freedom Conservancy',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Neural Archives Foundation',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Open Medicine Foundation',1000000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Reagent Project',100000,NULL,NULL,'donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','TalkLife',50000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Wings for Conservation',250000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Wild Me',250000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Empower Work',100000,'2018-01-17','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Apache Software Foundation',1000000,'2018-01-17','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','OpenMRS',1000000,'2018-01-17','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Justice and Care',1000000,'2018-01-20','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Enthea',50000,NULL,NULL,'donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Organ Preservation Alliance',2000000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Wiki Education',500000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Indigo Project',50000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Replate',250000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
;
