insert into donations (donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url,
    donor_cause_area_url, notes, affected_countries,
    affected_regions) values
    ('Pineapple Fund','Watsi',2000000,'2017-12-08','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','The Water Project',1000000,'2017-12-08','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','BitGive Foundation',1000000,'2017-12-12','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Electronic Frontier Foundation',1000000,'2017-12-13','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Multidisciplinary Association for Psychedelic Studies',5000000,'2017-12-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','OpenBSD Foundation',50000,'2017-12-13','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','SENS Research Foundation',2000000,'2017-12-15','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','charity: water',2000000,'2017-12-15','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Mona Foundation',1000000,'2017-12-20','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','New Story',2000000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Internet Archive',2000000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Pencils of Promise',1250000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Greensteps',100000,'2017-12-23','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','GiveDirectly',5000000,'2017-12-27','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Professional Transformation Sports Development',50000,'2018-01-01','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Quill',1000000,'2018-01-01','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Possible',1000000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Hearts and Homes for Refugees',100000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','The Focus Foundation',1000000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Erowid',500000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','OpenStreetMap',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Software Freedom Conservancy',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Neural Archives Foundation',250000,'2018-01-10','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Open Medicine Foundation',5000000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Reagent Project',100000,NULL,NULL,'donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','TalkLife',50000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Wings for Conservation',250000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Wild Me',250000,'2018-01-14','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Empower Work',100000,'2018-01-17','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Apache Software Foundation',1000000,'2018-01-17','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','OpenMRS',1000000,'2018-01-17','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Justice and Care',1000000,'2018-01-20','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Enthea',50000,NULL,NULL,'donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Organ Preservation Alliance',2000000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Wiki Education',500000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Indigo Project',50000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Replate',250000,'2018-01-22','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Methuselah Foundation',1000000,'2018-01-26','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Experience Camps',500000,'2018-01-26','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Free Software Foundation',1000000,'2018-01-29','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','American Civil Liberties Union',2000000,'2018-01-30','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Women Who Tech',250000,'2018-02-02','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Blueprint at University of California, Berkeley',50000,'2018-02-04','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Canine Therapy Corps',250000,'2018-02-05','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Institute for Justice',2000000,'2018-02-07','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','TreeSisters',500000,'2018-02-07','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','human-I-T',250000,'2018-02-07','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','The Adventure Project',1000000,'2018-02-07','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Sustainable Ocean Alliance',1000000,'2018-02-08','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Many Hopes',250000,'2018-02-08','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Let''s Encrypt',250000,'2018-02-09','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Snow Lovers',50000,'2018-02-12','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','SoGal',1000000,'2018-02-13','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Tennessee River Gorge Trust',250000,'2018-02-15','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','KDE e.V.',200000,'2018-02-16','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Nuzzles & Co',1000000,'2018-02-18','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','New Incentives',250000,'2018-02-18','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Myalgic Encephalomyelitis Action Network',50000,'2018-02-20','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Council on Spiritual Practices',250000,'2018-02-27','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
    ,('Pineapple Fund','Alter Global',1000000,'2018-03-06','day','donation log','FIXME','https://pineapplefund.org/','FIXME',NULL,NULL,NULL)
;
