# Grantees entered on 2019-01-10; see http://archive.today/2019.01.11-004309/https://www.sandlerfoundation.org/grants/
insert into donations (donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, url, notes) values
    ('Sandler Foundation', 'American Asthma Foundation', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Center for American Progress', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Center for Responsible Lending', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Human Rights Center', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Learning Policy Institute', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Program for Breakthrough Biomedical Research', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'ProPublica', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Research Centers on Equitable Growth', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Sandler Asthma Basic Research Center', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Sandler Center for Drug Discovery', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'UCSF Center for Next-Gen Precision Medicine Diagnostics', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'American Civil Liberties Union', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'American Constitution Society', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Campaign Legal Center', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Center on Budget and Policy Priorities', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Civil Rights Corps', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Clinical Excellence Research Center', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Earthjustice', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Human Rights Watch', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'MDRC', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'National Center for Youth Law', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Northwest Mexico Land Conservation', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Oceana', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'PICO National Network', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Public Library of Science', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Safe Credit Cards Project', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Truman National Security Project', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Center for Biological Diversity', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'J Street Education Fund', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Johns Hopkins’ Project to Eliminate Central-Line Infections', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Sierra Club’s Beyond Coal Campaign', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'Tax Policy Center', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
    ,('Sandler Foundation', 'UCSF Sandler Neurosciences Center', NULL, '2019-01-01', 'multi-year', 'donation log', 'https://www.sandlerfoundation.org/grants/', NULL)
;
