/* 80,000 Hours */
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, goal_amount, fraction, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Survival and Flourishing Fund','80,000 Hours',280000,'2019-08-01','month','donation log','Effective altruism/movement growth/career counseling','https://survivalandflourishing.fund/','Alex Flint|Andrew Critch|Eric Rogstad','2019-08-29','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/cc4ba1e3975f4e4847272ffaf72a6ce09c19648f/_data/recommendations.tsv',880000,0.3182,
  /* donation_process */ 'Part of the founding batch of grants for the Survival and Flourishing Fund made in August 2019. The fund is partly a successor to part of the grants program of the Berkeley Existential Risk Initiative (BERI) that handled grantmaking by Jaan Tallinn; see http://existence.org/tallinn-grants-future/ As such, this 80,000 Hours grant may represent a followup to a $350,000 grant made by BERI to 80,000 Hours earlier in the year.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant may represent a followup to a $350,000 grant made by BERI to 80,000 Hours earlier in the year.',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; the Survival and Flourishing Fund is making its first round of grants in August 2019.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee in future grant rouds (such as https://survivalandflourishing.fund/sff-2019-q4-recommendations in 2019 Q4) suggest continued satisfaction with the donee.',
  /* notes */ NULL),

  ('Survival and Flourishing Fund','80,000 Hours',40000,'2019-11-01','month','donation log','Effective altruism/movement growth/career counseling','https://survivalandflourishing.fund/sff-2019-q4-recommendations','Alex Flint|Alex Zhu|Andrew Critch|Eric Rogstad|Oliver Habryka','2019-12-15','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/aa47e9860dff38e2af8d08da56a0a13389a75af4/_data/recommendations.tsv',920000,0.0435,
  /* donation_process */ 'Part of the 2019 Q4 grants based on the S-process (simulation process) that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different Recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'This represents a renewal of a larger grant made by SFF of $280,000 in its previous funding round (2019 Q3).',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s second round. SFF made a grant to 80,000 Hours in the previous round as well.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee in future grant rouds (such as https://survivalandflourishing.fund/sff-2020-h1-recommendations in 2020 H1) suggest continued satisfaction with the donee.',
  /* notes */ 'The grant round also includes a $70,000 grant from Jaan Tallinn to the same grantee (80,000 Hours).'),

  ('Jaan Tallinn','80,000 Hours',70000,'2019-11-01','month','donation log','Effective altruism/movement growth/career counseling','https://survivalandflourishing.fund/sff-2019-q4-recommendations','Alex Flint|Alex Zhu|Andrew Critch|Eric Rogstad|Oliver Habryka','2019-12-15','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/aa47e9860dff38e2af8d08da56a0a13389a75af4/_data/recommendations.tsv',1090000,0.0642,
  /* donation_process */ 'Part of the 2019 Q4 grants based on the S-process (simulation process) that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different Recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s second round and the first one with grants made directly by Jaan Tallinn. SFF made a grant to 80,000 Hours in the previous round as well.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee in future grant rouds (such as https://survivalandflourishing.fund/sff-2020-h1-recommendations in 2020 H1) suggest continued satisfaction with the donee.',
  /* notes */ 'The grant round also includes a $40,000 grant directly from the Survival and Flourishing Fund to the same grantee (80,000 Hours).'),

  ('Survival and Flourishing Fund','80,000 Hours',120000,'2020-04-01','quarter','donation log','Effective altruism/movement growth/career counseling','https://survivalandflourishing.fund/sff-2020-h1-recommendations','Alex Zhu|Andew Critch|Jed McCaleb|Oliver Habryka',NULL,NULL,NULL,650000,0.1846,
  /* donation_process */ 'Part of the 2020 H1 grants based on the S-process (simulation process). A request for grants was made at https://forum.effectivealtruism.org/posts/wQk3nrGTJZHfsPHb6/survival-and-flourishing-grant-applications-open-until-march and open till 2020-03-07. The S-process "nvolves allowing the recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn, Jed McCaleb, and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s third round. SFF made a grant to 80,000 Hours in the previous two rounds as well.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes grants from Jaan Tallinn ($30,000) and Jed McCaleb ($30,000) to the same grantee (80,000 Hours).'),

  ('Jaan Tallinn','80,000 Hours',30000,'2020-04-01','quarter','donation log','Effective altruism/movement growth/career counseling','https://survivalandflourishing.fund/sff-2020-h1-recommendations','Alex Zhu|Andew Critch|Jed McCaleb|Oliver Habryka',NULL,NULL,NULL,920000,0.0326,
  /* donation_process */ 'Part of the 2020 H1 grants based on the S-process (simulation process). A request for grants was made at https://forum.effectivealtruism.org/posts/wQk3nrGTJZHfsPHb6/survival-and-flourishing-grant-applications-open-until-march and open till 2020-03-07. The S-process "nvolves allowing the recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn, Jed McCaleb, and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s third round. SFF made a grant to 80,000 Hours in the previous two rounds as well',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes grants from Survival and Flourishing Fund ($120,000) and Jed McCaleb ($30,000) to the same grantee (80,000 Hours).'),

  ('Jed McCaleb','80,000 Hours',30000,'2020-04-01','quarter','donation log','Effective altruism/movement growth/career counseling','https://survivalandflourishing.fund/sff-2020-h1-recommendations','Alex Zhu|Andew Critch|Jed McCaleb|Oliver Habryka',NULL,NULL,NULL,250000,0.12,
  /* donation_process */ 'Part of the 2020 H1 grants based on the S-process (simulation process). A request for grants was made at https://forum.effectivealtruism.org/posts/wQk3nrGTJZHfsPHb6/survival-and-flourishing-grant-applications-open-until-march and open till 2020-03-07. The S-process "nvolves allowing the recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn, Jed McCaleb, and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s third round. SFF made a grant to 80,000 Hours in the previous two rounds as well.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes grants from Survival and Flourishing Fund ($120,000) and Jed McCaleb ($30,000) to the same grantee (80,000 Hours).');

/* Center for Applied Rationality */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, goal_amount, fraction, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Survival and Flourishing Fund','Center for Applied Rationality',110000,'2019-08-01','month','donation log','Rationality improvement','https://survivalandflourishing.fund/','Alex Flint|Andrew Critch|Eric Rogstad','2019-08-29','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/cc4ba1e3975f4e4847272ffaf72a6ce09c19648f/_data/recommendations.tsv',880000,0.125,
  /* donation_process */ 'Part of the founding batch of grants for the Survival and Flourishing Fund made in August 2019. The fund is partly a successor to part of the grants program of the Berkeley Existential Risk Initiative (BERI) that handled grantmaking by Jaan Tallinn; see http://existence.org/tallinn-grants-future/ As such, this grant to CFAR may represent a followup to past grants by BERI to CFAR',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The grant may represent a followup to past grants by BERI to CFAR.',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; the Survival and Flourishing Fund is making its first round of grants in August 2019.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee in future grant rouds (such as https://survivalandflourishing.fund/sff-2019-q4-recommendations in 2019 Q4) suggest continued satisfaction with the donee.',
  /* notes */ NULL),

  ('Survival and Flourishing Fund','Center for Applied Rationality',150000,'2019-11-01','month','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2019-q4-recommendations','Alex Flint|Alex Zhu|Andrew Critch|Eric Rogstad|Oliver Habryka','2019-12-15','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/aa47e9860dff38e2af8d08da56a0a13389a75af4/_data/recommendations.tsv',920000,0.163,
  /* donation_process */ 'Part of the 2019 Q4 grants based on the S-process (simulation process) that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different Recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s second round. SFF made a grant to CFAR in the previous round as well.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes a $50,000 grant from Jaan Tallinn to the same grantee (Center for Applied Rationality).'),

  ('Jaan Tallinn','Center for Applied Rationality',50000,'2019-11-01','month','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2019-q4-recommendations','Alex Flint|Alex Zhu|Andrew Critch|Eric Rogstad|Oliver Habryka','2019-12-15','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/aa47e9860dff38e2af8d08da56a0a13389a75af4/_data/recommendations.tsv',1090000,0.0459,
  /* donation_process */ 'Part of the 2019 Q4 grants based on the S-process (simulation process) that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different Recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s second round and the first one with grants made directly by Jaan Tallinn. SFF made a grant to CFAR in the previous round as well.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee in future grant rounds (such as https://survivalandflourishing.fund/sff-2020-h2-recommendations in 2020 H2) suggest continued satisfaction with the donee.',
  /* notes */ 'The grant round also includes a $150,000 grant from the Survival and Flourishing Fund to the same grantee (Center for Applied Rationality).'),

  ('Survival and Flourishing Fund','Center for Applied Rationality',212000,'2020-10-01','quarter','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2020-h2-recommendations','Oliver Habryka|Eric Rogstad',NULL,NULL,NULL,650000,0.3262,
  /* donation_process */ 'Part of the 2020 H2 grants based on the S-process (simulation process that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Recommenders specified marginal utility functions for funding each application, and adjusted those functions through discussions with each other as the round progressed. Similarly, funders specified and adjusted different utility functions for deferring to each Recommender. In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes grants from Jed McCaleb ($23,000) and Jaan Tallinn ($19,000) to the same grantee (Center for Applied Rationality).'),

  ('Jed McCaleb','Center for Applied Rationality',23000,'2020-10-01','quarter','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2020-h2-recommendations','Oliver Habryka|Eric Rogstad',NULL,NULL,NULL,250000,0.092,
   /* donation_process */ 'Part of the 2020 H2 grants based on the S-process (simulation process that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Recommenders specified marginal utility functions for funding each application, and adjusted those functions through discussions with each other as the round progressed. Similarly, funders specified and adjusted different utility functions for deferring to each Recommender. In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this is SFF''s fourth grant round. Grants to CFAR had been made in the first two grant rounds but not the third one.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes grants from the Survival and Flourishing Fund ($212,000) and Jaan Tallinn ($19,000) to the same grantee (Center for Applied Rationality).'),

  ('Jaan Tallinn','Center for Applied Rationality',19000,'2020-10-01','quarter','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2020-h2-recommendations','Oliver Habryka|Eric Rogstad',NULL,NULL,NULL,2705000,0.007,
   /* donation_process */ 'Part of the 2020 H2 grants based on the S-process (simulation process that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Recommenders specified marginal utility functions for funding each application, and adjusted those functions through discussions with each other as the round progressed. Similarly, funders specified and adjusted different utility functions for deferring to each Recommender. In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this is SFF''s fourth grant round. Grants to CFAR had been made in the first two grant rounds but not the third one.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee in future grant rounds (such as https://survivalandflourishing.fund/sff-2021-h1-recommendations in 2021 H1) suggest continued satisfaction with the donee.',
  /* notes */ 'The grant round also includes grants from the Survival and Flourishing Fund ($212,000) and Jed McCaleb ($23,000) to the same grantee (Center for Applied Rationality).'),

  ('Jaan Tallinn','Center for Applied Rationality',1207000,'2021-04-01','quarter','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2021-h1-recommendations','Ben Hoskin|Katja Grace|Oliver Habryka|Adam Marblestone',NULL,NULL,NULL,9513000,0.1269,
   /* donation_process */ 'Part of the 2021 H1 grants based on the S-process (simulation process that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Recommenders specified marginal utility functions for funding each application, and adjusted those functions through discussions with each other as the round progressed. Similarly, funders specified and adjusted different utility functions for deferring to each Recommender. In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this is SFF''s fifth grant round. Grants to CFAR had been made in the first, second, and fourth grant round not the third one.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'Although Jed McCaleb also participated as a funder in this grant round, he did not make any grants to this grantee (Center for Applied Rationality).');

/* Grants to AI Impacts */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, goal_amount, fraction, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Survival and Flourishing Fund','AI Impacts',70000,'2019-11-01','month','donation log','AI safety','https://survivalandflourishing.fund/sff-2019-q4-recommendations','Alex Flint|Alex Zhu|Andrew Critch|Eric Rogstad|Oliver Habryka','2019-12-15','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/aa47e9860dff38e2af8d08da56a0a13389a75af4/_data/recommendations.tsv',920000,0.0761,
  /* donation_process */ 'Part of the 2019 Q4 grants based on the S-process (simulation process) that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different Recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s second round.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes a grant from Jaan Tallinn ($30,000) to the same grantee (AI Impacts).'),

  ('Jaan Tallinn','AI Impacts',30000,'2019-11-01','month','donation log','AI safety','https://survivalandflourishing.fund/sff-2019-q4-recommendations','Alex Flint|Alex Zhu|Andrew Critch|Eric Rogstad|Oliver Habryka','2019-12-15','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/aa47e9860dff38e2af8d08da56a0a13389a75af4/_data/recommendations.tsv',1090000,0.0276,
  /* donation_process */ 'Part of the 2019 Q4 grants based on the S-process (simulation process) that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different Recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this November 2019 round of grants is SFF''s second round.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'Continued grants from the donor to the donee (such as https://survivalandflourishing.fund/sff-2020-h1-recommendations in 2020 H1) suggest continued satisfaction with the donee.',
  /* notes */ 'The grant round also includes a grant from the Survival and Flourishing Fund ($70,000) to the same grantee (AI Impacts).'),

  ('Jaan Tallinn','AI Impacts',40000,'2020-04-01','quarter','donation log','AI safety','https://survivalandflourishing.fund/sff-2020-h1-recommendations','Alex Zhu|Andew Critch|Jed McCaleb|Oliver Habryka',NULL,NULL,NULL,920000,0.0435,
  /* donation_process */ 'Part of the 2020 H1 grants based on the S-process (simulation process). A request for grants was made at https://forum.effectivealtruism.org/posts/wQk3nrGTJZHfsPHb6/survival-and-flourishing-grant-applications-open-until-march and open till 2020-03-07. The S-process "nvolves allowing the recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn, Jed McCaleb, and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this 2020 H1 round of grants is SFF''s third round; grants to AI Impacts had also been made in the second round in 2019 Q4.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes a grant from Jed McCaleb ($20,000) to the same grantee (AI Impacts). Although the Survival and Flourishing Fund also participates as a funder in the round, it had no direct grants to AI Impacts in the round.'),

  ('Jed McCaleb','AI Impacts',20000,'2020-04-01','quarter','donation log','AI safety','https://survivalandflourishing.fund/sff-2020-h1-recommendations','Alex Zhu|Andew Critch|Jed McCaleb|Oliver Habryka',NULL,NULL,NULL,920000,0.0217,
  /* donation_process */ 'Part of the 2020 H1 grants based on the S-process (simulation process). A request for grants was made at https://forum.effectivealtruism.org/posts/wQk3nrGTJZHfsPHb6/survival-and-flourishing-grant-applications-open-until-march and open till 2020-03-07. The S-process "nvolves allowing the recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Funders were free to assign different weights to different recommenders in the process; the weights were determined by marginal utility functions specified by the funders (Jaan Tallinn, Jed McCaleb, and SFF). In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this 2020 H1 round of grants is SFF''s third round; grants to AI Impacts had also been made in the second round in 2019 Q4.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes a grant from Jaan Tallinn ($40,000) to the same grantee (AI Impacts). Although the Survival and Flourishing Fund also participates as a funder in the round, it has no direct grants to AI Impacts.'),

  ('Jaan Tallinn','AI Impacts',221000,'2021-04-01','quarter','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2021-h1-recommendations','Ben Hoskin|Katja Grace|Oliver Habryka|Adam Marblestone',NULL,NULL,NULL,9513000,0.0232,
   /* donation_process */ 'Part of the 2021 H1 grants based on the S-process (simulation process that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Recommenders specified marginal utility functions for funding each application, and adjusted those functions through discussions with each other as the round progressed. Similarly, funders specified and adjusted different utility functions for deferring to each Recommender. In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this is SFF''s fifth grant round. Grants to AI Impacts had been made in the second and third grant rounds.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes a grant from Jed McCaleb ($82,000) to the same grantee (AI Impacts).'),

  ('Jed McCaleb','AI Impacts',82000,'2021-04-01','quarter','donation log','Rationality improvement','https://survivalandflourishing.fund/sff-2021-h1-recommendations','Ben Hoskin|Katja Grace|Oliver Habryka|Adam Marblestone',NULL,NULL,NULL,243000,0.3374,
  /* donation_process */ 'Part of the 2021 H1 grants based on the S-process (simulation process that "involves allowing the Recommenders and funders to simulate a large number of counterfactual delegation scenarios using a spreadsheet of marginal utility functions. Recommenders specified marginal utility functions for funding each application, and adjusted those functions through discussions with each other as the round progressed. Similarly, funders specified and adjusted different utility functions for deferring to each Recommender. In this round, the process also allowed the funders to make some final adjustments to decide on their final intended grant amounts."',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; this is SFF''s fifth grant round. Grants to AI Impacts had been made in the second and third grant rounds.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The grant round also includes a grant from Jaan Tallinn ($221,000) to the same grantee.');

/* Other grants */

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, goal_amount, fraction, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('Survival and Flourishing Fund','Centre for the Study of Existential Risk',40000,'2019-08-01','month','donation log','Global catastrophic risks','https://survivalandflourishing.fund/','Alex Flint|Andrew Critch|Eric Rogstad','2019-08-29','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/cc4ba1e3975f4e4847272ffaf72a6ce09c19648f/_data/recommendations.tsv', 880000, 0.0455,
  /* donation_process */ 'Part of the founding batch of grants for the Survival and Flourishing Fund made in August 2019. The fund is partly a successor to part of the grants program of the Berkeley Existential Risk Initiative (BERI) that handled grantmaking by Jaan Tallinn; see http://existence.org/tallinn-grants-future/ As such, this grant to FLI may represent a followup to past grants by BERI in support of CSER (though BERI did not grant directly to CSER)',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'This grant may represent a followup to past grants by BERI in support of CSER (though BERI did not grant directly to CSER)',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; the Survival and Flourishing Fund is making its first round of grants in August 2019',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Survival and Flourishing Fund','Future of Life Institute',130000,'2019-08-01','month','donation log','Global catastrophic risks','https://survivalandflourishing.fund/','Alex Flint|Andrew Critch|Eric Rogstad','2019-08-29','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/cc4ba1e3975f4e4847272ffaf72a6ce09c19648f/_data/recommendations.tsv', 880000, 0.1477,
  /* donation_process */ 'Part of the founding batch of grants for the Survival and Flourishing Fund made in August 2019. The fund is partly a successor to part of the grants program of the Berkeley Existential Risk Initiative (BERI) that handled grantmaking by Jaan Tallinn; see http://existence.org/tallinn-grants-future/ As such, this grant to FLI may represent a followup to past grants by BERI to FLI',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'This grant may represent a followup to past grants by BERI to FLI',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; the Survival and Flourishing Fund is making its first round of grants in August 2019',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Survival and Flourishing Fund','Global Catastrophic Risk Institute',60000,'2019-08-01','month','donation log','Global catastrophic risks','https://survivalandflourishing.fund/','Alex Flint|Andrew Critch|Eric Rogstad','2019-08-29','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/cc4ba1e3975f4e4847272ffaf72a6ce09c19648f/_data/recommendations.tsv', 880000, 0.0682,
  /* donation_process */ 'Part of the founding batch of grants for the Survival and Flourishing Fund made in August 2019. The fund is partly a successor to part of the grants program of the Berkeley Existential Risk Initiative (BERI) that handled grantmaking by Jaan Tallinn; see http://existence.org/tallinn-grants-future/ As such, this grant to GCRI may represent a followup to past grants by BERI in support of GCRI',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'This grant may represent a followup to past grants by BERI in support of GCRI',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'Timing determined by timing of grant round; the Survival and Flourishing Fund is making its first round of grants in August 2019',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL),

  ('Survival and Flourishing Fund','LessWrong 2.0',260000,'2019-08-01','month','donation log','Global catastrophic risks','https://survivalandflourishing.fund/','Alex Flint|Andrew Critch|Eric Rogstad','2019-08-29','day','https://github.com/survivalandflourishing/survivalandflourishing.github.io/blob/cc4ba1e3975f4e4847272ffaf72a6ce09c19648f/_data/recommendations.tsv', 880000, 0.2955,
  /* donation_process */ 'Part of the founding batch of grants for the Survival and Flourishing Fund made in August 2019. The fund is partly a successor to part of the grants program of the Berkeley Existential Risk Initiative (BERI) that handled grantmaking by Jaan Tallinn; see http://existence.org/tallinn-grants-future/ As such, this grant to LessWrong 2.0 may represent a renewal of grants totaling $250,000 made by BERI to LessWrong 2.0 in 2018',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'This grant to LessWrong 2.0 may represent a renewal of grants totaling $250,000 made by BERI to LessWrong 2.0 in 2018',
  /* donor_amount_reason */ 'This grant to LessWrong 2.0 may represent a renewal of grants totaling $250,000 made by BERI to LessWrong 2.0 in 2018',
  /* donor_timing_reason */ 'Timing determined by timing of grant round; the Survival and Flourishing Fund is making its first round of grants in August 2019. Also, it is likely that the timeframe previous BERI grant to LessWrong 2.0 (made September 2018) has ended',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL);

