insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, goal_amount, fraction, affected_countries, donation_earmark, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes) values
  ('GiveWell discretionary regranting','Against Malaria Foundation',4700000,'2019-06-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','GiveWell',4700000,1.0,'Democratic Republic of the Congo',NULL,
  /* donation_process */ 'GiveWell looked at the funding gap and value of marginal funds for each of its top charities. Two charities that competed closely for the discretionary regrant were Malaria Consortium and Against Malaria Foundation. The blog post https://blog.givewell.org/2019/06/12/allocation-of-discretionary-funds-from-q1-2019/ has a section "Our process" describing how GiveWell decided to support AMF instead of Malaria Consortium',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'AMF expects to allocate all funding that it receives in the near future toward distributing insecticide-treated nets in the Democratic Republic of Congo (DRC) in 2020. More is explained in https://blog.givewell.org/2019/06/12/allocation-of-discretionary-funds-from-q1-2019/ in the "What AMF will do with additional funding" section',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'In the section "Updates since March 2019" of the blog post https://blog.givewell.org/2019/06/12/allocation-of-discretionary-funds-from-q1-2019/ GiveWell explains why it selected AMF instead of Malaria Consortium for this discretionary regrant, even though the previous quarter, it had selected MC. The two main reasons listed are: (1) An error correction in the cost-effectiveness estimate for AMF, described at https://www.givewell.org/how-we-work/our-criteria/cost-effectiveness/cost-effectiveness-models/changelog-2019#Version_3_Published_March_21_2019 has increased GiveWell''s cost-effectiveness estimate for AMF, (2) After the previous quarter''s discretionary regrant to MC in March 2019 described at https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/ GiveWell thinks MC has less room for more funding',
  /* donor_amount_reason */ 'The amount is the amount donated by donors to GiveWell for discretionary regranting to top charities in Q1 2019; GiveWell allocates the money separately for each quarter',
  /* donor_timing_reason */ 'This discretionary regrant is done every quarter, for the completed quarter. This particular grant is for Q1 2019 (January to March) and would therefore be expected to be in Q2 2019, which it is',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The donation is announced and explained in the blog post https://blog.givewell.org/2019/06/12/allocation-of-discretionary-funds-from-q1-2019/'),
  ('GiveWell discretionary regranting','Malaria Consortium',8400000,'2019-03-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','GiveWell',8400000,1.0,'Burkina Faso|Nigeria|Chad',NULL,
  /* donation_process */ 'GiveWell looked at the funding gap and value of marginal funds for each of its top charities. Two charities that competed closely for the discretionary regrant were Malaria Consortium and Against Malaria Foundation. The blog post https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/ has a lengthy section "Comparing Malaria Consortium and AMF" that applies the six principles in https://blog.givewell.org/2018/11/26/our-recommendation-to-good-ventures/#Principles to compare the two options, ultimately deciding on allocating 100% to Malaria Consortium',
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'Malaria Consortium expects to use the funding (earmarked for seasonal malaria chemoprevention) on these projects, in decreasing order of priority: (1) Contribute to filling a potential funding gap in Burkina Faso, (2) Scale up further in Nigeria and Chad in 2020, (3) Fund the continuation of programs into 2021.',
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'Malaria Consortium is operating in a domain, seasonal malaria chemprevention, that GiveWell considers highly cost-effective, and is estimated at delivering 8.3x as much value per unit money as cash transfers. Reasons for selecting Malaria Consortium over the Against Malaria Foundation include: stronger organizational management at Malaria Consortium, and more cooperation from Malaria Consortium in helping with GiveWell''s evaluation process',
  /* donor_amount_reason */ 'The amount of $8.4 million includes $7.6 million in discretionary funds directly available to GiveWell for regranting, and an additiona $0.8 million held by the Centre for Effective Altruism on its behalf. $1.7 million from the Effective Altruism Funds (Global Health and Development Fund) is also allocated to Malaria Consortium along with this $8.4 million',
  /* donor_timing_reason */ 'This discretionary regrant is done every quarter, for the completed quarter. This particular grant is for Q4 2018 (September to December) and would therefore be expected to be in Q1 2019. The discretionary regranting is relatively delayed compared to normal (it is usually completed within two months after the end of the quarter). The reason for the delay is likely that GiveWell waited for the end-of-year giving season to finish in order to better assess the remaining room for more funding',
  /* donor_next_donation_thoughts */ NULL,
  /* donot_retrospective */ 'Although not an explicit retrospective, the blog post discussing the next GiveWell discretionary regrant https://blog.givewell.org/2019/06/12/allocation-of-discretionary-funds-from-q1-2019/ describes some of GiveWell''s updated thinking about the same problem',
  /* notes */ 'The reasoning for the allocation is described in detail in the blog post https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/ (published 2019-03-29)'
);

# -- GiveWell discretionary regranting
insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, affected_countries, goal_amount, fraction, influencer) values
  ('GiveWell discretionary regranting','Malaria Consortium',1100000,'2018-11-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','See https://blog.givewell.org/2018/11/26/our-updated-top-charities-for-giving-season-2018/ for more detail. Grant uses money donated between July and September 2018 (i.e., Q3 2018) of $1.1 million. The entire amount was donated to Malaria Consortium because that was identified by GiveWell at the time as the charity with the most pressing funding gap to fill',NULL,1100000,1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',2870000,'2018-08-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','See https://blog.givewell.org/2018/08/28/allocation-of-discretionary-funds-from-q2-2018/ for more detail. Grant uses money donated between April and June 2018 (i.e., Q2 2018) of $1.2 million, as well as $2.9 million of unrestricted funds ($1.8 million held in reserve, and $1.1 million from a single donor donating $2.1 million). 70% of this total of $4.1 million is allocated to AMF in line with the general recommendation to donors to give 70% to AMF and 30% to SCI',NULL,4100000,0.7,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',1230000,'2018-08-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','See https://blog.givewell.org/2018/08/28/allocation-of-discretionary-funds-from-q2-2018/ for more details. Grant uses money donated between April and June 2018 (i.e., Q2 2018) of $1.2 million, as well as $2.9 million of unrestricted funds ($1.8 million held in reserve, and $1.1 million from a single donor donating $2.1 million). 30% of this total of $4.1 million is allocated to SCI in line with the general recommendation to donors to give 70% to AMF and 30% to SCI',NULL,4100000,0.3,'GiveWell'),  
  ('GiveWell discretionary regranting','Against Malaria Foundation',2072000,'2018-05-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2018 (i.e., Q1 2018). See https://blog.givewell.org/2018/06/04/allocation-of-discretionary-funds-from-q1-2018/ for more details. Note that the grantmaking page rounds the total to $3.0 million, but the blog post specifies the amount as $2.96 million; we are using 70% of the latter',NULL,2960000,0.7,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',888000,'2018-05-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2018 (i.e., Q1 2018). See https://blog.givewell.org/2018/06/04/allocation-of-discretionary-funds-from-q1-2018/ for more details. Note that the grantmaking page rounds the total to $3.0 million, but the blog post specifies the amount as $2.96 million; we are using 30% of the latter',NULL,2960000,0.3,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',5600000,'2018-03-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and December 2017 (i.e., Q4 2017). See https://blog.givewell.org/2018/04/06/allocation-of-discretionary-funds-from-q4-2017/ for more details',NULL,5600000,1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',700000,'2017-11-27','day','date of donation announcement','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and September 2017. See https://blog.givewell.org/2017/11/27/our-top-charities-for-giving-season-2017/ for more details. This is part of $15.9 million GiveWell is attempting to allocate to Deworm the World Initiative; the remaining $15.2 million will come from Good Ventures','India|Kenya',700000,1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',2250000,'2017-08-30','day','date of donation announcement','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and June 2017. Blog post https://blog.givewell.org/2017/08/30/why-were-allocating-discretionary-funds-to-the-deworm-the-world-initiative/ announces $2.25 million in made and planned grants to Deworm the World Initiative from funds given to GiveWell to regrant at its discretion (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities). This is the entirety of the money being granted or considered for granting at this time; the blog post explains why the grant is being made to Deworm the World Initiative even though GiveWell continues to recommend Against Malaria Foundation as the top charity that donors should allocate 100% of their donations to. Amount includes $1.25 million already granted and an additional $1 million that is planned for granting in the next month or two',NULL,2250000,1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',2500000,'2017-08-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and February 2017. Blog post https://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/ announces $4.4 million grant to AMF from the funds GiveWell has for discretionary regranting (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities). This is because AMF has the largest remaining Execution Level 1 gap based on the funding gaps identified in November 2016, and reports of funds raised as of February 2017. An additional $0.5 million is being granted to Deworm the World Initiative, and GiveWell recommends that donors giving now should donate all their money to the Against Malaria Foundation. Although a total grant of $4.4 million is announced, only $2.1 million is allocated at the time. The remaining $2.5 million (a bit more than the original estimate would suggest) for donations between January and February 2017 is paid out in August 2017',NULL,4900000,0.510,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',2100000,'2017-04-03','day','date of donation announcement','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and December 2016. Blog post https://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/ announces $4.4 million grant to AMF from the funds GiveWell has for discretionary regranting (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities). This is because AMF has the largest remaining Execution Level 1 gap based on the funding gaps identified in November 2016, and reports of funds raised as of February 2017. An additional $0.5 million is being granted to Deworm the World Initiative, and GiveWell recommends that donors giving now should donate all their money to the Against Malaria Foundation. Although a total grant of $4.4 million is announced, only $2.1 million out of that is allocated at this time; the rest would be granted in April',NULL,4900000,0.429,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',500000,'2017-04-03','day','date of donation announcement','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and December 2016. Blog post https://blog.givewell.org/2017/04/03/allocation-of-discretionary-funds/ announces $0.5 million to Deworm the World Initiative from the funds GiveWell has for discretionary regranting (see https://blog.givewell.org/2016/12/19/discretionary-grant-making-and-implications-for-donor-agency/ for more background on how this differs from GiveWell top charities), to fill most of an unfilled $0.53 million Execution Level 2 funding gap. This is out of a total of $4.9 million in granted money (the remaining $4.4 million went to the Against Malaria Foundation, with the highest priority of funding gap). The funding to Deworm the World Initiative was decided over other alternatives, including Schistosomiasis Control Initiative, the END Fund, GiveDirectly, Malaria Consortium, and Sightsavers',NULL, 4900000, 0.102,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',500000,'2016-12-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and September 2016', NULL, 500000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',300000,'2016-09-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between May and June 2016', NULL, 300000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',200000,'2016-06-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between March and April 2016', NULL, 200000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',1000000,'2016-04-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and February 2016', NULL, 1000000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',1600000,'2016-02-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated in December 2015', NULL, 1600000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',800000,'2016-01-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between October and November 2015', NULL, 800000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',600000,'2015-12-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between June and September 2015', NULL, 600000, 1.0,'GiveWell'),
  ('GiveWell discretionary regranting','Against Malaria Foundation',667000,'2015-07-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.667,'GiveWell'),
  ('GiveWell discretionary regranting','GiveDirectly',133000,'2015-07-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.133,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',133000,'2015-07-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.133,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',67000,'2015-07-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and May 2015', NULL, 1000000, 0.067,'GiveWell'),

  ('GiveWell discretionary regranting','Against Malaria Foundation',1467400,'2015-03-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.667,'GiveWell'),
  ('GiveWell discretionary regranting','GiveDirectly',292600,'2015-03-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.133,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',292600,'2015-03-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.133,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',147400,'2015-03-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between November and December 2014', NULL, 2200000, 0.133,'GiveWell'),

  ('GiveWell discretionary regranting','Against Malaria Foundation',66700,'2015-01-01','month','donation log','Global health/malaria','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.667,'GiveWell'),
  ('GiveWell discretionary regranting','GiveDirectly',13300,'2015-01-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.133,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',13300,'2015-01-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.133,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',6700,'2015-01-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between July and October 2014',NULL,100000,0.067,'GiveWell'),

  ('GiveWell discretionary regranting','GiveDirectly',60000,'2014-08-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between April and June 2014',NULL,100000,0.6,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',20000,'2014-08-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between April and June 2014',NULL,100000,0.2,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',20000,'2014-08-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between April and June 2014',NULL,100000,0.2,'GiveWell'),
  
  ('GiveWell discretionary regranting','GiveDirectly',110000,'2014-05-01','month','donation log','Cash transfers','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2014',NULL,200000,0.55,'GiveWell'),
  ('GiveWell discretionary regranting','Schistosomiasis Control Initiative',80000,'2014-05-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2014',NULL,200000,0.4,'GiveWell'),
  ('GiveWell discretionary regranting','Deworm the World Initiative',10000,'2014-05-01','month','donation log','Global health/deworming','https://www.givewell.org/about/FAQ/discretionary-grantmaking','Grant uses money donated between January and March 2014',NULL,200000,0.05,'GiveWell');


