insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, fraction, goal_amount) values
  # -- 2018
  ('Aaron Gertler','Massachusetts Bail Fund',50,'2018-11-28','day','donation log','Criminal justice reform/bail reform','https://aarongertler.net/donations-all-years/','Gift for a friend',0.5,100),
  ('Aaron Gertler','GiveDirectly',50,'2018-11-28','day','donation log','Cash transfers','https://aarongertler.net/donations-all-years/','Gift for a friend',0.5,100),
  ('Aaron Gertler','The Life You Can Save',500,'2018-11-27','day','donation log','Effective altruism/fundraising','https://aarongertler.net/donations-all-years/','Timed to coincide with matching funds from Facebook''s Giving Tuesday event. The match was successful, so Facebook matched the full $500',0.125,4000),
  ('Aaron Gertler','Iodine Global Network',500,'2018-11-27','day','donation log','Global health/nutrition/iodine','https://aarongertler.net/donations-all-years/','Timed to coincide with matching funds from Facebook''s Giving Tuesday event. The match was successful, so Facebook matched the full $500',0.125,4000),
  ('Aaron Gertler','Effective Altruism Funds',1000,'2018-11-27','day','donation log','Effective altruism/movement growth','https://aarongertler.net/donations-all-years/','Timed to coincide with matching funds from Facebook''s Giving Tuesday event. The match was successful, so Facebook matched the full $1000',0.25,4000),
  ('Aaron Gertler','GiveWell',2000,'2018-11-27','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Timed to coincide with matching funds from Facebook''s Giving Tuesday event. The match was successful, so Facebook matched the full $2000',0.5,4000),
  ('Aaron Gertler','Internet Archive',25,'2018-11-26','day','donation log','Digital preservation','https://aarongertler.net/donations-all-years/','Warm-and-fuzzy',NULL,NULL),
  # -- 2017
  ('Aaron Gertler','Centre for Effective Altruism',1000,'2017-11-28', 'day', 'donation log', 'Global health/malaria', 'https://aarongertler.net/donations-all-years/', '60% of donations made by Facebook on Giving Tuesday to qualify for matching by Facebook and the Bill and Melinda Gates Foundation', 0.5714, 1750),
  ('Aaron Gertler','GiveWell',750,'2017-11-28','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/', '40% of donations made by Facebook on Giving Tuesday to qualify for matching by Facebook and the Bill and Melinda Gates Foundation', 0.4286, 1750),
  ('Aaron Gertler','Effective Altruism Funds',500,'2017-10-28','day','donation log','Effective altruism/movement growth','https://aarongertler.net/donations-all-years/', 'Money to the EA Community Fund managed by Nick Beckstead', NULL, NULL),
  ('Aaron Gertler','Effective Altruism Funds',500,'2017-09-27','day','donation log','Effective altruism/movement growth','https://aarongertler.net/donations-all-years/', 'Money to the EA Community Fund managed by Nick Beckstead', NULL, NULL),
  ('Aaron Gertler','GiveDirectly',250,'2017-08-15','day','donation log','Cash transfers','https://aarongertler.net/donations-all-years/','Money to support the basic income experiment', NULL, NULL),
  ('Aaron Gertler','Against Malaria Foundation',150,'2017-04-14','day','donation log','Global health/malaria','https://aarongertler.net/donations-all-years/',NULL, NULL, NULL),
  # -- 2016  
  ('Aaron Gertler', 'Donor lottery', 500, '2016-12-15', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'See http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/ for more details', 0.4, 1250),
  ('Aaron Gertler', 'Centre for Effective Altruism', 750, '2016-12-15', 'day', 'donation log', 'Effective altruism/movement growth', 'https://aarongertler.net/donations-all-years/', 'End-of-year donation. $750 went to CEA, which runs a number of useful EA projects.', 0.6, 1250),
  ('Aaron Gertler', 'Against Malaria Foundation,Innovations for Poverty Action,Environmental Defense Fund', 350, '2016-12-06', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'Share of donations from a Giving Game co-sponsored by The Life You Can Save.', NULL, NULL),
  ('Aaron Gertler', 'GiveWell', 750, '2016-09-10', 'day', 'donation log', 'Charity evaluator', 'https://aarongertler.net/donations-all-years/', 'Operational funding', NULL, NULL),
  ('Aaron Gertler', 'Against Malaria Foundation', 500, '2016-07-12', 'day', 'donation log', 'Global health/malaria', 'https://aarongertler.net/donations-all-years/', 'In support of a friend’s campaign.', NULL, NULL),
  ('Aaron Gertler', 'Against Malaria Foundation', 600, '2016-06-26', 'day', 'donation log', 'Global health/malaria', 'https://aarongertler.net/donations-all-years/', '60% of the donations that day; the other 40% went to .impact', 0.6, 1000),
  ('Aaron Gertler', 'Rethink Charity', 400, '2016-06-26', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'The donation was to .impact, which is now Rethink Charity. 40% of the donations that day; the other 60% went to Against Malaria Foundation', 0.4, 1000),
  ('Aaron Gertler', 'Against Malaria Foundation', 1400, '2016-04-17', 'day', 'donation log', 'Global health/malaria', 'https://aarongertler.net/donations-all-years/', '70% of the donations that day; the other 30% went to GiveDirectly', 0.7, 2000),
  ('Aaron Gertler', 'GiveDirectly', 600, '2016-04-17', 'day', 'donation log', 'Cash transfers', 'https://aarongertler.net/donations-all-years/', 'The donation resulted from their basic income announcement, though I gave unrestricted funding.', 0.3, 2000),
  ('Aaron Gertler', 'GiveWell', 900, '2016-02-01', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'Operational funding. 90% of the donations that day, the other 10% went to CFAR', 0.9, 1000),
  ('Aaron Gertler', 'Center for Applied Rationality', 100, '2016-02-01', 'day', 'donation log', 'Rationality improvement', 'https://aarongertler.net/donations-all-years/', '10% of the donations that day, the other 90% went to GiveWell', 0.1, 1000),
  ('Aaron Gertler', 'Rethink Charity', 500, '2016-01-15', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'The donation was to .impact, which is now Rethink Charity. 40% of donations made that day', 0.4, 1250),
  ('Aaron Gertler', 'Parsemus Foundation', 250, '2016-01-15', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'Gift to David Benatar. 20% of donations made that day', 0.2, 1250),
  ('Aaron Gertler', 'Against Malaria Foundation', 500, '2016-01-15', 'day', 'donation log', 'Global health/malaria', 'https://aarongertler.net/donations-all-years/', 'Matched a fundraiser from EA Adelaide. 40% of donations made that day', 0.4, 1250),
  # -- 2015
  ('Aaron Gertler','Evidence Action,GiveDirectly,Against Malaria Foundation', 1515, '2015-11-23', 'day', 'donation log', NULL, 'https://aarongertler.net/donations-all-years/', 'Two-thirds of this was matching funds for winter fundraisers by student EA groups. The other third went to sponsor a Giving Game', NULL, NULL),
  ('Aaron Gertler','GiveWell', 495, '2015-10-16', 'day', 'donation log', 'Charity evaluator', 'https://aarongertler.net/donations-all-years/', 'Monthly donation. 55% of total monthly donation', 0.55, 900),
  ('Aaron Gertler','Global Priorities Project', 405, '2015-10-16', 'day', 'donation log', 'Charity evaluator', 'https://aarongertler.net/donations-all-years/', 'Monthly donation. 45% of total monthly donation', 0.45, 900),
  ('Aaron Gertler','GiveWell',500,'2015-09-17','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation. Support for GiveWell operations',1.0,500),
  ('Aaron Gertler','GiveWell',400,'2015-08-09','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation',1.0,400),
  ('Aaron Gertler','GiveWell',100,'2015-07-25','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation',1.0,100),
  ('Aaron Gertler','Internet Archive',20,'2015-07-25','day','donation log','Digital preservation','https://aarongertler.net/donations-all-years/','Warm-and-fuzzy',NULL,NULL),
  ('Aaron Gertler','Centre for Effective Altruism',75,'2015-06-11','day','donation log','Effective altruism/movement growth','https://aarongertler.net/donations-all-years/','Donation to Giving What We Can, which is now under the Centre for Effective Altruism',NULL,NULL),
  ('Aaron Gertler','GiveWell',50,'2015-05-23','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation',1.0,50),
  ('Aaron Gertler','Seva,Possible',50,'2015-05-12','day','donation log',NULL,'https://aarongertler.net/donations-all-years/',NULL,NULL,NULL),
  ('Aaron Gertler','Against Malaria Foundation',20,'2015-05-04','day','donation log','Global health/malaria','https://aarongertler.net/donations-all-years/','Gift for a friend birthday',NULL,NULL),
  ('Aaron Gertler','Seva',30,'2015-03-12','day','donation log',NULL,'https://aarongertler.net/donations-all-years/','Yale Effective Altruists giving game',NULL,NULL),
  ('Aaron Gertler','Oxfam',20,'2015-03-12','day','donation log',NULL,'https://aarongertler.net/donations-all-years/','Yale Effective Altruists giving game',NULL,NULL),
  ('Aaron Gertler','Charity Science',100,'2015-02-20','day','donation log',NULL,'https://aarongertler.net/donations-all-years/','Annual matching fundraiser',NULL,NULL),
  ('Aaron Gertler','GiveWell',40,'2015-01-31','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','In memory of a friend',NULL,NULL),
  ('Aaron Gertler','GiveWell',50,'2015-01-27','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','In memory of a friend',NULL,NULL),
  ('Aaron Gertler','Centre for Effective Altruism',15,'2015-01-21','day','donation log','Effective altruism/movement growth','https://aarongertler.net/donations-all-years/','Annual matching fundraiser',NULL,NULL),
  # -- 2014
  ('Aaron Gertler','Center for Applied Rationality',50,'2014-12-27','day','donation log','Rationalty improvement','https://aarongertler.net/donations-all-years/','Annual matching fundraiser',NULL,NULL),
  ('Aaron Gertler','Evidence Action',100,'2014-12-25','day','donation log',NULL,'https://aarongertler.net/donations-all-years/','Yale Effective Altruists winter fundraiser',NULL,NULL),
  ('Aaron Gertler','Evidence Action',100,'2014-12-23','day','donation log',NULL,'https://aarongertler.net/donations-all-years/','Yale Effective Altruists winter fundraiser',NULL,NULL),
  ('Aaron Gertler','GiveWell',100,'2014-12-02','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation', 1.0, 100),
  ('Aaron Gertler','GiveWell',100,'2014-11-02','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation', 1.0, 100),
  ('Aaron Gertler','Yale Effective Altruists',300,'2014-10-22','day','donation log','Effective altruism/movement growth','https://aarongertler.net/donations-all-years/','Initial funds for a nonprofit founded by him. Spent on operating costs and advocacy work', NULL, NULL),
  ('Aaron Gertler','GiveWell',125,'2014-09-30','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation', 1.0, 125),
  ('Aaron Gertler','GiveWell',38,'2014-09-07','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation', 1.0, 38),
  ('Aaron Gertler','Machine Intelligence Research Institute',100,'2014-08-01','day','donation log','AI safety','https://aarongertler.net/donations-all-years/','Monthly donation', NULL, NULL),
  ('Aaron Gertler','GiveWell',152,'2014-07-23','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation', 1.0, 152),
  ('Aaron Gertler','GiveWell',150,'2014-07-03','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Monthly donation', 1.0, 150),
  ('Aaron Gertler','GiveWell',20,'2014-06-05','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Gift for a friend',NULL,NULL),
  ('Aaron Gertler','GiveWell',200,'2014-05-29','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','Birthday donation',NULL,NULL),
  ('Aaron Gertler','GiveWell',150,'2014-03-07','day','donation log','Charity evaluator','https://aarongertler.net/donations-all-years/','First donation after becoming an effective altruist',NULL,NULL),
  # -- 2012
  ('Aaron Gertler','Vittana',115,'2012-12-24','day','donation log',NULL,'https://aarongertler.net/donations-all-years/','Christmas gifts for family',NULL,NULL);
  
