insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, goal_amount, fraction, payment_modality, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes, amount_original_currency, original_currency, currency_conversion_basis) values
  ('Anonymous MIRI cryptocurrency donor','Machine Intelligence Research Institute',1006549,'2017-05-30','day','date of donation announced in announcement','AI safety','https://intelligence.org/2017/07/04/updates-to-the-research-team-and-a-major-donation/',NULL,'2017-07-04','day','https://intelligence.org/2017/07/04/updates-to-the-research-team-and-a-major-donation/',NULL,NULL,'Ethereum transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The blog post announcing the donation says that the donor "had donated roughly $50k to our research programs over many years."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ 'A further much larger donation of $15.6 million announced at https://intelligence.org/2021/05/13/two-major-donations/ (2021-05-13) by the same donor suggests continued satisfaction with MIRI.',
  /* notes */ NULL,
  /* amount_original_currency */ NULL,
  /* original_currency */ 'ETH',
  /* currency_conversion_basis */ 'donee calculation'),

  ('Anonymous MIRI cryptocurrency donor','Machine Intelligence Research Institute',15592829,'2021-05-13','day','date of donation announcement','AI safety','https://intelligence.org/2021/05/13/two-major-donations/',NULL,'2021-05-13','day','https://intelligence.org/2021/05/13/two-major-donations/',NULL,NULL,'MakerDAO transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The blog post announcing the donation says that the donor "previously donated $1.01M in ETH to MIRI in 2017."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The blog post announcing the donation says: "Their amazingly generous new donation comes in the form of 3001 MKR, governance tokens used in MakerDAO, a stablecoin project on the Ethereum blockchain. MIRI liquidated the donated MKR for $15,592,829 after receiving it. With this donation, the anonymous donor becomes our largest all-time supporter."',
  /* amount_original_currency */ 3001,
  /* original_currency */ 'MKR',
  /* currency_conversion_basis */ 'donee calculation');
