insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, payment_modality, match_eligible, goal_amount, influencer, employer_match, matching_employer) values
  ('Ben Kuhn', 'GiveDirectly', 120, NULL, '2013-07-06', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'Schistosomiasis Control Initiative', 80, NULL, '2013-07-06', 'day', 'donation log', 'Global health/deworming', 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'Against Malaria Foundation', 200, NULL, '2013-07-06', 'day', 'donation log', 'Global health/malaria', 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'GiveWell', 6000, NULL, '2013-11-22', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'GiveWell', 10000, NULL, '2014-12-31', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'GiveWell', 10000, NULL, '2015-12-31', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', NULL, NULL, true, NULL, 'GiveWell', 10000, 'Wave'),
  ('Ben Kuhn', 'Effective Altruism Policy Analytics', 6333, NULL, '2015-06-07', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/eapa for more context', NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'Charity Entrepreneurship', 2000, NULL, '2015-12-31', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  # -- 2016 donations
  ('Ben Kuhn', 'GiveDirectly', 1000, NULL, '2016-12-31', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Ben Kuhn', 'GiveWell top charities', 5000, NULL, '2016-12-31', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2016 for more context', NULL, NULL, NULL, 'GiveWell', NULL, NULL),
  ('Ben Kuhn', 'EA Giving Group', 20000, NULL, '2016-12-31', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2016 for more context', NULL, true, NULL, 'Nick Beckstead', 10000, 'Wave'),
  # -- 2017 donations
  ('Ben Kuhn', 'GiveWell', 1400, 0.0233, '2017-12-30', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2017 for more context. The total donation amount for the year of $60,000 was calculated as 50% of total income for the year. The intended allocation to GiveWell was 2% (which would be $1200), but due to a miscalculation, a little more was allocated. After accounting for the employer match of $10,000 for another donations, the donation amount worked out to 18% of the total donation (including employer match) for the year', NULL, NULL, 60000, 'GiveWell', NULL, NULL),
  ('Ben Kuhn','GiveWell top charities',12600, 0.21, '2017-12-30', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2017 for more context. The total donation amount of $60,000 was calculated as 50% of total income for the year. The intended allocation to GiveWell top charities was 18% (which would be $10,800) but due to a miscalculation, a little more was allocated. After accounting for the employer match of $10,000 for another donations, the donation amount worked out to 18% of the total donation (including employer match) for the year', NULL, NULL, 60000, 'GiveWell', NULL, NULL),
  ('Ben Kuhn','Ben Kuhn donor-advised fund',46000, 0.7667, '2017-12-28', 'day', 'donation log', NULL, 'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2017 for more context. The total donation amount for the year of $60,000 was calculated as 50% of total income for the year. The intended allocation to the donor-advised fund was 80%, but due to a miscalculation, a little less was allocated. After account for the employer match of $10,000, the donation amount worked out to 80% of the total donation (including employer match) for the year', NULL, true, 60000, NULL, 10000, 'Wave'),
  # -- 2018 donations
  ('Ben Kuhn','GiveWell',1400,0.02,'2019-01-20','day','donation log',NULL,'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2018 for more context. Although the donation was made in January 2019, it is considered part of the donation for 2018; the reason for making the donation in 2019 was due to fewer liquid finances in December to make the donation. The total donation amount for the year of $70,000 was calculated as 50% of total income for the year. The allocation of $1,400 was calculated as 2% of the total donation amount. Logistics-wise, the donation was made via the donor-advised fund, and along with the donation of $12,600 to GiveWell top charities (i.e., a donation of $14,000 was made to GiveWell with 10% marked as an unrestricted donation to GiveWell)',NULL, NULL, 70000, 'GiveWell', NULL, NULL),
  ('Ben Kuhn','GiveWell top charities',12600,0.18,'2019-01-20','day','donation log',NULL,'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2018 for more context. Although the donation was made in January 2019, it is considered part of the donation for 2018; the reason for making the donation in 2019 was due to fewer liquid finances in December to make the donation. The total donation amount for the year of $70,000 was calculated as 50% of total income for the year. The allocation of $12,600 was calculated as 18% of the total donation amount. Logistics-wise, the donation was made via the donor-advised fund, and along with the donation of $1,400 to GiveWell (i.e., a donation of $14,000 was made to GiveWell with 10% marked as an unrestricted donation to GiveWell)',NULL, NULL, 70000, 'GiveWell', NULL, NULL),
  ('Ben Kuhn','Ben Kuhn donor-advised fund',56000,0.8,'2018-12-27','day','donation log',NULL,'https://www.benkuhn.net/ea/', 'See https://www.benkuhn.net/giving-2018 for more context. The total donation amount for the year of $70,000 was calculated as 50% of total income for the year. The allocation of $56,000 was calculated as 80% of the total donation amount (note that it was also the only donation to which the employer match was applied). Kuhn decided to donate to his donor-advised fund in order to defer the decision of where to ultimately direct his donations, partly because he has been busy with work and has not been closely following developments in the effective altruism space. However, he expects that, unless he finds a better target, he will likely donate from his donor-advised fund to the Effective Altruism Funds in 2019',NULL,NULL,70000,NULL,10000,'Wave');
