# -- Brian Tomasik donations
insert into donations(donor, donee, amount, fraction, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes,
    payment_modality, match_eligible, goal_amount, influencer, employer_match,
    matching_employer) values
   ('Brian Tomasik','Natural Resources Defense Council',NULL,NULL,'2004-01-01','multi-year','donation log','Animal welfare/environmentalism','http://reducing-suffering.org/my-donations-past-and-present/','Donations to this and similar organizations environmentalist orgs; belief that environment/natural preservation is related to animal welfare; since repudiated', NULL, NULL, NULL, NULL, NULL, NULL),
   ('Brian Tomasik','Vegan Outreach',NULL,1.0,'2005-01-01','multi-year','donation log','Animal welfare/diet change/veganism','http://reducing-suffering.org/my-donations-past-and-present/','Monthly donations from 2005 to 2007', NULL, NULL, NULL, 'Vegan Outreach', NULL, NULL),
   ('Brian Tomasik','Machine Intelligence Research Institute',12000.0,1.0,'2008-01-01','year','donation log','AI risk','http://reducing-suffering.org/my-donations-past-and-present/',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
   ('Brian Tomasik','Machine Intelligence Research Institute',12000,1.0,'2009-01-01','year','donation log','AI risk/suffering reduction','http://reducing-suffering.org/my-donations-past-and-present/','Donation earmarked for suffering reduction work that would not have happened counterfactually; at the time, the organization was called the Singularity Institute for Artificial Intelligence (SIAI)',NULL,NULL,NULL,NULL,12000,'Microsoft'),
   ('Brian Tomasik','Vegan Outreach',12000,1.0,'2010-01-01','year','donation log','Animal welfare/diet change/veganism','http://reducing-suffering.org/my-donations-past-and-present/','Stopped MIRI donations due to concern of insufficient suffering focus; excited about Vegan Outreach for long-term benefits of raising profile of animal suffering',NULL,NULL,NULL,NULL,12000,'Microsoft'),
   ('Brian Tomasik','Vegan Outreach',12000,1.0,'2011-01-01','year','donation log','Animal welfare/diet change/veganism','http://reducing-suffering.org/my-donations-past-and-present/','Same reasons as in 2010',NULL,NULL,NULL,NULL,12000,'Microsoft'),
   ('Brian Tomasik','Vegan Outreach',12000,1.0,'2012-01-01','year','donation log','Animal welfare/diet change/veganism','http://reducing-suffering.org/my-donations-past-and-present/','Asked for donation to be used in online vegan ads research; inspired by conversation with Nick Cooney of The Humane League',NULL,NULL,NULL,'Nick Cooney',12000,'Microsoft'),
   ('Brian Tomasik','Animal Charity Evaluators',12000,1.0,'2013-01-01','year','donation log','Animal welfare/factory farming/meta/charity evaluator','http://reducing-suffering.org/my-donations-past-and-present/','Called Effective Animal Activism (EAA) at the time; switch from Vegan Outreach to this was because of belief in higher leverage per dollar',NULL,NULL,NULL,'Nick Cooney',12000,'Microsoft'),
   ('Brian Tomasik','Machine Intelligence Research Institute',10,NULL,'2014-01-01','year','donation log','AI risk',NULL,'Part of a donation drive; information conveyed via private communication and published with permission',NULL,NULL,NULL,NULL,NULL,NULL),
   ('Brian Tomasik','Machine Intelligence Research Institute',2000,NULL,'2015-01-01','year','donation log','AI risk',NULL,'Thank you for a helpful conversation with outgoing director Luke Muehlhauser; information conveyed via private communication and published with permission',NULL,NULL,NULL,'Luke Muehlhauser',NULL,NULL);
