insert into money_moved(influencer, identified_donees, identified_donors, amount, start_date, end_date, document_url, document_title,notes) values
  ('Double Up Drive','Effective Animal Advocacy Fund',NULL,313927,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','Against Malaria Foundation',NULL,290194,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','Effective Altruism Funds',NULL,139594,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Money for the Long Term Future Fund. Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','The Good Food Institute',NULL,431282,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','GiveDirectly',NULL,433155,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','GiveWell top charities',NULL,271630,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','Helen Keller International',NULL,44304,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Funds for the Vitamin A supplementation (VAS) program. Total of funds that qualified for matching under the Double Up Drive'),
  ('Double Up Drive','Machine Intelligence Research Institute',NULL,228966,'2018-11-27','2018-12-29','https://doubleupdrive.com/','Double Up Drive','Total of funds that qualified for matching under the Double Up Drive. The matching is also discussed in MIRI''s 2018 fundraising retrospective https://intelligence.org/2019/02/11/our-2018-fundraiser-review/');
