/* 2019 / 2020 (announced 2021-06-23) */

insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, goal_amount, influencer, intended_use_of_funds_category, intended_use_of_funds, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, notes) values
  ('Jacob Steinhardt','GiveWell Maximum Impact Fund',6300,0.14,'2021-06-23','day','date of donation announcement','Global health and development','https://bounded-regret.ghost.io/donations-19-20/',45000,'GiveWell',
  /* intended_use_of_funds_category */ 'Regranting',
  /* intended_use_of_funds */ 'The GiveWell Maximum Impact Fund regrants money quarterly to GiveWell top charities based on which ones have the most cost-effective and time-sensitive funding need.',
  /* donor_donee_reason */ 'This 14% allocation should be viewed along with another of the donor''s global health and development donations: 12% to the EA Funds (Global Health and Development Fund). The donation post says: "I had decided that I wanted around 20% of my donations to go toward helping the global poor in a relatively straightforward way (i.e. not through research about what to do in the future, but direct interventions that will help today). Based on my estimate of their portfolios, the 14% + 12% mix between these two funds got me to the 20% target while also allocating some money towards research."',
  /* donor_amount_reason */ 'This 14% allocation should be viewed along with another of the donor''s global health and development allocation: 12% to the EA Funds (Global Health and Development Fund). The donation post says: "I had decided that I wanted around 20% of my donations to go toward helping the global poor in a relatively straightforward way (i.e. not through research about what to do in the future, but direct interventions that will help today). Based on my estimate of their portfolios, the 14% + 12% mix between these two funds got me to the 20% target while also allocating some money towards research." It also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ 'The donation post suggests that the donor will not be granting to the GiveWell Maximum Impact Fund any more, saying: "In retrospect, I think a better allocation would have been 40% to GHDF and 5% to GiveWell. The reason is that GHDF is actively managed by someone who I trust, who has similar goals than me, and who is significantly more informed than I am, so I would expect whatever allocation Elie chooses to be better than what I chose above. In addition, I have grown more comfortable with higher-risk donations; I was already fairly comfortable with them, allocating ~80% to high-risk/high-reward opportunities, but I''d now feel okay with up to ~90%."',
  /* notes */ NULL),

  ('Jacob Steinhardt','Effective Altruism Funds: Global Health and Development Fund',5400,0.12,'2021-06-23','day','date of donation announcement','Global health and development','https://bounded-regret.ghost.io/donations-19-20/',45000,NULL,
  /* intended_use_of_funds_category */ 'Regranting',
  /* intended_use_of_funds */ 'The Global Health and Development Fund is managed by Elie Hassenfeld, CEO of GiveWell, and primarily funds GiveWell Incubation Grants.',
  /* donor_donee_reason */ 'This 14% allocation should be viewed along with another of the donor''s global health and development donations: 12% to the GiveWell Maximum Impact Fund. The donation post says: "I had decided that I wanted around 20% of my donations to go toward helping the global poor in a relatively straightforward way (i.e. not through research about what to do in the future, but direct interventions that will help today). Based on my estimate of their portfolios, the 14% + 12% mix between these two funds got me to the 20% target while also allocating some money towards research."',
  /* donor_amount_reason */ 'This 14% allocation should be viewed along with another of the donor''s global health and development donations: 12% to the GiveWell Maximum Impact Fund. The donation post says: "I had decided that I wanted around 20% of my donations to go toward helping the global poor in a relatively straightforward way (i.e. not through research about what to do in the future, but direct interventions that will help today). Based on my estimate of their portfolios, the 14% + 12% mix between these two funds got me to the 20% target while also allocating some money towards research." It also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ 'The donation post suggests that the donor will increase granting to this fund, saying: "In retrospect, I think a better allocation would have been 40% to GHDF and 5% to GiveWell. The reason is that GHDF is actively managed by someone who I trust, who has similar goals than me, and who is significantly more informed than I am, so I would expect whatever allocation Elie chooses to be better than what I chose above. In addition, I have grown more comfortable with higher-risk donations; I was already fairly comfortable with them, allocating ~80% to high-risk/high-reward opportunities, but I''d now feel okay with up to ~90%."',
  /* notes */ NULL),

  ('Jacob Steinhardt','Center for Global Development',7650,0.17,'2021-06-23','day','date of donation announcement','Global health and development','https://bounded-regret.ghost.io/donations-19-20/',45000,NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ 'This money partly goes toward the intersection of "helping the global poor" of today and funding research (as opposed to interventions that can be applied immediately). The donation post says: "The Center for Global Development is primarily focused on research, and has a strong track record of past effectiveness."',
  /* donor_amount_reason */ 'This money partly goes toward the intersection of "helping the global poor" of today and funding research (as opposed to interventions that can be applied immediately). With a budget of 45% toward "helping the global poor" of which 20% was to direct interventions, the left-over amount after various adjustments worked out to 17%. The donation post also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ 'The donation post suggests that the donor may not grant to CGD in future years: "In retrospect, I think a better allocation would have been 40% to GHDF and 5% to GiveWell. The reason is that GHDF is actively managed by someone who I trust, who has similar goals than me, and who is significantly more informed than I am, so I would expect whatever allocation Elie chooses to be better than what I chose above. In addition, I have grown more comfortable with higher-risk donations; I was already fairly comfortable with them, allocating ~80% to high-risk/high-reward opportunities, but I''d now feel okay with up to ~90%."',
  /* notes */ NULL),

  ('Jacob Steinhardt','GiveWell',900,0.02,'2021-06-23','day','date of donation announcement','Global health and development','https://bounded-regret.ghost.io/donations-19-20/',45000,'GiveWell',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ 'These funds are to direct support GiveWell''s operating expenses. This is in contrast with unrestricted support to GiveWell, that could get reallocated by GiveWell to its top charities when it has excess funds.',
  /* donor_donee_reason */ 'The donation post talks of a 14% donation to the GiveWell Maximum Impact Fund, and adds: "Finally, GiveWell recommends allocating 10% of the donation to them to operating expenses, which I rounded up [from 10% of 14% = 1.4%] to 2%."',
  /* donor_amount_reason */ 'The donation post talks of a 14% donation to the GiveWell Maximum Impact Fund, and adds: "Finally, GiveWell recommends allocating 10% of the donation to them to operating expenses, which I rounded up [from 10% of 14% = 1.4%] to 2%." It also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ 'The donation post says: "Finally, I feel that giving only 2% to GiveWell created perverse incentives: if GHDF hadn''t existed, I would have donated more to GiveWell and thus given more to cover their operating costs. Since GHDF is run by the CEO of GiveWell, it seems incorrect to penalize GiveWell for GHDF''s existence, so moving forward I will allocate 10% of my {GiveWell + GHDF} donation to cover operating expenses."',
  /* notes */ NULL),

  ('Jacob Steinhardt','Effective Altruism Funds: Long-Term Future Fund',11225,0.25,'2021-06-23','day','date of donation announcement','Longtermism','https://bounded-regret.ghost.io/donations-19-20/',45000,NULL,
  /* intended_use_of_funds_category */ 'Regranting',
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ 'The donation post says: "The Long-Term Future Fund funds technical or conceptual research oriented towards safeguarding the long-term future of humanity. They are actively managed and mostly give small grants to individual researchers or small organizations, an approach which I think has the potential for high impact. While some of the areas they focus on, such as safe AI, are not primarily cash-constrained, I think LTFF does a good job of identifying instances where cash can actually help. In some cases, they made grants that I was initially skeptical of but that in retrospect seemed like good ideas. I therefore trust their judgment to align reasonably well with what I would conclude after significant investigation."',
  /* donor_amount_reason */ 'The reason that only about half of the 51% allocation for the long-term future was to the Long-Term Future Fund was described in the donation post as follows: "On the other hand, they mostly do not fund policy-related work, and I think that good AI policy, especially surrounding international conflict and arms races, could be very important for humanity''s long-term future. I therefore split my donations in this area in half between these two directions." It also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ 'The donation post says: "In retrospect, I think LTFF probably put significantly more effort than I did into evaluating all of the organizations I looked at, as well as several others, when deciding on their grant allocations. Therefore, in the future I would probably just allocate [all my long-term future donations] to LTFF and trust their decision-making. I feel somewhat worried about this, because if everyone pursues this strategy then it would concentrate grant-making in a small number of organizations, which could distort the overall funding ecosystem. That being said, I think the ultimate solution is to have other competitors to LTFF, rather than making low-information decisions as an individual. My hope is that funding them generously this year will help incentivize the creation of other strong grantmaking organizations."',
  /* notes */ NULL),

  ('Jacob Steinhardt','Legal Priorities Project',450,0.01,'2021-06-23','day','date of donation announcement','Longtermism','https://bounded-regret.ghost.io/donations-19-20/',45000,NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ 'The donation post says: "I also donated a small amount to the Legal Priorities Project. They are a relatively new organization that in part seeks to improve law to take future generations into account; they also tackle several other questions in legal research that they view as high-impact. They were one of several small organizations that I investigated this year, and seemed the most impressive to me. Although they do not yet have a clear track record of success, I don''t view this as unusual for an organization at their age, and I think supporting good organizations early on before they are clearly successful is often the highest-impact (assuming you can pick the organizations well, which can be difficult)."',
  /* donor_amount_reason */ 'The donation post suggests that the "small" amount of the donation reflects the organization''s small size and the value of even a small amount of funding in helping it grow. It also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ 'The donation post says: "in the future I would probably just allocate [all my long-term future donations] to LTFF and trust their decision-making." This, along with the fact that the donation to the Legal Priorities Project made sense specifically in the context of its early stage, suggests that the donor is unlikely to make further donations to the Legal Priorities Project.',
  /* notes */ NULL),

  ('Jacob Steinhardt','International Refugee Assistance Project',1800,0.04,'2021-06-23','day','date of donation announcement','Global health and development','https://bounded-regret.ghost.io/donations-19-20/',45000,NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ 'The donation post says: "I felt that IRAP was plausibly in the same ballpark as global health interventions in terms of impact, since they focus on immigration reform, whose beneficiaries are primarily in other countries. This is a neglected policy area within the U.S., and policy can be a strong philanthropic lever in areas that are not entrenched along partisan lines. A secondary benefit is that better immigration policy could help recruit more talented researchers to the U.S., which could help in other areas such as AI."',
  /* donor_amount_reason */ 'The reason for the relatively small allocation to IRAP is explained in the donation post as follows: "I am less confident that these donations maximize impact compared to the ones above, although I do feel that IRAP is a very good organization. The main reason these wouldn''t maximize impact is that they are U.S.-centric, while most of the strongest philanthropic opportunities lie abroad." It also includes context on the total amount ($45,000): "Each year I aim to donate around 10% of my income. [...] The impact of COVID-19 on poor countries made me better appreciate how much better I have it than most of the world, so I tried to donate closer to 20% of my 2020 income, and that will be my goal moving forward as well. Between 2019 and 2020, this came out to $45,000 in total."',
  /* donor_timing_reason */ 'The donation post says: "Each year I aim to donate around 10% of my income. In 2019, I fell behind on this, probably due to the chaos of COVID-19 (but really this was just an embarassing logistical failure on my part). I''ve recently, finally, finished processing donations for 2019 and 2020."',
  /* donor_next_donation_thoughts */ NULL,
  /* notes */ NULL);

/* 2016 */

insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis,
    cause_area, url, notes, payment_modality, match_eligible, goal_amount, influencer, employer_match, matching_employer)
    values
    ('Jacob Steinhardt', 'Donor lottery', 4000.00, 0.40, '2017-01-04','day', 'transaction', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', 'See https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016/ for more context; the announcement was 2016-12-28, before the actual transaction', NULL, NULL, NULL, 'Carl Shulman', NULL, NULL),
    ('Jacob Steinhardt', 'GiveWell Maximum Impact Fund', 2500.00, 0.25, '2016-12-28','day', 'date of donation announcement', 'Global health and development', 'https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016/', 'Although donation was announced on this day we do not know when it was made', NULL, NULL, NULL, 'GiveWell', NULL, NULL),
    ('Jacob Steinhardt','GiveDirectly',500,0.05,'2016-12-28','day','date of donation announcement', 'Cash transfers','https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016/', 'Although donation was announced on this day we do not know when it was made', NULL, NULL, NULL, 'GiveWell + a student of Pascaline Dupas', NULL, NULL),
    ('Jacob Steinhardt','Carnegie Endowment for International Peace',500,0.05,'2016-12-28','day','date of donation announcement', 'World peace','https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016/', 'Earmarked for Carnegie-Tsinghua Center. Although donation was announced on this day we do not know when it was made', NULL, NULL, NULL, 'Nick Beckstead', NULL, NULL),
    ('Jacob Steinhardt','Blue Ribbon Study Panel on Biodefense',500,0.05,'2016-12-28','day','date of donation announcement', 'World peace','https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016/', 'Although donation was announced on this day we do not know when it was made', NULL, NULL, NULL, 'Jaime Yassif', NULL, NULL);
