insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes) values
  ('Loren Merritt', 'Machine Intelligence Research Institute', 10000, '2011-08-25','day', 'date of donation announcement', 'AI safety', 'http://lesswrong.com/lw/78s/help_fund_lukeprog_at_siai/4p1x', 'Donation is announced in response to the post http://lesswrong.com/lw/78s/help_fund_lukeprog_at_siai/ by Eliezer Yudkowsky asking for help to fund Luke Muehlhauser at MIRI (then called SIAI, the Singularity Institute for Artificial Intelligence'),
  ('Loren Merritt', 'Machine Intelligence Research Institute', 110000, '2012-01-01','year','date of donation announced in announcement', 'AI safety', 'http://lesswrong.com/lw/ftg/2012_winter_fundraiser_for_the_singularity/7zt4', 'Donation is announced in response to the post http://lesswrong.com/lw/ftg/2012_winter_fundraiser_for_the_singularity/ for the MIRI 2012 winter fundraiser'),
  ('Loren Merritt', 'Machine Intelligence Research Institute', 20000, '2012-12-07','day','date of donation announced in announcement', 'AI safety', 'http://lesswrong.com/lw/ftg/2012_winter_fundraiser_for_the_singularity/7zt4', 'Donation is announced in response to the post http://lesswrong.com/lw/ftg/2012_winter_fundraiser_for_the_singularity/ for the MIRI 2012 winter fundraiser'),
  ('Loren Merritt', 'Machine Intelligence Research Institute', 245000, '2013-01-01', 'multi-year','donation log', 'AI safety', 'http://web.archive.org/web/20140403110808/http://intelligence.org/topdonors/', 'Total amount donated up to this point is listed as $385,000. Of this, $140,000 is accounted for by explicitly disclosed donations; the remainder is approximately attributed to 2013'),
  ('Loren Merritt', 'Machine Intelligence Research Institute', 115000, '2016-01-01', 'multi-year','donation log', 'AI safety', 'http://web.archive.org/web/20170204024838/https://intelligence.org/topdonors/', 'Total amount donated up to this point is listed as $500,000. The amount listed as of November 2016 at http://web.archive.org/web/20161118163935/https://intelligence.org/topdonors/ is 4385,000. The additional $115,000 was likely raised at the end of 2016'),
  ('Loren Merritt','Machine Intelligence Research Institute', 25000, '2017-10-01','quarter','donation log','AI safety','http://web.archive.org/web/20171223071315/https://intelligence.org/topcontributors/', 'Total amount donated by Loren Merritt to MIRI as of 2017-12-23 is $525,000. The amount listed as of October 2017 was http://web.archive.org/web/20171003083300/https://intelligence.org/topcontributors/ so the extra $25,000 was donated between those months'),
  # -- CFAR
  ('Loren Merritt', 'Center for Applied Rationality', 40000, '2014-01-07', 'day', 'date of donation announcement', 'Rationality improvement', 'http://lesswrong.com/lw/jej/why_cfar/ab0o', 'Donation is announced in response to the post http://lesswrong.com/lw/jej/why_cfar/ by Anna Salamon of CFAR, making the case for donating to it');
