insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, goal_amount, influencer, intended_use_of_funds_category, intended_use_of_funds, donor_donee_reason, donor_amount_reason, donor_timing_reason, notes) values
  /* 2020 */
  ('Patrick Brinich-Langlois','Guarding Against Pandemics',15030,NULL,'2020-10-24','day','donation log','Biosecurity and pandemic preparedness','https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The donations page says: "This was for a campaign for a Denver ballot initiative that would increase marijuana taxes to fund pandemic-preparedness research."',
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'The reasons for the specific amount are not given, but the donations page gives some context: "It''s not tax-deductible, and it includes a $30 wire-transfer fee."',
  /* donor_timing_reason */ 'Reasons for timing are not provided, but the timing is likely influenced by the timing of the ballot, which is likely part of the November 2020 elections.',
  /* notes */ NULL),

  ('Patrick Brinich-Langlois','Rethink Priorities',22492,NULL,'2020-11-01','day','donation log','Effective altruism','https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ 'Direct project expenses',
  /* intended_use_of_funds */ 'The donations page says: "Restricted to longtermism and meta/movement-building."',
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* notes */ NULL),

  ('Patrick Brinich-Langlois','Centre for Effective Altruism',10,NULL,'2020-11-02','day','donation log','Effective altruism','https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ NULL,
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* notes */ 'The donations page says: "This was made through Every.org, and I also gave the $25 referral bonus to the CEA."'),

  ('Patrick Brinich-Langlois','Donor lottery',30,NULL,'2020-11-29','day','donation log',NULL,
'https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ NULL,
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ 'The donations page says: "Test donations in preparation for Facebook''s Giving Tuesday matching program." The selection of donee was likely reflective of the fact that this "donation" was a wash in expected value.',
  /* donor_amount_reason */ 'The donations page says: "Test donations in preparation for Facebook''s Giving Tuesday matching program." The small amount reflects the "test" nature of the donation.',
  /* donor_timing_reason */ 'The donations page says: "Test donations in preparation for Facebook''s Giving Tuesday matching program." This expains the timing of the donation, two days before Giving Tuesday.',
  /* notes */ 'No donations are recorded as having been made on Giving Tuesday, so it''s unclear what the testing was for.'),

  ('Patrick Brinich-Langlois','Centre for Effective Altruism',10,NULL,'2020-12-21','day','donation log','Effective altruism','https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ NULL,
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* notes */ NULL),

  ('Patrick Brinich-Langlois','Donor lottery',42000,NULL,'2020-11-29','day','donation log',NULL,
'https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ NULL,
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* notes */ NULL),

  /* 2021 */
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',500,NULL,'2021-03-06','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL,NULL,
  /* intended_use_of_funds_category */ NULL,
  /* intended_use_of_funds */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ 'The grant page says: "I got a credit card that gives you $200 if you spend $500 within the first three months." This explains the donation amount of 500 USD.',
  /* donor_timing_reason */ 'The grant page says: "I got a credit card that gives you $200 if you spend $500 within the first three months." Presumably the credit card had been received within the last three months.',
  /* notes */ NULL);

insert into donations(donor, donee, amount, fraction, donation_date, donation_date_precision, donation_date_basis, cause_area, url, notes, payment_modality, match_eligible, goal_amount, influencer, employer_match, matching_employer, special_donation_reason) values
  /* Berkeley REACH donations */
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-12-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-11-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-10-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-09-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-08-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-07-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-06-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-05-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-04-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-03-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-02-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2019-01-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-12-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-11-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-10-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-09-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-08-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-07-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-06-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like one of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  ('Patrick Brinich-Langlois','Berkeley REACH',100,NULL,'2018-05-01','day','donation log','Rationality community','https://www.patbl.com/misc/other/donations/','This looks like the first of many monthly donations for $100.', NULL, NULL, NULL, NULL, NULL, NULL, 'Committed periodic donation'),
  /* Other donations */
  ('Patrick Brinich-Langlois','Berkeley Existential Risk Initiative',7497,NULL,'2019-12-03','day','donation log','AI safety','https://www.patbl.com/misc/other/donations/',NULL,NULL,NULL,NULL,NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Alliance to Feed the Earth in Disasters',7497,NULL,'2019-12-03','day','donation log','Global catastrophic risks','https://www.patbl.com/misc/other/donations/','Donation via Facebook Fundraisers on Giving Tuesday; fully matched by Facebook','Facebook Fundraisers',NULL,NULL,'Giving Tuesday Facebook match', NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',44000,NULL,'2019-10-16','day','donation log','Global catastrophic risks/other long-term future','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Global Catastrophic Risk Institute',5,NULL,'2018-11-27','day','donation log','Global catastrophic risks','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',2504,NULL,'2018-11-27','day','donation log','Global catastrophic risks/other long-term future','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Alliance to Feed the Earth in Disasters',2499,NULL,'2018-11-27','day','donation log','Global catastrophic risks','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Centre for Effective Altruism',55,NULL,'2018-11-26','day','donation log','Effective altruism/movement growth','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',14000,NULL,'2018-10-27','day','donation log','Global catastrophic risks/other long-term future','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',11100,NULL,'2017-12-29','day','donation log','Global catastrophic risks/other long-term future','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Effective Altruism Infrastructure Fund',11100,NULL,'2017-12-29','day','donation log','Effective altruism/movement growth','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','AIDS/LifeCycle',50,NULL,'2017-12-19','day','donation log','Global health/STD control including HIV/AIDS','https://www.patbl.com/misc/other/donations/',NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Machine Intelligence Research Institute',3000,NULL,'2017-12-10','day','donation log','AI safety','https://www.patbl.com/misc/other/donations/',NULL,NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',20000,NULL,'2017-08-28','day','donation log','Global catastrophic risks/other long-term future','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','The Humane League',117.32,NULL,'2017-08-12','day','donation log','Animal welfare/factory farming','https://www.patbl.com/misc/other/donations/', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Long-Term Future Fund',7500,NULL,'2017-03-25','day','donation log','Global catastrophic risks/other long-term future','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Effective Altruism Funds: Effective Altruism Infrastructure Fund',7500,NULL,'2017-03-25','day','donation log','Effective altruism/movement growth','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','EA Giving Group',10055.55,NULL,'2016-12-30','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/','Chose amount to reach donation goal total of 55555.55', NULL, NULL, 55555.55, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','EA Giving Group',15000,NULL,'2016-11-05','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, 55555.55, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','EA Giving Group',10000,NULL,'2016-07-04','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, 55555.55, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Mercy For Animals',500,NULL,'2016-06-13','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/','Offsetting a month of omnivore diet', NULL, NULL, 55555.55, NULL, NULL, NULL, 'Offset'),
  ('Patrick Brinich-Langlois','EA Giving Group',10000,NULL,'2016-04-22','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, 55555.55, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Rethink Charity',5000,NULL,'2016-03-21','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, 55555.55, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Rethink Charity',5000,NULL,'2016-02-01','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, 55555.55, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Centre for Effective Altruism',5000,NULL,'2015-12-22','day','donation log','Effective altruism/movement growth','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Animal Charity Evaluators',10000,NULL,'2015-12-22','day','donation log','Animal welfare/factory farming/meta/charity evaluator','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','80,000 Hours',1692.42,NULL,'2015-10-06','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','80,000 Hours',38307.58,NULL,'2015-08-24','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/','Grant from The Eleemosynary Flying Orang−Utans Fund', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Animal Charity Evaluators',10000,NULL,'2015-07-07','day','donation log','Animal welfare/factory farming/meta/charity evaluator','https://www.patbl.com/misc/other/donations/','Grant from The Eleemosynary Flying Orang−Utans Fund', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','80,000 Hours',30000,NULL,'2014-01-08','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','St. Olaf College',10,NULL,'2014-01-08','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','Animal Charity Evaluators',10000,NULL,'2013-07-02','day','donation log','Animal welfare/factory farming/meta/charity evaluator','https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','80,000 Hours',500,NULL,'2012-11-06','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','St. Olaf College',2,NULL,'2012-10-31','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/','Comment: I was told that even a small amount would help immensely', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','The Humane League',800,NULL,'2012-04-12','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','The Humane League',800,NULL,'2012-04-23','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','The Humane League',800,NULL,'2012-05-04','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('Patrick Brinich-Langlois','The Humane League',800,NULL,'2012-05-30','day','donation log',NULL,'https://www.patbl.com/misc/other/donations/',NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
