insert into donations(donor,donee,amount,donation_date,donation_date_precision,donation_date_basis,cause_area,url,notes) values
  ('Vitalik Buterin','Machine Intelligence Research Institute',802136.0,'2018-01-17','year','donee contributor list','AI safety','https://web.archive.org/web/20180117010054/https://intelligence.org/topcontributors/',NULL);

insert into donations(donor, donee, amount, donation_date, donation_date_precision, donation_date_basis, cause_area, url, influencer, donation_announcement_date, donation_announcement_date_precision,donation_announcement_url, goal_amount, fraction, payment_modality, donation_process, intended_use_of_funds_category, intended_use_of_funds, intended_funding_timeframe_in_months, donor_donee_reason, donor_amount_reason, donor_timing_reason, donor_next_donation_thoughts, donor_retrospective, notes, amount_original_currency, original_currency, currency_conversion_basis) values
  ('Vitalik Buterin','SENS Research Foundation',2400000.0,'2017-12-14','day','transaction','Life sciences/anti-aging','https://web.archive.org/web/20180204023122/http://www.sens.org/outreach/press-releases/srf-receives-24m-ethereum-donation-from-vitalik-buterin','Pineapple Fund','2018-02-02','day','https://web.archive.org/web/20180204023122/http://www.sens.org/outreach/press-releases/srf-receives-24m-ethereum-donation-from-vitalik-buterin',NULL,NULL,'Ethereum transaction',
  /* donation_process */ 'The donation appears to be one of many made by Vitalik Buterin at around this time, and a result of his thinking around how to use cryptocurrency for "actually achieving something meaningful for society." See https://twitter.com/VitalikButerin/status/945987507941978112 and https://www.ccn.com/intenet-archive-sees-big-donations-vitalik-buterin-pineapple-fund/ for more.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ 'The press release page https://web.archive.org/web/20180204023122/http://www.sens.org/outreach/press-releases/srf-receives-24m-ethereum-donation-from-vitalik-buterin quotes Vitalik Buterin as saying: "I''ve been a fan of Aubrey''s work since I first read Ending Aging when I was a teenager, and I am happy to have been blessed with the opportunity to personally support SENS''s efforts. Their focus on creating solutions to the diseases of aging, one of the greatest problems facing humanity, is very much in line with my goal to positively impact the lives of millions of people around the world."',
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'The timing seems related to the substantial increases in Ethereum prices, making Buterin much wealthier, and Buterin''s thinking around how to use cryptocurrency for "actually achieving something meaningful for society." See https://twitter.com/VitalikButerin/status/945987507941978112 and https://www.ccn.com/intenet-archive-sees-big-donations-vitalik-buterin-pineapple-fund/ for more.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'The press release page https://web.archive.org/web/20180204023122/http://www.sens.org/outreach/press-releases/srf-receives-24m-ethereum-donation-from-vitalik-buterin says: ""SENS Research Foundation is honored to be the recipient of Vitalik''s incredible generosity. This was his second donation to us in 2017 and his support is critical to SENS Research Foundation''s expansion of our programs," said Mike Kope, CEO, SENS Research Foundation. "Our work to cure the diseases of aging is dependent on the generous support of our donors and we appreciate his support tremendously."" The actual Ethereum transaction appears to have been done in multiple steps on 2017-12-14: https://etherscan.io/tx/0x6fc6eb8bdc6499254e321aadbe66d040468470a5449857006d3aff5904183a87 https://etherscan.io/tx/0xa2846317fd6dd54c142dfbd68a0a1820390ce918e5e8a8b3f561189307b36d19 https://etherscan.io/tx/0x14dd7128325877a113df425752f9318039810668697a829decea8381bb4a71a2',
  /* amount_original_currency */ NULL,
  /* original_currency */ 'ETH',
  /* currency_conversion_basis */ NULL),

  ('Vitalik Buterin','Internet Archive',85075,'2018-02-10','day','transaction','Digital preservation','https://etherscan.io/tx/0x8bd3cbe28b90786afbdf16ce9f1c99e76726623a3b764fc7e6e55563c9767777','Pineapple Fund',NULL,NULL,NULL,NULL,NULL,'Ethereum transaction',
  /* donation_process */ 'The donation appears to be one of many made by Vitalik Buterin at around this time, and a result of his thinking around how to use cryptocurrency for "actually achieving something meaningful for society." See https://twitter.com/VitalikButerin/status/945987507941978112 and https://www.ccn.com/intenet-archive-sees-big-donations-vitalik-buterin-pineapple-fund/ for more.',
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ 'The timing seems related to the substantial increases in Ethereum prices, making Buterin much wealthier, Pineapple Fund''s donation matching, and Buterin''s thinking around how to use cryptocurrency for "actually achieving something meaningful for society." See https://twitter.com/VitalikButerin/status/945987507941978112 and https://www.ccn.com/intenet-archive-sees-big-donations-vitalik-buterin-pineapple-fund/ for more.',
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'https://www.ccn.com/intenet-archive-sees-big-donations-vitalik-buterin-pineapple-fund/ has more context on the donations. That post gives the amount using the price of Ethereum at the time of the article, namely 93,469, which is higher than the price at the time of the transaction.',
  /* amount_original_currency */ 100,
  /* original_currency */ 'ETH',
  /* currency_conversion_basis */ NULL),

  ('Vitalik Buterin','GiveDirectly',4271350.62,'2021-01-29','day','transaction','Cash transfers/unconditional cash transfers','https://etherscan.io/tx/0x1d700574aea0c3f8a3509e9eb83f9f5bdd7ca4f4c40e1f57fc9e2137efb9c851',NULL,'2021-02-01','day','https://twitter.com/vitalikbuterin/status/1356177116744839169',NULL,NULL,'USDC transaction over Ethereum network',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ NULL,
  /* original_currency */ NULL,
  /* currency_conversion_basis */ NULL),

  ('Vitalik Buterin','India Covid Relief Fund',931193533.78,'2021-05-12','day','transaction','Global health/COVID-19','https://etherscan.io/tx/0xb65bcbb85c1633b0ab4e4886c3cd8eeaeb63edbb39cacdb9223fdcf4454fd2c7',NULL,'2021-05-12','day','https://www.forbes.com/sites/ninabambysheva/2021/05/12/ethereums-co-founder-vitalik-buterin-donates-over-1-billion-to-india-covid-relief-fund-and-other-charities/',NULL,NULL,'SHIB transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ 50693552078053,
  /* original_currency */ 'SHIB',
  /* currency_conversion_basis */ 'Etherscan.io'),

  ('Vitalik Buterin','Gitcoin',374797066.19,'2021-05-12','day','transaction',NULL,'https://etherscan.io/tx/0x2fb8b58f85ab4773da00771f7f1e1a9eacf99af0ef3310b75ebcd017099f7b3c',NULL,'2021-05-12','day','https://www.forbes.com/sites/ninabambysheva/2021/05/12/ethereums-co-founder-vitalik-buterin-donates-over-1-billion-to-india-covid-relief-fund-and-other-charities/',NULL,NULL,'AKITA transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ 49340000069420,
  /* original_currency */ 'AKITA',
  /* currency_conversion_basis */ 'Etherscan.io'),

  ('Vitalik Buterin','GiveWell',50659666.68,'2021-05-12','day','transaction',NULL,'https://etherscan.io/tx/0x33e4aa32018786e2c75a90b2e096164cbefb55664cb4ce586cb46dd379cf0390',NULL,'2021-05-12','day','https://www.forbes.com/sites/ninabambysheva/2021/05/12/ethereums-co-founder-vitalik-buterin-donates-over-1-billion-to-india-covid-relief-fund-and-other-charities/',NULL,NULL,'Ethereum transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ 13292,
  /* original_currency */ 'ETH',
  /* currency_conversion_basis */ 'Etherscan.io'),

  ('Vitalik Buterin','Methuselah Foundation',231061626.05,'2021-05-12','day','transaction',NULL,'https://etherscan.io/tx/0xdab7634a04e3b7afb0d5a9faf9db59a05a04372234c0c960342102a4859aca16',NULL,'2021-05-12','day','https://www.forbes.com/sites/ninabambysheva/2021/05/12/ethereums-co-founder-vitalik-buterin-donates-over-1-billion-to-india-covid-relief-fund-and-other-charities/',NULL,NULL,'Dogelon transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ NULL,
  /* amount_original_currency */ 432000583089106,
  /* original_currency */ 'ELON',
  /* currency_conversion_basis */ 'Etherscan.io'),

  ('Vitalik Buterin','Machine Intelligence Research Institute',4001854.50,'2021-05-12','day','transaction',NULL,'https://etherscan.io/tx/0x949bc96c02090165ccb2c180dc105ce6592514576dced024356402248844836d',NULL,'2021-05-12','day','https://www.forbes.com/sites/ninabambysheva/2021/05/12/ethereums-co-founder-vitalik-buterin-donates-over-1-billion-to-india-covid-relief-fund-and-other-charities/',NULL,NULL,'Ethereum transaction',
  /* donation_process */ NULL,
  /* intended_use_of_funds_category */ 'Organizational general support',
  /* intended_use_of_funds */ NULL,
  /* intended_funding_timeframe_in_months */ NULL,
  /* donor_donee_reason */ NULL,
  /* donor_amount_reason */ NULL,
  /* donor_timing_reason */ NULL,
  /* donor_next_donation_thoughts */ NULL,
  /* donor_retrospective */ NULL,
  /* notes */ 'A blog post https://intelligence.org/2021/05/13/two-major-donations/ by the Machine Intelligence Research Institute the next day describes the donation and lists the USD amount as $4,378,159.',
  /* amount_original_currency */ 1050,
  /* original_currency */ 'ETH',
  /* currency_conversion_basis */ 'Etherscan.io');
