# -- These donations are mostly taken from the MIRI top donors list
insert into donations(donor,donee,amount,donation_date,donation_date_precision,donation_date_basis,cause_area,url,notes) values
  ('Zvi Mowshowitz','Machine Intelligence Research Institute',5010,'2015-01-17','multi-year','donee contributor list','AI safety','https://web.archive.org/web/20150117213932/https://intelligence.org/donortools/topdonors.php',NULL),
  ('Zvi Mowshowitz','Machine Intelligence Research Institute',10000,'2017-12-23','year','donee contributor list','AI safety','https://web.archive.org/web/20171223071315/https://intelligence.org/topcontributors/','The document https://thezvi.wordpress.com/2017/12/17/i-vouch-for-miri/ explains that he believes that MIRI understands the hardness of the AI safety problem, is focused on building solutions for the long term, and has done humanity a great service through its work on functional decision theory'),
  ('Zvi Mowshowitz','Machine Intelligence Research Institute',10000,'2018-04-07','year','donee contributor list','AI safety','https://intelligence.org/topcontributors/',NULL);

# -- Here are some other donations
insert into donations(donor,donee,amount,donation_date,donation_date_precision,donation_date_basis,cause_area,url,notes) values
  ('Zvi Mowshowitz','Center for Applied Rationality',4000,'2017-12-25','day','date of donation announcement','Epistemic institutions','https://thezvi.wordpress.com/2017/12/25/the-story-cfar/','The document explains the motivation to donate to CFAR in addition to the $10,000 donation to MIRI documented at https://thezvi.wordpress.com/2017/12/17/i-vouch-for-miri/ The reasons for donating to CFAR include: endorsement of rationality improvement, endorsement of CFAR as an organization and its approach to the problem, direct personal benefits, and an especially important time for CFAR because they need enough funding for a venue');
