create table documents (
  document_id int(11) not null auto_increment primary key,
  url varchar(200),
  title varchar(200),
  publication_date date,
  modified_date date,
  author varchar(40),
  publisher varchar(40),
  affected_donors varchar(1000),
  affected_donees varchar(1000),
  document_scope enum('Broad donor strategy','Single donation documentation','Donee periodic update','Donee donation case','Evaluator review of donee','Evaluator update on donee','Evaluator consolidated recommendation list','Periodic donation list documentation','Reasoning supplement','Third-party coverage of donor strategy','Third-party case for donation','Third-party case against donation','Donation suggestion list', 'Unsolicited third-party suggestions for donor'),
  notes varchar(2000),
  unique key url(`url`)
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://www.openphilanthropy.org/blog/good-ventures-and-giving-now-vs-later-2016-update','Good Ventures and Giving Now vs. Later (2016 Update)','2016-12-28','2016-12-28','Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Malaria Consortium,Sightsavers,END Fund,Development Media International,Food Fortification Initiative,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods,Project Healthy Children','Reasoning supplement','Explanation of reasoning that led to $50 million allocation to GiveWell top charities'),
  ('http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/','Our updated top charities for giving season 2016','2016-11-28','2016-12-15','Natalie Stone-Crispin','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Malaria Consortium,Sightsavers,END Fund,Development Media International,Food Fortification Initiative,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods,Project Healthy Children','Evaluator consolidated recommendation list','GiveWell annual top charity refresh, also announced amounts recommended for Good Ventures to donate to top charities. Added three new top charities'),
  ('http://blog.givewell.org/2016/06/23/top-charities-refresh/','Mid-year update to top charity recommendations','2016-06-23','2016-07-28','Natalie Stone-Crispin','GiveWell',NULL,'GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly','Evaluator consolidated recommendation list','First mid-year refresh of top charities from GiveWell. No change to charity list, and no donation recommended for Good Ventures'),
  ('http://blog.givewell.org/2016/06/20/weve-learned-sci-year/','What we’ve learned about SCI this year','2016-06-20','2016-09-15','Andrew Martin','GiveWell',NULL,'Schistosomiasis Control Initiative','Evaluator update on donee','Discovery of some financial errors, but affirmed continued top charity status for now'),
  ('http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/','Our updated top charities for giving season 2015','2015-11-20','2016-08-03','Elie Hassenfeld,Josh Rosenberg','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Development Media International,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods','Evaluator consolidated recommendation list','No change to charity list; significant funding recommended from Good Ventures. This would be later classified as Open Philanthropy Project spending'),
  ('http://blog.givewell.org/2014/12/01/our-updated-top-charities/','Our updated top charities','2014-12-01','2015-05-04','Elie Hassenfeld','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Development Media International,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods','Evaluator consolidated recommendation list','Against Malaria Foundation returned to top charities list. Amounts donated by Good Ventures would later be classified as Open Philanthropy Project spending'),
  ('http://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/','GiveWell’s top charities for giving season 2013','2013-12-01','2016-07-25','Holden Karnofsky','GiveWell','Open Philanthropy Project,Good Ventures','Against Malaria Foundation,GiveDirectly,Schistosomiasis Control Initiative,Deworm the World Initiative','Evaluator consolidated recommendation list','Against Malaria Foundation not in top charities list (it was in 2013) due to room for more funding issues. Good Ventures allocations not included in this post'),
  ('http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans','Our Giving Season Plans','2013-12-03',NULL,'Cari Tuna','Good Ventures','Open Philanthropy Project,Good Ventures','GiveDirectly,Deworm the World Initiative,Schistosomiasis Control Initiative','Periodic donation list documentation','Good Ventures announced $2 million to GiveDirectly, $1.5 million to DtWI, and $750000 to SCI. Also announced up to $5 million in matching funds for GiveDirectly, despite disagreement from GiveWell'),
  ('http://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/','Our top charities for the 2012 giving season','2012-11-26','2016-07-25','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,GiveDirectly,Schistosomiasis Control Initiative','Evaluator consolidated recommendation list','GiveDirectly promoted from standout to top charity, other two charities same as for 2011'),
  ('http://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/','Top charities for holiday season 2011: Against Malaria Foundation and Schistosomiasis Control Initiative','2011-11-29','2011-12-08','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,GiveDirectly,Innovations for Poverty Action,Nyaya Health,Pratham,Small Enterprise Foundation','Evaluator consolidated recommendation list','Against Malaria Foundation and Schistosomiasis Control Initiative were the top charities; the others were standouts'),
  ('http://blog.givewell.org/2011/12/08/deciding-between-two-outstanding-charities/','Deciding between two outstanding charities','2011-12-08','2011-12-08','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative','Reasoning supplement','Provided more in-depth coverage of tradeoffs between the two top charities, supplementing the announcement post at http://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/');

# -- Open Phil farm animal welfare strategy
  
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://www.openphilanthropy.org/blog/initial-grants-support-corporate-cage-free-reforms','Initial Grants to Support Corporate Cage-free Reforms','2016-03-31',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','The Humane League,Mercy for Animals,Humane Society of the United States','Broad donor strategy','Written to explain a bunch of grants already made in 2016-02 to support cage-free reforms in the United States for egg-laying chicken. The blog post had a heated comment section, potentially influencing future Open Phil communication on the subject'),
  ('http://www.huffingtonpost.com/entry/chickens-animal-abuse-video_us_57fac5c5e4b0e655eab5485d','Grisly Undercover Video Shows Chickens Being Starved To Produce More Eggs','2016-10-11',NULL,'Nico Pitney','Huffington Post','Open Philanthropy Project','Humane Society International,Mercy for Animals,Animal Equality,People for Animals,The Humane League','Third-party coverage of donor strategy','Provides some context for the move by the Open Philanthropy Project in mid-2016 to expand its cage-free campaign funding internationally'),
  ('https://www.facebook.com/groups/EffectiveAnimalActivism/permalink/656583861179155/','The Open Philanthropy Project just announced our latest grant to WildAid in China','2016-10-25',NULL,'Lewis Bollard','Open Philanthropy Project','Open Philanthropy Project','Green Monday,World Animal Protection,Brighter Green,WildAid','Broad donor strategy','Announcement of strategy on Facebook; might do an official blog post later'),
  ('https://www.facebook.com/groups/EffectiveAnimalActivism/search/?query=broiler%20chicken','Broiler chicken search in Effective Animal Activism group on Facebook','2016-08-27','2016-12-14','Brian Tomasik,Chris Byrd',NULL,'Third-party coverage of donor strategy','Humane Society of the United States,Mercy for Animals','Third-party coverage of donor strategy','Just a few Facebook posts -- no coherent strategy articulation yet');

# -- Animal Charity Evaluators recommendations

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('https://animalcharityevaluators.org/blog/updated-recommendations-december-2015/','Updated Recommendations: December 2015','2015-12-01',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Animal Equality,Mercy for Animals,The Humane League,Animal Ethics,Animals Australia,Faunalytics,New Harvest,Nonhuman Rights Project,Albert Schweitzer Foundation for Our Contemporaries,Humane Society of the United States,Vegan Outreach','Evaluator consolidated recommendation list','2015 recommendations list; top charities are Animal Equality,Mercy for Animals, and The Humane League; five new standout charities added to existing four'),
  ('https://animalcharityevaluators.org/blog/updated-recommendations-december-2016/','Updated Recommendations: December 2016','2016-11-28',NULL,'Jon Bockman','Animal Charity Evaluators',NULL,'Mercy for Animals,The Humane League,The Good Food Institute,VEBU,Animal Equality,Humane Society of the United States,Vegan Outreach,Albert Schweitzer Foundation for Our Contemporaries','Evaluator consolidated recommendation list','Mercy for Animals and The Humane League remain top charities, and The Good Food Institute added to the list; Animal Equality moved from top charity to standout charity; VEBU added to standout charities');

# -- Giving What We Can recommendations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('https://www.givingwhatwecan.org/post/2015/12/giving-what-we-cans-recommendations-for-giving-season-2015/','Giving What We Can’s Recommendations for Giving Season 2015','2015-12-16','2015-12-17','Hauke Hillebrandt','Giving What We Can',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,Project Healthy Children','Evaluator consolidated recommendation list','Same charities as for 2014 (i.e., no change to list). Noted that Project Healthy Children is a good option for those concerned about crowding out by GiveWell-moved money (since GiveWell had not recommended it). Also, noted GiveDirectly as a fallback option for people concerned about scalability'),
  ('https://www.givingwhatwecan.org/post/2014/12/our-recommended-charities-year/','Our recommended charities for the year','2014-12-05','2015-11-10','Michelle Hutchinson','Giving What We Can',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,Project Healthy Children','Evaluator consolidated recommendation list','Same charity list as for 2013');

# -- Donee donation cases
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://effective-altruism.com/ea/14p/cea_is_fundraising_winter_2016/','CEA is Fundraising! (Winter 2016)','2016-12-06',NULL,'William MacAskill','Centre for Effective Altruism',NULL,'Centre for Effective Altruism','Donee donation case','CEA makes its case to be funded in 2016'),
  ('http://effective-altruism.com/ea/15d/why_donate_to_80000_hours/','Why donate to 80,000 Hours','2016-12-24',NULL,'Benjamin Todd','80000 Hours',NULL,'80000 Hours','Donee donation case','Makes the case for 80000 Hours to be funded by effective altruists (and posted on the Effective Altruism Forum). Supplements their annual review https://80000hours.org/2016/12/annual-review-dec-2016 that provides the underlying data and narrative; however, the case made here explicitly focuses on argumentation appealing to EAs, and makes a clearer ask'),
  ('http://lesswrong.com/r/discussion/lw/mj0/miri_fundraiser_why_now_matters/','MIRI Fundraiser: Why now matters','2015-07-24',NULL,'Nate Soares','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','Cross-posted at LessWrong and on the MIRI blog at https://intelligence.org/2015/07/20/why-now-matters/ -- this post occurs just two months after Soares takes over as MIRI Executive Director. It is a followup to https://intelligence.org/2015/07/17/miris-2015-summer-fundraiser/'),
  ('https://intelligence.org/2015/07/17/miris-2015-summer-fundraiser/','MIRI’s 2015 Summer Fundraiser!','2015-07-17',NULL,'Nate Soares','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','MIRI announces its summer fundraiser and links to a number of documents to help donors evaluate it. This is the first fundraiser under new Executive Director Nate Soares, just a couple months after he assumed office'),
  ('https://intelligence.org/2016/09/16/miris-2016-fundraiser/','MIRI’s 2016 Fundraiser','2016-09-16',NULL,'Nate Soares','Machine Intelligence Research Institute',NULL,'Machine Intelligence Research Institute','Donee donation case','MIRI announces its single 2016 fundraiser (as opposed to previous years when it conducted two fundraisers, it is conducting just one this time, in the Fall)'),
  ('http://lesswrong.com/lw/jej/why_cfar/','Why CFAR','2013-12-28',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Salamon, the boss of CFAR, explains the long-term goal (Competence, Epistemic Rationality, and Do-Gooding), plan, and progress to date. This is the first year for CFAR as a standalone organization, after its spinoff from MIRI. Funding situation is dire, with an emergency loan currently taken out that is due in three months. Comments include a $40K donation and a number of other donations'),
  ('http://lesswrong.com/lw/lfg/cfar_in_2014_continuing_to_climb_out_of_the/','CFAR in 2014: Continuing to climb out of the startup pit, heading toward a full prototype','2014-12-26',NULL,'Anna Salamon','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','CFAR reports better finances than 2013 (more stability), improvements to its curriculum, attempts to do a full prototype. There is a long discussion of how it redefined the way epistemic rationality fit into the curriculum (moving away from a separate low-rating module to something that is incorporated throughout the course through practical application). Comments are supportive, and include the first appearance of Gleb Tsipursky advertising Intentional Insights'),
  ('http://lesswrong.com/lw/n39/why_cfar_the_view_from_2015/','Why CFAR? The view from 2015','2015-12-23',NULL,'Pete Michaud','Center for Applied Rationality',NULL,'Center for Applied Rationality','Donee donation case','Reports 2015 as a year of consolidation and streamlining. Fewer workshops, more efforts to streamline both workshops and continued research on improving rationality. Consolidated original three goals (Competence, Epistemic Rationality, and Do-Gooding) into single framework of applying epistemic rationality. Emphasis on concept of double crux');

# -- Donation documentations
insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('https://acesounderglass.com/2016/12/01/5167/','Seeing Like A State, Flashlights, and Giving This Year','2016-12-01',NULL,'Elizabeth Van Nostrand','Personal blog','Elizabeth Van Nostrand,Ozy Brennan','Tostan','Third-party case for donation','Argues that donations to things that build capacity could be more valuable than donations to things with directly measured impact. Recommends Tostan for its capacity-building. The post influenced others to donate to Tostan: see https://thingofthings.wordpress.com/2016/12/22/donations-post-2016/ and https://acesounderglass.com/2017/01/05/tracking-donations/'),
  ('http://effective-altruism.com/ea/16b/why_i_donated_to_the_environmental_data/','Why I donated to the Environmental Data & Governance Initiative','2017-01-16',NULL,'Jacob Trefethen','Effective Altruism Forum','Jacob Trefethen','Environmental Data and Governance Initiative','Single donation documentation','Part 1 of the post focused on the case for donating to young, promising organizations. Part 2 explained why the author considered the specific donee a good fit'),
  ('http://effective-altruism.com/ea/15y/where_i_gave_and_why_in_2016/','Where I gave and why in 2016 ','2017-01-06',NULL,'Ben Kuhn','Effective Altruism Forum','Ben Kuhn','EA Giving Group,GiveWell,GiveDirectly','Periodic donation list documentation','Originally posted at http://www.benkuhn.net/giving-2016 and cross-posted to Effective Altruism Forum due to evidence that people like donation write-ups'),
  ('http://effective-altruism.com/ea/14u/eas_write_about_where_they_give/','EAs write about where they give','2016-12-09',NULL,'Julia Wise','Effective Altruism Forum','Blake Borgeson,Eva Vivalt,Ben Kuhn,Alexander Gordon-Brown and Denise Melchin,Elizabeth Van Nostrand','Machine Intelligence Research Institute,Center for Applied Rationality,AidGrade,Charity Science: Health,80000 Hours,Centre for Effective Altruism,Tostan','Periodic donation list documentation','Julia Wise got submissions from multiple donors about their donation plans and put them together in a single post. The goal was to cover people outside of organizations that publish such posts for their employees'),
  ('http://blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/','Staff members’ personal donations for giving season 2016','2016-12-09','2016-12-09','Natalie Stone-Crispin','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Timothy Telleen-Lawton,Josh Rosenberg,Rebecca Raible,Helen Toner,Sophie Monahan,Laura Muñoz,Catherine Hollander,Andrew Martin,Lewis Bollard,Chelsea Tabart,Sarah Ward,Chris Somerville,Ajeya Cotra,Chris Smith,Isabel Arjmand','A political campaign,GiveWell top charities,International Genetically Engineered Machine Foundation,UPMC Center for Health Security,Donor lottery,EA Giving Group,GiveDirectly,Center for Applied Rationality,Malaria Consortium,Animal Charity Evaluators,Northwest Health Law Advocates,Strong Minds,Against Malaria Foundation,Schistosomiasis Control Initiative,Humane Society of the United States,The Humane League,Mercy for Animals,Humane Society International,Compassion in World Farming USA,The Good Food Institute,Citizens for Farm Animal Protection,END Fund,Causa Justa,Planned Parenthood,International Refugee Assistance Project','Periodic donation list documentation','GiveWell and Open Philanthropy Project staff describe their annual donation plans for 2016. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('http://blog.givewell.org/2015/12/09/staff-members-personal-donations-for-giving-season-2015/','Staff members’ personal donations for giving season 2015','2015-12-09','2016-12-09','Elie Hassenfeld','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Timothy Telleen-Lawton,Sean Conley,Josh Rosenberg,Jake Marcus,Rebecca Raible,Milan Griffes,Helen Toner,Sophie Monahan,Laura Muñoz,Catherine Hollander,Andrew Martin,Claire Zabel,Nicole Ross,Lewis Bollard','GiveWell top charities,Against Malaria Foundation,GiveWell,GiveDirectly,Wikimedia Foundation,Center for Global Development,Martha’s Table,Country Dance and Song Society,Northwest Health Law Advocates,Mercy for Animals,The Humane League,Animal Charity Evaluators,Raising for Effective Giving,Humane Society of te United States','Periodic donation list documentation','GiveWell and Open Philanthropy Project staff describe their annual donation plans for 2015. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('http://blog.givewell.org/2014/12/17/staff-members-personal-donations-giving-season-2014/','Staff members’ personal donations – giving season 2014','2014-12-17','2016-12-09','Holden Karnofsky','GiveWell','Elie Hassenfeld,Holden Karnofsky,Natalie Stone-Crispin,Alexander Berger,Eliza Scheffler,Timothy Telleen-Lawton,Josh Rosenberg,Ben Rachbach,Jake Marcus,Rebecca Raible,Milan Griffes,Tyler Heishman','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveWell standout charities','Periodic donation list documentation','GiveWell staff describe their annual donation plans for 2014. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('http://blog.givewell.org/2013/12/12/staff-members-personal-donations/','Staff members’ personal donations','2013-12-12','2016-12-09','Holden Karnofsky','GiveWell','Holden Karnofsky,Elie Hassenfeld,Alexander Berger,Natalie Stone-Crispin,Eliza Scheffler,Timothy Telleen-Lawton,Sean Conley,Josh Rosenberg,Ben Rachbach,Howie Lempel,Jake Marcus','GiveDirectly,Mercy for Animals,Schistosomiasis Control Initiative,Against Malaria Foundation,Deworm the World Initiative,Humane Society of the United States','Periodic donation list documentation','GiveWell staff describe their annual donation plans for 2013. Some of these are tentative and get superseded by further events. Also, not all employees are present in the document (participation is optional). Amounts donated are not included, per a decision by GiveWell'),
  ('https://www.centreforeffectivealtruism.org/blog/cea-staff-donation-decisions-2016/','CEA Staff Donation Decisions 2016','2016-12-06','2016-12-07','Sam Deere','Centre for Effective Altruism','William MacAskill,Michelle Hutchinson,Tara MacAulay,Alison Woodman,Seb Farquhar,Hauke Hillebrandt,Marinella Capriati,Sam Deere,Max Dalton,Larissa Hesketh-Rowe,Michael Page,Stefan Schubert,Pablo Stafforini,Amy Labenz','Centre for Effective Altruism,80000 Hours,Against Malaria Foundation,Schistosomiasis Control Initiative,Animal Charity Evaluators,Charity Science: Health,New Incentives,Project Healthy Children,Deworm the World Initiative,Machine Intelligence Research Institute,Strong Minds,Future of Humanity Institute,Future of Life Institute,Centre for the Study of Existential Risk,Effective Altruism Foundation,Sci-Hub,Vote.org,The Humane League,Foundational Research Institute','Periodic donation list documentation','Centre for Effective Altruism (CEA) staff describe their donation plans. The donation amounts are not disclosed.'),
  ('http://www.openphilanthropy.org/blog/suggestions-individual-donors-open-philanthropy-project-staff-2016','Suggestions for Individual Donors from Open Philanthropy Project Staff - 2016','2016-12-14',NULL,'Holden Karnofsky','Open Philanthropy Project','','','Donation suggestion list','Open Philanthropy Project staff describe suggestions for best donation opportunities for individual donors in their specific areas'),
  ('https://animalcharityevaluators.org/blog/where-the-ace-staff-members-are-giving-in-2016-and-why/','Where the ACE Staff Members are Giving in 2016 and Why','2016-12-23',NULL,'Leah Edgerton','Animal Charity Evaluators','Allison Smith,Jacy Reese,Toni Adleberg,Gina Stuessy,Kieran Grieg,Eric Herboso,Erika Alonso','Animal Charity Evaluators,Animal Equality,Vegan Outreach,Act Asia,Faunalytics,Farm Animal Rights Movement,Sentience Politics,Direct Action Everywhere,The Humane League,The Good Food Institute,Collectively Free,Planned Parenthood,Future of Life Institute,Future of Humanity Institute,GiveDirectly,Machine Intelligence Research Institute,Humane Society of the United States,Farm Sanctuary,Strong Minds','Periodic donation list documentation','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2016'),
  ('https://animalcharityevaluators.org/blog/where-ace-staff-are-giving-and-why/','Where the ACE Staff Members Are Giving and Why','2015-12-21',NULL,'Leah Edgerton','Animal Charity Evaluators','Jon Bockman,Allison Smith,Erika Alonso,Jacy Reese,Kieran Grieg','Animal Charity Evaluators,Vegan Outreach,Mercy for Animals,Direct Action Everywhere,The Humane League,Animal Equality,Farm Sanctuary,Humane Society of the United States,Animal Equality,Nonhuman Rights Project,New Harvest,Charity Science,Schistosomiasis Control Initiative,Raising for Effective Giving','Periodic donation list documentation','Animal Charity Evaluators (ACE) staff describe where they donated or plan to donate in 2015');

# -- ('https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016','

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://effective-altruism.com/ea/134/where_i_am_donating_in_2016/','Where I Am Donating in 2016','2016-11-01',NULL,'Michael Dickens','Effective Altruism Forum','Michael Dickens','Animal Charity Evaluators,The Good Food Institute,Mercy for Animals,Raising for Effective Giving','Single donation documentation','Dickens described his evaluation of each of the four finalists and the reasoning behind his (tentatively) final decision to The Good Food Institute'),
  ('http://effective-altruism.com/ea/10t/why_the_open_philanthropy_project_should/','Why the Open Philanthropy Project Should Prioritize Wild Animal Suffering','2016-08-26',NULL,'Michael Dickens','Effective Altruism Forum','Open Philanthropy Project',NULL,'Unsolicited third-party suggestions for donor','Michael Dickens offers reasons that the Open Philanthropy Project should prioritize Wild Animal Suffering. He writes: "What we need is a large, committed source of funding to jump-start the cause. If the Open Philanthropy Project began funding work on wild animal suffering, it could stimulate new research efforts or small-scale interventions by offering grants. Specifically, Open Phil should probably create a new focus area for wild animal suffering and possibly hire dedicated staff. This problem has such large scale, and so many possible interventions, that it absolutely deserves to be a dedicated focus area. Open Phil might consider lumping WAS under its farm animal welfare program, but this would excessively constrain its budget and limit the amount of staff time that it could receive. Wild animal suffering is a massive problem, and easily deserves as much attention as most of Open Phil’s other focus areas."'),
  ('http://effective-altruism.com/ea/ns/my_cause_selection_michael_dickens/','My Cause Selection: Michael Dickens','2015-09-15',NULL,'Michael Dickens','Effective Altruism Forum','Michael Dickens','Machine Intelligence Research Institute,Future of Humanity Institute,Centre for the Study of Existential Risk,Future of Life Institute,Open Philanthropy Project,Animal Charity Evaluators,Animal Ethics,Foundational Research Institute,Giving What We Can,Charity Science,Raising for Effective Giving','Single donation documentation','Explanation by Dickens of giving choice for 2015. After some consideration, narrows choice to three orgs: MIRI, ACE, and REG. Finally chooses REG due to weighted donation multiplier');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('https://jsteinhardt.wordpress.com/2016/12/28/donations-for-2016','Donations for 2016','2016-12-28',NULL,'Jacob Steinhardt',NULL,'Jacob Steinhardt','Donor lottery,GiveWell top charities,GiveDirectly,Blue Ribbon Study Panel,Carnegie Endowment for International Peace','Periodic donation list documentation','Explanation for donation choices, also mention experimental funding of smaller projects');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://effective-altruism.com/ea/128/students_for_high_impact_charity_review_and_10k/','Students for High Impact Charity: Review and $10K Grant','2016-09-27',NULL,'Peter Hurford',NULL,'Peter Hurford','Students for High Impact Charity','Single donation documentation','Explanation of some of the investigative process that led the author to decide to donate to SHIC. The focus is on the investigation process and information revealed about SHIC rather than on the amount donated');

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://effective-altruism.com/ea/14w/2017_ai_risk_literature_review_and_charity/','2017 AI Risk Literature Review and Charity Comparison','2016-12-13',NULL,'Ben Hoskin',NULL,'Ben Hoskin','Machine Intelligence Research Institute,Future of Humanity Institute,OpenAI,Center for Human-Compatible AI,Future of Life Institute,Centre for the Study of Existential Risk,Global Catastrophic Risks Institute,Global Priorities Project,AI Impacts,Xrisks Institute,X-Risks Net,Center for Applied Rationality,80000 Hours,Raising for Effective Giving','Evaluator review of donee','The lengthy blog post covers all the published work of prominent organizations focused on existential risk. References http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#sources1007 for the MIRI part of it but notes the absence of information on the many other orgs'),
  ('http://effective-altruism.com/ea/14c/why_im_donating_to_miri_this_year/',"Why I'm donating to MIRI this year", #'
   '2016-11-30',NULL,'Owen Cotton-Barratt',NULL,'Owen Cotton-Barratt','Machine Intelligence Research Institute','Single donation documentation','Primary interest is in existential risk. Cited CoI and other reasons for not donating to own employer, Centre for Effective Altruism. Notes disagreements with MIRI, citing http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support#research but highlights need for epistemic humility'),
  ('http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support','Machine Intelligence Research Institute — General Support','2016-09-01',NULL,'Open Philanthropy Project','Open Philanthropy Project','Open Philanthropy Project','Machine Intelligence Research Institute','Evaluator review of donee','Open Phil writes about the grant at considerable length, more than it usually does. This is because it says that it has found the investigation difficult and believes that others may benefit from its process. The writeup also links to reviews of MIRI research by AI researchers, commissioned by Open Phil: http://files.openphilanthropy.org/files/Grants/MIRI/consolidated_public_reviews.pdf');


