create table documents (
  document_id int(11) not null auto_increment primary key,
  url varchar(200),
  title varchar(200),
  publication_date date,
  modified_date date,
  author varchar(40),
  publisher varchar(40),
  affected_donors varchar(500),
  affected_donees varchar(500),
  document_scope enum('Broad donor strategy','Single donation documentation','Donee periodic update','Donee donation case','Evaluator review of donee','Evaluator update on donee','Evaluator consolidated recommendation list','Periodic donation list documentation','Reasoning supplement'),
  notes varchar(2000),
  unique key url(`url`)
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into documents(url,title,publication_date,modified_date,author,publisher,affected_donors,affected_donees,document_scope,notes) values
  ('http://www.openphilanthropy.org/blog/good-ventures-and-giving-now-vs-later-2016-update','Good Ventures and Giving Now vs. Later (2016 Update)','2016-12-28','2016-12-28','Holden Karnofsky','Open Philanthropy Project','Open Philanthropy Project','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Malaria Consortium,Sightsavers,END Fund,Development Media International,Food Fortification Initiative,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods,Project Healthy Children','Reasoning supplement','Explanation of reasoning that led to $50 million allocation to GiveWell top charities'),
  ('http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/','Our updated top charities for giving season 2016','2016-11-28','2016-12-15','Natalie Stone-Crispin','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Malaria Consortium,Sightsavers,END Fund,Development Media International,Food Fortification Initiative,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods,Project Healthy Children','Evaluator consolidated recommendation list','GiveWell annual top charity refresh, also announced amounts recommended for Good Ventures to donate to top charities. Added three new top charities'),
  ('http://blog.givewell.org/2016/06/23/top-charities-refresh/','Mid-year update to top charity recommendations','2016-06-23','2016-07-28','Natalie Stone-Crispin','GiveWell',NULL,'GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly','Evaluator consolidated recommendation list','First mid-year refresh of top charities from GiveWell. No change to charity list, and no donation recommended for Good Ventures'),
  ('http://blog.givewell.org/2016/06/20/weve-learned-sci-year/','What we’ve learned about SCI this year','2016-06-20','2016-09-15','Andrew Martin','GiveWell',NULL,'Schistosomiasis Control Initiative','Evaluator update on donee','Discovery of some financial errors, but affirmed continued top charity status for now'),
  ('http://blog.givewell.org/2015/11/18/our-updated-top-charities-for-giving-season-2015/','Our updated top charities for giving season 2015','2015-11-20','2016-08-03','Elie Hassenfeld,Josh Rosenberg','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Development Media International,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods','Evaluator consolidated recommendation list','No change to charity list; significant funding recommended from Good Ventures. This would be later classified as Open Philanthropy Project spending'),
  ('http://blog.givewell.org/2014/12/01/our-updated-top-charities/','Our updated top charities','2014-12-01','2015-05-04','Elie Hassenfeld','GiveWell','Open Philanthropy Project,Good Ventures','GiveWell top charities,Against Malaria Foundation,Schistosomiasis Control Initiative,Deworm the World Initiative,GiveDirectly,Development Media International,Global Alliance for Improved Nutrition,Iodine Global Network,Living Goods','Evaluator consolidated recommendation list','Against Malaria Foundation returned to top charities list. Amounts donated by Good Ventures would later be classified as Open Philanthropy Project spending'),
  ('http://blog.givewell.org/2013/12/01/givewells-top-charities-for-giving-season-2013/','GiveWell’s top charities for giving season 2013','2013-12-01','2016-07-25','Holden Karnofsky','GiveWell','Open Philanthropy Project,Good Ventures','GiveDirectly,Schistosomiasis Control Initiative,Deworm the World Initiative','Evaluator consolidated recommendation list','Against Malaria Foundation not in top charities list (it was in 2013) due to room for more funding issues. Good Ventures allocations not included in this post'),
  ('http://www.goodventures.org/research-and-ideas/blog/our-giving-season-plans','Our Giving Season Plans','2013-12-03',NULL,'Cari Tuna','Good Ventures','Open Philanthropy Project,Good Ventures','GiveDirectly,Deworm the World Initiative,Schistosomiasis Control Initiative','Periodic donation list documentation','Good Ventures announced $2 million to GiveDirectly, $1.5 million to DtWI, and $750000 to SCI. Also announced up to $5 million in matching funds for GiveDirectly, despite disagreement from GiveWell'),
  ('http://blog.givewell.org/2012/11/26/our-top-charities-for-the-2012-giving-season/','Our top charities for the 2012 giving season','2012-11-26','2016-07-25','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,GiveDirectly,Schistosomiasis Control Initiative','Evaluator consolidated recommendation list','GiveDirectly promoted from standout to top charity, other two charities same as for 2011'),
  ('http://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/','Top charities for holiday season 2011: Against Malaria Foundation and Schistosomiasis Control Initiative','2011-11-29','2011-12-08','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative,GiveDirectly,Innovations for Poverty Action,Nyaya Health,Pratham,Small Enterprise Foundation','Evaluator consolidated recommendation list','Against Malaria Foundation and Schistosomiasis Control Initiative were the top charities; the others were standouts'),
  ('http://blog.givewell.org/2011/12/08/deciding-between-two-outstanding-charities/','Deciding between two outstanding charities','2011-12-08','2011-12-08','Holden Karnofsky','GiveWell',NULL,'Against Malaria Foundation,Schistosomiasis Control Initiative','Reasoning supplement','Provided more in-depth coverage of tradeoffs between the two top charities, supplementing the announcement post at http://blog.givewell.org/2011/11/29/top-charities-for-holiday-season-2011-against-malaria-foundation-and-schistosomiasis-control-initiative/');
