create table donations (
    donation_id int(11) not null auto_increment primary key,
    donor varchar(40),
    donee varchar(80),
    amount float(14,2),
    fraction float(3, 2),
    donation_date date,
    cause_area varchar(100),
    url varchar(100),
    notes varchar(2000) DEFAULT NULL,
    payment_modality varchar(100),
    matched boolean,
    goal_amount float(14,2),
    influencer varchar(40)
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into donations(donor, donee, amount, fraction, donation_date,
    cause_area, url, notes, payment_modality, matched, goal_amount, influencer)
    values
    ('Vipul Naik', 'Wikimedia Foundation', 125.00, NULL, '2007-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Mozilla Foundation', 12.50, NULL, '2007-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Creative Commons', 25.00, NULL, '2007-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Children’s International', NULL, 1.00, '2008-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Children’s International', NULL, 1.00, '2009-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Children’s International', NULL, NULL, '2010-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'VillageReach', 1250.00, NULL, '2010-03-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'VillageReach', 2000.00, NULL, '2010-06-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', NULL, 7500.00, NULL, '2010-09-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'VillageReach', 5100.00, NULL, '2010-12-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', NULL, 500.00, NULL, '2011-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'GiveDirectly', 500.00, NULL, '2012-12-01', 'Global poverty',
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL, NULL),

    ('Peter Hurford', 'Obama for America', 5.00, NULL, '2011-12-31', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 10.00, NULL, '2011-12-31',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL, NULL),
    ('Peter Hurford', 'Obama for America', 20.00, NULL, '2012-03-31', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Obama for America', 20.00, NULL, '2012-04-30', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 200.00, NULL, '2012-04-10',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 123.00, NULL, '2012-05-10',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL, NULL),
    ('Peter Hurford', 'GiveDirectly', 20.00, NULL, '2012-12-18', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Animal Charity Evaluators', 660.00, NULL, '2012-12-25',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL, NULL),
    ('Peter Hurford', 'Center for Effective Altruism', 1700.00, NULL,
        '2013-07-04', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Center for Effective Altruism', 80.00, NULL,
        '2013-12-12', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Schistosomiasis Control Initiative', 33.00, NULL,
        '2013-12-22', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Machine Intelligence Research Institute', 90.00, NULL,
        '2014-05-06', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'GiveDirectly', 46.00, NULL, '2014-06-17', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Charity Science Outreach', 1000.00, NULL, '2014-06-12',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL, NULL),
    ('Peter Hurford', 'Charity Science Outreach', 1000.00, NULL, '2014-08-15',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL, NULL),
    ('Peter Hurford', '.impact', 79.00, NULL, '2014-09-07', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 516.00, NULL, '2014-09-30', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 13.00, NULL, '2014-11-25', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 435.00, NULL, '2014-12-14', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Center for Effective Altruism', 100.00, NULL,
        '2014-12-19', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 1259.00, NULL,
        '2014-12-31', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 1524.00, NULL,
        '2015-01-02', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Mercy for Animals', 1300.00, NULL,
        '2015-01-22', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Schistosomiasis Control Initiative', 519.00, NULL,
        '2015-03-22', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Schistosomiasis Control Initiative', 493.00, NULL,
        '2015-03-28', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Deworm the World', 177.00, NULL,
        '2015-04-06', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    /* this one is listed twice for some reason, not sure why */
    ('Peter Hurford', 'Deworm the World', 177.00, NULL,
        '2015-04-06', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 36.00, NULL,
        '2015-04-20', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Deworm the World', 45.00, NULL,
        '2015-04-23', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Charity Science Outreach', 5200.00, NULL,
        '2015-04-24', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 40.00, NULL,
        '2015-08-14', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Mercy for Animals', 2000.00, NULL,
        '2015-08-18', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 47.00, NULL,
        '2015-09-03', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 500.00, NULL,
        '2015-09-03', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 150.00, NULL,
        '2015-12-03', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Reducetarian Foundation', 2500.00, NULL,
        '2015-12-16', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    /* this one is listed twice as well */
    ('Peter Hurford', 'Reducetarian Foundation', 2500.00, NULL,
        '2015-12-16', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Charity Entrepreneurship', 15717.00, NULL,
        '2015-12-23', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 5377.00, NULL,
        '2015-12-23', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Charity Entrepreneurship', 4283.00, NULL,
        '2015-12-23', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Schistosomiasis Control Initiative', 2650.00, NULL,
        '2015-12-22', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 106.00, NULL,
        '2016-01-11', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 90.00, NULL,
        '2016-03-01', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Animal Charity Evaluators', 12.00, NULL,
        '2016-03-26', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 7792.00, NULL,
        '2016-04-20', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Charity Science Outreach', 6000.00, NULL,
        '2016-04-20', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 100.00, NULL,
        '2016-04-29', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 12000.00, NULL,
        '2016-05-01', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 192.00, NULL,
        '2016-08-07', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 500.00, NULL,
        '2016-08-24', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Animal Charity Evaluators', 24.00, NULL,
        '2016-08-24', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 90.00, NULL,
        '2016-08-28', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 50.00, NULL,
        '2016-09-26', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 35.00, NULL,
        '2016-10-13', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Hillary for America', 25.00, NULL,
        '2016-11-05', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'My Ride to Vote', 25.00, NULL,
        '2016-11-07', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 13.00, NULL,
        '2016-11-28', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Defend Democracy PAC', 1000.00, NULL,
        '2016-12-14', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 1000.00, NULL,
        '2016-12-16', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Raising for Effective Giving', 50.00, NULL,
        '2016-12-24', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Animal Charity Evaluators', 1000.00, NULL,
        '2016-12-29', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Schistosomiasis Control Initiative', 337.00, NULL,
        '2016-12-30', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL, NULL),

    ('Jeff Kaufman', 'Against Malaria Foundation', 6000.00, NULL, '2017-01-05', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 6000.00, NULL, '2017-01-05', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 10000.00, NULL, '2016-12-24', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'EA Giving Group Fund', 80100.00, NULL, '2016-12-24', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 134.58, NULL, '2016-12-05', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 55000.00, NULL, '2016-06-25', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation2', 11.00, NULL, '2016-06-12', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Innovations for Poverty Action2', 20.00, NULL, '2016-06-12', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Nurse Family Partnership2', 69.00, NULL, '2016-06-12', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 10000.00, NULL, '2016-05-11', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Give Directly', 5000.00, NULL, '2016-02-24', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 79152.00, NULL, '2015-12-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 34152.00, NULL, '2015-12-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 5000.00, NULL, '2015-08-30', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 50000.00, NULL, '2015-05-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 6000.00, NULL, '2015-05-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'To GiveWell, for distribution to their top charities', 6443.00, NULL, '2014-12-31', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'To GiveWell, for distribution to their top charities', 57763.00, NULL, '2014-12-20', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Give Directly', 20.00, NULL, '2014-08-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 30000.00, NULL, '2014-07-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'To GiveWell, for distribution to their top charities', 4250.00, NULL, '2014-02-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'GiveWell', 100.00, NULL, '2014-02-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 30000.00, NULL, '2014-01-08', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 5800.00, NULL, '2014-01-08', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'To GiveWell, for distribution to their top charities', 13000.00, NULL, '2013-12-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 10000.00, NULL, '2013-12-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'To GiveWell, for distribution to their top charities', 1550.00, NULL, '2013-12-09', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 15000.00, NULL, '2013-08-11', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 1000.00, NULL, '2013-08-08', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Centre for Effective Altruism', 26000.00, NULL, '2013-08-08', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 10000.00, NULL, '2013-07-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 10000.00, NULL, '2013-06-26', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 6000.00, NULL, '2013-04-26', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 5800.00, NULL, '2013-04-26', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 400.00, NULL, '2013-02-08', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 6000.00, NULL, '2013-02-04', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 5800.00, NULL, '2013-02-04', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 200.00, NULL, '2013-01-21', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Giving What We Can', 4200.00, NULL, '2012-11-17', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', '80,000 Hours', 21053.00, NULL, '2012-11-07', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 19000.00, NULL, '2012-09-18', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 12000.00, NULL, '2012-09-18', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 1000.00, NULL, '2012-09-10', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 150.00, NULL, '2012-07-07', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 2000.00, NULL, '2012-06-04', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Schistomiasis Control Initiative', 31.00, NULL, '2012-05-28', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Against Malaria Foundation', 5000.00, NULL, '2012-01-29', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Schistomiasis Control Initiative', 500.00, NULL, '2012-01-29', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America, for monitoring and evaluation', 10000.00, NULL, '2010-10-17', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 75.00, NULL, '2010-07-23', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 1391.00, NULL, '2010-07-08', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 25.00, NULL, '2010-06-03', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 505.00, NULL, '2010-05-19', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 14000.00, NULL, '2010-05-10', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 10.00, NULL, '2010-02-23', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 10000.00, NULL, '2010-02-03', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 13000.00, NULL, '2009-11-10', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 719.00, NULL, '2009-11-04', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 10.00, NULL, '2009-09-11', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 50.00, NULL, '2009-04-15', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 7000.00, NULL, '2009-04-15', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 30.00, NULL, '2009-03-19', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 7000.00, NULL, '2009-02-19', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 3400.00, NULL, '2008-12-26', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 500.00, NULL, '2008-12-26', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 360.00, NULL, '2008-12-15', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 5000.00, NULL, '2008-10-11', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Oxfam America', 1500.00, NULL, '2008-07-26', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Save the Children', 336.00, NULL, '2007-01-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Save the Children', 336.00, NULL, '2006-01-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Save the Children', 336.00, NULL, '2005-01-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Save the Children', 168.00, NULL, '2004-01-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),
    ('Jeff Kaufman', 'Save the Children', 168.00, NULL, '2003-01-01', NULL, 'https://www.jefftk.com/donations', NULL, NULL, NULL, NULL, NULL),

    ('Ben Kuhn', 'GiveDirectly', 120.00, NULL, '2013-07-06', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'Schistosomiasis Control Initiative', 80.00, NULL, '2013-07-06', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'Against Malaria Foundation', 200.00, NULL, '2013-07-06', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'GiveWell (unrestricted)', 6000.00, NULL, '2013-11-22', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'GiveWell (unrestricted)', 10000.00, NULL, '2014-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'GiveWell (unrestricted)', 10000.00, NULL, '2015-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', NULL, 18333.00, NULL, NULL, NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'EA Policy Analytics', 6333.00, NULL, '2015-06-07', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'GiveWell (unrestricted)', 10000.00, NULL, '2015-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'Charity Entrepreneurship', 2000.00, NULL, '2015-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'EA Giving Group', 10000.00, NULL, '2016-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', NULL, 26000.00, NULL, NULL, NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'GiveDirectly', 1000.00, NULL, '2016-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'GiveWell top charities', 5000.00, NULL, '2016-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),
    ('Ben Kuhn', 'EA Giving Group', 20000.00, NULL, '2016-12-31', NULL, 'http://www.benkuhn.net/ea/', NULL, NULL, NULL, NULL, NULL),

    ('Michael Dickens', 'The Humane League', 500.00, NULL, '2014-05-01', NULL, 'http://mdickens.me/donations/', NULL, NULL, NULL, NULL, NULL),
    ('Michael Dickens', 'Animal Charity Evaluators', 3000.00, NULL, '2015-05-01', NULL, 'http://mdickens.me/donations/', NULL, NULL, NULL, NULL, NULL),
    ('Michael Dickens', 'Raising for Effective Giving', 20000.00, NULL, '2015-10-01', NULL, 'http://mdickens.me/donations/', NULL, NULL, NULL, NULL, NULL),
    ('Michael Dickens', 'The Humane League', 20.00, NULL, '2015-11-01', NULL, 'http://mdickens.me/donations/small.html', NULL, NULL, NULL, NULL, NULL),
    ('Michael Dickens', 'Raising for Effective Giving', 20.00, NULL, '2015-12-01', NULL, 'http://mdickens.me/donations/small.html', NULL, NULL, NULL, NULL, NULL),
    ('Michael Dickens', 'Machine Intelligence Research Institute', 20.00, NULL, '2016-01-01', NULL, 'http://mdickens.me/donations/small.html', NULL, NULL, NULL, NULL, NULL),
    ('Michael Dickens', 'Animal Equality', 10.00, NULL, '2016-03-01', NULL, 'http://mdickens.me/donations/small.html', NULL, NULL, NULL, NULL, NULL),

    ('Timothy Telleen-Lawton', 'Donor lottery', 5000.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Gregory Lewis', 'Donor lottery', 5000.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Ajeya Cotra', 'Donor lottery', 2200.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Rohin Shah', 'Donor lottery', 2800.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Helen Toner', 'Donor lottery', 2500.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Nicole Ross', 'Donor lottery', 500.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Howie Lempel', 'Donor lottery', 5000.00, NULL, '2016-12-07', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Rebecca Raible', 'Donor lottery', 2000.00, NULL, '2016-12-12', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Pablo Stafforini', 'Donor lottery', 2000.00, NULL, '2016-12-12', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Aaron Gertler', 'Donor lottery', 500.00, NULL, '2016-12-16', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Brayden McLean', 'Donor lottery', 5000.00, NULL, '2016-12-24', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Benjamin Hoffman', 'Donor lottery', 100.00, NULL, '2016-12-24', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Catherine Olsson', 'Donor lottery', 500.00, NULL, '2016-12-26', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Eric Herboso', 'Donor lottery', 500.00, NULL, '2016-12-31', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Ian David Moss', 'Donor lottery', 2500.00, NULL, '2016-12-31', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Glenn Willen', 'Donor lottery', 500.00, NULL, '2017-01-02', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL),
    ('Jacob Steinhardt', 'Donor lottery', 4000.00, NULL, '2017-01-04', NULL, 'http://effective-altruism.com/ea/14d/donor_lotteries_a_stepbystep_guide_for_mall/', NULL, NULL, NULL, NULL, NULL)
;
