create table donations (
    donation_id int(11) not null auto_increment primary key,
    donor varchar(40),
    donee varchar(40),
    amount float(14,2),
    fraction float(3, 2),
    donation_date date,
    cause_area varchar(100),
    url varchar(100),
    notes varchar(2000) DEFAULT NULL,
    payment_modality varchar(100),
    matched boolean,
    goal_amount float(14,2)
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into donations(donor, donee, amount, fraction, donation_date,
    cause_area, url, notes, payment_modality, matched, goal_amount) values
    ('Vipul Naik', 'Wikimedia Foundation', 125.00, NULL, '2007-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Mozilla Foundation', 12.50, NULL, '2007-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Creative Commons', 25.00, NULL, '2007-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Children’s International', NULL, 1.00, '2008-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Children’s International', NULL, 1.00, '2009-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'Children’s International', NULL, NULL, '2010-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'VillageReach', 1250.00, NULL, '2010-03-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'VillageReach', 2000.00, NULL, '2010-06-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', NULL, 7500.00, NULL, '2010-09-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'VillageReach', 5100.00, NULL, '2010-12-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', NULL, 500.00, NULL, '2011-01-01', NULL,
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),
    ('Vipul Naik', 'GiveDirectly', 500.00, NULL, '2012-12-01', 'Global poverty',
        'https://vipulnaik.com/donation-history/', NULL, NULL, NULL, NULL),

    ('Peter Hurford', 'Obama for America', 5.00, NULL, '2011-12-31', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 10.00, NULL, '2011-12-31',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL),
    ('Peter Hurford', 'Obama for America', 20.00, NULL, '2012-03-31', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Obama for America', 20.00, NULL, '2012-04-30', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 200.00, NULL, '2012-04-10',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 123.00, NULL, '2012-05-10',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL),
    ('Peter Hurford', 'GiveDirectly', 20.00, NULL, '2012-12-18', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Animal Charity Evaluators', 660.00, NULL, '2012-12-25',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL),
    ('Peter Hurford', 'Center for Effective Altruism', 1700.00, NULL,
        '2013-07-04', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Center for Effective Altruism', 80.00, NULL,
        '2013-12-12', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Schistosomiasis Control Initiative', 33.00, NULL,
        '2013-12-22', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Machine Intelligence Research Institute', 90.00, NULL,
        '2014-05-06', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'GiveDirectly', 46.00, NULL, '2014-06-17', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Charity Science Outreach', 1000.00, NULL, '2014-06-12',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL),
    ('Peter Hurford', 'Charity Science Outreach', 1000.00, NULL, '2014-08-15',
        NULL, 'http://peterhurford.com/other/donations.html', NULL, NULL, NULL,
        NULL),
    ('Peter Hurford', '.impact', 79.00, NULL, '2014-09-07', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 516.00, NULL, '2014-09-30', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 13.00, NULL, '2014-11-25', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', '.impact', 435.00, NULL, '2014-12-14', NULL,
        'http://peterhurford.com/other/donations.html', NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Center for Effective Altruism', 100.00, NULL,
        '2014-12-19', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL),
    ('Peter Hurford', 'Against Malaria Foundation', 1259.00, NULL,
        '2014-12-31', NULL, 'http://peterhurford.com/other/donations.html',
        NULL, NULL, NULL, NULL),
;
