create table donees (
    donee_id int(11) not null auto_increment primary key,
    donee_type enum('Private nonprofit','Donor-advised fund','Subsidiary') default 'Private nonprofit',
    donee varchar(100) not null,
    former_name varchar(100),
    country varchar(40), # -- Country of main activity
    bay_area boolean, # -- Whether the person currently lives in the San Francisco Bay Area
    facebook_username varchar(100),
    website varchar(100),
    donate_page varchar(200),
    donor_list_page varchar(200),
    transparency_and_financials_page varchar(200),
    donation_case_page varchar(1000), # -- The most recent case(s) made for donations to the org
    donation_statistics_page varchar(1000),
    contact_email varchar(40),
    twitter_username varchar(40),
    eahub_username varchar(40),
    wikipedia_page varchar(100),
    givewell_review varchar(100),
    open_phil_grant_review varchar(200),
    ace_review varchar(200),
    key_people varchar(2000),
    cause_area varchar(2000),
    recommenders varchar(2000),
    launch_date date,
    launch_date_precision enum('day','month','year','multi-year'),
    launch_date_url varchar(200),
    notes varchar(2000) default null,
    youtube_username varchar(100),
    instagram_username varchar(100),
    tumblr_subdomain varchar(100),
    medium_username varchar(100),
    pinterest_username varchar(100),
    charity_navigator_page varchar(100),
    guidestar_page varchar(100),
    timelines_wiki_page varchar(100)
    unique key donee(`donee`)
) ENGINE=InnoDB AUTO_INCREMENT=15239276 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

# -- AI risk donees
insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url, charity_navigator_page, guidestar_page, timelines_wiki_page) values
  ('Machine Intelligence Research Institute','Singularity Institute for Artificial Intelligence','United States',true,'MachineIntelligenceResearchInstitute','https://intelligence.org','https://intelligence.org/donate/','https://intelligence.org/topdonors/','https://intelligence.org/transparency/','http://effective-altruism.com/ea/12n/miri_update_and_fundraising_case/',NULL,'MIRIBerkeley','miri','https://en.wikipedia.org/wiki/Machine_Intelligence_Research_Institute',NULL,'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/machine-intelligence-research-institute-general-support',NULL,'Eliezer Yudkowsky,Nate Soares,Luke Muehlhauser','AI risk',NULL,NULL,'MIRIBerkeley',NULL,NULL,NULL,NULL,'2000-01-01','year','https://intelligence.org/transparency/', 'https://www.charitynavigator.org/index.cfm?bay=search.profile&ein=582565917', 'https://www.guidestar.org/profile/58-2565917', 'https://timelines.issarice.com/wiki/Timeline_of_Machine_Intelligence_Research_Institute'),
  ('Center for Human-Compatible AI',NULL,'United States',true,NULL,'http://humancompatible.ai/','http://humancompatible.ai/get-involved#supporter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/uc-berkeley-center-human-compatible-ai',NULL,'Stuart Russsell,Bart Sellman,Michael Wellman,Andrew Critch','AI risk',NULL,'Received a 5.5 million dollar grant from the Open Philanthropy Project at the time of founding, with a 50% probability estimate that it would be a respected AI-related organization in two years',NULL,NULL,NULL,NULL,NULL,'2016-08-01','month','http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/uc-berkeley-center-human-compatible-ai', NULL, NULL, NULL),
  ('Future of Life Institute',NULL,NULL,false,'futureoflifeinstitute','https://futureoflife.org/',NULL,NULL,'https://futureoflife.org/tax-forms/','https://futureoflife.org/wp-content/uploads/2016/02/FLI-2015-Annual-Report.pdf',NULL,'FLIxrisk',NULL,'https://en.wikipedia.org/wiki/Future_of_Life_Institute',NULL,'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/future-life-institute-artificial-intelligence-risk-reduction',NULL,'Jaan Tallinn,Max Tegmark,Meia Chita-Tegmark,Viktoriya Krakovna,Anthony Aguirre','AI risk/other global catastrophic risks',NULL,NULL,'UC-rCCy3FQ-GItDimSR9lhzw',NULL,NULL,NULL,NULL,'2014-03-01','month','https://en.wikipedia.org/wiki/Future_of_Life_Institute', NULL, NULL, NULL),
  ('OpenAI',NULL,'United States',true,'openai.research','https://openai.com/',NULL,NULL,NULL,NULL,NULL,'openai',NULL,'https://en.wikipedia.org/wiki/OpenAI',NULL,'http://www.openphilanthropy.org/focus/global-catastrophic-risks/potential-risks-advanced-artificial-intelligence/openai-general-support',NULL,'Sam Altman,Elon Musk,Ilya Sutskever,Ian Goodfellow,Greg Brockman','AI risk',NULL,'Started by Sam Altman and Elon Musk (with billion dollar commitment from Musk) to help with safe creation of human-level artificial intelligence in an open and robust way',NULL,NULL,NULL,NULL,NULL,'2015-12-11','day','https://medium.com/backchannel/how-elon-musk-and-y-combinator-plan-to-stop-computers-from-taking-over-17e0e27dd02a', NULL, NULL, NULL),
  ('Berkeley Existential Risk Initiative',NULL,'United States',true,NULL,'http://existence.org/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Andrew Critch,Gina Stuessy,Michael Keenan','AI risk/other global catastrophic risks','Nick Beckstead','Launched to provide fast-moving support to existing existential risk organizations. Works closely with Machine Intelligence Research Institute, Center for Human-Compatible AI, Centre for the Study of Existential Risk, and Future of Humanity Institute. People working at it are closely involved with MIRI and the Center for Applied Rationality',NULL,NULL,NULL,NULL,NULL,'2017-01-01','year',NULL, NULL, NULL, NULL);

# -- Global health donees
insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url, charity_navigator_page, guidestar_page, timelines_wiki_page) values
  ('Against Malaria Foundation',NULL,'United Kingdom',false,'AgainstMalaria','https://www.againstmalaria.com/','https://www.againstmalaria.com/Donation.aspx','https://www.againstmalaria.com/Donations.aspx','https://www.againstmalaria.com/Transparency.aspx',NULL,'https://www.againstmalaria.com/DonationStatistics.aspx','againstmalaria','against-malaria-foundation','https://en.wikipedia.org/wiki/Against_Malaria_Foundation','http://www.givewell.org/charities/against-malaria-foundation',NULL,NULL,'Rob Mather','Global health/malaria','GiveWell,Giving What We Can,The Life You Can Save,Charity Science',NULL,'AgainstMalaria',NULL,NULL,NULL, NULL,'2004-01-01','year','https://www.againstmalaria.com/History.aspx', 'https://www.charitynavigator.org/index.cfm?bay=search.profile&ein=203069841', 'https://www.guidestar.org/profile/20-3069841', 'https://timelines.issarice.com/wiki/Timeline_of_Against_Malaria_Foundation'),
  ('Schistosomiasis Control Initiative',NULL,'United Kingdom',false,NULL,'http://www.imperial.ac.uk/schistosomiasis-control-initiative','http://www.imperial.ac.uk/schistosomiasis-control-initiative/donate/',NULL,'http://www.imperial.ac.uk/schistosomiasis-control-initiative/about/financial-statement/',NULL,NULL,'sci_ntds','sci-schistosomiasis-control-initiative','https://en.wikipedia.org/wiki/Schistosomiasis_Control_Initiative','http://www.givewell.org/charities/schistosomiasis-control-initiative',NULL,NULL,NULL,'Global health/deworming','GiveWell,Giving What We Can,The Life You Can Save,Charity Science','Subsidiary of Imperial College London','schisto2002',NULL,NULL,NULL,NULL,'2002-01-01','year','https://en.wikipedia.org/wiki/Schistosomiasis_Control_Initiative', NULL, NULL, NULL),
  ('Deworm the World Initiative','Deworm the World','United States',false,NULL,'https://www.evidenceaction.org/dewormtheworld/','https://www.evidenceaction.org/give',NULL,NULL,'https://www.evidenceaction.org/dewormtheworld/',NULL,'dewormtheworld','deworm-world-initiative','https://en.wikipedia.org/wiki/Deworm_the_World_Initiative','http://www.givewell.org/charities/deworm-world-initiative',NULL,NULL,NULL,'Global health/deworming','GiveWell,Giving What We Can,The Life You Can Save,Charity Science','The initiative is run by Evidence Action, which also runs some other evidence-based programs in domains related to global health and global poverty. Previously, it was supported by the Partnership for Child Development and Innovations for Poverty Action, and simply called "Deworm the World". The program was originally created by MIT Professor Kristin J. Forbes in 2007 along with Esther Duflo, as an initiative of the Forum of Young Global Leaders. It has worked with te Clinton Health Access Initiative and the Abdul Latif Jameel Poverty Action Lab','DEWORMWORLD',NULL,NULL,NULL,NULL,'2007-01-01','year','http://news.mit.edu/2010/deworming-forbes', NULL, NULL, NULL);

# -- Animal welfare and rights donees
insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url, charity_navigator_page, guidestar_page, timelines_wiki_page) values
  ('Vegan Outreach','Animal Liberation Action','United States',false,'veganoutreach','http://veganoutreach.org','http://veganoutreach.org/donate/',NULL,NULL,NULL,NULL,'veganoutreach',NULL,'https://en.wikipedia.org/wiki/Vegan_Outreach',NULL,NULL,'https://animalcharityevaluators.org/research/charity-review/vegan-outreach/','Matt Ball,Jack Norris','Animal welfare/Diet change/Veganism/Leafleting',NULL,NULL,'UCtvZ0idC1JG2MDBeIUlKKcQ','veganoutreach',NULL,NULL,'veganoutreach','1993-01-01','year','http://veganoutreach.org/history/', NULL, NULL, NULL),
  ('The Good Food Institute',NULL,'United States',false,'thegoodfoodinstitute','http://www.gfi.org/','https://www.gfi.org/donate',NULL,NULL,'http://www.gfi.org/why',NULL,'GoodFoodInst',NULL,'https://en.wikipedia.org/wiki/The_Good_Food_Institute',NULL,'http://www.openphilanthropy.org/focus/us-policy/farm-animal-welfare/good-food-institute-general-support','https://animalcharityevaluators.org/research/charity-review/the-good-food-institute/',NULL,'Animal welfare/meat alternatives','Michael Dickens',NULL,NULL,NULL,NULL,NULL,NULL,'2016-02-01','month','https://animalcharityevaluators.org/research/charity-review/the-good-food-institute/', NULL, NULL, NULL),
  ('The Humane League',NULL,'United States',false,'thehumaneleague','http://www.thehumaneleague.com/','http://www.thehumaneleague.com/donate/',NULL,NULL,'http://www.thehumaneleague.com/impact/',NULL,'TheHumaneLeague','humane-league','https://en.wikipedia.org/wiki/The_Humane_League',NULL,NULL,'https://animalcharityevaluators.org/research/charity-review/the-humane-league/',NULL,'Animal welfare/Diet change/Veganism/Factory farming','Animal Charity Evaluators',NULL,'TheHumaneLeague','thehumaneleague',NULL,NULL,NULL,'2005-01-01','month','https://www.youtube.com/watch?v=JQQaecFfMbM', NULL, NULL, NULL),
  ('Mercy For Animals',NULL,'United States',false,'mercyforanimals','http://www.mercyforanimals.org/','http://www.mercyforanimals.org/donate',NULL,NULL,NULL,NULL,'MercyForAnimals','mercy-animals','https://en.wikipedia.org/wiki/Mercy_for_Animals',NULL,NULL,'https://animalcharityevaluators.org/research/charity-review/mercy-for-animals/','Nathan Runkle','Animal welfare/Diet change/Veganism/Factory farming','Animal Charity Evaluators',NULL,'mercyforanimals','mercyforanimals',NULL,NULL,NULL,'1999-01-01','year','https://en.wikipedia.org/wiki/Mercy_for_Animals', NULL, NULL, NULL);

# -- Biosecurity donees
insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url, charity_navigator_page, guidestar_page, timelines_wiki_page) values
  ('Blue Ribbon Study Panel on Biodefense',NULL,'United States',false,'biodefensestudy','http://www.biodefensestudy.org',NULL,'http://www.biodefensestudy.org/sponsors',NULL,'http://www.biodefensestudy.org/impact',NULL,'BiodefenseStudy',NULL,'https//en.wikipedia.org/wiki/Blue_Ribbon_Study_Panel_on_Biodefense',NULL,'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/blue-ribbon-study-panel-biodefense-general-support',NULL,'John Brennan','Biosecurity and pandemic preparedness','Jacob Steinhardt',NULL,NULL,NULL,NULL,NULL,NULL,'2014-12-04','day','http://www.biodefensestudy.org/PDFs/Lieberman-Ridge-launch-biodefense-panel-12-4-14.pdf', NULL, NULL, NULL),
  ('Johns Hopkins Center for Health Security','UPMC Center for Health Security','United States',false,'Johns-Hopkins-Center-for-Health-Security-81157515807','http://www.centerforhealthsecurity.org/',NULL,NULL,NULL,NULL,NULL,'UPMC_CHS',NULL,'https://en.wikipedia.org/wiki/Johns_Hopkins_Center_for_Health_Security',NULL,'http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic',NULL,NULL,'Biosecurity and pandemic preparedness',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1998-01-01','year','http://www.openphilanthropy.org/focus/global-catastrophic-risks/biosecurity/center-health-security-biosecurity-global-health-security-and-global-catastrophic', NULL, NULL, NULL);

# -- EA misc donees
insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url, charity_navigator_page, guidestar_page, timelines_wiki_page) values
  ('Animal Charity Evaluators','Effective Animal Activism','United States',false,'AnimalCharityEvaluators','http://www.animalcharityevaluators.org/',NULL,'https://animalcharityevaluators.org/about/top-donors/','https://animalcharityevaluators.org/about/transparency/',NULL,NULL,'AnimalCharityEv','animal-charity-evaluators','https://github.com/vipulnaik/working-drafts/blob/master/wikipedia/ace.mediawiki',NULL,NULL,NULL,'Jon Bockman','Animal welfare/Charity evaluation',NULL,NULL,'animalcharityeval',NULL,NULL,NULL,NULL,'2012-08-01','month','https://animalcharityevaluators.org/about/history/', NULL, NULL, NULL),
  ('Centre for Effective Altruism',NULL,'United Kingdom',false,'CentreforEffectiveAltruism','https://www.centreforeffectivealtruism.org/','https://www.centreforeffectivealtruism.org/donate/',NULL,NULL,'https://www.centreforeffectivealtruism.org/fundraising/',NULL,NULL,'centre-effective-altruism',NULL,NULL,NULL,NULL,'William MacAskill','Effective altruism',NULL,NULL,'EffectiveAltruist',NULL,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL, NULL),
  ('GiveWell',NULL,'United States',true,'GiveWell.org','http://www.givewell.org','https://secure.givewell.org/support-givewell',NULL,'http://www.givewell.org/about/official-records','http://blog.givewell.org/2015/12/25/december-2015-update-on-givewells-funding-needs/',NULL, 'givewell','givewell','https://en.wikipedia.org/wiki/GiveWell',NULL,NULL,NULL,'Holden Karnofsky,Elie Hassenfeld','Charity evaluation/global health/poverty',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2007-01-01','year','http://www.givewell.org/about/story', NULL, NULL, NULL),
  ('80000 Hours',NULL,'United Kingdom',false,'80000Hours','https://80000hours.org/','https://80000hours.org/support-us/donate/','https://80000hours.org/about/donors/','https://80000hours.org/about/credibility/evaluations/','http://effective-altruism.com/ea/15d/why_donate_to_80000_hours/',NULL,'80000hours',NULL,'https://en.wikipedia.org/wiki/80%2C000_Hours',NULL,NULL,NULL,'William MacAskill,Benjamin Todd,Robert Wiblin','Career coaching/life guidance',NULL,NULL,'eightythousandhours',NULL,NULL,NULL,NULL,'2011-11-01','month','https://80000hours.org/about/', NULL, NULL, NULL),
  ('Rethink Charity','.impact',NULL,false,'https://www.facebook.com/groups/dotimpact/','http://dotimpact.im/','http://dotimpact.causevox.com/',NULL,NULL,'http://dotimpact.causevox.com/',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Peter Hurford,Tom Ash','Effective altruism/Community project coordination',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2014-01-05','day','http://dotimpact.im/2014/01/05/introducing-dotimpact', NULL, NULL, NULL),
  ('Raising for Effective Giving',NULL,'Switzerland',false,'raisingforeffectivegiving','https://reg-charity.org/','https://reg-charity.org/donate/',NULL,'https://reg-charity.org/about/transparency/',NULL,NULL,'regcharity',NULL,'https://en.wikipedia.org/wiki/Raising_for_Effective_Giving',NULL,NULL,NULL,'Liv Boeree, Igor Kurganov, Philipp Gruissem','Effective altruism/Fundraising/Poker and sports',NULL,NULL,'regcharity',NULL,NULL,NULL,NULL,'2014-07-03','day','https://en.wikipedia.org/wiki/Raising_for_Effective_Giving', NULL, NULL, NULL),
  ('Founders Pledge',NULL,'United Kingdom',false,'FoundersPledge','https://founderspledge.com/',NULL,NULL,NULL,NULL,NULL,'founderspledge',NULL,'https://en.wikipedia.org/wiki/Founders_Pledge',NULL,'http://www.openphilanthropy.org/giving/grants/founders-pledge-general-support',NULL,'David Goldberg','Effective altruism/donor pledges',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2015-06-10','day','http://www.forbes.com/sites/davidprosser/2015/06/10/entrepreneurs-pledge-millions-to-social-good/#4c08c17a3d46', NULL, NULL, NULL),
  ('Center for Applied Rationality',NULL,'United States',true,'AppliedRationality','http://rationality.org/','http://rationality.org/donate','http://rationality.org/about/top-donors','http://rationality.org/about/official-records','http://lesswrong.com/lw/n39/why_cfar_the_view_from_2015/',NULL,'cfarnews',NULL,'https://en.wikipedia.org/wiki/Center_for_Applied_Rationality',NULL,'http://www.openphilanthropy.org/giving/grants/center-applied-rationality-general-support',NULL,'Julia Galef,Anna Salamon','Rationality',NULL,NULL,'AppliedRationality',NULL,NULL,NULL,NULL,'2012-01-01','year','https://www.fastcompany.com/3037333/most-creative-people/inside-the-rationality-movement-that-has-silicon-valley-buzzing-with-po', NULL, NULL, 'https://timelines.issarice.com/wiki/Timeline_of_Center_for_Applied_Rationality'),
  ('Students for High Impact Charity',NULL,'United States',false,'shicschools','http://www.shicschools.org/','http://www.shicschools.org/donate',NULL,NULL,'https://docs.google.com/document/d/1VLA9-twZzxq8DNENpsK9eeOmQv4ucFlGa0kbEjyjxSY/edit',NULL,'SHICorg',NULL,NULL,NULL,NULL,NULL,'Tee Barnett','Effective altruism/movement growth','Peter Hurford',NULL,NULL,'SHIC_org','shicschools',NULL,NULL,'2016-04-01','month','http://effective-altruism.com/ea/ys/help_shic_get_off_the_ground/', NULL, NULL, NULL);

# -- Random others
insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url, charity_navigator_page, guidestar_page, timelines_wiki_page) values
  ('Tostan',NULL,'United States',false,NULL,'http://www.tostan.org/','http://www.tostan.org/donate','http://www.tostan.org/about-us/our-partners-and-donors','http://www.tostan.org/annual-reports-financials',NULL,NULL,'Tostan',NULL,'https://en.wikipedia.org/wiki/Tostan',NULL,NULL,NULL,'Molly Melching,Susanne Bowles','Female empowerment/community empowerment/human rights','Elizabeth Van Nostrand',NULL,'TostanInternational','tostaninc',NULL,NULL,NULL,'1991-01-01','year','http://www.tostan.org/about-us/mission-history', NULL, NULL, 'https://timelines.issarice.com/wiki/Timeline_of_Tostan'),
  ('International Refugee Assistance Project','Iraqi Refugee Assistance Project','United States',false,'RefugeeAssist','https://refugeerights.org/','https://refugeerights.org/donate/',NULL,NULL,NULL,NULL,'RefugeeAssist',NULL,NULL,NULL,'http://www.openphilanthropy.org/focus/us-policy/immigration-policy/international-refugee-assistance-project-general-support',NULL,'Becca Heller','Migration policy/refugee assistance/legal help','Elizabeth Van Nostrand',NULL,'UCajuNyE3j3xO3zZ6m_S_JUQ',NULL,NULL,NULL,NULL,'2008-01-01','year','https://refugeerights.org/our-work/', NULL, NULL, NULL),
  ('Environmental Data and Governance Initiative',NULL,'United States',false,'EnviroDGI','https://envirodatagov.org/','https://www.generosity.com/community-fundraising/protect-public-environmental-data-and-research','https://www.generosity.com/community-fundraising/protect-public-environmental-data-and-research','https://www.generosity.com/community-fundraising/protect-public-environmental-data-and-research','https://envirodatagov.org/wp-content/uploads/2017/02/EDGI-Introduction-and-Accomplishments-Report.pdf','https://www.generosity.com/community-fundraising/protect-public-environmental-data-and-research','EnviroDGI',NULL,NULL,NULL,NULL,NULL,NULL,'Environmentalism/environmental governance/data preservation/watchdog','Jacob Trefethen',NULL,NULL,NULL,NULL,NULL,NULL,'2016-12-01','month','https://envirodatagov.org/blog/', NULL, NULL, NULL),
  ('Ayni Institute','Movement Mastery','United States',false,'ayni.institute','http://www.ayni.institute','https://www.eservicepayments.com/cgi-bin/Vanco_ver3.vps?appver3=Fi1giPL8kwX_Oe1AO50jRoo3RD3OWJuCJfAhCXOxXeNEOVZpPcIw91FrYieK2rA42EvVVAEjqawDomKT1pboubXjp_TwG8kyxMbMiK5GWvE=&ver=3',NULL,NULL,NULL,NULL,'AyniTeam',NULL,NULL,NULL,'http://www.openphilanthropy.org/focus/us-policy/criminal-justice-reform/ayni-institute-movement-ecology-training',NULL,NULL,'Criminal justice reform',NULL,NULL,'MovementMastery',NULL,NULL,NULL,NULL,'2013-01-01','year','http://www.ayni.institute/who_we_are', NULL, NULL, NULL),
  ('GiveDirectly',NULL,'United States',false,'givedirectly','https://www.givedirectly.org/','https://www.givedirectly.org/give-now#',NULL,NULL,'https://www.givedirectly.org/research-at-give-directly',NULL,'Give_Directly','givedirectly','https://en.wikipedia.org/wiki/GiveDirectly','http://www.givewell.org/charities/give-directly',NULL,NULL,'Paul Niehaus,Rohit Wanchoo,Michael Faye,Jeremy Shapiro','Cash transfers','GiveWell',NULL,'UCi29RpkCdO43kVN_nr8FhRA','givedirectly',NULL,NULL,NULL,'2009-01-01','year','https://www.givedirectly.org/faq', NULL, NULL, NULL);

# -- insert into donees(donee, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, ace_review, key_people, cause_area, recommenders, notes, youtube_username, instagram_username, tumblr_subdomain, medium_username, pinterest_username, launch_date, launch_date_precision, launch_date_url) values

insert into donees(donee, donee_type, former_name, country, bay_area, facebook_username, website, donate_page, donor_list_page, transparency_and_financials_page, donation_case_page, donation_statistics_page, twitter_username, eahub_username, wikipedia_page, givewell_review, open_phil_grant_review, key_people, cause_area, recommenders) values
  ('EA Giving Group','Donor-advised fund',NULL,'United States',true,NULL,'https://docs.google.com/spreadsheets/d/1H2hF3SaO0_QViYq2j1E7mwoz3sDjdf9pdtuBcrq7pRU/edit#gid=0','https://docs.google.com/forms/d/e/1FAIpQLScFYVJs3Inhmg50eGyENNg3CRvbfQ-L-KNJyywYtwl67dc56w/viewform',NULL,NULL,'blog.givewell.org/2016/12/09/staff-members-personal-donations-giving-season-2016/',NULL,NULL,NULL,NULL,NULL,NULL,'Nick Beckstead','Existential risk/far future/trajectory improvement',NULL),
  ('GiveWell top charities','Subsidiary',NULL,'United States',true,'GiveWell.org','http://www.givewell.org','https://secure.givewell.org/',NULL,NULL,'http://blog.givewell.org/2016/11/28/updated-top-charities-giving-season-2016/','http://www.givewell.org/about/impact', 'givewell','givewell','https://en.wikipedia.org/wiki/GiveWell#Top-rated_charities',NULL,NULL,'Holden Karnofsky,Elie Hassenfeld','Charity evaluation/global health/poverty',NULL);
