# -- Animal welfare
insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, influencer, goal_amount, fraction, notes, affected_countries) values
  ('Effective Altruism Funds','The Humane League',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.17,'Bollard describes how grantee is a promising organization that played a major role in US corporate campaigns for chicken welfare. Open Phil accounts for 50% of funding, so Open Phil may choose to not donate more due to dependence concerns','United States'),
  ('Effective Altruism Funds','Animal Equality',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.17,'Bollard notes that grantee does grassroots activism, corporate campaigning, and undercover investigations across Europe, the Americas, and India. Bollard is impressed based on constant updating on evidence: moving from farm animal welfare work to a focus on corporate campaigns. Also impressed with co-founders',NULL),
  ('Effective Altruism Funds','New Harvest',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.17,'Grantee is a clean meat research group. Unlike The Good Food Institute, it may not attract enough in funding from big donors like Open Phil. Grant partly because Bollard believes that the funds invested right now will determine the pace of progress in the next 20-50 years',NULL),
  ('Effective Altruism Funds','Effective Altruism Foundation',30000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.17,'Grant will fund research on the welfare of wild animals done by researchers Ozy Brennan and Persis Eskander, which internal changes at EAF have resulted in a loss of funding for. Bollard is impressed with their recent research, which focuses on foundational questions like the best scientific methods for measuring the wellbeing of wild animals, and relatively non-controversial potential interventions, like more humane methods of pest control',NULL),
  ('Effective Altruism Funds','Fórum Nacional de Proteção e Defesa Animal',20000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.11,'Grantee is Brazil’s largest animal protection network with 120+ affiliated NGOs (mainly companion animal groups). Open Phil accounts for 50% of funding, so Open Phil may choose to not donate more due to dependence concerns','Brazil'),
  ('Effective Altruism Funds','Compassion in World Farming USA',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.06,'Grantee has played a role in recent US corporate campaigns for chicken welfare. Open Phil accounts for 50% of funding, so Open Phil may choose to not donate more due to dependence concerns','United States'),
  ('Effective Altruism Funds','Albert Schweitzer Foundation for Our Contemporaries',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.06,'Grantee has played a role in corporate campaigns in Germany. Grantee has medium-term funding needs','Germany'),
  ('Effective Altruism Funds','Animal Charity Evaluators',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.06,'Bollard likes the work that ACE does to build a more effective farm animal movement through research, charity recommendations, and outreach to donors, researchers, and advocates. After recommending the grant, Bolalrd became more confident that funding gaps of grantee would be met and so is less likely to recommend for further grants',NULL),
  ('Effective Altruism Funds','Otwarte Klatki',10000,'2017-04-20','day','date of donation announcement','Animal welfare','http://effective-altruism.com/ea/19d/update_on_effective_altruism_funds/','https://app.effectivealtruism.org/funds/animal-welfare','Lewis Bollard',180000,0.06,'Grantee achieved corporate reforms in tough political environment on small budget. Has medium-term funding needs','Poland');

# -- AI risk

# -- Global health
