# -- Google.org grants

# -- Grants in education

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, notes, affected_cities, affected_states, affected_countries) values
  ('Google.org','War Child Holland',2500000,'2016-01-01','multi-year','donation log','Education/tablet-based educational games/conflict zone education/refugee education','https://www.google.org/our-work/education/war-child/','Recipient distributes tablet-based educational games that can be played in informal refugee learning centres without classrooms and teachers, and students can still learn. In addition to funding, Google is providing technical expertise of Googler volunteers to turn the approach of War Child Holland and partners into a scalable solution',NULL,NULL,'Sudan,Lebanon,Jordan'),
  ('Google.org','Pratham',3850000,'2013-01-01','multi-year','donation log','Education/open-source platform for book translation','https://www.google.org/our-work/education/storyweaver/','Grant supports StoryWeaver, an online platfor that connecs readers, authors, illustrators, and translators. Open-sourced stories are translated to up to 60 languages and therefore become accessible to people in different regions. Translated content can be downloaded, accessed on multiple devices, and printed',NULL,NULL,'India'),
  ('Google.org','Khan Academy',11000000,'2010-01-01','multi-year','donation log','Education/online video education','https://www.google.org/our-work/education/khan-academy/','Grant supports continued operation and growth of recipient, specifically investments in intelligent software, deep data analytics, and intuitive user interfaces',NULL,NULL,NULL),
  ('Google.org','Pratham',4000000,'2007-01-01','multi-year','donation log','Education/assessment','https://www.google.org/our-work/education/pratham/','The $4 million from Google.org since 2007 helped fund the ASER (Annual Status of Education Report) Centre, that conducts surveys to assess the level of literacy or numeracy of children in rural India. Finding: although 96% of children are enrolled in school, about half cannot read a simple text or do arithmetic',NULL,NULL,'India'),
  ('Google.org','Pratham',6100000,'2016-01-01','year','donation log','Education/tablet-based education','https://www.google.org/our-work/education/pratham/','This funding includes $3 million toward devices and an additional $3.1 million to support the Hybrid Learning Program, an initiative that empowers students to use self driven, tablet-based curricula to learn outside of the classroom.',NULL,NULL,'India'),
  ('Google.org','Clooney Foundation for Justice',1000000,'2016-01-01','multi-year','donation log','Education/refugee education','https://www.google.org/our-work/education/clooney-foundation-justice/','Funding supports grantee efforts to provide education to out-of-school refugee children in Lebanon. Googler volunteers, working on the ground and remotely, will provide technical expertise',NULL,NULL,'Lebanon'),
  ('Google.org','Nova Escola',5100000,'2016-01-01','multi-year','donation log','Education/digital education','https://www.google.org/our-work/education/nova-escola/','Funding supports the creation of standards-aligned digital lessons, to deal with quality problems in the Brazil education system (it ranks low in international educational comparisons). Nova Escola is also supported by the Lemann Foundation, a leading Brazilian education organization. Goal is to reach 1 million teachers in the next 5 years',NULL,NULL,'Brazil'),
  ('Google.org','RTI International',2000000,'2016-01-01','multi-year','donation log','Education/Teacher training','https://www.google.org/our-work/education/rti-international/','Funding is for Tangerine:Tutor, an open-source software platform built by grantee by helping teacher coaches in low-resource environments provide targeted guidance for improved student learning. Google.org intends to help RTI update Tangerine:Tutor technical infrastructure and ope-source documentation to help with scaling up, and meeting five-year goal of supporting teachers who reach 4 million students',NULL,NULL,'Kenya,Uganda,Nepal'),
  ('Google.org','Code.org',5500000,'2013-01-01','multi-year','donation log','Education/online coding education','https://www.google.org/our-work/education/code-org/','Funding is to facilitate Code.org partnerships with teachers and school districts to promote the study of computer science. Although Code.org is globally accessible, the partnerships are in the United States. Google.org supports Code.org in many ways. For instance, the Google visual coding language, Blockly, underpins the Code.org educational content. Googlers also volunteer for in-person activities and provide project management skills',NULL,NULL,'United States');
# --  ('Google.org','Anita Borg Institute',
