# -- Google.org grants

# -- Year-wise grants to Khan Academy where available

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, affected_cities, affected_states, affected_countries) values
  ('Google.org','Khan Academy',2000000,'2014-01-01','year','donation log','Education/online video education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant supports continued operation and growth of recipient, specifically investments in intelligent software, deep data analytics, and intuitive user interfaces. Separate grant of this amount ',NULL,NULL,NULL),
  ('Google.org','Khan Academy',1000000,'2015-01-01','year','donation log','Education/online video education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant supports continued operation and growth of recipient, specifically investments in intelligent software, deep data analytics, and intuitive user interfaces',NULL,NULL,NULL),
  ('Google.org','Khan Academy',5000000,'2016-01-01','year','donation log','Education/online video education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant supports continued operation and growth of recipient, specifically investments in intelligent software, deep data analytics, and intuitive user interfaces',NULL,NULL,NULL);

# -- Year-wise grants to Code.org where available

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, affected_cities, affected_states, affected_countries) values
  ('Google.org','Code.org',1500000,'2016-01-01','year','donation log','Education/online coding education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Funding is to facilitate Code.org partnerships with teachers and school districts to promote the study of computer science. Although Code.org is globally accessible, the partnerships are in the United States. Google.org supports Code.org in many ways. For instance, the Google visual coding language, Blockly, underpins the Code.org educational content. Googlers also volunteer for in-person activities and provide project management skills',NULL,NULL,'United States'),
  ('Google.org','Code.org',1000000,'2015-01-01','year','donation log','Education/online coding education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Funding is to facilitate Code.org partnerships with teachers and school districts to promote the study of computer science. Although Code.org is globally accessible, the partnerships are in the United States. Google.org supports Code.org in many ways. For instance, the Google visual coding language, Blockly, underpins the Code.org educational content. Googlers also volunteer for in-person activities and provide project management skills',NULL,NULL,'United States');

# -- Grants in education

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, affected_cities, affected_states, affected_countries) values
  ('Google.org','War Child Holland',2500000,'2016-01-01','multi-year','donation log','Education/tablet-based educational games/conflict zone education/refugee education','https://www.google.org/our-work/education/war-child/','https://www.google.org/our-work/education/','Recipient distributes tablet-based educational games that can be played in informal refugee learning centres without classrooms and teachers, and students can still learn. In addition to funding, Google is providing technical expertise of Googler volunteers to turn the approach of War Child Holland and partners into a scalable solution',NULL,NULL,'Sudan,Lebanon,Jordan'),
  ('Google.org','Pratham',3850000,'2013-01-01','multi-year','donation log','Education/open-source platform for book translation','https://www.google.org/our-work/education/storyweaver/','https://www.google.org/our-work/education/','Grant supports StoryWeaver, an online platfor that connecs readers, authors, illustrators, and translators. Open-sourced stories are translated to up to 60 languages and therefore become accessible to people in different regions. Translated content can be downloaded, accessed on multiple devices, and printed',NULL,NULL,'India'),
  ('Google.org','Khan Academy',3000000,'2010-01-01','multi-year','donation log','Education/online video education','https://www.google.org/our-work/education/khan-academy/','https://www.google.org/our-work/education/','Grant supports continued operation and growth of recipient, specifically investments in intelligent software, deep data analytics, and intuitive user interfaces. The grant amount listed here subtracts separately listed grants at https://www.google.org/our-work/education/ (More education grantees section)',NULL,NULL,NULL),
  ('Google.org','Pratham',4000000,'2007-01-01','multi-year','donation log','Education/assessment','https://www.google.org/our-work/education/pratham/','https://www.google.org/our-work/education/','The $4 million from Google.org since 2007 helped fund the ASER (Annual Status of Education Report) Centre, that conducts surveys to assess the level of literacy or numeracy of children in rural India. Finding: although 96% of children are enrolled in school, about half cannot read a simple text or do arithmetic',NULL,NULL,'India'),
  ('Google.org','Pratham',6100000,'2016-01-01','year','donation log','Education/tablet-based education','https://www.google.org/our-work/education/pratham/','https://www.google.org/our-work/education/','This funding includes $3 million toward devices and an additional $3.1 million to support the Hybrid Learning Program, an initiative that empowers students to use self driven, tablet-based curricula to learn outside of the classroom.',NULL,NULL,'India'),
  ('Google.org','Clooney Foundation for Justice',1000000,'2016-01-01','multi-year','donation log','Education/refugee education','https://www.google.org/our-work/education/clooney-foundation-justice/','https://www.google.org/our-work/education/','Funding supports grantee efforts to provide education to out-of-school refugee children in Lebanon. Googler volunteers, working on the ground and remotely, will provide technical expertise',NULL,NULL,'Lebanon'),
  ('Google.org','Nova Escola',5100000,'2016-01-01','multi-year','donation log','Education/digital education','https://www.google.org/our-work/education/nova-escola/','https://www.google.org/our-work/education/','Funding supports the creation of standards-aligned digital lessons, to deal with quality problems in the Brazil education system (it ranks low in international educational comparisons). Nova Escola is also supported by the Lemann Foundation, a leading Brazilian education organization. Goal is to reach 1 million teachers in the next 5 years',NULL,NULL,'Brazil'),
  ('Google.org','RTI International',2000000,'2016-01-01','multi-year','donation log','Education/Teacher training','https://www.google.org/our-work/education/rti-international/','https://www.google.org/our-work/education/','Funding is for Tangerine:Tutor, an open-source software platform built by grantee by helping teacher coaches in low-resource environments provide targeted guidance for improved student learning. Google.org intends to help RTI update Tangerine:Tutor technical infrastructure and ope-source documentation to help with scaling up, and meeting five-year goal of supporting teachers who reach 4 million students',NULL,NULL,'Kenya,Uganda,Nepal'),
  ('Google.org','Code.org',3000000,'2013-01-01','multi-year','donation log','Education/online coding education','https://www.google.org/our-work/education/code-org/','https://www.google.org/our-work/education/','Funding is to facilitate Code.org partnerships with teachers and school districts to promote the study of computer science. Although Code.org is globally accessible, the partnerships are in the United States. Google.org supports Code.org in many ways. For instance, the Google visual coding language, Blockly, underpins the Code.org educational content. Googlers also volunteer for in-person activities and provide project management skills. The grant amount listed here subtracts separately listed grants at https://www.google.org/our-work/education/ (More education grantees section)',NULL,NULL,'United States'),
  ('Google.org','Anita Borg Institute',300000,'2016-01-01','multi-year','donation log','Education/computer science education/gender representation and race/ethnicity representation','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Funding is for the BRAID initiative, a partnership with universities across the United States to increase the percentage of women and students of color majoring in computer science',NULL,NULL,'United States'),
  ('Google.org','Calliope',555000,'2016-01-01','multi-year','donation log','Education/micro-computers and related support','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant is to distribute Calliope micro-computers and offer related support for schoolchildren in Germany',NULL,NULL,'Germany'),
  ('Google.org','First Australia',693810,'2016-01-01','multi-year','donation log','Education/robotics','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant is to expand access to robotics clubs in underserved schools in Australia',NULL,NULL,'Australia'),
  ('Google.org','Foundation for Learning Equality',5000000,'2016-01-01','multi-year','donation log','Education/offline access to online education','https://www.google.org/our-work/education/learning-equality/','https://www.google.org/our-work/education/','Grantee has a Kolibri platform that organizes content in a cloud based library, where it can be downloaded by teachers and learners and used offline, whether in schools, refugee camps, or orphanages. In addition to money, Google.org intends to work with grantee product team in areas such as UX/UI, content integration, and video compression technology. See http://ucsdnews.ucsd.edu/pressrelease/learning_equality_awarded_5m_through_google.org_global_education_commitment (2017-03-22) and https://techcrunch.com/2017/03/21/google-org-grants-50-million-to-nonprofits-striving-for-equal-access-in-education/ (2017-03-21) for more coverage of the grant',NULL,NULL,'India,Latin America,Sub-Saharan Africa'),
  ('Google.org','Future Class Network',457737,'2016-01-01','multi-year','donation log','Education/teacher information sharing and funding student projects','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grantee is a platform for supporting teacher information sharing and funding student projects',NULL,NULL,'South Korea'),
  ('Google.org','Hispanic Foundation of Silicon Valley',250000,'2016-01-01','multi-year','donation log','Education/parental support','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to help parents of Latino students become more knowledgeable about the local education system and how best to support their children, in order to increase the high school and college graduation rates of the children','Sunnvale,Mountain View','California','United States'),
  ('Google.org','IAIS Fraunhofer',5000000,'2016-01-01','multi-year','donation log','Education/computer science education/offline training for primary and secondary school students','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to deliver offline STEM and coding trainings to 64,000 primary and secondary pupils and 1,500 teachers',NULL,NULL,'Germany'),
  ('Google.org','JUMP SP',228869,'2016-01-01','multi-year','donation log','Education/mentorship of disadvantaged students','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant for mentoring program for disadvantaged youth in which mentors (university students) can earn scholarships and credits for college',NULL,NULL,'South Korea'),
  ('Google.org','Kiron Open Higher Education gUG',281400,'2016-01-01','multi-year','donation log','Education/online degrees for refugees','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/',NULL,NULL,NULL,'Germany'),
  ('Google.org','Libraries without Borders',2250000,'2016-01-01','multi-year','donation log','Education/refugee education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to expand Ideas Boxes to more countries, enabling access to content in refugee settings, rural areas, and underserved neighborhoods',NULL,NULL,NULL),
  ('Google.org','Like Lion',457737,'2016-01-01','multi-year','donation log','Education/coding bootcamp','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant for social impact-focused bootcamps',NULL,NULL,'South Korea'),
  ('Google.org','Literacy Lab',250000,'2016-01-01','multi-year','donation log','Education/digital books','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grantee gives kids access to digital books in multiple languages while creating a supportive online community for parents and caregivers',NULL,NULL,'United States'),
  ('Google.org','Million Sparks Foundation',1233020,'2016-01-01','multi-year','donation log','Education/easy-to-use teaching tools and training modules','https://www.google.org/our-work/education/million-sparks-foundation/','https://www.google.org/our-work/education/','Grantee to improve the quality of education for low-income students in India by developing mobile technology that shares easy-to-use teaching tools and training modules aligned to local curriculum',NULL,NULL,'India'),
  ('Google.org','Abdul Latif Jameel Poverty Action Lab',1500000,'2016-01-01','multi-year','donation log','Education/Educational research','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant for research and education under the Post-Primary Education Initiative, particularly related to educational technology',NULL,NULL,NULL),
  ('Google.org','Society for Black Engineers',300000,'2016-01-01','multi-year','donation log','Education/computer science education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant for Code Success, a comprehensive program that increases graduation rates for African-American college students interested in and pursuing Computer Science degrees',NULL,NULL,'United States'),
  ('Google.org','Spark',100000,'2016-01-01','multi-year','donation log','Education/school success','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grantee to inspire 7th, 8th and 9th grade students to succeed in high school and beyond by connecting them with mentors in leading workplaces and supporting their academic journey with skill-building and resources',NULL,NULL,'United States'),
  ('Google.org','The Australian Literacy and Numeracy Foundation',192109,'2016-01-01','multi-year','donation log','Education/language preservation','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grantee to preserve indigenous languages via community-driven literacy applications',NULL,NULL,'Australia'),
  ('Google.org','UNETE',2100000,'2016-01-01','multi-year','donation log','Education/digital content for people with limited connectivity','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grantee to increase access to digital educational content for students in Mexico with limited internet connectivity, through implementation of a new software platform, training and teacher support, and new devices',NULL,NULL,'Mexico'),
  ('Google.org','826 Valencia',217440,'2015-01-01','multi-year','donation log','Education/community-based creative writing','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant for a community-based creative writing center in a renovated liquor store in the Tenderloin','San Francisco','California','United States'),
  ('Google.org','Australian Indigenous Mentoring Experience',247000,'2015-01-01','multi-year','donation log','Education/STEM education/Computer science education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to raise awareness of STEM and CS pathways among indigenous students',NULL,NULL,'Australia'),
  ('Google.org','Benetech: Bookshare',800000,'2015-01-01','multi-year','donation log','Education/book distribution','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to expand the reach of Bookshare by expanding the availability of quality content and improve its functionality to improve content distribution',NULL,NULL,NULL),
  ('Google.org','Bibliothèques Sans Frontières',217440,'2015-01-01','multi-year','donation log','Education/refugee education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant for a toolkit-in-a-box approach to address social isolation of refugees and migrant populations',NULL,NULL,'EMEA'),
  ('Google.org','British Computing Society',400000,'2015-01-01','multi-year','donation log','Education/computer science education/online teacher training','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to create professional development in computational thinking and to provide in-person and online teacher training',NULL,NULL,'United Kingdom'),
  ('Google.org','City Year San Jose/Silicon Valley',500000,'2015-01-01','multi-year','donation log','Education/mentorship','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant supports tutoring, mentoring, and STEM program for underserved youth in the Overfelt High School feeder schools in East San Jose','San Jose','California','United States'),
  ('Google.org','Fundacion Ayuda en Accion',765000,'2015-01-01','multi-year','donation log','Education/computer science education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to provide in-depth, high-quality computer science education to 5,000 schoolchildren and 500 teachers in high-need schools',NULL,NULL,'Spain'),
  ('Google.org','Kiron University',336465,'2015-01-01','multi-year','donation log','Education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to launch pilot projects and/or set up operations in Turkey and Jordan',NULL,NULL,'Turkey,Jordan'),
  ('Google.org','Royal Belgian Institut of Natural Sciences',758000,'2015-01-01','multi-year','donation log','Education/science education/technology-assisted education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Grant to distribute "infrared birdboxes" around the country of Belgium for a Raspberry Pi program',NULL,NULL,'Belgium'),
  ('Google.org','NCWIT',500000,'2015-01-01','multi-year','donation log','Education/computer science education','https://www.google.org/our-work/education/','https://www.google.org/our-work/education/','Fund to support the creation and expansion of women in computing support groups (WICs); build eco-systems of WICs and get them sharing best practices, mentoring other WICs etc',NULL,NULL,'United States');

# -- Economic opportunity

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, affected_cities, affected_states, affected_countries) values
  ('Google.org','Colnodo',600000,'2014-01-01','multi-year','donation log','Job training/digital skills','https://www.google.org/our-work/economic-opportunity/colnodo/','https://www.google.org/our-work/economic-opportunity/','Grantee works to train unemployed urban youth and rural populations in digital skills to prepare them for technolog sector jobs',NULL,NULL,'Colombia'),
  ('Google.org','Oakland Digital',600000,'2015-01-01','multi-year','donation log','Job training/digital skills','https://www.google.org/our-work/economic-opportunity/oakland-digital/','https://www.google.org/our-work/economic-opportunity/','Grantee has a BRIDGEGOOD hiring platform that pairs early stage creatives (designers, photographers, illustrators) with business owners and nonprofits that need design or markeing expertise. Google.org is helping with grant money, state-of-the-art technology devices, Googler developer volunteer hours, and a San Francisco coworking space. The donations are being used to design, build, launch and scale the BRIDGEGOOD platform in the San Francisco Bay Area','Oakland,San Francisco,Berkeley','California','United States'),
  ('Google.org','GiveDirectly',2400000,'2012-12-01','month','date of donation announced in announcement','Cash transfers','https://www.theatlantic.com/business/archive/2012/12/can-4-economists-build-the-most-economically-efficient-charity-ever/266510/','https://www.google.org/our-work/economic-opportunity/','Grantee page is at https://www.google.org/our-work/economic-opportunity/give-directly/ and explains reasons for Google being excited about the Good Ventures approach of unconditional cash transfers',NULL,NULL,'Kenya'),
  ('Google.org','America Makes',250000,'2016-01-01','multi-year','donation log','Job training/manufacturing','https://www.google.org/our-work/economic-opportunity/','https://www.google.org/our-work/economic-opportunity/','Grant is for job-ready skills training in advanced manufacturing techniques for former military veterans',NULL,NULL,'United States'),
  ('Google.org','BSS (Making a World Together)',228869,'2016-01-01','multi-year','donation log','Financing/credit rating system','https://www.google.org/our-work/economic-opportunity/','https://www.google.org/our-work/economic-opportunity/','Alternative credit rating system based on social signals',NULL,NULL,'South Korea'),
  ('Google.org','Czechitas',257700,'2016-01-01','multi-year','donation log','Job training/digital skills and data science','https://www.google.org/our-work/economic-opportunity/','https://www.google.org/our-work/economic-opportunity/','Digital skills and data science trainings for women in the Czech Republic',NULL,NULL,'Czech Republic'),
  ('Google.org','Digitale-Helden gemeinnützige GmbH',281400,'2016-01-01','multi-year','donation log','Digital literacy/online safety training','https://www.google.org/our-work/economic-opportunity/','https://www.google.org/our-work/economic-opportunity/','Peer to peer training for digital literacy / online safety',NULL,NULL,'Germany'),
  ('Google.org','Root Impact',228869,'2016-01-01','multi-year','donation log','Career counseling','https://www.google.org/our-work/economic-opportunity/','https://www.google.org/our-work/economic-opportunity/','Program to connect high potential youth with social impact career opportunities',NULL,NULL,'South Korea');

# -- Criminal justice reform (they call it "inclusion")

insert into donations(donor, donee, amount, donation_date,
    donation_date_precision, donation_date_basis, cause_area, url, donor_cause_area_url, notes, affected_cities, affected_states, affected_countries) values
  ('Google.org','Measures for Justice',1500000,'2016-01-01','multi-year','donation log','Criminal justice reform/United States','https://www.google.org/our-work/inclusion/measures-justice/','https://www.google.org/our-work/inclusion/','Grantee is a national nonprofit with the goal of making information on the working of their local justice system to anybody in the United States. The grant helps the grantee expand throughout the United States, with an inital focus on California. Googler volunteers are also advising on data processing for the database',NULL,'California','United States'),
  ('Google.org','Equal Justice Initiative',1000000,'2016-01-01','multi-year','donation log','Criminal justice reform/United States','https://www.google.org/our-work/inclusion/equal-justice-initiative/','https://www.google.org/our-work/inclusion/','Grantee is committed to ending mass incarceration and excessive punishment in the United States, to challenging racial and economic injustice, and to protecting basic human rights for the most vulnerable people in American society. Grant supports two projects: a museum examining African American history (called "From Enslavement to Mass Incarceration") and a national memorial to lynching victims (called the "Memorial to Peace and Justice").',NULL,NULL,'United States'),
  ('Google.org','Center for Policing Equity',5000000,'2016-01-01','multi-year','donation log','Criminal justice reform/United States/public safety/racial profiling','https://www.google.org/our-work/inclusion/center-policing-equity/','https://www.google.org/our-work/inclusion/','Grantee grated the National Justice Database (NJD) in 2013, claimed to be the first database tracking national statistics on police behavior, including stops and use of force.',NULL,NULL,'United States');
